### ISSUE TITLE
Enhancement: Easier mod support,  possibly integrating modding+

### ISSUE THREAD

**Issue by QueenLinuxGlitch** [KadeArchive/Kade-Engine#10]

**Comment by Kiffolisk** [comment]
might take time for kade to do easy modding shit, also i don't think modding+ has downloadable source code

**Comment by QueenLinuxGlitch** [comment]
> might take time for kade to do easy modding shit, also i don't think modding+ has downloadable source code

They do! I was looking at it earlier, maybe if I get a chance to dig in, i can implement some easy features and go from there. I love the new engine, i just have to make it work for good times lol. I always love picking up a new language for kicks

**Comment by Kade-github** [comment]
basically, all I've seen is modding+ is just straight fps+ with custom characters.  It'll be pretty easy to implement custom songs, but you'll still have to learn the new asset system since that's already in the base game. I'm probably going to keep focusing on replays and big bugs for now, but I'll keep this in mind.

**Comment by TentaRJ** [comment]
how does the new asset system work? I understand that it is more organized but I don't understand how it is handled. Was there a new file added to manage file paths?

**Comment by Kade-github** [comment]
> how does the new asset system work? I understand that it is more organized but I don't understand how it is handled. Was there a new file added to manage file paths?

it's liteartly called paths.hx

**Comment by TentaRJ** [comment]
> > how does the new asset system work? I understand that it is more organized but I don't understand how it is handled. Was there a new file added to manage file paths?
> 
> it's liteartly called paths.hx

My bad. Haven't seen any of the new updates in a couple of weeks.
