### ISSUE TITLE
Bug Report: downscroll arrows reversed

### ISSUE THREAD

**Issue by Pandoken** [KadeArchive/Kade-Engine#100]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
I am on Windows 10 64bit
## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1 FNF, 1.3.1 Kade Engine
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Set to downscroll in Options.
The rest of the settings are as follows:
DFJK (doesn't matter which one it's on, WASD also does it)
New Input
Accuracy On
Song Position Off
Eterna Mode Off

## Please describe your issue. Provide extensive detail and images if possible.
![Friday Night Funkin' 3_30_2021 10_03_33 PM](https://user-images.githubusercontent.com/81668812/113093003-f0c3e980-91a3-11eb-8384-0f573e20f180.png)

The Up and Down arrows are reversed when downscroll is enabled. I did confirm that upscroll works as expected.

**Comment by theDetourist** [comment]
Did you download the latest 1.3.1-KE version? If yes, try the latest Nightly build, this has already been fixed.

**Comment by Pandoken** [comment]
I didn't see the Nightly build, thank you so much!
