### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by mrpiggy100** [KadeArchive/Kade-Engine#1000]
After I built the game to test if the installation worked, whenever I went into a song and pressed the up and right arrows it just didnt register. I can ghost tap with them but when i press them when a note comes it's counted as a miss. This doesnt happen with the left and down arrows. Can somebody help?

**Comment by blackm1n** [comment]
Congratulations for being 1000th Issue Reported, you won a Lamborgini and 25,000$

**Comment by mrpiggy100** [comment]
...

**Comment by Kade-github** [comment]
should be fixed
