### ISSUE TITLE
Bug Report: Notes are disappearing

### ISSUE THREAD

**Issue by BombasticTom** [KadeArchive/Kade-Engine#1002]
When I was playing M.I.L.F, I noticed my note disappeared. I thought that was my mistake, that I didn't press the note correctly. So I've restarted the song and it still kept going.

https://user-images.githubusercontent.com/85838311/123182293-64b61b00-d48f-11eb-946e-b9589379d515.mp4

**Comment by Prod-42** [comment]
Is the Anti-mashing system, maybe other problem is the safe FPS you have, i don't really know try change the safe FPS to 10 again, sorry if it don't works

**Comment by PixelHUN** [comment]
This is not only happening to you, possibly a duplicate of #990 
I'm gonna quote the last reply I got, as it actually fixed my issue:

If you prefer the old hit detection, edit line 214-215 of Note.hx from:

if (strumTime > Conductor.songPosition - Conductor.safeZoneOffset
&& strumTime < Conductor.songPosition + Conductor.safeZoneOffset)
to:
if (strumTime > Conductor.songPosition - Conductor.safeZoneOffset
&& strumTime < Conductor.songPosition + (Conductor.safeZoneOffset * 0.5))

**Comment by Kade-github** [comment]
Fixed in the latest release.
