### ISSUE TITLE
Enhancement: song lists

### ISSUE THREAD

**Issue by PjWags7195** [KadeArchive/Kade-Engine#101]
so i enjoy modding the game because its simple and easy, after learning how on your engine it still was, except when you boot up a song without either the Inst or voices it straight up crashes the game, I just recommend making so they aren't required to play the levels as a lot of mods use only one and delete the other. 
thanks!

**Comment by puyoxyz** [comment]
...isn't there a needsVoices option in the song json?

**Comment by Jaduplex** [comment]
> ...isn't there a needsVoices option in the song json?

exactly. Plus, tutorial doesn't use that option, and the game doesnt crash.
