### ISSUE TITLE
Bug Report: Discord-rpc problem

### ISSUE THREAD

**Issue by zenolth** [KadeArchive/Kade-Engine#1011]
Hello, I have a problem, after running "lime test windows" it will show this 
"source_xp/Discord.hx:5: characters 8-30 : Type not found : discord_rpc.DiscordRpc
source_xp/Discord.hx:14: characters 3-13 : Type not found : DiscordRpc
source_xp/Discord.hx:24: characters 4-14 : Type not found : DiscordRpc
source_xp/Discord.hx:29: characters 3-13 : Type not found : DiscordRpc
source_xp/Discord.hx:34: characters 3-13 : Type not found : DiscordRpc
source_xp/Discord.hx:39: characters 3-13 : Type not found : DiscordRpc
source_xp/Discord.hx:75: characters 3-13 : Type not found : DiscordRpc"
and i cant find solution, neither on Discord server, so I would be grateful if someone told me the solution.

**Comment by KlutchDj** [comment]
uhh did you install `haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc` in the command prompt ?

**Comment by Justine101213k** [comment]
Type in command haxelib remove discord_rpc 
Then install discord_rpc
Install haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc in the command prompt

**Comment by Slussh** [comment]
"could not clone git repository" got after running Install haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc

**Comment by lol1111111111111** [comment]
could not use git error
