### ISSUE TITLE
Bug Report: Ay yo, what does this mean?

### ISSUE THREAD

**Issue by YamiZoroThingNG** [KadeArchive/Kade-Engine#1012]
Don't mind the background...

Everytime I try and start up Lo-Fight, I get this error. What?

![Screenshot (31)](https://user-images.githubusercontent.com/86450046/123355289-ffb00300-d52a-11eb-9498-855ad1c65eb9.png)

**Comment by KlutchDj** [comment]
that means the json doesnt exist , or the json is named wrong , or the formatting is wrong. make sure in the format that its labeled the same way the folder is named.

**Comment by KlutchDj** [comment]
i worded that so wrong

**Comment by Kade-github** [comment]
Song doesn't exist

**Comment by ACardboardBox1** [comment]
the beatles
