### ISSUE TITLE
Bug Report: Boyfriend goes to idle too quickly

### ISSUE THREAD

**Issue by RagdollClash** [KadeArchive/Kade-Engine#1018]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86_64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.
Kade Engine 1.5.4

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
1. Go to any song, any difficulty.
2. Press the notes and look at boyfriend's animation.

## Please describe your issue. Provide extensive detail and images if possible.
Sometimes when you release a note, Boyfriend goes back to his idle animation immediately.

1.5.4:

https://user-images.githubusercontent.com/15317421/123373944-2413db80-d53b-11eb-987a-e08832167006.mp4

1.5.3 and below:

https://user-images.githubusercontent.com/15317421/123374128-7ce37400-d53b-11eb-84c1-e6ae17ee9784.mp4

This issue doesn't happen if you hold the note after hitting it.

**Comment by Spel0** [comment]
You can probably close it since it was fixed with #1229 and #1269

**Comment by RagdollClash** [comment]
good catch, thanks!
