### ISSUE TITLE
(Only Visual) Bug Report: Up is Down, Down is Up

### ISSUE THREAD

**Issue by ZmanAce** [KadeArchive/Kade-Engine#102]
#### Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.
I did. It might have something to do with my offset cause its so high... **NOPE!!!**
I even tried deleting and redownloading. That didn't work. Thankfully when I did that my high scores didn't go away.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows x64 download, x86 laptop.

## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1 FNF - 1.3.1 Kade Engine

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
There's only one step: PLAY ANY SONG

## Please describe your issue. Provide extensive detail and images if possible.
The images describe it all. And the title, that too.
No matter which song, scroll direction, control scheme, you name it, the moving arrows will have reversed directions for Up and Down only. Left and Right **aren't affected**
![FNFGLICH](https://user-images.githubusercontent.com/68093097/113146228-44eebe00-91e4-11eb-8a27-9fc7544c8633.png)
![FNFGlitch](https://user-images.githubusercontent.com/68093097/113146230-44eebe00-91e4-11eb-971d-383eea3f9052.png)

**Comment by Kade-github** [comment]
Fixed in the latest nightly build.
