### ISSUE TITLE
Bug Report: Type not found : discord_rpc.DiscordRpc

### ISSUE THREAD

**Issue by zenolth** [KadeArchive/Kade-Engine#1024]
Hello, I was compiling my game and I got these errors 
"source/Discord.hx:5: characters 8-30 : Type not found : discord_rpc.DiscordRpc
source/Discord.hx:14: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:24: characters 4-14 : Type not found : DiscordRpc
source/Discord.hx:29: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:34: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:39: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:75: characters 3-13 : Type not found : DiscordRpc"
Can someone help me fix them?

**Comment by Kade-github** [comment]
https://github.com/KadeDev/Kade-Engine/blob/master/BUILDING.md
