### ISSUE TITLE
Bug Report: Unable to hit notes on HTML5 build.

### ISSUE THREAD

**Issue by Keoiki** [KadeArchive/Kade-Engine#1025]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## What version of the game are you using? Look in the bottom left corner of the main menu.
KE 1.5.4

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Test on HTML5

## Please describe your issue. Provide extensive detail and images if possible.
I was going to start updating a mod to 1.5.4 but quickly found this issue on the HTML5 build which I do all the testing on. Began playing Roses to make it works but lost because none of the notes were being registered. I built a Desktop version and I could hit notes there perfectly fine. (See videos below, HTML5 version first, then Desktop version.)

Both HTML5 and Desktop versions were built using the newest version of source code as of writing. I did make sure that the settings on both versions were the same.

https://user-images.githubusercontent.com/55053690/123432616-3f322a00-d5d3-11eb-82a7-ee923a837b0a.mp4

https://user-images.githubusercontent.com/55053690/123432966-9f28d080-d5d3-11eb-83b4-47538b340910.mp4

**Comment by Kade-github** [comment]
Should be fixed in this commit https://github.com/KadeDev/Kade-Engine/commit/10d601ddc90dac1731d62eec67d6d9727f3cb997
