### ISSUE TITLE
Bug Report: Input system change makes repeated sustain notes (and possibly jacks) impossible.

### ISSUE THREAD

**Issue by ScrubRTA** [KadeArchive/Kade-Engine#1026]
I tried Bopeebo on KE 1.5.4, and between the 2nd and 3rd notes, if I hold the 2nd note even close to long enough, the 3rd note immediately registers as early as possible because I was holding the button. On previous versions, this wasn't the case - you could hold the 2nd note fully, quickly release right and press it again. Holding buttons shouldn't register as early tap inputs.

**Comment by Kade-github** [comment]
https://user-images.githubusercontent.com/26305836/123495783-f467e080-d5d9-11eb-8951-805e91e42fd2.mp4

fixed in https://github.com/KadeDev/Kade-Engine/commit/002479871540e30b2b7dc05f06a81b7a64c8472a
