### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by DoomEternal** [KadeArchive/Kade-Engine#1032]
When compiling the game it first asked for a webm download, which I provided, then I compile the game and it'll say "C:/HaxeToolkid/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189:   characters 30-43 : Warning : This typedef is depracated in favor of haxe.xml.Access" and it just wont do anything else.

**Comment by Kade-github** [comment]
not an error, thats a warning. if you get that, CTRL-C and restart the build. works for me so.
