### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by savirxd** [KadeArchive/Kade-Engine#1037]
source/PlayState.hx:1156: characters 14-29 : Cannot access private field SKIP_STEP_LIMIT
source/PlayState.hx:1156: characters 14-29 : Cannot access private field SKIP_STEP_LIMIT
source/WebmHandler.hx:32: characters 10-26 : Not enough arguments, expected io:webm.WebmIo, soundEnabled:Bool
source/WebmHandler.hx:33: characters 8-12 : webm.WebmPlayer has no field fuck
source/WebmHandler.hx:96: characters 8-21 : webm.WebmPlayer has no field changePlaying
source/WebmHandler.hx:102: characters 8-21 : webm.WebmPlayer has no field changePlaying
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/WebmHandler.hx:53: characters 8-12 : webm.WebmPlayer has no field fuck
source/WebmHandler.hx:119: characters 8-19 : webm.WebmPlayer has no field removePause

this is weird

**Comment by Kade-github** [comment]
https://github.com/KadeDev/Kade-Engine/blob/stable/docs/building.md
