### ISSUE TITLE
Enhancement: Make Linux build works

### ISSUE THREAD

**Issue by stilic** [KadeArchive/Kade-Engine#1043]
## What is your suggestion, and why should it be implemented?
I think the Linux build system may be fixed for make guys with an Linux PC can install Kade Engine on it.

**Comment by TheDrawingCoder-Gamer** [comment]
modcharts are likely broken but i am unsure of other breaky thingies.

**Comment by Kade-github** [comment]
> modcharts are likely broken but i am unsure of other breaky thingies.

been working on fixing that lately just gotta wait for a response on smth

**Comment by stilic** [comment]
I see it is fixed!
