### ISSUE TITLE
Bug Report: Holding down a note registers the next one instantly

### ISSUE THREAD

**Issue by ThatTransSky** [KadeArchive/Kade-Engine#1047]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86_64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.
 Kade Engine 1.5.4

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
1. Go to any song, preferably on hard difficulty.
2. Hold down a long note and the next note on the same line will be registered instantly.

## Please describe your issue. Provide extensive detail and images if possible.
While playing, whenever you hold down a long note and a note appears, it registers it instantly as if you tried to hit it.

**Comment by heckay** [comment]
Yea I have this issue too

**Comment by Phantom1224** [comment]
I also have this issue.

**Comment by Kade-github** [comment]
fixed in https://github.com/KadeDev/Kade-Engine/commit/002479871540e30b2b7dc05f06a81b7a64c8472a already.
