### ISSUE TITLE
Bug Report: crash on Freeplay (DiffCalc)

### ISSUE THREAD

**Issue by Lucky-56** [KadeArchive/Kade-Engine#1048]
## What version of the game are you using? Look in the bottom left corner of the main menu.
1.5.4 master 84d7b68af77fa02b2396558304f3d6277aff73e4
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
open Freeplay Menu
## Please describe your issue. Provide extensive detail and images if possible.
The game crashes on https://github.com/KadeDev/Kade-Engine/blob/84d7b68af77fa02b2396558304f3d6277aff73e4/source/DiffCalc.hx#L41

**Comment by Kade-github** [comment]
anything else? cuz it doesn't crash for me so uh.

**Comment by Lucky-56** [comment]
well I could try again

**Comment by Lucky-56** [comment]
ok, apparently it works now
