### ISSUE TITLE
Bug Report: 1.5.4 when binding to numpad the bindings switch to NULL 

### ISSUE THREAD

**Issue by GhostFire90** [KadeArchive/Kade-Engine#1049]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows x86_64
## What version of the game are you using? Look in the bottom left corner of the main menu.
1.5.4 release build
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Go into bindings,
Try to bind to numpad keys
## Please describe your issue. Provide extensive detail and images if possible.
Numpad keys are unable to be bound for keybinds

**Comment by isakube** [comment]
haha yeah FlxKey does that sometimes

**Comment by Kade-github** [comment]
no numpad's are blacklisted since our new input system won't be able to actually detect them.
