### ISSUE TITLE
I cant compile pls help

### ISSUE THREAD

**Issue by TyricSatyric** [KadeArchive/Kade-Engine#1050]
I have this error and i have a ApiStuff.hx file created (the black boxes is a privacity thing)

source/Main.hx:98: characters 21-30 : Unknown identifier : ourSource
source/Main.hx:98: characters 21-30 : For optional function argument 'vPath'
source/VideoState.hx:48: characters 31-46 : Cannot access static field SKIP_STEP_LIMIT from a class instance

**Comment by isakube** [comment]
brb gonna fix this :troll:

**Comment by ACardboardBox1** [comment]
àã more compile issues!!!! 😭

**Comment by TyricSatyric** [comment]
I fixed the error
