### ISSUE TITLE
YXAB Controller Buttons and Pause Menu issue

### ISSUE THREAD

**Issue by aladairmaxwell** [KadeArchive/Kade-Engine#1053]
So, the new controller update is cool and stuff. So, here is the thing. I made a bind for YXAB buttons, cause I don't like Dpad. And the pause menu going crazy. I cannot use Dpad for control, can't use buttons properly too. I press no matter what button and the game acting very weird. I can use Y for switching only up. A just to close the pause.

![image](https://user-images.githubusercontent.com/69295711/123524471-3fb1ea00-d6d3-11eb-8a70-4c467cd0d898.png)

After pressing B or X this thing happens. Resume button disappears. Trying to press Restart or Exit to menu with A just restarts the song.

![image](https://user-images.githubusercontent.com/69295711/123524501-63753000-d6d3-11eb-8ea7-a190ae95ea71.png)

**Comment by Kade-github** [comment]
fixed in https://github.com/KadeDev/Kade-Engine/commit/213b9688871f7e3a3413451811a09b2420ceb800

**Comment by aladairmaxwell** [comment]
Unfortunately, that didn't help. I have Dpad controls now for switching between buttons, but I still can't use gamepad YXAB for doing actions such as B for closing tab, A for activation, etc. Because I have bind for it in Controls neither Dpad buttons.
