### ISSUE TITLE
Bug Report: Pixel Note Asset Bugged (Visually)

### ISSUE THREAD

**Issue by KlutchDj** [KadeArchive/Kade-Engine#1060]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below. 'Windows 64'

## Please describe your issue. Provide extensive detail and images if possible.
When Using Optimization Mode on 1.5.4, the Pixel Note asset has a problem with its sprite being offset when inputting a note . Heres a Example - 

https://user-images.githubusercontent.com/81717689/123535855-5b75ba00-d6ec-11eb-9ae6-51ead78de675.mp4

**Comment by arceuss** [comment]
able to reproduce on latest linux dev build

**Comment by arceuss** [comment]
able to reproduce on linux 

https://user-images.githubusercontent.com/28229451/123847192-88d08c80-d8d3-11eb-955d-032df3f80c06.mp4

**Comment by Lucky-56** [comment]
I have a fix for that in my pr, but it's likely it won't get pulled soon as it is also changing the week locking mechanism.
#894

**Comment by Lucky-56** [comment]
fixed please close this issue
