### ISSUE TITLE
Various issues with idle animations

### ISSUE THREAD

**Issue by arthu-rguo** [KadeArchive/Kade-Engine#1061]
Latest release 1.5.4, issues were not present on 1.5.3 and below.

1. Boyfriend goes idle too quickly, often cutting off his own sing animations during dense note streams.
2. ~~When the camera focuses on the opponent, their idle animation will freeze.~~ _fixed_
3. ~~All opponent idle animations no longer sync with the music.~~ _fixed_

Here's a video showing the desynced headbanging at the beginning of the song, as well as Boyfriend cutting off his own animations by going idle. (ignore the awful gameplay lol)

edit: opened a pr for 1 and 2
edit: 1 and 2 now fixed, closing as this is now a dupe

https://user-images.githubusercontent.com/73672820/123536629-675b7f00-d6e0-11eb-863d-79627819ca87.mp4

**Comment by Kade-github** [comment]
3 is more or less a dup of #1018
2 is a main game issue
1 is a main game issue
