### ISSUE TITLE
Bug Report: In All Songs (with optimization turned on, if I make a mistake, the voice cuts off from player 1 "and I only go if I hit my turn")

### ISSUE THREAD

**Issue by NGS300** [KadeArchive/Kade-Engine#1066]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below. ('Win10x64bit")

## What version of the game are you using? Look in the bottom left corner of the main menu.
KE V1.5.4

https://user-images.githubusercontent.com/86559005/123546931-1033c980-d735-11eb-9926-6246a230a46b.mp4

https://user-images.githubusercontent.com/86559005/123547015-67399e80-d735-11eb-9017-d059c6397649.mp4

### Please describe your issue. Provide extensive detail and images if possible.
"Plz Fix This"

**Comment by ACardboardBox1** [comment]
i think it's cutting off cuz u missed, not sure about the other things tho

**Comment by ACardboardBox1** [comment]
oh the "and I only go if I hit my turn" is on purpose i think lol

**Comment by NGS300** [comment]
> oh the "and I only go if I hit my turn" is on purpose i think lol

(I think it's bad, because it breaks the music and the effect "because it's also just for the audio and the eye")

**Comment by Kade-github** [comment]
naw that's a base game mechanic and it's intended.

**Comment by yardmith** [comment]
@KadeDev 

So you're saying that that the the enemy's voice cutting off is intended? 'Cause last time I checked, only the BF can miss.

**Comment by ACardboardBox1** [comment]
> 
> 
> @KadeDev
> 
> So you're saying that that the the enemy's voice cutting off is intended? 'Cause last time I checked, only the BF can miss.

yes, it's intended. The vocals dont continue until you press a note again, so you could miss a note, and the opponent's section would just completely die out.

**Comment by RagdollClash** [comment]
the enemy's voice cutting off is intended due to how it mutes bf's voice, but it's always supposed to play when its the enemy's turn

https://user-images.githubusercontent.com/15317421/123739144-04dabe00-d85b-11eb-90dd-c74c9483253e.mp4

**Comment by Lucky-56** [comment]
and I assume when playing on optimized, there is now way to check if the opponent has played notes
