### ISSUE TITLE
Bug Report: game crashing after game trys to save a replay file

### ISSUE THREAD

**Issue by EnvyBun** [KadeArchive/Kade-Engine#107]
im on macos and while i was playing a level, the game crashed after playing the song with an error saying "Error : [file_open,assets/replays/replay-Tutorial-time1617214201391.61.kadeReplay]" it does this with every level (modded in or not)

**Comment by Kade-github** [comment]
Fixed in the latest commit. Should prolly wait until a new nightly comes out.
