### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by Wajegi** [KadeArchive/Kade-Engine#1073]
My version of Kade Engine won't compile. (1.5.4) this is the error
![erroragain](https://user-images.githubusercontent.com/83383274/123580047-a0f2bf80-d79e-11eb-8701-112354f10895.PNG)

**Comment by Raltyro** [comment]
Considering you don't have linc_luajit installed in haxelib, or i'm wrong.

**Comment by Wajegi** [comment]
> 
> 
> Considering you don't have linc_luajit installed in haxelib, or i'm wrong.

thanks it works now
