### ISSUE TITLE
I cannot download  lime rebuild extension-webm windows

### ISSUE THREAD

**Issue by ethancolon** [KadeArchive/Kade-Engine#1074]
![Capture](https://user-images.githubusercontent.com/67854275/123594167-62203200-d7bd-11eb-8aa1-b5a95fcb0e59.PNG)
When i was trying to make a mod  was download last one it say Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

**Comment by thunni-noi** [comment]
I think you're missing some component required for building windows version.
Written in the docs/building.md
[building.md](https://github.com/KadeDev/Kade-Engine/files/6724677/building.md)


### Windows-only dependencies (only for building *to* Windows. Building html5 on Windows does not require this)
If you are planning to build for Windows, you also need to install **Visual Studio 2019**. While installing it, *don't click on any of the options to install workloads*. Instead, go to the **individual components** tab and choose the following:

-   MSVC v142 - VS 2019 C++ x64/x86 build tools
-   Windows SDK (10.0.17763.0)
-   C++ Profiling tools
-   C++ CMake tools for windows
-   C++ ATL for v142 build tools (x86 & x64)
-   C++ MFC for v142 build tools (x86 & x64)
-   C++/CLI support for v142 build tools (14.21)
-   C++ Modules for v142 build tools (x64/x86)
-   Clang Compiler for Windows
-   Windows 10 SDK (10.0.17134.0)
-   Windows 10 SDK (10.0.16299.0)
-   MSVC v141 - VS 2017 C++ x64/x86 build tools
-   MSVC v140 - VS 2015 C++ build tools (v14.00)

This will install about 22 GB of crap, but is necessary to build for Windows.

If you've already installed all of this then i have no idea.(maybe try reinstall?)
