### ISSUE TITLE
Enhancement: different judgment timings?

### ISSUE THREAD

**Issue by arceuss** [KadeArchive/Kade-Engine#1076]
![judgementday](https://user-images.githubusercontent.com/28229451/123683838-ee584680-d809-11eb-8eab-89b77eb42b86.png)
and theres this if needed

**Comment by ScrubRTA** [comment]
Safe frames and complex accuracy exist. Also, I mentioned the possibility of a 5th judgement earlier, and Kade said "no, just no" - I think that's really not happening.

**Comment by isakube** [comment]
nah ^

**Comment by Kade-github** [comment]
> Safe frames and complex accuracy exist. Also, I mentioned the possibility of a 5th judgement earlier, and Kade said "no, just no" - I think that's really not happening.

^

**Comment by arceuss** [comment]
ok ill try safe frames then
