### ISSUE TITLE
 You must have a "project.xml" file or specify another valid project file when using the 'test' command

### ISSUE THREAD

**Issue by ethancolon** [KadeArchive/Kade-Engine#1079]
i have is bug when i try build a game or do modchart i get is
![save me](https://user-images.githubusercontent.com/67854275/123711775-05655b80-d83f-11eb-956c-0d69cebbc30e.PNG)

**Comment by ACardboardBox1** [comment]
click on the folders that appear until you see project.xml. copy the directory with project.xml, cd to it, and then lime build windows (or lime test windows)
