### ISSUE TITLE
extension-webm.ndll is not installed

### ISSUE THREAD

**Issue by RealLumiOff** [KadeArchive/Kade-Engine#1084]
It just doesnt get installed, what do I do?
Already tried:
haxelib git extension-webm https://github.com/KadeDev/extension-webm
haxelib run lime rebuild extension-webm windows (With new GetThreadContext failed error!)
Recompiling
Reinstalling EVERYTHING
Following the steps in https://github.com/KadeDev/Kade-Engine/blob/stable/docs/building.md

**Comment by Raltyro** [comment]
> It just doesnt get installed, what do I do?

```
haxelib git extension-webm https://github.com/KadeDev/extension-webm
haxelib run lime rebuild extension-webm windows
```

**Comment by RealLumiOff** [comment]
Thanks, I did that. But its literally NOT in the file.

**Comment by ACardboardBox1** [comment]
try recompiling?? idk

**Comment by RealLumiOff** [comment]
Ok how do I do that

**Comment by ACardboardBox1** [comment]
oh wait
if you compiled from the source code, just do that again
if you got the precompiled version, try redownloading it 

> 
> 
> Ok how do I do that

oh wait
if you got the source code, compile again,
if you got the precompiled one, try downloading it again

**Comment by RealLumiOff** [comment]
> oh wait
> if you compiled from the source code, just do that again
> if you got the precompiled version, try redownloading it
> 
> > Ok how do I do that
> 
> oh wait
> if you got the source code, compile again,
> if you got the precompiled one, try downloading it again

![image](https://user-images.githubusercontent.com/84149666/123841046-60ff1a00-d90f-11eb-8e66-f90a8f455e12.png)
Same error.

**Comment by Megaman9009** [comment]
THANK YOU Raltyro IT WORKED!!!! You need to type in command prompt on your computer search bar. Than paste that code in. After tht do a lime test and it should work!

**Comment by RealLumiOff** [comment]
> THANK YOU Raltyro IT WORKED!!!! You need to type in command prompt on your computer search bar. Than paste that code in. After tht do a lime test and it should work!

I literally said I already did it
Nice try here but I already said it doesnt work.

**Comment by ghost** [comment]
I'm having a similar problem with this.
This is what I get when I type in: haxelib run lime rebuild extension-webm windows
![WAAA](https://user-images.githubusercontent.com/77366347/123882238-360acb00-d8fb-11eb-93fc-4dcca026a2fe.png)

I already installed all the required dependencies so i don't know what to do.

 sorry for making this post i know its kinda off topic.

**Comment by Megaman9009** [comment]
> > THANK YOU Raltyro IT WORKED!!!! You need to type in command prompt on your computer search bar. Than paste that code in. After tht do a lime test and it should work!
> 
> I literally said I already did it
> Nice try here but I already said it doesnt work.

Oh Im not sure then. Is it your first time doing this or have you done it before?

**Comment by ghost** [comment]
> Oh Im not sure then. Is it your first time doing this or have you done it before?

no not really besides trying to build a exe file on the normal fnf.

**Comment by Megaman9009** [comment]
Yeah so with kade engine you It makes you download extra stuff with it. Check the build instructions again. I dont remember but it made download an extra haxlib thing. Also you might need to use Visual Studio 2019 for Kade engine

**Comment by ghost** [comment]
> Yeah so with kade engine you It makes you download extra stuff with it. Check the build instructions again. I dont remember but it made download an extra haxlib thing. Also you might need to use Visual Studio 2019 for Kade engine

I Downloaded VS Community 2019 Serval Times To Get The Packages I Need And Visual Studio Failed Each Time Or It Was Kade Engine

**Comment by Raltyro** [comment]
> I'm having a similar problem with this.
> This is what I get when I type in: haxelib run lime rebuild extension-webm windows
> ![WAAA](https://user-images.githubusercontent.com/77366347/123882238-360acb00-d8fb-11eb-93fc-4dcca026a2fe.png)
> 
> I already installed all the required dependencies so i don't know what to do.
> 
> sorry for making this post i know its kinda off topic.

```
haxelib install HXCPP_VARS
```
?

**Comment by ghost** [comment]
> haxelib install HXCPP_VARS

I am confused about what you are trying to do or say. because it says no project such as : HXCPP_VARS
I'm confused because there is no context of what you are trying to say

**Comment by RealLumiOff** [comment]
> Oh Im not sure then. Is it your first time doing this or have you done it before?

First time.

**Comment by Kade-github** [comment]
Follow each step in 
https://github.com/KadeDev/Kade-Engine/blob/stable/docs/building.md

**Comment by RealLumiOff** [comment]
> Follow each step in
> https://github.com/KadeDev/Kade-Engine/blob/stable/docs/building.md

I did, but the file is not there
