### ISSUE TITLE
Bug Report: "No Ghost Tapping" Has Zero Discernable Gameplay Differences From "Ghost Tapping"

### ISSUE THREAD

**Issue by RareBeeph** [KadeArchive/Kade-Engine#1085]
Having attempted to mash through a song with both settings, I fail to see any distinction between the settings. This seems to imply that the "No Ghost Tapping" variant is not functioning properly.

EDIT: This problem does not occur for me in 1.5.3, however it does occur in 1.5.4

**Comment by isakube** [comment]
try pressing buttons where there aren't. it's fine.

**Comment by MBCollector672** [comment]
> try pressing buttons where there aren't. it's fine.

this does absolutely nothing. i was excited to see this feature added but it just doesn't work at all for me.

**Comment by arthu-rguo** [comment]
works for me...? ghost tap on = no miss, off = miss

**Comment by RareBeeph** [comment]
for me, ghost tap on = no miss, off = also no miss

**Comment by BlueDude557** [comment]
Hey Idk if a solution will come out of this, but I wanted to confirm that I'm actually having the same issue. Whether Ghost Tapping is on or off, my gameplay is only behaving like it's on. What's weirder, I'm pretty sure it was initially fine when 1.5.4 came out, and now it seems like it stopped working after compiling.

**Comment by Kade-github** [comment]
Fixed in https://github.com/KadeDev/Kade-Engine/commit/1f75d363b3f8da53f0bbb5c2636ce171e113006e
