### ISSUE TITLE
Week 7 to kade engine

### ISSUE THREAD

**Issue by Xucaaaa** [KadeArchive/Kade-Engine#1087]
Week 7 source code, i need

**Comment by ACardboardBox1** [comment]
week 7 is a newgrounds exclusive preview, we dont have the source code to it yet

**Comment by epicbobmanbob** [comment]
it will come once week 7 is downloadable.

**Comment by ACardboardBox1** [comment]
^

**Comment by Xucaaaa** [comment]
And nobody knows when the official 0.2.8 comes out?

**Comment by isakube** [comment]
no. now close

**Comment by ACardboardBox1** [comment]
^

**Comment by Lucky-56** [comment]
> 
> 
> Week 7 source code, i need

don't we all ?
**pls close**
