### ISSUE TITLE
Enhancement: speedmod or something

### ISSUE THREAD

**Issue by arceuss** [KadeArchive/Kade-Engine#11]
like a menu to change the chart speed to 1.05x 1.1x etc

**Comment by Kade-github** [comment]
idk this can be changed via the charter already. low on the list.

**Comment by arceuss** [comment]
huh i never knew that

**Comment by Kiffolisk** [comment]
> idk this can be changed via the charter already. low on the list.

yes it can be done, it changes notespeed
