### ISSUE TITLE
Bug Report: Error compiling the game.

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#110]
## It brings these two error messages.

source/Controls.hx:411: characters 25-33 : Array<Int> has no field contains
source/Replay.hx:94: characters 16-17 : Missing type declaration

And I haven't edited or touched these files. Help!

I'm using lime 7.9.0 and openfl 9.0.2 and haxe 4.0
![Screenshot (24)](https://user-images.githubusercontent.com/64946614/113212262-86af5100-9244-11eb-8d40-b0a394633988.png)

**Comment by Kade-github** [comment]
We cannot help you build the engine. You must do this yourself. Make sure you are updated to the latest commit though.
