### ISSUE TITLE
Bug Report: Week 6 Shows A Black Screen

### ISSUE THREAD

**Issue by raf13lol** [KadeArchive/Kade-Engine#1106]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows x86_64
## What version of the game are you using? Look in the bottom left corner of the main menu.
1.5.4
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Yes. Just go to week 6 and play any song.
## Please describe your issue. Provide extensive detail and images if possible.
It shows a black screen and just the player's notes and other.
![Screenshot 2021-06-30 192735](https://user-images.githubusercontent.com/79861112/124012951-9f610b80-d9d9-11eb-99ab-6f91f811fbe1.png)

**Comment by NGS300** [comment]
disable optimization on options

**Comment by arceuss** [comment]
you have optimization on

**Comment by raf13lol** [comment]
oh thanks guys
