### ISSUE TITLE
Bug Report: DownScroll Arrows

### ISSUE THREAD

**Issue by tahiadz1962** [KadeArchive/Kade-Engine#111]
Operating system: Windows (x86/x64)

0.2.7.1 FNF - 1.3.1 Kade Engine

When up and down arrows are un-hit on DownScroll, they are flipped.

Screenshot 1:
![downscroll](https://user-images.githubusercontent.com/79606983/113213053-9c714600-9245-11eb-93db-96612ce43afd.PNG)

Screenshot 2:
![downscroll2](https://user-images.githubusercontent.com/79606983/113213106-ac892580-9245-11eb-8389-bfe63c2690df.PNG)

**Comment by tahiadz1962** [comment]
Ask me if you want a replay!

**Comment by Kade-github** [comment]
this was fixed in Nightly2

**Comment by tahiadz1962** [comment]
Oh...

**Comment by NukeThief** [comment]
But how you download Nightly2? What even is this?

**Comment by NukeThief** [comment]
nvm i found what it is nvm
