### ISSUE TITLE
Bug Report: Offset Number Decimals 

### ISSUE THREAD

**Issue by KlutchDj** [KadeArchive/Kade-Engine#112]
64bit Windows 10 btw , downloaded obviously 0.2.7.1 

So when i head into the settings menu to mess around to see any offset bug , and i have found one that is coverts the 1 digit into infinite decimals in some numbers like 4 and 7 and more , and only by doing this is just changing the offest 

Here is some for example :

![Screenshot (73)](https://user-images.githubusercontent.com/81717689/113224931-1c9da880-9252-11eb-80ad-3d759c899aff.png)
![Screenshot (72)](https://user-images.githubusercontent.com/81717689/113224962-29220100-9252-11eb-9084-4f5c2c1efdb7.png)
![Screenshot (71)](https://user-images.githubusercontent.com/81717689/113224969-2de6b500-9252-11eb-8932-9d2c485d3273.png)

**Comment by Kade-github** [comment]
thats more of a visual glitch. we're going to end up truncating it anyways so it doesn't really matter.
