### ISSUE TITLE
Won't compile with extension-webm for Windows

### ISSUE THREAD

**Issue by catchclover** [KadeArchive/Kade-Engine#1127]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
macOS

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.5.4
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Just trying to compile the game with extension-webm for Windows
## Please describe your issue. Provide extensive detail and images if possible.
When I attempt to compile Kade for Windows, It gives me the error "/usr/local/lib/haxe/lib/extension-webm/git/webm/WebmPlayer.hx:3: characters 8-15 : You cannot access the cpp package while targeting neko (for cpp.Lib)
source/WebmHandler.hx:12: characters 18-28 :     referenced here" When I compile for Mac, however, it works just fine. I am on MacOS Big Sur.

**Comment by ALX-00** [comment]
You cannot compile for windows if you are using mac, it also won't work vice-versa.
