### ISSUE TITLE
Bug Report: "Time Your Offset" Crashes your game

### ISSUE THREAD

**Issue by KlutchDj** [KadeArchive/Kade-Engine#113]
0.2.7.1 kade obviously 64bit , (Kade 1.3.1 Nightly 3) 

When i booted up the game , i went to go test out the New "Time your offset" feature in the Options menu , only to find out that it gives me a error saying there isnt a ID with this option and when you click "Ok" it crashes your game . 
![Screenshot (74)](https://user-images.githubusercontent.com/81717689/113225337-017f6880-9253-11eb-81cc-e06e4f657e09.png)

**Comment by KlutchDj** [comment]
I did look at the Offsettes file in the data folder , the coding was all there so idk what was the issue

**Comment by GuyOnAComputer** [comment]
was about to report this, same thing happened to me

**Comment by Kade-github** [comment]
I'm probably just gonna set it to use tutorial to just ignore this entire problem.
