### ISSUE TITLE
Bug Report: Can't compile the game.

### ISSUE THREAD

**Issue by Smiley-official** [KadeArchive/Kade-Engine#1132]
When i typing "lime test windows -debug -clear" (and without -debug -clear) i have those errors:
source/ModchartState.hx:15: characters 8-20 : Type not found : llua.Convert
source/ModchartState.hx:16: characters 8-16 : Type not found : llua.Lua
source/ModchartState.hx:17: characters 8-18 : Type not found : llua.State
source/ModchartState.hx:18: characters 8-17 : Type not found : llua.LuaL
source/ModchartState.hx:27: characters 24-29 : Type not found : State
source/StoryMenuState.hx:22: lines 22-399 : Defined in this class
source/PlayState.hx:1174: characters 32-51 : Class<ModchartState> has no field createModchartState
source/PlayState.hx:1175: characters 16-28 : ModchartState has no field executeState
source/PlayState.hx:2451: characters 16-19 : ModchartState has no field die
source/PlayState.hx:2501: characters 19-22 : ModchartState has no field die
source/PlayState.hx:1721: characters 16-22 : ModchartState has no field setVar
source/PlayState.hx:1722: characters 16-22 : ModchartState has no field setVar
source/PlayState.hx:1723: characters 16-22 : ModchartState has no field setVar
source/PlayState.hx:1724: characters 16-28 : ModchartState has no field executeState
source/PlayState.hx:1739: characters 36-42 : ModchartState has no field getVar
source/PlayState.hx:1740: characters 31-37 : ModchartState has no field getVar
source/PlayState.hx:1742: characters 20-26 : ModchartState has no field getVar
source/PlayState.hx:1761: characters 25-31 : ModchartState has no field getVar
source/PlayState.hx:1762: characters 25-31 : ModchartState has no field getVar
source/PauseSubState.hx:5: characters 8-16 : Type not found : llua.Lua
source/PlayState.hx:1848: characters 17-20 : ModchartState has no field die
source/PlayState.hx:1890: characters 17-20 : ModchartState has no field die
source/PlayState.hx:1902: characters 17-20 : ModchartState has no field die
source/PlayState.hx:2047: characters 17-23 : ModchartState has no field setVar
source/PlayState.hx:2057: characters 28-34 : ModchartState has no field getVar
source/PlayState.hx:2058: characters 28-34 : ModchartState has no field getVar
source/PlayState.hx:2064: characters 18-30 : ModchartState has no field executeState
source/PlayState.hx:2091: characters 28-34 : ModchartState has no field getVar
source/PlayState.hx:2092: characters 28-34 : ModchartState has no field getVar
source/PlayState.hx:2099: characters 18-30 : ModchartState has no field executeState
source/PlayState.hx:2346: characters 20-32 : ModchartState has no field executeState
source/PlayState.hx:3107: characters 17-29 : ModchartState has no field executeState
source/PlayState.hx:2888: characters 38-50 : ModchartState has no field executeState
source/PlayState.hx:2889: characters 38-50 : ModchartState has no field executeState
source/PlayState.hx:2890: characters 36-48 : ModchartState has no field executeState
source/PlayState.hx:2891: characters 39-51 : ModchartState has no field executeState
source/PlayState.hx:3258: characters 19-31 : ModchartState has no field executeState
source/PauseSubState.hx:195: characters 29-32 : ModchartState has no field die
source/PlayState.hx:3397: characters 16-22 : ModchartState has no field setVar
source/PlayState.hx:3398: characters 16-28 : ModchartState has no field executeState
source/PlayState.hx:3432: characters 16-22 : ModchartState has no field setVar
source/PlayState.hx:3433: characters 16-28 : ModchartState has no field executeState
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
How to fix it?

**Comment by Smiley-official** [comment]
If you want watch my project there it is:
`<?xml version="1.0" encoding="utf-8"?>
<project>
	

	<app title="Friday Night Funkin' VS BF" file="Funkin" packageName="com.ninjamuffin99.funkin" package="com.ninjamuffin99.funkin" main="Main" version="0.2.7.1" company="ninjamuffin99" />

	
	<set name="APP_ID" value="0x0100f6c013bbc000" />

	
	
	<app preloader="flixel.system.FlxPreloader" />

	
	<set name="SWF_VERSION" value="11.8" />

	

	
	<window width="1280" height="720" fps="" background="#000000" hardware="true" vsync="false" />

	
	<window if="html5" resizable="true" />

	
	<window if="desktop" orientation="landscape" fullscreen="true" resizable="true" vsync="false"/>

	
	<window if="mobile" orientation="landscape" fullscreen="true" width="0" height="0" resizable="false"/>

	
	<window if="switch" orientation="landscape" fullscreen="true" width="0" height="0" resizable="true" />

	

	<set name="BUILD_DIR" value="export_FORMOD/debug" if="debug" />
	<set name="BUILD_DIR" value="export_FORMOD/release" unless="debug" />
	<set name="BUILD_DIR" value="export_FORMOD/32bit" if="32bit" />

	<classpath name="source" />

	<assets path="assets/preload" rename="assets" exclude="*.ogg" if="web"/>
	<assets path="assets/preload" rename="assets" exclude="*.mp3" unless="web"/>
	
	
	<define name="PRELOAD_ALL" unless="web" />
	<define name="NO_PRELOAD_ALL" unless="PRELOAD_ALL"/>
	
	<section if="PRELOAD_ALL">
		<library name="songs"    preload="true" />
		<library name="shared"   preload="true" />
		<library name="tutorial" preload="true" />
		<library name="week1"    preload="true" />
		<library name="week2"    preload="true" />
		<library name="week3"    preload="true" />
		<library name="week4"    preload="true" />
		<library name="week5"    preload="true" />
		<library name="week6"    preload="true" />
		<library name="dialogue"    preload="true" />
	</section>
	
	<section if="NO_PRELOAD_ALL">
		<library name="songs"    preload="false" />
		<library name="shared"   preload="false" />
		<library name="tutorial" preload="false" />
		<library name="week1"    preload="false" />
		<library name="week2"    preload="false" />
		<library name="week3"    preload="false" />
		<library name="week4"    preload="false" />
		<library name="week5"    preload="false" />
		<library name="week6"    preload="false" />
	</section>
	
	<assets path="assets/songs"    library="songs"    exclude="*.ogg" if="web"/>
	<assets path="assets/songs"    library="songs"    exclude="*.mp3" unless="web"/>
	<assets path="assets/shared"   library="shared"   exclude="*.ogg" if="web"/>
	<assets path="assets/shared"   library="shared"   exclude="*.mp3" unless="web"/>
	<assets path="assets/tutorial" library="tutorial" exclude="*.ogg" if="web"/>
	<assets path="assets/tutorial" library="tutorial" exclude="*.mp3" unless="web"/>
	<assets path="assets/week1"    library="week1"    exclude="*.ogg" if="web"/>
	<assets path="assets/week1"    library="week1"    exclude="*.mp3" unless="web"/>
	<assets path="assets/week2"    library="week2"    exclude="*.ogg" if="web"/>
	<assets path="assets/week2"    library="week2"    exclude="*.mp3" unless="web"/>
	<assets path="assets/week3"    library="week3"    exclude="*.ogg" if="web"/>
	<assets path="assets/week3"    library="week3"    exclude="*.mp3" unless="web"/>
	<assets path="assets/week4"    library="week4"    exclude="*.ogg" if="web"/>
	<assets path="assets/week4"    library="week4"    exclude="*.mp3" unless="web"/>
	<assets path="assets/week5"    library="week5"    exclude="*.ogg" if="web"/>
	<assets path="assets/week5"    library="week5"    exclude="*.mp3" unless="web"/>
	<assets path="assets/week6"    library="week6"    exclude="*.ogg" if="web"/>
	<assets path="assets/week6"    library="week6"    exclude="*.mp3" unless="web"/>
	
	<assets path='example_mods' rename='mods' embed='false'/>
	<assets path='art/readme.txt' rename='do NOT readme.txt' />
	
	
	<assets path="CHANGELOG.md" rename='changelog.txt'/>

	
	<assets path="assets/fonts" embed='true'/>
	

	<haxelib name="flixel" />
	<haxedev set='webgl' />

	
	<haxelib name="flixel-addons" />
	<haxelib name="hscript" />

	
	<haxelib name="flixel-ui" />
	<haxelib name="newgrounds"/>
	<haxelib name="faxe" if='switch'/>
	<haxelib name="polymod"/>
	<haxelib name="discord_rpc" if="desktop"/>
	

	
	

	
	

	

	
	

	
	

	
	

	
	
	
	
	

	
	

	
	

	
	<haxedef name="FLX_NO_FOCUS_LOST_SCREEN" />

	
	<haxedef name="FLX_NO_DEBUG" unless="debug" />

	
	<haxedef name="NAPE_RELEASE_BUILD" unless="debug" />

	

	
	
	<icon path="art/icon16.png" size='16'/>
	<icon path="art/icon32.png" size='32'/>
	<icon path="art/icon64.png" size='64'/>
	<icon path="art/iconOG.png" />


	
	<haxedef name="NG_LOGIN" if="newgrounds" />
	
</project>`

**Comment by Lucky-56** [comment]
do you have all dependencies installed ?

**Comment by Smiley-official** [comment]
> do you have all dependencies installed ?

Yes, from haxe and haxelib to lime and visualstudio 2019.

**Comment by Smiley-official** [comment]
No one can help me
