### ISSUE TITLE
Bug Report: Compiling Error

### ISSUE THREAD

**Issue by EcoVeni** [KadeArchive/Kade-Engine#1133]
Hey! i have a problem. i want to make a mod for fnf like a gamer but when i want to compile the game i am getting this error

source/PlayState.hx:3379: characters 17-32 : Class<webm.WebmPlayer> has no field SKIP_STEP_LIMIT
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access

anyone know how to fix it? please.

Information: Kade engine version: latest OS: Windows 10 64 bit Command: lime test windows -debug

please help me with this

**Comment by MadeySlime** [comment]
Go to Playstate.hx, find the code (WebmPlayer.SKIP_STEP_LIMIT = 90;) at the line 3379 and delete it ! then save the hx file

**Comment by EcoVeni** [comment]
OMG THANKS YOU ARE A GENIUS!
