### ISSUE TITLE
Bug Report: Number pad won't work with the keybinds

### ISSUE THREAD

**Issue by KutikiPlayz** [KadeArchive/Kade-Engine#1138]
I usually use the keys z x num2 and num3 for playing, but whenever I try to use 2 or 3 it just says "null" and when I press those buttons after I open a song nothing happens.

**Comment by isakube** [comment]
known, close

**Comment by KlutchDj** [comment]
this is pretty known. if you are using numpad keys to play , just keep using autohotkey for now on. haxe doesnt pick up numpad controls for some reason.
