### ISSUE TITLE
Enhancement: Speeding and slowing down songs

### ISSUE THREAD

**Issue by blackm1n** [KadeArchive/Kade-Engine#114]
## What is your suggestion, and why should it be implemented?
Here's an idea I have. Speeding and slowing down songs. What I mean by that is there's a speed setting that if changed, changes how fast the song and chart goes. Clone Hero would be a great example. People love to speed up easier songs to smth like 150% speed and try to FC them. I think it will also be cool for FNF

**Comment by MoezTrigui** [comment]
lol it already exists in vanilla fnf change the bpm and distance between arrows

**Comment by MagnusStrom** [comment]
Looked into this: Not possible unless you want bloat

**Comment by puyoxyz** [comment]
uhhh search isseus i guess,,,,, we already explained why this cant happen somewhere else idk
