### ISSUE TITLE
Story Menu Bug

### ISSUE THREAD

**Issue by Glitch-Animates** [KadeArchive/Kade-Engine#1145]
I am trying to make a mod and I am trying to edit the story menu and every time I enter the story menu, I get an error message saying: haxe.xml.XmlParserException: Expected = at line 162 char 26, if anyone could help that would be appreciated.
![KE Issue](https://user-images.githubusercontent.com/85759654/124328687-1c19f400-db58-11eb-83b8-92847b4438c7.PNG)

**Comment by epicbobmanbob** [comment]
can you give me the StoryMenuState file's code?
i might be able to fix it

**Comment by Glitch-Animates** [comment]
> can you give me the StoryMenuState file's code?
> i might be able to fix it

[StoryMenuState_hx.zip](https://github.com/KadeDev/Kade-Engine/files/6757626/StoryMenuState_hx.zip)
here you go

**Comment by Lucky-56** [comment]
what does your `campaign_menu_UI_assets.xml` look like in `assets/preload/images`

**Comment by Glitch-Animates** [comment]
![campaign_menu_UI_characters](https://user-images.githubusercontent.com/85759654/124339781-be4cd280-db7e-11eb-952a-11e373607a6e.png)

****XML FILE IS BELOW****
	SubTexture name="Glitch idle Black Lines0001" x="4227" y="3093" width="232" height="726/>
	SubTexture name="Glitch idle Black Lines0002" x="4515" y="3093" width="232" height="726"/>
	SubTexture name="Glitch idle Black Lines0003" x="4799" y="3091" width="232" height="726"/>
	SubTexture name="Glitch idle Black Lines0004" x="5084" y="3090" width="232" height="726"/>
	SubTexture name="Glitch idle Black Lines0005" x="5084" y="3105" width="232" height="726"/>
	SubTexture name="Glitch idle Black Lines0006" x="5084" y="3111" width="232" height="726"/>
	SubTexture name="Glitch idle Black Lines0007" x="5084" y="3111" width="232" height="726"/>
	SubTexture name="Glitch idle Black Lines0008" x="5084" y="3111" width="232" height="726"/>
	SubTexture name="Glitch idle Black Lines0009" x="5084" y="3111" width="232" height="726"/>
	SubTexture name="Glitch idle Black Lines0010" x="5084" y="3111" width="232" height="726"/>
	SubTexture name="Glitch idle Black Lines0011" x="5084" y="3111" width="232" height="726"/>
	SubTexture name="Glitch idle Black Lines0012" x="4799" y="3091" width="232" height="726"/>
	SubTexture name="Glitch idle Black Lines0013" x="4515" y="3093" width="232" height="726"/>
</TextureAtlas>
 
Had to type it out
dindt want to edit the whole thing so I just did the xml for glitch

**Comment by Lucky-56** [comment]
1. you forgot a " on the first line at height

2. it should look like this:
```xml
<TextureAtlas imagePath="campaign_menu_UI_characters.png">
	<SubTexture name="Glitch idle Black Lines0001" x="4227" y="3093" width="232" height="726" />
	<SubTexture name="Glitch idle Black Lines0002" x="4515" y="3093" width="232" height="726" />
	<SubTexture name="Glitch idle Black Lines0003" x="4799" y="3091" width="232" height="726" />
	<SubTexture name="Glitch idle Black Lines0004" x="5084" y="3090" width="232" height="726" />
	<SubTexture name="Glitch idle Black Lines0005" x="5084" y="3105" width="232" height="726" />
	<SubTexture name="Glitch idle Black Lines0006" x="5084" y="3111" width="232" height="726" />
	<SubTexture name="Glitch idle Black Lines0007" x="5084" y="3111" width="232" height="726" />
	<SubTexture name="Glitch idle Black Lines0008" x="5084" y="3111" width="232" height="726" />
	<SubTexture name="Glitch idle Black Lines0009" x="5084" y="3111" width="232" height="726" />
	<SubTexture name="Glitch idle Black Lines0010" x="5084" y="3111" width="232" height="726" />
	<SubTexture name="Glitch idle Black Lines0011" x="5084" y="3111" width="232" height="726" />
	<SubTexture name="Glitch idle Black Lines0012" x="4799" y="3091" width="232" height="726" />
	<SubTexture name="Glitch idle Black Lines0013" x="4515" y="3093" width="232" height="726" />
</TextureAtlas>
```
but with all the other characters too xD
