### ISSUE TITLE
Enhancement: Health % in the HUD

### ISSUE THREAD

**Issue by sdslayer** [KadeArchive/Kade-Engine#1147]
This could be put next to Accuracy before your current rating
Displays your Health as a percentage (50% at the start of a song, 100% if bar is fully green, 0% when you fail)

**Concept Image**
![concept](https://user-images.githubusercontent.com/32582698/124337686-81c2ac00-db69-11eb-976f-e51cefebfa91.png)

**Comment by Kade-github** [comment]
Never. I hate it.

**Comment by sdslayer** [comment]
well ok then my bad bro
