### ISSUE TITLE
game crashes after hovering over a newly made week on macos

### ISSUE THREAD

**Issue by EnvyBun** [KadeArchive/Kade-Engine#115]
i created week 7 in the code correctly, all the songs work in freeplay but when i hover over the newly made week the game crashes not even letting me start the week

**Comment by theDetourist** [comment]
Are you sure the problem is with the engine? Did you try debugging with trace() to see if it isn't your code that's actually broken?

**Comment by Kade-github** [comment]
> Are you sure the problem is with the engine? Did you try debugging with trace() to see if it isn't your code that's actually broken?

Exactly. We cannot help you with your own code.
