### ISSUE TITLE
Bug Report: Freeplay menu skips songs and selecting one chooses the wrong song

### ISSUE THREAD

**Issue by RagdollClash** [KadeArchive/Kade-Engine#1151]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86_64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.
AppVeyor compiled version of 293df1e2b87e61b00df97a67fcb6ab5e72a9f961

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
1. Go to Freeplay
2. Press down
3. Press enter

## Please describe your issue. Provide extensive detail and images if possible.
In the Freeplay menu, the selection will only select every other song. Selecting the song will actually take you to the next song.
I have tested this on a blank save file to ensure it wasn't an issue with the save.

https://user-images.githubusercontent.com/15317421/124340132-dbc27200-db67-11eb-9e54-b25a440eac11.mp4

**Comment by Lucky-56** [comment]
yeah I noticed that, but was to lazy to create an issue today so thanks I guess

**Comment by arceuss** [comment]
same here

**Comment by Kade-github** [comment]
Fixed in the pr above this msg
