### ISSUE TITLE
Bug Report: Keybinds like Comma and Period are buggy when you try to hit a note with them

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#1167]
## Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows (`x86_64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.5.4 Kade Engine
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Using any keybinds that are symbols, like Comma, Period, Semicolon, etc. (excluding the arrow keys)

## Please describe your issue. Provide extensive detail and images if possible.
My main key bindings for any rythm game are Z, X, Comma and Period. I downloaded the VS Sunday mod and found out that you could change your keybinds (yes i'm really outdated in Kade Engine lmao), so i changed it to my main, i went on story mode to play the Sunday week and tried hitting the keys Comma and Period, i couldn't hit the notes, i restarted the song because i lost and tried using the arrow keys, which worked, i tried changing the keybinds to Z X Period Semicolon and the same happened.

**Comment by Spel0** [comment]
I think you should create a bug report in sunday repo, this issue have nothing to do with vanilla kade engine

**Comment by isakube** [comment]
w e . k n o w
