### ISSUE TITLE
Bug Report:I can't build it.

### ISSUE THREAD

**Issue by PapyrusSwap3** [KadeArchive/Kade-Engine#117]
It says "lime is not internal or external
command, executable program, or batch file."
Such thing wuth butler.

**Comment by theDetourist** [comment]
Did you follow the instructions @ the [README.md](https://github.com/KadeDev/Kade-Engine/blob/master/README.md) properly?

**Comment by PapyrusSwap3** [comment]
> Did you follow the instructions @ the [README.md](https://github.com/KadeDev/Kade-Engine/blob/master/README.md) properly?

Yes,I read it and install all what I need,but I still can't build it,the same error.
