### ISSUE TITLE
Bug Report: Could not find haxelib "extension-webm" even if it is installed

### ISSUE THREAD

**Issue by flustix** [KadeArchive/Kade-Engine#1175]
OS: Windows x86

Version: Newest (1.5.4)

Steps:
1. Compile the Project

Description:
When i try to compile a fresh installation of the Kade Engine Source Code i get an error that "extension-webm" could not be found. But i installed the library from KadeDev's link in Project.xml [https://github.com/KadeDev/extension-webm/] and it still doesn't work 
![image](https://user-images.githubusercontent.com/65369281/124383505-198cdb00-dccd-11eb-8b65-61b2244b79ed.png)

**Comment by Raltyro** [comment]
you havent rebuild it i guess

**Comment by flustix** [comment]
what?

**Comment by isakube** [comment]
HAXELIB REBUILD EXTENSION-WEBM WINDOWS
HAVE WE PUT THIS IN BUILDING YET

**Comment by flustix** [comment]
rebuild is not a haxelib command

**Comment by arceuss** [comment]
> rebuild is not a haxelib command

correct
its lime rebuild extension-webm windows

**Comment by ACardboardBox1** [comment]
> 
> 
> HAXELIB REBUILD EXTENSION-WEBM WINDOWS
> HAVE WE PUT THIS IN BUILDING YET

lemme check

**Comment by flustix** [comment]
@arceuss thanks

**Comment by ACardboardBox1** [comment]
> 
> 
> @arceuss thanks

now close 😤
