### ISSUE TITLE
Bug Report: Ghost tapping wont turn off despite turning it off in settings 

### ISSUE THREAD

**Issue by Gold93284** [KadeArchive/Kade-Engine#1178]
So even when i have the "No Ghost Tapping" Option selected it still doesn't turn off ghost tapping. P.S this is on the desktop version not browser

**Comment by TurtleLoverTy** [comment]
Wait, you mean that you didn't encounter this issue on the browser or you didn't test out the browser version? Because I had this issue on both the windows and browser versions of the game.

**Comment by Gold93284** [comment]
> Wait, you mean that you didn't encounter this issue on the browser or you didn't test out the browser version? Because I had this issue on both the windows and browser versions of the game.

yes it dosent work on browser either i tried there

**Comment by Kade-github** [comment]
Fixed in https://github.com/KadeDev/Kade-Engine/commit/1f75d363b3f8da53f0bbb5c2636ce171e113006e
