### ISSUE TITLE
When loading a character, the game gives the message [NULL OBJECT REFERENCE] and crashes.

### ISSUE THREAD

**Issue by WaterKat98** [KadeArchive/Kade-Engine#1184]
So I'm making a mod to FNF and following this tutorial.

https://www.youtube.com/watch?v=ddzZ8hJROWw&list=PLAPMw90C3Tr58Z7ayeQvdod5Mxb7D_ciN&index=7

And when I loaded my character, the game gives a crash report and closes. I've tried things to get it to work, but I cannot. What am I doing wrong?

**Comment by ACardboardBox1** [comment]
i think this should be a discussion
