### ISSUE TITLE
Bug Report: Keybinding P to your controls will still pause the game.

### ISSUE THREAD

**Issue by IJustLikeModFiles** [KadeArchive/Kade-Engine#1187]
no, that's it. nothing more complex.

(This might be a stupid thing to write as I'm on the official kade-engine page and not the mod page, but it happened to me on [Castle Crashers Boss Rush - Barbarian Champion mod](https://gamebanana.com/mods/299039) and it's on 0.2.7.1)
## 0.2.7.1

**Comment by KlutchDj** [comment]
could you possibly send a video doing that on the kade 1.5.4? because im not having this issue. either you are using a outdated kade or your literally using the vanilla engine.

**Comment by IJustLikeModFiles** [comment]
> could you possibly send a video doing that on the kade 1.5.4? because I'm not having this issue. either you are using an outdated kade-engine or you're literally using the vanilla engine.

[ain't prepared for 10MB huh](https://drive.google.com/file/d/1g6Ij5xcfDr-4RQXOIZ0sOnps5-AIFTLH/view?usp=sharing)
