### ISSUE TITLE
it says im playing kade engine but not showing any info

### ISSUE THREAD

**Issue by Clover12469** [KadeArchive/Kade-Engine#119]
its not showing the song status or any of that shiz 
![image](https://user-images.githubusercontent.com/56419130/113351269-3eedff80-9300-11eb-8f16-10c4479fb76a.png)

**Comment by Kiffolisk** [comment]
did you put kade engine as game activity or not? if so it might be that

**Comment by Kade-github** [comment]
this is due to the base games repo not cleaning up discord-rich presence. it'll be fixed.

**Comment by Clover12469** [comment]
oh ok thanks

**Comment by Kade-github** [comment]
Fixed in the latest release
