### ISSUE TITLE
Bug Report: Lua modchart doesn't work on Linux

### ISSUE THREAD

**Issue by Penncilk** [KadeArchive/Kade-Engine#1195]
While modding FNF on Linux, I noticed that modchart.lua doesn't work on this system, I looked in the code and saw that it was done with #if windows is there a way around this? or should I wait for a update to solve it?

Sorry if this was a easy question, sincerely, JTU

**Comment by isakube** [comment]
lol no

the lua library we use only has binaries or something for Windows, which congratulations on cross-platform there aidan

**Comment by Kade-github** [comment]
I'M ALREADY TRYING TO GET IT TO WORK STOP MAKING ISSUES :((((
https://github.com/AndreiRudenko/linc_luajit/issues/7

**Comment by Penncilk** [comment]
Sorry for the trouble, thank you for letting me know! I can't wait to see the outcome, and I meant no trouble ^^

Thank you for the awesome work put into this mod KadeDev! ^^
