### ISSUE TITLE
Compiling Issue.

### ISSUE THREAD

**Issue by DoomEternal** [KadeArchive/Kade-Engine#1196]
I try to compile the game and add the folders and files necessary but this will always pop up, every. single. time. 

source/PlayState.hx:3379: characters 17-32 : Class<webm.WebmPlayer> has no field SKIP_STEP_LIMIT
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access

**Comment by ghost** [comment]
To fix that go into the webm extension folder in the haxe folder. After that go into webm folder. When your in there open up webmplayer.hx with whatever you use to code. After that go to the line that says public var SKIP_STEP_LIMIT = 0; and replace it with public static var SKIP_STEP_LIMIT = 0;

You then save it and try to compile kade engine. After that it should work.

**Comment by wefrewergqerg** [comment]
thanks it worked

**Comment by RonyxDumb** [comment]
THANKSSSS!!!!!!! I HAVE THIS PROBLEM FOR A LONG TIME
THANKK YOUUU
