### ISSUE TITLE
FNF Kade Engine Modding Compiling issue

### ISSUE THREAD

**Issue by XRocketBoiX** [KadeArchive/Kade-Engine#1199]
So whenever I type this command to compile the game, ("lime test windows") it says "typedef is deprecated", also I am adding Tankman to the coded Kade Engine, so Idk if that is the problem or, but I really hate when it does that, because it pushes it away from creating my own FNF mod. So can someone please fix this?

**Comment by KlutchDj** [comment]
may you send a screenshot of the error ?

**Comment by ACardboardBox1** [comment]
thats a deprecation
it doesnt do anything
try compiling again

**Comment by FelipeBacana** [comment]
> may you send a screenshot of the error ?

![Captura de Tela (933)](https://user-images.githubusercontent.com/87283163/126199188-9bd0c638-cb46-45ba-a976-2fa748b266a9.png)
I having this issue to.Forget about this portuguese thing
