### ISSUE TITLE
Enhancement: Ability to toggle on/off the charting clap

### ISSUE THREAD

**Issue by ScarabWasTaken** [KadeArchive/Kade-Engine#1201]
## What is your suggestion, and why should it be implemented?
The clap is a little echoy making high nps sections difficult to check while charting. It also means theres no way to listen to the music on its own while charting if there are notes on the section. Its also a little buggy when it comes to pressing pause/play.

Being able to toggle it on/off would be a great QoL improvement.

**Comment by KlutchDj** [comment]
are you referring to the note hit sounds ? because if you are , that is a toggleable in the Data Section. if not , then this is confusing of what this enhancement is or im just dumb.

**Comment by ScarabWasTaken** [comment]
Well then I'm either stupid, on an old build, blind, or all of the above. Lol

**Comment by Kade-github** [comment]
yeah this exists already
