### ISSUE TITLE
HTML5 Compile Problem

### ISSUE THREAD

**Issue by Yuuki795** [KadeArchive/Kade-Engine#121]
When compiling to HTML5 trying to load a custom song and chart it just stops on the loading screen not giving me any errors even when using -debug

**Comment by Assestions** [comment]
custom song as in u edited a week?

**Comment by Yuuki795** [comment]
made a new week

**Comment by theDetourist** [comment]
By "new week", you mean new code too?

**Comment by Yuuki795** [comment]
yea but it works when building it for windows

**Comment by theDetourist** [comment]
Sorry to tell you that but we don't give support for custom code, if it isn't something exclusively problematic on the engine itself, we can't help you with it.

**Comment by Jaduplex** [comment]
> Sorry to tell you that but we don't give support for custom code, if it isn't something exclusively problematic on the engine itself, we can't help you with it.

I've done this in base kade engine too. Doesn't compile HTML5 no matter what

**Comment by Kade-github** [comment]
this shoulda been fixed
