### ISSUE TITLE
Bug Report: 'lime' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Clemisome** [KadeArchive/Kade-Engine#1213]
I'm Trying To Test My Mod But I Can't Do Anything Because `lime` Refuses To Work And Just Keeps Giving Me The Error Line Of When A Command Either Doesn't Make Sense Or It Doesn't Exist.

'lime' is not recognized as an internal or external command,
operable program or batch file.

(https://user-images.githubusercontent.com/87088102/124869734-88ae4c00-dfb9-11eb-9c8f-b6bc1d9b3750.png)

Please Help Me.

**Comment by greenec03** [comment]
type `haxelib install lime` inside of the terminal

**Comment by Clemisome** [comment]
> haxelib install lime

'haxelib' is not recognized as an internal or external command,
operable program or batch file.

**Comment by greenec03** [comment]
> > haxelib install lime
> 
> 'haxelib' is not recognized as an internal or external command,
> operable program or batch file.

install haxe from haxe.org (you dont have haxe)

**Comment by Clemisome** [comment]
> > > haxelib install lime
> > 
> > 
> > 'haxelib' is not recognized as an internal or external command,
> > operable program or batch file.
> 
> install haxe from haxe.org (you dont have haxe)

Nope. Not Working. But Don't Worry. I Forgot To Do setup.bat! I've Fixed It Now

**Comment by greenec03** [comment]
Ok np!
