### ISSUE TITLE
Make the loading screen pre-cache everything.

### ISSUE THREAD

**Issue by CowSoftware** [KadeArchive/Kade-Engine#1214]
**What is your suggestion, and why should it be implemented?** I think making the loading screen pre-cache stuff could improve the performance and since I got a good computer, this game still struggles to run on my PC.

**Comment by isakube** [comment]
we already cache garbage so i have no idea what you mean

**Comment by CowSoftware** [comment]
Huh? So I might have messed up something in my settings of my graphic card. Thanks for answering.
