### ISSUE TITLE
I cant load a new character to the game

### ISSUE THREAD

**Issue by greenec03** [KadeArchive/Kade-Engine#1215]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Windows ('x86_64')

## What version of the game are you using? Look in the bottom left corner of the main menu.

1.5.4

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

I have not identified any steps to reproduce the bug.

## Please describe your issue. Provide extensive detail and images if possible.

When I add a new character and load it into the game, the game just crashes.
I dont know why this happens but it just does it. Here are some videos/photos:

https://user-images.githubusercontent.com/70741560/124907666-c8158080-e02b-11eb-8e02-c741fec9e695.mp4

![Screenshot (9)](https://user-images.githubusercontent.com/70741560/124908614-d6b06780-e02c-11eb-985a-44f159dd561e.png)

**Comment by RagdollClash** [comment]
did you add a healthicon entry for them as well?

**Comment by Blixermations** [comment]
Yea I have, I used the 'face' one for it and in game it says it cant find it

**Comment by greenec03** [comment]
> did you add a healthicon entry for them as well?

Yea I have, I used the 'face' one for it and in game it says it cant find it

**Comment by epicbobmanbob** [comment]
> > did you add a healthicon entry for them as well?
> 
> Yea I have, I used the 'face' one for it and in game it says it cant find it

That's because the game looks for a defined icon that is the name of that character.
So this is what you would do in HealthIcon.hx `animation.add('cwin', [10, 11], 0, false, isPlayer);`

**Comment by Blixermations** [comment]
> That's because the game looks for a defined icon that is the name of that character.
> So this is what you would do in HealthIcon.hx `animation.add('cwin', [10, 11], 0, false, isPlayer);`

Ok thanks ill see if that works

**Comment by greenec03** [comment]
@meeptey2 I just loaded Kade engine after compiling it but it still doesn't want to load

**Comment by epicbobmanbob** [comment]
Sorry for the long reply! Maybe its the custom folder?

**Comment by greenec03** [comment]
> Sorry for the long reply! Maybe its the custom folder?

Probably is, ill change the source code and update the file and edit this post stating if it worked.

EDIT: It didn't :(

**Comment by greenec03** [comment]
I was able to figure out the problem! The .png file that the xml file was trying to reach did not exist. it for some reason was trying to find cwin.png_assets which didn't exist. I have know idea how that happened but I fixed it!
