### ISSUE TITLE
How do you open the offset editor for player 1?

### ISSUE THREAD

**Issue by EvanOrSomething** [KadeArchive/Kade-Engine#1217]
8 opens up the offset editor for player 2, but I need it for player 1. No other button on my keyboard seems to do anything.

**Comment by NeeEoo** [comment]
Pressing 0 should open the offset editor for player 1

**Comment by ACardboardBox1** [comment]
if that doesnt work just put ur player 1 as player 2 in the charting menu

**Comment by EvanOrSomething** [comment]
> if that doesnt work just put ur player 1 as player 2 in the charting menu

Ended up just doing this
