### ISSUE TITLE
Bug Report: FlxGamepadAttachment error after compilation

### ISSUE THREAD

**Issue by reithegoat** [KadeArchive/Kade-Engine#122]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
n/a

## What version of the game are you using? Look in the bottom left corner of the main menu.
Version 1.4 Source Code

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
I tried compiling the game within Visual Studio Code. It seemed to use this command `lime build windows -debug --haxelib=hxcpp-debug-server --connect 6000`

## Please describe your issue. Provide extensive detail and images if possible.
I received this error when it tried to open the game after compilation.
```
Link: ApplicationMain-debug.exe
   Creating library ApplicationMain-debug.lib and object ApplicationMain-debug.exp
2e3bca92_FlxGamepadAttachment.obj : error LNK2011:  precompiled object not linked in; image may not run Hint on symbols that are defined and could potentially match:

__@@_PchSym_@00@UtrgsfyUpzwvRvmtrmvCUvckligUwvyftUdrmwldhUlyqUlyqUnhexBJGERwvyftRmxUPPkxsUifmgrnvUscxkkOlyq@linkb15a6d14e76b9416881676023b4d480d    

__@@_PchSym_@00@UtrgsfyUufmprmUvckligUwvyftUdrmwldhUlyqUlyqUnhexBJGERwvyftRmxUPPkxsUszcvUscxkkOlyq@linka287f4763c91921ac3533fc173dcb227

__@@_PchSym_@00@UztvmgUPdlipUGDUhUrmgvinvwrzgvUexgllohUoryxlmxigOmzgrevkilqPPCAIGEFEHHHUlyqiUznwGEUkxsOlyq@4B2008FD98C1DD4     

ApplicationMain-debug.exe : fatal error LNK1120: 1 unresolved externals

The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command lime test windows -debug --haxelib=hxcpp-debug-server --connect 6000" terminated with exit code: 1.
```

**Comment by theDetourist** [comment]
Delete the contents inside export and recompile again.

**Comment by Kiffolisk** [comment]
Remove the "export" folder
