### ISSUE TITLE
Enhancement: "fullscreen" global boolean for modcharts

### ISSUE THREAD

**Issue by leppycolon3** [KadeArchive/Kade-Engine#1234]
## What is your suggestion, and why should it be implemented?
being able to toggle whether the game is in fullscreen or not could be useful for modcharts that mess with the window, because messing with the window on fullscreen kinda breaks the game.

**Comment by Kade-github** [comment]
more or less can be accomplished by proxy with 
```lua
resizeWindow(getScreenWidth(),getScreenHeight())
```

**Comment by Kade-github** [comment]
> more or less can be accomplished by proxy with
> 
> ```lua
> resizeWindow(getScreenWidth(),getScreenHeight())
> ```

^ and to undo that just do smth like this `resizeWindow(1280,720)`

**Comment by leppycolon3** [comment]
i think i didn't explain it well, this is what i meant by in fullscreen it breaks the game

https://user-images.githubusercontent.com/60763676/125156133-4e1fed00-e13a-11eb-94e3-ce6f35d3f3d3.mp4

i tried to resize the screen in function start() and it just made the screen offset down
