### ISSUE TITLE
Bug Report: Customize Gameplay crashes (1.4.2 onwards)

### ISSUE THREAD

**Issue by fletcherdotnet** [KadeArchive/Kade-Engine#1237]
- This issue has been submitted but closed and moved to another issue, that doesn't at all relate. 

- My system is running on Windows x86.

- I'm developing on 1.4.2, however this also happens on mods such as VS Camellia which runs on 1.5.4.

Go to Settings > Gameplay > Customize Gameplay. This will cause the game's audio to stutter on a black screen and then crash. Running in debug mode gives a Null Object Reference error and the console cannot find the Boyfriend assets or idle animation. I do have the assets in the correct places.
![image](https://user-images.githubusercontent.com/85912871/125165063-33c32f00-e18d-11eb-829f-9106c839637e.png)

**Comment by isakube** [comment]
## Alright
what idiot forgot to add the shared library to the asset reference

**Comment by Jaduplex** [comment]
> ## Alright
> what idiot forgot to add the shared library to the asset reference

it was probably just because no one bothered to update it when that became a requirement for asset references lol

**Comment by fletcherdotnet** [comment]
Fixed. Both BF and Daddy Dearest don't have `,"shared")` at the end of their paths argument in Character.hx, but adding it fixes the crashes and loads Customize Gameplay just fine.
