### ISSUE TITLE
I can't add a song 

### ISSUE THREAD

**Issue by BobGaming** [KadeArchive/Kade-Engine#1245]
I can't select my song in the chart editor no audio plays it says 0/0 for time i can't fix it i've done multiple file edits and txt edits but no matter what i do i can't fix it I'm using the latest version but it also doesn't work in 1.4.2 i haven't tried any other versions 
![image](https://user-images.githubusercontent.com/87250802/125180029-4b5ce080-e1aa-11eb-89a5-5bb3b94ad77c.png)
![image](https://user-images.githubusercontent.com/87250802/125180036-53b51b80-e1aa-11eb-8617-dbb6c851c982.png)
![image](https://user-images.githubusercontent.com/87250802/125180042-5e6fb080-e1aa-11eb-8707-7d09e8c9a532.png)
![image](https://user-images.githubusercontent.com/87250802/125180063-a42c7900-e1aa-11eb-8bef-738a34396991.png)

**Comment by KlutchDj** [comment]
my bro , it needs to be a ogg before you can actually play it on the game. and if you havent alrdy , rename the song ID in the source code before you could actually play it. and delete the other files as well

**Comment by BobGaming** [comment]
> my bro , it needs to be a ogg before you can actually play it on the game. and if you havent alrdy , rename the song ID in the source code before you could actually play it. and delete the other files as well

it's already ogg dude but i will look at that source code thing

**Comment by BobGaming** [comment]
> my bro , it needs to be a ogg before you can actually play it on the game. and if you havent alrdy , rename the song ID in the source code before you could actually play it. and delete the other files as well

where do i go to rename it in the source code

**Comment by BobGaming** [comment]
after much trial and error it turns out i had false information and you can't name your files with spaces instead of dashes in the newer updates
