### ISSUE TITLE
Bug Report: Potential Breaking Changes from Recent Discord Rpc Package

### ISSUE THREAD

**Issue by massivelivefun** [KadeArchive/Kade-Engine#125]
## If you are playing a downloaded version of the game, what operating system are you using?
x64 Windows 10 Version 20H2 (OS Build: 19042.870)

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.4 Release Source Code Zip Package

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Going through the repository's README.md build instruction will produce this build error.

## Please describe your issue. Provide extensive detail and images if possible.
![image](https://user-images.githubusercontent.com/9347096/113465677-e8a9bb00-93ea-11eb-8347-e508c0735530.png)

When building the game the discord rpc dependency makes the build fail. There were recent changes in the repo about 7 days ago: https://github.com/Aidan63/linc_discord-rpc

They are probably breaking changes with the 1.4 release of the Kade Engine.

**Comment by SamAugust69** [comment]
Same issue here

**Comment by SamAugust69** [comment]
A quick really bad fix, for now, would be just removing the **discord.hx** file and inside of **MusicBeatState.hx**, on line 3, removing the **import Discord.DiscordClient;**

**Comment by Kade-github** [comment]
consider just wrapping those imports in
```haxe
#if desktop

#end
```
