### ISSUE TITLE
Bug Report: can't compile the game bcz of this error

### ISSUE THREAD

**Issue by LK-Lilon** [KadeArchive/Kade-Engine#1255]
Update:**It's fixed now... I had to reinstall discord_rpc. I already had it installed but idk why it couldn't use it... Anyways I deleted the old one and installed it again now its working perfectly 🙂**

**When i tried to compile this fresh kade engine copy i got this error**

source/Discord.hx:5: characters 8-30 : Type not found : discord_rpc.DiscordRpc
source/Discord.hx:14: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:24: characters 4-14 : Type not found : DiscordRpc
source/Discord.hx:29: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:34: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:39: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:75: characters 3-13 : Type not found : DiscordRpc
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access

_I haven't change anything inside it yet_
### I am using the latest kade engine

**If anyone knows how to fix this please let me know**

**Comment by SimplyMerlin** [comment]
Have you followed [this](https://kadedev.github.io/Kade-Engine/building)?
It seems like you havent ran the command `haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc`

**Comment by LK-Lilon** [comment]
@SimplyMerlin I did run all the commands. Still I will run them again to see if that fixes it.

**In case if it doesn't work, is there any other solution to fix this?**
