### ISSUE TITLE
Bug Report: FPS Counter is not enabled on startup according to saved settings

### ISSUE THREAD

**Issue by cuckydev** [KadeArchive/Kade-Engine#1264]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows (`x86_64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.
KE 1.5.4 (Latest binary off release as of writing this)

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Enable "FPS COUNTER" in Options -> Misc, then restart the game
![image](https://user-images.githubusercontent.com/44537737/125208324-9be24580-e25f-11eb-9726-9f25c84c71e2.png)

## Please describe your issue. Provide extensive detail and images if possible.
When "FPS COUNTER" is set to ON, the FPS counter is displayed, but upon resetting the game it will not appear until you toggle the option off and back on again. See image above.

**Comment by cuckydev** [comment]
Note: this may have been fixed after the latest release, but I looked through both the issues and pull requests and saw nothing related to this issue so I've assumed it's still an issue. If it has been fixed already though, please do close.

**Comment by Trayfellow** [comment]
lego yoda death sound
