### ISSUE TITLE
Enhancement: Skip Song > Story Mode

### ISSUE THREAD

**Issue by KlutchDj** [KadeArchive/Kade-Engine#1268]

**Comment by KlutchDj** [comment]
WHY IS IT IN BOLD

**Comment by ACardboardBox1** [comment]
THIS
OR LIKE WHEN YOU FIX DIALOGUE FOR A CERTAIN SONG BUT IT'S ON LIKE A 2ND OR THIRD SONG SO YOU DONT HAVE TO GO THROUGH THE SONGS
