### ISSUE TITLE
Freeplay is broken in 1.4 

### ISSUE THREAD

**Issue by Assestions** [KadeArchive/Kade-Engine#128]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows 10 Home Edition (64-bit)

## What version of the game are you using? Look in the bottom left corner of the main menu.
KadeEngine 1.4. Game version 2.7.1

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
i tried redownloading KadeEngine and restarting the game nothing worked
(https://user-images.githubusercontent.com/81839175/113480288-95bf1a80-9461-11eb-83ab-bcb00109b546.PNG)

## Please describe your issue. Provide extensive detail and images if possible.
(https://user-images.githubusercontent.com/81839175/113480288-95bf1a80-9461-11eb-83ab-bcb00109b546.PNG)
freeplay menu shows tutorial only

**Comment by Kiffolisk** [comment]
Huh

**Comment by Assestions** [comment]
?

**Comment by Assestions** [comment]
i downloaded it again, seems to work

**Comment by Kade-github** [comment]
it's not
