### ISSUE TITLE
Bug Report: when i run "lime test windows or

### ISSUE THREAD

**Issue by HePpYPro** [KadeArchive/Kade-Engine#1284]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows (`x86)
## What version of the game are you using? Look in the bottom left corner of the main menu.
1.5.4
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible
No
## Please describe your issue. Provide extensive detail and images if possible.
![2021-07-12-14-29-43](https://user-images.githubusercontent.com/79279257/125287848-b549c700-e31d-11eb-9540-e95b3cf4a6b6.png)
![2021-07-14-12-43-26](https://user-images.githubusercontent.com/79279257/125609514-68f372dc-4405-47fd-b3cd-7d2831783d49.png)

Well, every single time i run the command "lime test windows" or "lime test windows -debug" it says this: Error: Pointer.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include\yvals.h(12): fatal error C1083: Unable to open include file: 'crtdbg.h': No such file or directory. 

And when i run the command lime rebuild extension-webm windows says what it says on the 2 image

And i'm asking to you if you know anyway to solve that crap because even though i try it never works
P.S: When i try it with instead of windows, but html5 it dosen't give me the custom exe, it gets me to a page where is the exe but still i prefer the exe.

Have a great day and the person that solves me this crap will be on the credits of my mod

**Comment by LK-Lilon** [comment]
_I think u didn't install all the Microsoft Visual 2019 **individual components** or one of them didn't install properly._

 I exactly don't know what is missing here but I'm sure that it's related to Microsoft Visual 2019 since you can build the html5 version.

**Possible solution: I think you should reinstall Microsoft Visual 2019 with all of the individual components for windows/mac/Linux (whatever u are on) mentioned [here](https://github.com/KadeDev/Kade-Engine/blob/stable/docs/building.md).**

**Comment by HePpYPro** [comment]
I tried everything you said but still dosen't work and also i cannot download (lime rebuild extension-webm windows) so now i think that is relationed with the problem

**Comment by LK-Lilon** [comment]
@HePpYPro what version of Haxe you are using? Bcz the latest version of haxe have some issues with kade engine..

**You will need the [Haxe 4.1.5](https://haxe.org/download/version/4.1.5/) version**

**Comment by HePpYPro** [comment]
@LK-Lilon i'm using the 4.1.5 but i think when you run the command haxelib update flixel it updates haxe to 4.2.1/ the lastest version.

**Comment by HePpYPro** [comment]
i've tried to do what you told me to do on the 1 message:"I think u didn't install all the Microsoft Visual 2019 individual components or one of them didn't install properly." And i tried to do it again because i didn't knew how to install the components but they are downloading so thank you for resolving tthe problem and this issue, is offically closed

Thx and bye!!
