### ISSUE TITLE
Bug Report: a bug with compiling

### ISSUE THREAD

**Issue by tofu111456** [KadeArchive/Kade-Engine#1285]
So I was trying to compile Kade Engine, but then this popped up when I tried to compile with the background and music and stuff:

source/PlayState.hx:531: characters 4-18 : Cannot rebind this method : please use 'dynamic' before method declaration
source/PlayState.hx:690: characters 18-20 : Int has no field l2
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access

I tried to switch versions from 1.5.4 (or whatever latest release) to 1.3, but the same thing popped up. PLEASE I NEED A HELP TO FIX IT

**Comment by LK-Lilon** [comment]
I think ur problem is located here
**Location : source/PlayState.hx 
Line :690 
Between 18 - 20 characters. 
Problem : Int has no field l2**
_It looks like u forgot to put a value (maybe..)_

**Comment by tofu111456** [comment]
![image](https://user-images.githubusercontent.com/69342634/125385695-2bedcf80-e3c5-11eb-94fb-0957d986e137.png)
i mean this is what i wrote

**Comment by LK-Lilon** [comment]
I'm not too sure but I think u need a _y_ value there? In the end of camPos? 
![IMG_20210713_115558](https://user-images.githubusercontent.com/87257947/125398740-82f9a180-e3d1-11eb-9379-e6ea07dda4e0.png)

**Comment by tofu111456** [comment]
![image](https://user-images.githubusercontent.com/69342634/125462017-eb37b2c4-ff41-4e55-89e1-07b71e1cfbf8.png)
neh.
ima retry to code everything. ill tell if the issue still happens

**Comment by tofu111456** [comment]
![image](https://user-images.githubusercontent.com/69342634/125560763-26b07a38-045d-40e6-9b5f-b1d6b7f13b9b.png)
now this happened

**Comment by tofu111456** [comment]
no one seem to reply, so i think ill close the issue. thanks for not helping me

**Comment by ACardboardBox1** [comment]
> 
> 
> no one seem to reply, so i think ill close the issue. thanks for not helping me

it's probably the flxg.cameras shit, change that back to whatever it said, cuz when people get that error that's the answer most of the time.

**Comment by ACardboardBox1** [comment]
also make sure derp is a character in character.hx and fully working.
btw you put 106.l2 and not 106.12 as the y value. hehe

**Comment by chriz993** [comment]
> 
> 
> also make sure derp is a character in character.hx and fully working.
> btw you put 106.l2 and not 106.12 as the y value. hehe

ohhhh i didnt even realize that until u said it lol

**Comment by tofu111456** [comment]
> 
> 
> also make sure derp is a character in character.hx and fully working.
> btw you put 106.l2 and not 106.12 as the y value. hehe

oh i didnt even realize that lol
im gonna try to recode it

**Comment by tofu111456** [comment]
> 
> 
> also make sure derp is a character in character.hx and fully working.
> btw you put 106.l2 and not 106.12 as the y value. hehe

i tried to recode it and the same thing still happens (also derp is a character and it already functions)

**Comment by tofu111456** [comment]
i think ill try to RE-REcode it again but on ke 1.5.4
