### ISSUE TITLE
Still YouCant Delete Notes

### ISSUE THREAD

**Issue by UnknownSkid** [KadeArchive/Kade-Engine#129]
Why Arent You Fixing That???!!

**Comment by Kiffolisk** [comment]
Should be already fixed. By the way, please do not insist on something for no reason.

**Comment by Assestions** [comment]
none did insist and how do u insist for a reason? what im gonna say "FIXX IT NOW BC I SAID SO" and it will be ok? wtf

**Comment by Kiffolisk** [comment]
He's saying "Why Arent You Fixing That???!!" even though it's already fixed.

**Comment by Assestions** [comment]
are u assuming someones gender? bruh u dont know boy or girl

**Comment by Toppat-dalek** [comment]
I can still delete notes so idk what you're talking about.

**Comment by Assestions** [comment]
btw xyyb20 

Try this:

Redownload KadeEngine 1.4

ReLaunch the game

Make sure the music file you put is a ogg file and matchs the name

Make sure the music u wanna put in has a Inst not just voices

**Comment by Kiffolisk** [comment]
> are u assuming someones gender? bruh u dont know boy or girl

Yes, I am. What's wrong with assuming genders again? Sure, you could call a girl a boy, but it doesn't really matter that much.

**Comment by Kiffolisk** [comment]
It's not a crime.

**Comment by Assestions** [comment]
i know but still its rude

**Comment by Assestions** [comment]
and calling a girl a boy is rude

**Comment by Kade-github** [comment]
we already fixed it lol
