### ISSUE TITLE
Bug Report: game spams misses if you press a normal note while doing a jump hold i think?

### ISSUE THREAD

**Issue by arceuss** [KadeArchive/Kade-Engine#13]
i pressed a normal note while doing a long hold and the game spams misses and i instantly die

**Comment by arceuss** [comment]
on new input btw

**Comment by Kade-github** [comment]
I've never seen this happen. Could you provide a video?

**Comment by arceuss** [comment]
whats your discord ill send it there

**Comment by arceuss** [comment]
ill send it tomorrow tho cuz im going to bed

**Comment by Kade-github** [comment]
> ill send it tomorrow tho cuz im going to bed

Please send it here.

**Comment by Kiffolisk** [comment]
cringe........................................................ he didnt send.....................................

**Comment by arceuss** [comment]
it seems to happen on some simfiles converted to fnf tho
not all of them

**Comment by arceuss** [comment]
i was using get fucked from uksrt8 with [https://github.com/shockdude/fnf-to-sm/releases/](https://github.com/shockdude/fnf-to-sm/releases/) if you wanna try it

**Comment by Kade-github** [comment]
> i was using get fucked from uksrt8 with https://github.com/shockdude/fnf-to-sm/releases/ if you wanna try it

probably due to notes being between beats (aka squares) in the editor.

**Comment by arceuss** [comment]
huh

**Comment by Kiffolisk** [comment]
if you hold shift, snap gets toggled and you can place notes everywhere

**Comment by Kade-github** [comment]
wait I was tired this isn't at all the write repo I was writing in lmao. But uh still need a video though.

**Comment by Kade-github** [comment]
I still haven't received a video. Im going to close this, if you encounter it again re-comment on this.

**Comment by FatBoyJohn** [comment]
I just had this issue and i also have a video to show it

https://user-images.githubusercontent.com/87459156/125724396-c1ff7494-eb1f-41f6-8a3e-fc6e4d8c8adb.mp4
