### ISSUE TITLE
Bug Report: Voices file error

### ISSUE THREAD

**Issue by Toppat-dalek** [KadeArchive/Kade-Engine#130]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows 10

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.4 kade dev engine

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Well it seems as if it happens when the original song SHOULD have ended

## Please describe your issue. Provide extensive detail and images if possible.
The voice track seems to cut out for little to no reason. I worked again after the section that it first cut out on once I put notes there, but that section still had no voice even after I put notes.

**Comment by Toppat-dalek** [comment]
oh and the song was bopeebo

**Comment by Assestions** [comment]
was it the only song that glitched?

**Comment by Assestions** [comment]
no glitchs on my end

**Comment by Toppat-dalek** [comment]
huh. might just be my copy of the game then. the song was 5 mins long so that could have something to do with it

**Comment by Toppat-dalek** [comment]
could the voice file and inst file being slightly different lengths have something to do with it?

**Comment by Toppat-dalek** [comment]
section 32 seems to be where it is happening. Ill check the JSON to see if that's messing with it.

**Comment by Kiffolisk** [comment]
The game code automatically runs the "endSong" function once the instrumentals are completed, meaning it's probably the voice files.

**Comment by Toppat-dalek** [comment]
I mean, the song still goes on. and it's only a 2-second difference between the inst and the voices

**Comment by Toppat-dalek** [comment]
hold on it could have something to do with the difference

**Comment by Toppat-dalek** [comment]
the problem is still there even after I made them the same length

**Comment by theDetourist** [comment]
Can you post a video of it so we can see it?

**Comment by Toppat-dalek** [comment]
This is mainly a mod for my friend so keep that in mind. I don't wanna get sued for making a mod I'm not gonna post. but still, I want to know a fix for this if it happens with a song/chart I intend to post. (also I just made the chart. the song and other mods are not mine) also, I know the audio quality is absolute garbage. also, JT music made the song if you're curious. 


https://user-images.githubusercontent.com/77013267/113493369-b2347480-94ac-11eb-9aa3-52421821f8a7.mp4

**Comment by theDetourist** [comment]
Bopeebo does have some beats that are hard coded to be muted for some reason, but it's only three of them. Is the charted part without vocals supposed to be the problem?

**Comment by Toppat-dalek** [comment]
yea but now that I know what the problem is I can just switch over to fresh in order to fix it.
