### ISSUE TITLE
Bug Report: Funkin.exe keeps disappearing after I extract it. 

### ISSUE THREAD

**Issue by zelofi** [KadeArchive/Kade-Engine#131]
After I extract it, it pops up with a message
**"Cannot open KadeEngine1.4-Release-Edited\Funkin.exe.**

Does anyone know how to fix this?

**Comment by Assestions** [comment]
then sucks for you

**Comment by Assestions** [comment]
obv im kidding, 
Try this:
Redownload KadeEngine
dont extract it and install winrar or 7-zip

if those dont work then idk what will

**Comment by Assestions** [comment]
and dont install the source code  install the engine not the source

**Comment by Assestions** [comment]
wait, no its your problem, u have linux or macos, they cant run .exe files, sorry but u cant download unless they make a new verson for linux or macos

**Comment by Assestions** [comment]
install windows 10 on a virtualbox to run

**Comment by Kiffolisk** [comment]
Are you on Mac or Linux? If so, please use Wine.

**Comment by Assestions** [comment]
wine doesent work because the dll is different then linuxs and linuxs code is different so it wont match up if u use wine

**Comment by Assestions** [comment]
macos is the same

**Comment by Assestions** [comment]
and even if u replace the file executables it wont work, sorry man tuff luck on getting this engine ported

**Comment by Kiffolisk** [comment]
"lime build mac"

**Comment by Assestions** [comment]
still

**Comment by Kade-github** [comment]
ur av
