### ISSUE TITLE
Question: While trying to add dialogue to a little Kade Engine mod I am doing for myself, I decided to not add dialogue, and now this error pops up.

### ISSUE THREAD

**Issue by TheGamingCat89** [KadeArchive/Kade-Engine#1312]
I've deleted the dialogue code and the .txt files for the dialogue, any idea on what's causing this issue?
![image](https://user-images.githubusercontent.com/81439207/125548162-1ca057ea-1829-45a4-b0bc-4453acb40346.png)
(was suggested to post this here)

**Comment by Voidymite** [comment]
what do u really think is going on? put a file named dialogue1.txt in that location and put random dialogue shit in it so it works

**Comment by TheGamingCat89** [comment]
> what do u really think is going on? put a file named dialogue1.txt in that location and put random dialogue shit in it so it works

lmao i guess ill try that

**Comment by ACardboardBox1** [comment]
sarvente
