### ISSUE TITLE
Bug Report: Game Crashing with Custom Noteskins

### ISSUE THREAD

**Issue by ishsharm0** [KadeArchive/Kade-Engine#1320]
#### Please check for duplicates, similar issues or closed issues with the same problem, as well performing simple troubleshooting steps (such as deleting the export folder if it's an issue with compiling, reinstalling Kade Engine) before submitting an issue.

Done.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Running Win-10 x64 edition.

## What version of the game are you using? Look in the bottom left corner of the main menu.

I'm currently running v1.5.4 (latest as of this report).

#### 1. Replace in-game noteskins with the ones I used.

Can be done (using decompiled version) by going into `assets/shared/images/NOTE_assets.png` and `assets/shared/images/NOTE_assets.xml` and replacing them.

The files I used can be found here  (png, xml, fla):
[noteskins-KE-issue.zip](https://github.com/KadeDev/Kade-Engine/files/6825701/noteskins-KE-issue.zip)

2. `lime test windows` and try any song.

## Please describe your issue. Provide extensive detail and images if possible.

When I use the noteskins above and go into any song, the game simply crashes. No errors logged into console, nothing like that. A video demonstration can be found here:

https://user-images.githubusercontent.com/73258485/125847251-ee3e9813-7700-4ef3-b236-40d96798a494.mp4

I have not modified any of the input systems, simply the intro screen, Freeplay list and weekData.

**Comment by ACardboardBox1** [comment]
this shouldnt happen cuz it's just a skin... maybe the xml animation names arent correct with the animations in note.hx?

**Comment by devShimaru** [comment]
> this shouldnt happen cuz it's just a skin... maybe the xml animation names arent correct with the animations in note.hx?

Seems to may have been an issue with my .xml file when I exported it from Animate, not sure. There seem to be way more frames in this:
![image](https://user-images.githubusercontent.com/87498840/125860557-ad5d004e-ca13-4d58-8db6-dfe0a2a1b3ac.png)

As opposed to other mods (in this case V.S. Kapi):
![image](https://user-images.githubusercontent.com/87498840/125860593-909a41d9-53fb-494a-8fc6-88936703fe95.png)


I'm not sure what I did incorrectly.

**Comment by ishsharm0** [comment]
> this shouldnt happen cuz it's just a skin... maybe the xml animation names arent correct with the animations in note.hx?

I don't think so, it's the same as a default KE XML as of 1.5.4.

**Comment by isakube** [comment]
> ![image](https://user-images.githubusercontent.com/87498840/125860557-ad5d004e-ca13-4d58-8db6-dfe0a2a1b3ac.png)
> ![image](https://user-images.githubusercontent.com/87498840/125860593-909a41d9-53fb-494a-8fc6-88936703fe95.png)

You got way too many fucking `right press` frames LOL
edit: and no thats not the issue. we changed the frame names :))

**Comment by ishsharm0** [comment]
> > ![image](https://user-images.githubusercontent.com/87498840/125860557-ad5d004e-ca13-4d58-8db6-dfe0a2a1b3ac.png)
> > ![image](https://user-images.githubusercontent.com/87498840/125860593-909a41d9-53fb-494a-8fc6-88936703fe95.png)
> 
> You got way too many fucking `right press` frames LOL
> edit: and no thats not the issue. we changed the frame names :))

Thanks much!
