### ISSUE TITLE
Bug Report: Freeplay broke with the new update

### ISSUE THREAD

**Issue by coublee** [KadeArchive/Kade-Engine#133]
In the 1.4 KadeEngine, the freeplay doesnt work. It can on load week 1 songs, nothing more. 
Even changing the file, it still BROKEN.

**Comment by Kade-github** [comment]
its uh not. Redownload or build from the project.

**Comment by coublee** [comment]
well, thats strange, since i redownloaded it 10 times and it didnt work... hm

**Comment by KlutchDj** [comment]
ill leave a note pad here, this should work , just copy and paste it into the FreeplayList file in data and should work 
[freeplaySonglist.txt](https://github.com/KadeDev/Kade-Engine/files/6254088/freeplaySonglist.txt)
