### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by 1BlackWater1** [KadeArchive/Kade-Engine#1338]
### If you are playing a downloaded version of the game, what operating system are you using?

Windows (`x86_64`),

## What version of the game are you using? Look in the bottom left corner of the main menu.

KE 1.5.4

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

try to use mod chart variables

## Please describe your issue. Provide extensive detail and images if possible.

most of the mod chart variables will not function at all, I dont understand why it doesnt but I have tried so much at this point that it is possible that it may be a bug.

**Comment by KlutchDj** [comment]
im pretty sure this one is on you. not a bug. and are you sure thats is a LUA file and not a text document? there shouldn't be anything wrong with it as its just coding a single strumeline and the HUD.

**Comment by 1BlackWater1** [comment]
ok i solved the problem, windows wasnt properly changing the file extensions so i re-installed the latest update and it worked, gonna close this now

**Comment by ACardboardBox1** [comment]
> 
> 
> ok i solved the problem, windows wasnt properly changing the file extensions so i re-installed the latest update and it worked, gonna close this now

some of the way these issues get solved are so fucking funny
