### ISSUE TITLE
Fps cap doesnt stay after you close the game

### ISSUE THREAD

**Issue by coublee** [KadeArchive/Kade-Engine#134]
The fps cap option keeps changing to the original fps cap (126 fps).
Can u fix tht? thx anyways

**Comment by KlutchDj** [comment]
it shouldn't do that , mine works completely fine for me , make sure you have the right version

**Comment by coublee** [comment]
i sure do.

**Comment by coublee** [comment]
wait, actually it did worked with the redownload.=, but i dont know how, since i installed the normal version when it 1st came out,
strange
