### ISSUE TITLE
Enhancement: Modders will love

### ISSUE THREAD

**Issue by HePpYPro** [KadeArchive/Kade-Engine#1343]
Make a way to implement the source code on the release and that would actully work.
This would facilitate the things because.
1. You would already have the exe so it's pretty easy to mod into the game
2. You can publish the source code and the mod at the same time so there wouldn't be any problems or flags(on gamebanana or anywhere else)
3. If pepole want to make new weeks for that mod already published (example: vs matt and wiik3) they can do it with just one download.

And there's even more cool things to do if this would happend so, hope you like this suggestion and goodbye!!!

**Comment by Jaduplex** [comment]
We can't do it like this because there may be api keys or other sensitive information kept in the source code, that, while being git-ignorable, cannot be filtered by a build pipeline.

**Comment by HePpYPro** [comment]
Didn't thought about that but still would be cool that to actually happend
