### ISSUE TITLE
Bug Report: Reloading songs with spaces in the name

### ISSUE THREAD

**Issue by Joshua-The-Creator** [KadeArchive/Kade-Engine#1344]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
**Windows (`x86_64`).**

## What version of the game are you using? Look in the bottom left corner of the main menu.
**1.5.4. Most up to date on Stable.**

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
**Bring up a song like Dad Battle, which has a space in the name, and reload the JSON. [This will cause a crash.](https://www.youtube.com/watch?v=P4bL0Eh7JFE)**

## Please describe your issue. Provide extensive detail and images if possible.
**Reloading songs should be a part of the charter, similar to how it handles folders with spaces in the name, as to help with charting songs. Yes, we could change the name of the song, but that's boring, stupid, and honestly the names with spaces in the name can hit much better than anything else.**

**Comment by Kade-github** [comment]
already fixed
