### ISSUE TITLE
Bug Report: Attempting to select certain songs from Free Play Results in a crash

### ISSUE THREAD

**Issue by NerdiestAlpaca** [KadeArchive/Kade-Engine#135]
When I attempt to play any song with a cutscene (Winter Horrorland and All Week 6 songs) from Free Play mode, the game simply crashes. They can still be loaded up in story mode but they can't be opened from the Free Play menu.

**Comment by Kade-github** [comment]
interesting I dont see this. Mind trying the latest pre-release?

**Comment by NerdiestAlpaca** [comment]
> interesting I dont see this. Mind trying the latest pre-release?

That fixed the issue, thank you! and sorry for responding so late
