### ISSUE TITLE
Enhancement: Kade Engine needs a reset settings button.

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#1351]
I accidentally changed something random while trying to find how to switch to the old input system (just found out that option was removed) and now my accuracy barely lowers.

I have no idea how to fix it, and even though I've been searching for 2 hours I still have no way to fix it. I completely deleted Kade Engine, but after reinstalling it still remembered all my settings (I can tell because I set my controls to DFJK and it stayed that way)

I don't know what to do. I just want to reset my settings and get it over with, but I literally can't.

**Comment by Trayfellow** [comment]
i agree that there should be a reset option, but for the time being, you can reset your save data by going to appdata, roamings, kadedev, and there should be a folder called "Kade Engine", thats where the save is stored, you can just delete the folder, btw this only works on kade engine 1.5.1 - above since kade changed the package name from ninjamuffin99.funkin to kadedev.kadeengine

**Comment by ghost** [comment]
> i agree that there should be a reset option, but for the time being, you can reset your save data by going to appdata, roamings, kadedev, and there should be a folder called "Kade Engine", thats where the save is stored, you can just delete the folder, btw this only works on kade engine 1.5.1 - above since kade changed the package name from ninjamuffin99.funkin to kadedev.kadeengine

Oh my god thankyou so much, I looked through my program files and couldn't find any save data. I'm gonna do this right now.

**Comment by ACardboardBox1** [comment]
> 
> 
> > i agree that there should be a reset option, but for the time being, you can reset your save data by going to appdata, roamings, kadedev, and there should be a folder called "Kade Engine", thats where the save is stored, you can just delete the folder, btw this only works on kade engine 1.5.1 - above since kade changed the package name from ninjamuffin99.funkin to kadedev.kadeengine
> 
> Oh my god thankyou so much, I looked through my program files and couldn't find any save data. I'm gonna do this right now.

did it work

**Comment by Kade-github** [comment]
exists
