### ISSUE TITLE
Help me adding

### ISSUE THREAD

**Issue by HePpYPro** [KadeArchive/Kade-Engine#1355]
How to add new weeks, stages, songs and etc on kade engine 1.5.4?
Somebody tell me pls cause i don't know how to do that on 1.5.4

Thx and bye

**Comment by NIOBEG-ALT** [comment]
Go watch this tutorial: https://youtu.be/4r4j4R8b2bM it's cool

**Comment by flowerbearttv** [comment]
this is not a bug

**Comment by HePpYPro** [comment]
@NIOBEG-ALT  that was the tutorial i watched 1000 times before i asked xDDDDDDDDD

**Comment by HePpYPro** [comment]
oh ok then
