### ISSUE TITLE
numberpad problem

### ISSUE THREAD

**Issue by Furamona** [KadeArchive/Kade-Engine#1356]
![image](https://user-images.githubusercontent.com/87139954/126157035-fc27f085-03fa-4545-8678-fbbe31ba39bd.png)

when I try the numberpad buttons it says "null".

**Comment by tofu111456** [comment]
i think it only happens on some of the kade engine .exes i believe
idk how you should fix that tho

**Comment by Spel0** [comment]
> i think it only happens on some of the kade engine .exes i believe

Bruh wdym? It's literally hardcoded in cuz new input doesn't support numpad

**Comment by Kade-github** [comment]
we don't support numpad keybinds.
