### ISSUE TITLE
Bug Report: Graphics breaking and Freeplay duplication

### ISSUE THREAD

**Issue by bbpanzu** [KadeArchive/Kade-Engine#1365]
freeplay list duplicates after each freeplay menu enter

also occasionally character graphics either go invisible or black square then crash after restarting, but that might be a me thing

**Comment by Jaduplex** [comment]
character graphics issue might be either a caching error or a memory issue on your end, freeplay list thing idk

**Comment by HePpYPro** [comment]
yeah you should probably do a @K a d e  D e v  to your problem cause that's pretty weird

**Comment by Kade-github** [comment]
already fixed
