### ISSUE TITLE
Bug Report: Notes ALWAYS miss on HTML5

### ISSUE THREAD

**Issue by m-obeid** [KadeArchive/Kade-Engine#1368]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

HTML5

## What version of the game are you using? Look in the bottom left corner of the main menu.

KE 1.5.7 

## Please describe your issue. Provide extensive detail and images if possible.

Notes always miss for some reason on self compiled HTML5, idk why.

**Comment by ghost** [comment]
have you changed controls? theres a bug i think about the arrow keys dont work

**Comment by m-obeid** [comment]
> have you changed controls? theres a bug i think about the arrow keys dont work

No, it's the default controls for Kade engine

**Comment by Kade-github** [comment]
this shoulda been fixed in master.

**Comment by m-obeid** [comment]
> this shoulda been fixed in master.

Oh i just noticed WASD works however the arrow keys don't
