### ISSUE TITLE
Enhancement: Ram usage monitor

### ISSUE THREAD

**Issue by nahiassis** [KadeArchive/Kade-Engine#1370]
This would be kinda helpful if you added this so i and other people can see how much ram kade engine is using

**Comment by ToastcodeDev** [comment]
It consumes me much (I have 4gb) to play it I have to close everything.
![KadeEngine exe_RamUsage](https://user-images.githubusercontent.com/67870123/126652460-04fa0c74-3fbd-4ed0-9df6-30feedaa45c9.jpg)

**Comment by isakube** [comment]
task manager. also pretty sure this isnt possible lol

**Comment by ToastcodeDev** [comment]
> task manager. also pretty sure this isnt possible lol

Apparently in win11 it improves, it loads all the resources at the beginning and then everything goes well, it stays at about 700mb.

About the screenshot, I took it a few seconds before it closes, it was quite a challenge.
