### ISSUE TITLE
Bug Report: Is boyfriend bopping head too fast a new feature or a bug?

### ISSUE THREAD

**Issue by BombasticTom** [KadeArchive/Kade-Engine#1374]
So I've installed the new v1.6 pre-release, and I wanted to test out some of the new features. When I entered Philly Nice in freeplay mode, boyfriend was bopping his head to the beat as twice as fast as he should be bopping. Is this an issue or just an update?

https://user-images.githubusercontent.com/85838311/126338367-eb408bd6-02b9-4cda-8d2b-27a30c8f36f5.mp4

**Comment by XaraKuma** [comment]
I think that's a feature because I tried it with multiple different numbers of bpm and the speed of the head bopping is different so I think it's meant to make bf actually bob his head to the beats of the music.

**Comment by Jaduplex** [comment]
i think its messed up, kade set idle fpses wrong

**Comment by Kade-github** [comment]
fixed in https://github.com/KadeDev/Kade-Engine/commit/aab9cab7b402d6e630a3e79d28e8e12e365329de
