### ISSUE TITLE
Bug Report: Numpad keybinds dont work for me at least

### ISSUE THREAD

**Issue by UnchartedDemon** [KadeArchive/Kade-Engine#1378]
![awdawddw](https://user-images.githubusercontent.com/85630048/126375664-cb8f22df-a6f6-457e-90e2-064f84cc33d1.png)
for example my keybinds are  AS-Numpad5 & Numpad6. when ever i use any key on the numpad it gives me "null"

**Comment by StyleCannotCodeForShit** [comment]
openfl doesnt like them and they worked before because there was a different hit detection system that was much better but the price was not allowing special keys like the numpads to work

**Comment by Kade-github** [comment]
^
