### ISSUE TITLE
Bug Report: Kade Engine crashes after song

### ISSUE THREAD

**Issue by Kodendan** [KadeArchive/Kade-Engine#1379]
Okay. So I was making an FNF mod and was editing the charts. I finished editing the chart in the integrated editor and then tested the song. I exited this song and moved on to another song I needed to chart. as soon as I pressed "7" to edit the chart, the game crashes. And then when I reloaded the game, all of my work was reset to the default "Bop Bee Bo," "Fresh," and "Dad battle."

Does anyone know a fix/way to avoid this issue?

Thanks.

**Comment by Kade-github** [comment]
Auto save exists.

**Comment by Kodendan** [comment]
but it didnt save at all?

**Comment by Kade-github** [comment]
Auto save happens when ever you place a note so it did save

**Comment by Kodendan** [comment]
yet when i load the game again everything is back default

**Comment by Kade-github** [comment]
you need to load the auto save
![image](https://user-images.githubusercontent.com/26305836/126388320-2e62a7a0-57fe-4497-95d4-0124941e6d4f.png)

**Comment by Kodendan** [comment]
oh ok thank you KadeDev, Developer of the popular Friday Night Funkin' modding platform, KadeEngine.
