### ISSUE TITLE
Bug Report: Kade Engine not showing freeplay songs other than Tutorial.

### ISSUE THREAD

**Issue by GradeFUnderF** [KadeArchive/Kade-Engine#138]
Everytime I try to open KadeEngine and use freeplay, no other songs show up other than tutorial. I have tried multiple methods and they don't work.

**Comment by TSFthe** [comment]
Yeah, and that is a real issue.

**Comment by StellaBiscuit** [comment]
I can confirm this issue too, only happen on 1.4, not on 1.3, and of course, cause the version isn't shown on freeplay, can't make a screen proving that

**Comment by KlutchDj** [comment]
copy this and paste it into the FreeplayList:
[freeplaySonglist.txt](https://github.com/KadeDev/Kade-Engine/files/6255220/freeplaySonglist.txt)

**Comment by StellaBiscuit** [comment]
oh so Kade forgot this by accident lmao

**Comment by Kiffolisk** [comment]
No. Kade did not forget this by accident. The code is meant to add songs to the Freeplay menu automatically if a week is unlocked. The freeplayList.txt file only contains the Freeplay songs that can never get deleted.

**Comment by Kade-github** [comment]
all it does it actually makes that file useable for better modding. I didn't forget it, its in the latest release.
