### ISSUE TITLE
Bug Report/Help: Compiling seems to be stuck

### ISSUE THREAD

**Issue by StellaBiscuit** [KadeArchive/Kade-Engine#139]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows 7 (`x86_64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.
Kade Engine 1.4
FNF 0.2.7.1

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Well, I simply try to compile after following every step one by one and somehow I still can't compile the game and it's stuck, even after waiting for hours

## Please describe your issue. Provide extensive detail and images if possible.

It seems like it can compile everything except the game itself, as you can see with the two images

A Normal Kade Engine, freshly downloaded
![image](https://user-images.githubusercontent.com/53101126/113519523-c9ca3680-955a-11eb-8a32-af4e4bc5e0a9.png)
The Compiled Kade Engine, also freshly downloaded
![image](https://user-images.githubusercontent.com/53101126/113519520-c59e1900-955a-11eb-971e-97e334edd867.png)

It just don't want to do the game itself, I have the APIStuff.hx btw
In the terminal, it just show this and it's stuck there
(I've f-cked up the image so look in the comments to get it)

I've even tried to do it on C: inteed of D: cause I had problem with some programs because of that but that didn't work out either

I don't know what to do at this point

**Comment by Kiffolisk** [comment]
have you tried opening funkin.exe

**Comment by theDetourist** [comment]
Also, what exactly shows whenever you compile it? You never showed it.

**Comment by Kiffolisk** [comment]
did you run "lime test windows -debug" or "lime build windows -debug" might be that idk

**Comment by StellaBiscuit** [comment]
> 
> 
> have you tried opening funkin.exe

It's just not there, the one with the funkin.exe is the one I downloaded, not the one I compiled

> 
> 
> Also, what exactly shows whenever you compile it? You never showed it.

Oh sh*t, you're right, I f*cked up the last image let me get it again cause obviously it does the bug every time
![image](https://user-images.githubusercontent.com/53101126/113659313-bfe62780-966f-11eb-97f0-f1f09eee4d3f.png)



> 
> 
> did you run "lime test windows -debug" or "lime build windows -debug" might be that idk

Blame me if I'm wrong but I never saw the command "lime build windows -debug" anywhere whatever it's a video or the readme file
Can still try tho
Edit: Neither command work and they show the same things

(oh and btw, the "-debug" is just to rename the file it compile, I've tried it with it and without with no sucess)

**Comment by theDetourist** [comment]
1. What are you specs?
2. Have you ever compiled the engine before?
3. Why are you still using Windows 7?

**Comment by Kade-github** [comment]
> 1. What are you specs?
> 2. Have you ever compiled the engine before?
> 3. Why are you still using Windows 7?

these are all valid questions

**Comment by StellaBiscuit** [comment]
> 
> 
>     1. What are you specs?
> 
>     2. Have you ever compiled the engine before?
> 
>     3. Why are you still using Windows 7?

1. Ok, so first of all it's an old ass pc cause my parents are dumb and still think it's perfect... (and I don't have the money to upgrade/get a new one)
CPU : Intel(R) Core(TM) i5-3570k CPU @ 3.40GHz 3.40 GHz
RAM : 16Go
GPU : NVIDIA GeForce GTX 950
Motherboard : p8z77-v lx

2. I didn't, was the first time

3. Obviously, my dumb parent think Windows 7 is ok, even tho it's freaking dead, I do have the money to get it, but all my savings will be done for, I just can't rn and might never be able to get it on this computer, so I'm pretty much stuck with Windows 7, didn't got any problem with any program yet tho

**Comment by theDetourist** [comment]
Your specs are fine, might be a problem with the OS..? Is it fully updated?

**Comment by StellaBiscuit** [comment]
wh- I though Windows stopped suport on Windows 7 and so no update would be there... and I check and there is some update, wth, I guess I can retry after the updates

**Comment by StellaBiscuit** [comment]
hey I didn't say it's ok, it could still be broken after that

**Comment by StellaBiscuit** [comment]
Want to know the best??? After all that IT STILL DOESN'T WORK and I don't know why the issue got closed even if I didn't confirmed it was fixed (could have told earlier that it wasn't fix tho)

**Comment by theDetourist** [comment]
What version of Visual Studio do you have?

What happens when you compile to HTML5? Also, try to compile to Windows with the -32 flag so we can see if the problem is with the C++ compiler or if it even goes that far.

**Comment by StellaBiscuit** [comment]
Ok so it seems like the building thing got a lot of new things to install... I guess I will try redownload all just in case (except VS)

Oh and VS is Community 2019 with all the 22Go shit needed

**Comment by StellaBiscuit** [comment]
Hey! We've got a new line on the command thing before it freezes with the new things I installed
![image](https://user-images.githubusercontent.com/53101126/114469113-8a36c680-9bba-11eb-85f5-08118d055eb8.png)
And it's a small problem in the code lmao, but it's on a fresh version... so it shouldn't be that bad right?

**Comment by StellaBiscuit** [comment]
![image](https://user-images.githubusercontent.com/53101126/114470194-80ae5e00-9bbc-11eb-9858-19be0d4f5f82.png)
Ok, this is just strange, I've downloaded Discord RPC like 20 times and it gives me this when trying the HTML5

**Comment by puyoxyz** [comment]
You are compiling a very outdated version of Kade Engine. Please `git clone` the master branch or download the source of the latest release then try again.

**Comment by StellaBiscuit** [comment]
"Very Outdated" yeah 7 days is reeeeeeally outdated, jokes aside, I'll try again with the newest

(also hum, how do I even do git clone?)

**Comment by StellaBiscuit** [comment]
So, bad news, `lime test windows -debug` seems to continue being broken... (or I'm just dumb)
GOOD NEWS, `lime test html5 -debug` WOOOOOOORKS
