### ISSUE TITLE
Bug Report: Game crashes on scroll speed change event after placed and before second debug menu entry

### ISSUE THREAD

**Issue by te-agma-at** [KadeArchive/Kade-Engine#1397]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`)

## What version of the game are you using? Look in the bottom left corner of the main menu.
KE 1.6

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
1. Go into the Chart Editor
2. Place down a Scroll Speed event
3. Update position
4. Save
5. Press "Add event"
6. Exit the chart editor
7. Try to go into the chart editor again
It crashes

This very weird glitch is one of the various charting glitches within Kade Engine 1.6.
Expected behavior: Ability to actually handle events without crashing
Actual behavior: (See the steps to reproduce the bug above)

**Comment by Kade-github** [comment]
no it doesn't

https://user-images.githubusercontent.com/26305836/126858686-38a5030d-e535-420c-a957-c75f4ad2e117.mp4
