### ISSUE TITLE
Bug Report: game crashes in freeplay when selecting empty charts

### ISSUE THREAD

**Issue by napstaa967** [KadeArchive/Kade-Engine#1398]
was making something and i left a chart empty on 1.5.4
i moved all the assets and code and stuff to 1.6
now when im selecting a song in freeplay the game crashes as soon as i select the song with no notes

Operative System: Windows x64

**Comment by ZoySoy-dot** [comment]
You have to open the song in story mode and save a new json with the chart editor(Press "7")

**Comment by napstaa967** [comment]
> You have to open the song in story mode and save a new json with the chart editor(Press "7")

the thing is the chart is intended to be empty but for now i just added 1 note at the start

**Comment by Kade-github** [comment]
https://github.com/KadeDev/Kade-Engine/commit/0d35cdfbfe716139af9c31e9fc67b48eb1f8902b
