### ISSUE TITLE
basically kade engine having a stroke

### ISSUE THREAD

**Issue by TheGamingCat89** [KadeArchive/Kade-Engine#1402]
So I was trying to update my version of Kade Engine for my mod but every time I play a song only left arrows appear then it proceeds to crash, I have no idea why it happens.
If anyone has any idea of what's causing it (there are no error codes either).
![image](https://user-images.githubusercontent.com/81439207/126600961-77ee93a9-56c7-448d-9a51-63ee35cecc7a.png)

**Comment by LynoFunni** [comment]
there might  be something wrong the code where the notes are displayed but im not a coder so i dont really know but try checking it

**Comment by TheGamingCat89** [comment]
> there might be something wrong the code where the notes are displayed but im not a coder so i dont really know but try checking it

i didnt change any code related to the notes, the previous version of kade engine works just fine though

**Comment by Burger-Gaming** [comment]
The new update to the engine reworked the entirety of the notes, so any older noteskins aren't compatible for KE anymore.

**Comment by ZoySoy-dot** [comment]
Also had the same problem and I noticed it had something to do with the files in the "source' folder

**Comment by TheGamingCat89** [comment]
> The new update to the engine reworked the entirety of the notes, so any older noteskins aren't compatible for KE anymore.

that was probably it, because i just copied and pasted the assets folder to the new version ill close this issue if it was that
thanks

**Comment by TheGamingCat89** [comment]
> > The new update to the engine reworked the entirety of the notes, so any older noteskins aren't compatible for KE anymore.
> 
> that was probably it, because i just copied and pasted the assets folder to the new version ill close this issue if it was that
> thanks

damn it wasnt it 
![image](https://user-images.githubusercontent.com/81439207/126620325-8a1d34bf-557d-4ac2-a2f8-4e652c2fe1cd.png)
still the same issue

**Comment by isakube** [comment]
we changed the arrow files. so things are le broken

**Comment by TheGamingCat89** [comment]
> we changed the arrow files. so things are le broken

i already replaced the old note assets with the new ones, still no idea why its doing that lol

**Comment by Kade-github** [comment]
I think your mod got one of the limbo versions of this bug, try pulling again because this issue was already fixed.

**Comment by TheGamingCat89** [comment]
oh alright thanks
