### ISSUE TITLE
Enhancement: Middle Scroll

### ISSUE THREAD

**Issue by NukeThief** [KadeArchive/Kade-Engine#1405]
The title speaks for itself: add a Middle Scroll option (only boyfriend arrows on the middle), but make it work that you can tweak how transparent the notes of your opponent are on your row so you will still be able to see them.

**Comment by Declock** [comment]
so basically funky friday middle scroll

**Comment by NukeThief** [comment]
yea something like that but the way you see opponnent arrows is different

**Comment by isakube** [comment]
optimizations does this

i mean it sends you to the Shadow Realm but it works

**Comment by NukeThief** [comment]
yeah but i want it to NOT FUNKIN' MAKE THE SCREEN BLACK

**Comment by NukeThief** [comment]
Soo..... will it get added?

**Comment by NukeThief** [comment]
Changed it in a different post
