### ISSUE TITLE
Enhancement: Wiki

### ISSUE THREAD

**Issue by Toppat-dalek** [KadeArchive/Kade-Engine#141]
## What is your suggestion, and why should it be implemented?
I would like a sort of wiki page in order to help people get started making mods at the same level as the tricky mod and such, like how to add custom levels and such. and how to make the stage switch mid-song in the hex fight or add text bubbles like in the Whitty mod, or custom animations in the tricky and Whitty mods, or the fading effect in the zardy mod. you know, things like that.

**Comment by Kiffolisk** [comment]
Tutorials already exist. BrightFyre makes really great tutorials and explains shit really well, so people can really just watch those videos to learn how to do shit.

**Comment by Toppat-dalek** [comment]
ah I see ok thanks for telling me
