### ISSUE TITLE
Bug Report: Stepmania charts desync from their ogg

### ISSUE THREAD

**Issue by shnabbydoodle** [KadeArchive/Kade-Engine#1411]
Stepmania charts slowly drift and desync from the music on different scroll speed settings.
Playing on 64 bit Windows 10.

**Comment by Kade-github** [comment]
video? We've tested this a lot and I haven't seen it.

**Comment by poco0317** [comment]
provide .sm and audio

**Comment by shnabbydoodle** [comment]
I have included a video, the .sm file, and the .ogg file.
I edited the .sm file to only include challenge difficulty (for Kade engine).

https://www.youtube.com/watch?v=qmcA_nuvmuM
[FKS.zip](https://github.com/KadeDev/Kade-Engine/files/6872887/FKS.zip)

**Comment by shnabbydoodle** [comment]
I have included the .sm, ogg, and a video with the two side by side.

https://www.youtube.com/watch?v=qmcA_nuvmuM
[FKS.zip](https://github.com/KadeDev/Kade-Engine/files/6872888/FKS.zip)

**Comment by poco0317** [comment]
#STOPS:34.000=0.108
,35.000=0.109
,92.000=0.041
,92.250=0.041
,92.500=0.041
,92.750=0.041
,93.000=0.041
,93.250=0.041
,93.500=0.041
,93.750=0.041
,94.000=0.041
,94.250=0.041
,94.500=0.082
,95.000=0.041
,95.250=0.041
,95.500=0.082
,96.000=0.041
,96.250=0.041
,96.500=0.041
,96.750=0.041
,97.000=0.041
,97.250=0.041
,97.500=0.041
,97.750=0.041
,218.000=0.108
,219.000=0.108
,232.000=0.081
,232.750=0.081
,233.500=0.082
,234.250=0.081
,250.000=0.108
,251.000=0.108
,268.500=0.081
,269.250=0.081
,270.000=0.081
,270.750=0.081
,271.500=0.081
,272.250=0.082
,273.000=0.081
,273.750=0.081
,274.500=0.081
,275.250=0.081
,282.000=0.108
;


this feature is unsupported by the current implementation of the sm parser

**Comment by Kade-github** [comment]
which is why it is desynced. We do not support it.

**Comment by Futuremappermydud** [comment]
Why close this? It’s a missing feature that should be added as it affects gameplay

**Comment by napstaa967** [comment]
> Why close this? It’s a missing feature that should be added as it affects gameplay

it was under the label bug, maybe create a new issue with the label enhancement

**Comment by Futuremappermydud** [comment]
> > Why close this? It’s a missing feature that should be added as it affects gameplay
> 
> it was under the label bug, maybe create a new issue with the label enhancement

But it’s a bug… the result is not correct from what is should be.

**Comment by napstaa967** [comment]
> > > Why close this? It’s a missing feature that should be added as it affects gameplay
> > 
> > 
> > it was under the label bug, maybe create a new issue with the label enhancement
> 
> But it’s a bug… the result is not correct from what is should be.

i think the sm parser is made by kade, so maybe going to the repo and reporting it as a bug

not this repo, the sm parser one

**Comment by poco0317** [comment]
i helped kade through the majority of the sm parsing process. parsing stops, 0 bpm, and negative bpm are slightly more advanced concepts that do not fit into the engine in a satisfying way at the moment. refile this as a feature if you want it added.
