### ISSUE TITLE
I'm getting an error while following the build guide. #1404

### ISSUE THREAD

**Issue by Sky-LeL** [KadeArchive/Kade-Engine#1412]
Ok so I had an issue lime build windows and it gave me the error: Error: Source path "C:/HaxeToolkit/haxe/lib/extension-webm/git/ndll/Windows64/extension-webm.ndll" does not exist so I used ctrl + f to search the build guide for extension-webm. So I first ran haxelib git extension-webm https://github.com/KadeDev/extension-webm it updated what I already have. Then I tried lime rebuild extension-webm windows but it gave the error 

Error: ExternalInterface.cpp
C:\HaxeToolkit\haxe\lib\hxcpp\4,2,1\include\hx\OS.h(59): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory
Please can I have some help?

**Comment by isakube** [comment]
i hate vscode dependencies

and yes that's the cause of the issue

**Comment by Sky-LeL** [comment]
Can you please elaborate. And help me fix it @prokube?

**Comment by Sky-LeL** [comment]
@KadeDev do you know what to do? And before you say install MSVC I already did that.

**Comment by Sky-LeL** [comment]
This is dead so I'm reasking.

**Comment by littlestalker** [comment]
I don't know if you are still looking for an answer but I found that the problem can be solved by downloading Windows 10 SDK from here https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/ Hope this helps

**Comment by Armandox623** [comment]
@littlestalker omg thanks!

**Comment by RecruitZer0** [comment]
@littlestalker I downloaded the win 10 SDK, now what? What do I do now?
