### ISSUE TITLE
Arrows are only down, doesn't match the postion its in.

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#1413]
So i updated to 1.6 (latest release)

And when i putted my mod in 1.6 the arrows doesn't match the postion

ex:
Arrow down: Down
Arrow up: Down
Arrow right: Down
Arrow left: Down

any fixes or why its doing that?

**Comment by lemz1** [comment]
Turn off colors by quantization.
When I turned it off, it was fixed.

**Comment by ghost** [comment]
> Turn off colors by quantization.
> When I turned it off, it was fixed.

I already had it off, It might be the noteskin that is bugging out i guess?

**Comment by Kade-github** [comment]
The noteskin was changed, you'll have to download the latest kade engine version of it. https://github.com/KadeDev/Kade-Engine/blob/stable/assets/shared/images/NOTE_assets.png
