### ISSUE TITLE
Bug Report: Chart Editor does not load correctly.

### ISSUE THREAD

**Issue by TextBox75** [KadeArchive/Kade-Engine#1415]
The Chart Editor does not launch when 7 is pressed in any of the two gamemodes (Story Mode and Freeplay). The black fade once 7 is pressed does appear, but it then gets stuck. My OS is Windows x86_64 and this issue occurs when exporting to HTML5 on the newest release of the Kade Engine, 1.6.

Video:
https://youtu.be/50Plht-VsL8

**Comment by isakube** [comment]
LOL WE DID A STUPID

the new chart editor creates windows. you can't really do that lol.

someone forgor an `#if sys` somewhere

**Comment by Trayfellow** [comment]
> LOL WE DID A STUPID
> 
> the new chart editor creates windows. you can't really do that lol.
> 
> someone forgor an `#if sys` somewhere

![image](https://user-images.githubusercontent.com/48515908/126731960-0ebfa0cd-846a-42c1-8112-b3dcafca43ac.png)

**Comment by isakube** [comment]
We forgor :skull:

**Comment by Kade-github** [comment]
> LOL WE DID A STUPID
> 
> the new chart editor creates windows. you can't really do that lol.
> 
> someone forgor an `#if sys` somewhere

No thats incorrect, the chart editor in the 1.6 version does not run well on html5. (if you're exporting to that ur weird anyways)
but its been fixed already.

**Comment by Trayfellow** [comment]
> > LOL WE DID A STUPID
> > the new chart editor creates windows. you can't really do that lol.
> > someone forgor an `#if sys` somewhere
> 
> No thats incorrect, the chart editor in the 1.6 version does not run well on html5. (if you're exporting to that ur weird anyways)
> but its been fixed already.

i usually test on html5 first since its way faster than compiling for desktop lol
