### ISSUE TITLE
Bug Report: Null Object Reference

### ISSUE THREAD

**Issue by EagleEyeJsst** [KadeArchive/Kade-Engine#1416]
HI, this is probably not a issue for the majority of people. But im pretty stupid so i probably did something wrong that is obvious. Whenever i tried to open the debug menu to insert my character, when i exit i get a error called "null object reference"

![Screenshot 2021-07-22 192937](https://user-images.githubusercontent.com/87836462/126721318-4e5b3a08-fea3-4f19-a03f-238d92e1771f.png)

![Screenshot 2021-07-22 193342](https://user-images.githubusercontent.com/87836462/126721564-036c2277-485f-4852-88a7-51c4d018566f.png)

Im probably just retarded but thank you for anybody willing to help

and above are the character and healthbar .hx's

**Comment by MagnusStrom** [comment]
some people are truly monkeys

**Comment by Danyxandro** [comment]
Try writting
getSparrowAtlas('characters/impostor');
instead of getSparrowAtlas('characters/impostor','shared','true');

**Comment by EagleEyeJsst** [comment]
> Try writting
> getSparrowAtlas('characters/impostor');
> instead of getSparrowAtlas('characters/impostor','shared','true');

Thank you! that error is fixed but now i just have to fix the fact that he is floating in the air..... Eh i can probably figure that out..... Thank you again!

**Comment by ACardboardBox1** [comment]
> 
> 
> > Try writting
> > getSparrowAtlas('characters/impostor');
> > instead of getSparrowAtlas('characters/impostor','shared','true');
> 
> Thank you! that error is fixed but now i just have to fix the fact that he is floating in the air..... Eh i can probably figure that out..... Thank you again!

dad.x and dad.y 
@EagleEyeJsst

**Comment by pupokadeengine** [comment]
> > > Try writting
> > > getSparrowAtlas('characters/impostor');
> > > instead of getSparrowAtlas('characters/impostor','shared','true');
> > 
> > 
> > Thank you! that error is fixed but now i just have to fix the fact that he is floating in the air..... Eh i can probably figure that out..... Thank you again!
> 
> dad.x and dad.y
> @EagleEyeJsst

if he's floating you can press 8 and use wasd and arrow keys to move char. then go in characters.hx and type in your positions. Your welcome if this helped!!
