### ISSUE TITLE
Issue with rebuilding extension-webm: fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'ARM64'

### ISSUE THREAD

**Issue by undersxoree** [KadeArchive/Kade-Engine#1421]
For context, I am using Windows x86_64, or just x64.

## What version of the game are you using? Look in the bottom left corner of the main menu.
I am using the source code for Kade Engine 1.6

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
I am not sure how I have received this issue, so I don't think I can reproduce this issue on other systems.

## Please describe your issue. Provide extensive detail and images if possible.
I am attempting to compile the source code of Kade Engine 1.6. This requires me to install extension-webm using haxelib install openfl-webm.

Once that was done, I attempted to use lime rebuild extension-webm windows, like a large amount of people suggested in other reports, but I received errors.

Initially, I received an error and a window prompt stating GetThreadContext failed, but I disabled my antivirus and that went away.

After temporarily disabling my antivirus, I attempted to use lime rebuild extension-webm windows again. I was then met with this error I haven't seen before that I haven't been able to find in any other forum, at least with this same specific problem.

I receive this message in Command Prompt (cmd), Windows Powershell and in Virtual Studio Code (the 2019 installation):
![issue1](https://user-images.githubusercontent.com/40687191/126732859-41f9d356-3c49-44e0-b9c9-e53eeebb288e.PNG)
![issue2](https://user-images.githubusercontent.com/40687191/126732860-0f95849d-2c77-4736-af93-83525bd7c5c2.PNG)
![issue3](https://user-images.githubusercontent.com/40687191/126732861-ff7e8210-19a0-4001-8ef4-1ad991c3cef5.PNG)

Link: ../ndll/WindowsArm64/extension-webm.ndll
obj\msvc19-arm64\366fb629_ExternalInterface.obj : 
fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'ARM64'

I've tried to look at other forums to fix this issue, but I can't even find the root cause of this problem.

If this helps, I have a Ryzen CPU, I'm unsure if this causes any issues with x64 and ARM64.

I'm unsure if this can be considered a bug for Kade Engine, but I've only had issues with rebuilding extension-webm.

If anybody has any questions for me that could help solve this problem, I'll gladly attempt to help, but if anyone has any idea how to fix this problem, it would be greatly appreciated if you could help as I don't want to lose my work.

Sorry if anybody is inconvenienced by this.

**Comment by NotIlulus** [comment]
this sucks lol, im using a dell g5 5590 (https://www.dell.com/en-us/shop/dell-laptops/g15-gaming-laptop/spd/g-series-15-5510-laptop/gn5510eyrms) and its giving the same error lol. its weird

**Comment by Futuremappermydud** [comment]
Support: have the same issue on a intel I5, had to stop working on my engine because of this. Asked in haxe server and nobody there knew either

**Comment by VICK-sys** [comment]
> 
> 
> For context, I am using Windows x86_64, or just x64.
> ## What version of the game are you using? Look in the bottom left corner of the main menu.
> 
> I am using the source code for Kade Engine 1.6
> ## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
> 
> I am not sure how I have received this issue, so I don't think I can reproduce this issue on other systems.
> ## Please describe your issue. Provide extensive detail and images if possible.
> 
> I am attempting to compile the source code of Kade Engine 1.6. This requires me to install extension-webm using haxelib install openfl-webm.
> 
> Once that was done, I attempted to use lime rebuild extension-webm windows, like a large amount of people suggested in other reports, but I received errors.
> 
> Initially, I received an error and a window prompt stating GetThreadContext failed, but I disabled my antivirus and that went away.
> 
> After temporarily disabling my antivirus, I attempted to use lime rebuild extension-webm windows again. I was then met with this error I haven't seen before that I haven't been able to find in any other forum, at least with this same specific problem.
> 
> I receive this message in Command Prompt (cmd), Windows Powershell and in Virtual Studio Code (the 2019 installation):
> ![issue1](https://user-images.githubusercontent.com/40687191/126732859-41f9d356-3c49-44e0-b9c9-e53eeebb288e.PNG)
> ![issue2](https://user-images.githubusercontent.com/40687191/126732860-0f95849d-2c77-4736-af93-83525bd7c5c2.PNG)
> ![issue3](https://user-images.githubusercontent.com/40687191/126732861-ff7e8210-19a0-4001-8ef4-1ad991c3cef5.PNG)
> 
> Link: ../ndll/WindowsArm64/extension-webm.ndll
> obj\msvc19-arm64\366fb629_ExternalInterface.obj :
> fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'ARM64'
> 
> I've tried to look at other forums to fix this issue, but I can't even find the root cause of this problem.
> 
> If this helps, I have a Ryzen CPU, I'm unsure if this causes any issues with x64 and ARM64.
> 
> I'm unsure if this can be considered a bug for Kade Engine, but I've only had issues with rebuilding extension-webm.
> 
> If anybody has any questions for me that could help solve this problem, I'll gladly attempt to help, but if anyone has any idea how to fix this problem, it would be greatly appreciated if you could help as I don't want to lose my work.
> 
> Sorry if anybody is inconvenienced by this.

check the method fix I described here https://github.com/KadeDev/Kade-Engine/issues/1761 It may solve your issue

**Comment by undersxoree** [comment]
> > For context, I am using Windows x86_64, or just x64.
> > ## What version of the game are you using? Look in the bottom left corner of the main menu.
> > I am using the source code for Kade Engine 1.6
> > ## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
> > I am not sure how I have received this issue, so I don't think I can reproduce this issue on other systems.
> > ## Please describe your issue. Provide extensive detail and images if possible.
> > I am attempting to compile the source code of Kade Engine 1.6. This requires me to install extension-webm using haxelib install openfl-webm.
> > Once that was done, I attempted to use lime rebuild extension-webm windows, like a large amount of people suggested in other reports, but I received errors.
> > Initially, I received an error and a window prompt stating GetThreadContext failed, but I disabled my antivirus and that went away.
> > After temporarily disabling my antivirus, I attempted to use lime rebuild extension-webm windows again. I was then met with this error I haven't seen before that I haven't been able to find in any other forum, at least with this same specific problem.
> > I receive this message in Command Prompt (cmd), Windows Powershell and in Virtual Studio Code (the 2019 installation):
> > ![issue1](https://user-images.githubusercontent.com/40687191/126732859-41f9d356-3c49-44e0-b9c9-e53eeebb288e.PNG)
> > ![issue2](https://user-images.githubusercontent.com/40687191/126732860-0f95849d-2c77-4736-af93-83525bd7c5c2.PNG)
> > ![issue3](https://user-images.githubusercontent.com/40687191/126732861-ff7e8210-19a0-4001-8ef4-1ad991c3cef5.PNG)
> > Link: ../ndll/WindowsArm64/extension-webm.ndll
> > obj\msvc19-arm64\366fb629_ExternalInterface.obj :
> > fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'ARM64'
> > I've tried to look at other forums to fix this issue, but I can't even find the root cause of this problem.
> > If this helps, I have a Ryzen CPU, I'm unsure if this causes any issues with x64 and ARM64.
> > I'm unsure if this can be considered a bug for Kade Engine, but I've only had issues with rebuilding extension-webm.
> > If anybody has any questions for me that could help solve this problem, I'll gladly attempt to help, but if anyone has any idea how to fix this problem, it would be greatly appreciated if you could help as I don't want to lose my work.
> > Sorry if anybody is inconvenienced by this.
> 
> check the method fix I described here #1761 It may solve your issue

Oh my god- This actually worked! Thank you so much. I can finally get back to modding now. I had been attempting to fix this issue for months, to no avail, so this is amazing. I cannot stress this enough, thank you.
