### ISSUE TITLE
chaching problem

### ISSUE THREAD

**Issue by tofu111456** [KadeArchive/Kade-Engine#1423]
![image](https://user-images.githubusercontent.com/69342634/126735299-da4ef3a2-0234-4b71-9cec-7e1feb37f076.png)
this.
(i was just changing kadeenginelogo to pleasewait (my custom picture) and this happened)

**Comment by RagdollClash** [comment]
you forgot an apostrophe

```haxe
kadeLogo = new FlxSprite(FlxG.width / 2, FlxG.height / 2).loadGraphic(Paths.image('pleaseWait'));
```

**Comment by tofu111456** [comment]
oh thanks
