### ISSUE TITLE
Bug Report: Building issue - too many arguments

### ISSUE THREAD

**Issue by senkjor** [KadeArchive/Kade-Engine#1427]
Release verison of engine is 1.6, Im compiling a build for Windows 
After starting compiling, it stops with errors: 
`source/PlayState.hx:4471: characters 16-26 : Too many arguments`
`source/GameplayCustomizeState.hx:197: characters 19-23 : Too many arguments`
VSCode shows this: 
![изображение_2021-07-23_152105](https://user-images.githubusercontent.com/87860939/126780795-8ed80e14-627c-484d-9c93-1a5395511b68.png)
![изображение_2021-07-23_152220](https://user-images.githubusercontent.com/87860939/126780932-113e8dba-511a-44b9-8642-3be7351af7ec.png)
How can i fix this issue?
Thank you!

**Comment by senkjor** [comment]
I got some source files replaced, That's what causing issue. I will close the issue for now.

**Comment by Sylveondev** [comment]
I'm having the issue too, where did you get the files from
