### ISSUE TITLE
Bug Report: "There is no asset library with an ID of "songs"" when launching game from command line

### ISSUE THREAD

**Issue by napstaa967** [KadeArchive/Kade-Engine#1437]
i wanted to test something on the compiled version of the game, and i had an error so i wanted to see what the command line said but when i started it it just gave me this error
![image](https://user-images.githubusercontent.com/57607350/126826834-74b74bd6-2e14-4110-b9fc-c057884e3eab.png)

**Comment by KlutchDj** [comment]
do you have a songs folder in ur directory

**Comment by napstaa967** [comment]
> do you have a songs folder in ur directory

yeah

**Comment by Kade-github** [comment]
did you add it in ur project.xml?

**Comment by napstaa967** [comment]
> did you add it in ur project.xml?

its the precompiled version that's downloadable, i didn't build it

**Comment by napstaa967** [comment]
> > did you add it in ur project.xml?
> 
> its the precompiled version that's downloadable, i didn't build it

i just realized what broke it

was my mistake lol
