### ISSUE TITLE
Bug Report: bpm changes dont seem to change scroll speed??

### ISSUE THREAD

**Issue by arceuss** [KadeArchive/Kade-Engine#1440]
[ONYON.zip](https://github.com/KadeDev/Kade-Engine/files/6871435/ONYON.zip)
the .sm file used
bpm changes at the end but the scroll speed remains the same

**Comment by KlutchDj** [comment]
i think you have a universal scroll speed. otherwise i don't know what the cause of this issue is.

**Comment by arceuss** [comment]
> 
> 
> i think you have a universal scroll speed. otherwise i don't know what the cause of this issue is.

tried with default scroll speed and it still doesnt change at the ending

**Comment by Kade-github** [comment]
thats not how it works. bpm != scroll speed. 

upping the bpm will increase the amount of snapped notes per beat visible, aka you'll be able to see more notes because it's a higher bpm, not the scroll speed. 

Formula for scroll speed is:
`0.45 * (songPosition -strumTime) * scrollSpeed`
