### ISSUE TITLE
Arrows break when moved when the assets are moved to another folder

### ISSUE THREAD

**Issue by RealOrbital32** [KadeArchive/Kade-Engine#1442]
I don't know if this also applies to the Github version, but I had 1.5.4 KE (skin-mod) files and transferred them to 1.6. They broke.

I quickly found the **supposed** cause of this, the arrows png was different than the original. 

So then, I transferred every file EXCEPT the arrows in, and just when I thought I'd fixed it, yet they still broke.

This also happens when you transfer the exact same (but modified/different colored) png to the folder.

This don't include Week 6 arrows.

**Comment by Kade-github** [comment]
You are reporting a bug because you modified the game files with another version of a file, which we have not tested.

And it didn't work.

This isn't a bug.
