### ISSUE TITLE
Bug Report: source/Character.hx:387: characters 5-8 : Expected :

### ISSUE THREAD

**Issue by zarexeI** [KadeArchive/Kade-Engine#1453]
Hello! When I compile 1.6, I get the error source/Character.hx:387: characters 5-8 : Expected :

**Comment by idragons962** [comment]
Error: Source path "C:/HaxeToolkit/haxe/lib/extension-webm/git/ndll/Windows64/extension-webm.ndll" does not exist

**Comment by napstaa967** [comment]
> Hello! When I compile 1.6, I get the error source/Character.hx:387: characters 5-8 : Expected :

what do lines 386-389 say on character.hx?

**Comment by zarexeI** [comment]
Nevermind! I fixed it myself, I just had a little typo.
