### ISSUE TITLE
Bug Report: When I Try Compileing The Game It Said This.

### ISSUE THREAD

**Issue by idragons962** [KadeArchive/Kade-Engine#1454]
Error: Source path "C:/HaxeToolkit/haxe/lib/extension-webm/git/ndll/Windows64/extension-webm.ndll" does not exist

**Comment by napstaa967** [comment]
> Error: Source path "C:/HaxeToolkit/haxe/lib/extension-webm/git/ndll/Windows64/extension-webm.ndll" does not exist

you have to install extension-webm

**Comment by idragons962** [comment]
when i did it still wont work

**Comment by napstaa967** [comment]
make sure to run these commands first then building:
-haxelib git extension-webm https://github.com/KadeDev/extension-webm
-lime rebuild extension-webm windows

**Comment by idragons962** [comment]
oh thanks!

**Comment by ghost** [comment]
@napstaa967 I did that and it still didn't work

**Comment by ntgm714** [comment]
me too cant figure it out
