### ISSUE TITLE
code problem with the dialogue

### ISSUE THREAD

**Issue by tofu111456** [KadeArchive/Kade-Engine#1457]
![image](https://user-images.githubusercontent.com/69342634/126889969-204e04ca-6dfe-48ae-869a-cc0f8d2bebde.png)

how do i fix this?
i might be dumb

**Comment by napstaa967** [comment]
remove the "{" at line 120, its not being used

**Comment by napstaa967** [comment]
you're placing the "{" behind where it should actually be
the "{" has to go in front of the else if statement for it to work

also your code isn't properly indented to fit inside the else if statement

**Comment by tofu111456** [comment]
![image](https://user-images.githubusercontent.com/69342634/126890549-547b880c-41de-49c7-b5ee-729a9e463240.png)
so like this?

**Comment by napstaa967** [comment]
> ![image](https://user-images.githubusercontent.com/69342634/126890549-547b880c-41de-49c7-b5ee-729a9e463240.png)
> so like this?

it should be like this:

else if (PlayState.SONG.song.toLowerCase()=='stretch-roll')
{
    portraitLeft = new FlxSprite(-20, -40);
    rest of the code, you get the idea, add the missing 4 spaces/tabs
    portraitLeft.visible = false;
}

also you have duplicated the stuff for the left portrait

**Comment by tofu111456** [comment]
ok wait
ill try it

**Comment by tofu111456** [comment]
it works yay
ill tell if there are more issues
i guess

**Comment by tofu111456** [comment]
ok. now the game crashes everytime a dialogue is like loading
this also happens in the past

**Comment by tofu111456** [comment]
ill just open a new issue
