### ISSUE TITLE
Bug Report: Game crashes when character is switched

### ISSUE THREAD

**Issue by Dangan2020** [KadeArchive/Kade-Engine#146]
So apparently... the game crashes when I was playing one of the mods that has **switched the rival character from "parents-christmas" to "monster" in Cocoa.** And when I tried to **change the rival character in another song the game crashes as well**. Why did this happen?

**Comment by Kiffolisk** [comment]
From what I know, the game tries to load "assets\week5\images\monster.png" or something similar to that, making it crash.

**Comment by Dangan2020** [comment]
Huh? Wait, so do I have to put that asset in week 5 as well then?

**Comment by Kiffolisk** [comment]
I don't really know if that would work, because the manifest files have all the directories and files listed. I don't really know how the manifest files work.

**Comment by Dangan2020** [comment]
Just tried by putting monster's assets in there and... nope. Man... I'm screwed.

**Comment by tjdidit** [comment]
Same thing happens on my end too.

**Comment by FunkyHead-870** [comment]
This happens to me with other mods like Tricky or VSMatt (which use the Kade Engine)
But it doesn't happen with any character, it just happens with Pico.

**Comment by R-code-0** [comment]
Copy all weeks persons to shared/images
And problem solved! (You need to build a game)

**Comment by Kade-github** [comment]
dup of #88
