### ISSUE TITLE
when i load a custom song with dialogue the game crashes

### ISSUE THREAD

**Issue by tofu111456** [KadeArchive/Kade-Engine#1460]
when i load a custom song i made with all the things like sprites, music, chart, dialogue text, that stuff, the game crashes whenever starting to pop the first dialogue box up

the code is also right so idk how to fix it

**Comment by tofu111456** [comment]
why the hell is no one responding?
is it cause they have the same issue?

**Comment by Futuremappermydud** [comment]
Nobody is responding because it’s been 2 hours

**Comment by Futuremappermydud** [comment]
If you wait someone will respond

**Comment by tofu111456** [comment]
> 
> 
> If you wait someone will respond

okay then

**Comment by napstaa967** [comment]
> when i load a custom song i made with all the things like sprites, music, chart, dialogue text, that stuff, the game crashes whenever starting to pop the first dialogue box up
> 
> the code is also right so idk how to fix it

what do you have in dialouebox.hx
and do you have the cutscene function coded correctly in playstate.hx

**Comment by ACardboardBox1** [comment]
> 
> 
> why the hell is no one responding?
> is it cause they have the same issue?

some of yall need to calm down
bro someone will get to the issue sooner or later 😒

**Comment by tofu111456** [comment]
> 
> 
> > when i load a custom song i made with all the things like sprites, music, chart, dialogue text, that stuff, the game crashes whenever starting to pop the first dialogue box up
> > the code is also right so idk how to fix it
> 
> what do you have in dialouebox.hx
> and do you have the cutscene function coded correctly in playstate.hx

![image](https://user-images.githubusercontent.com/69342634/126919599-d91ec192-e1a6-49c8-add7-45c6934bf62e.png)
this is some of the stuff in dialoguebox.hx

and idk about cutscene function thing but i know i coded it correctly

**Comment by tofu111456** [comment]
aaand no responses again.

**Comment by theDetourist** [comment]
Not a KE issue, go to the [Discord server](https://discord.gg/CJtjeR8u) for better help with custom stuff.

**Comment by tofu111456** [comment]
> 
> 
> Not a KE issue, go to the [Discord server](https://discord.gg/CJtjeR8u) for better help with custom stuff.

ok then
