### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by ToaSt3635** [KadeArchive/Kade-Engine#148]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows x86
## What version of the game are you using? Look in the bottom left corner of the main menu.
1.3
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
All I do is open the debug menu and I just can't delete arrows at all.
## Please describe your issue. Provide extensive detail and images if possible.
When I try to remove any arrows in the debug menu, nothing happens. I can't delete any arrows, but I can place arrows though. There was one time where I could delete arrows, but I have no idea how I fixed it and the next time I tried to rechart a song it went back to not working.

The debug menu works fine on mods that don't use KadeEngine, but using KadeEngine I can't delete any arrows at all.

**Comment by Kade-github** [comment]
This was fixed in the latest version of Kade Engine.
