### ISSUE TITLE
Bug Report: Loading stuck at 20/21

### ISSUE THREAD

**Issue by SKBotNL** [KadeArchive/Kade-Engine#1480]
### If you are playing a downloaded version of the game, what operating system are you using?
Linux (Manjaro)

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.6

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Running the executable after building it on linux

## Please describe your issue. Provide extensive detail and images if possible.
When starting, it gets stuck at `Loading... (20/21)`. 
In the terminal, it says this:
```
source/Caching.hx:173: Finished caching...
source/Caching.hx:177: false
source/TitleState.hx:67: Loaded 0 assets (DEFAULT)
source/TitleState.hx:86: hello
```
In the terminal it looks like it is actually finished loading but the loading screen is still there.
![Screenshot from 2021-07-27 10-32-43](https://user-images.githubusercontent.com/68018116/127123087-f94b99f3-aae7-449b-905d-08473acee7a8.png)

**Comment by iijj22gg** [comment]
This appears to be the same issue as [https://github.com/KadeDev/Kade-Engine/issues/1447](url).

**Comment by SKBotNL** [comment]
Duplicate of #1447
