### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by Tyranex** [KadeArchive/Kade-Engine#149]
Just wanted to know what I was doing wrong exactly here. Getting compiling issues with specifically Kade Engine, I can compile the normal source code perfectly fine, and yet Kade Engine specifically throws this.

![Compiling error](https://user-images.githubusercontent.com/26897990/113656549-02b9f680-9694-11eb-9360-2ef18fc56c91.png)

I've tried replacing Discord.hx from the original games source code into Kade engines to see if that would make a difference, but no dice. Using lime test html5 -debug in both cases. No modifications have even been made yet other than changing the source folders name and changing project.xml for that change, but even before I did that, same error. Already have APIStuff.hx in the source too. Really not sure what I'm doing wrong here.

**Comment by Kade-github** [comment]
You will have to compile to CPP or just comment out all of the discord rich presence stuff. or smth like that.

**Comment by Tyranex** [comment]
> discord rich presence stuff. or smth like that.

Sorry I'm still sort of figuring things out here. CPP..? Also where exactly would I be commenting out? Just the Discord.hx file or is rich presence referenced in other files too?

**Comment by puyoxyz** [comment]
actually, with the new changes from my PR, html5 builds *should* work now? maybe `git pull` and try it again =p

**Comment by Tyranex** [comment]
> actually, with the new changes from my PR, html5 builds _should_ work now? maybe `git pull` and try it again =p

Feel like I'm being a pain here, really sorry. But git pull what exactly..?
If you mean Kade Engine I kinda downloaded it directly. I am.. Largely still learning and there's just not a lot out there to figure things like this out.

**Comment by puyoxyz** [comment]
It's fine, don't worry about it. Usually `git pull` is the command you'd run to update a local git repository, but since you downloaded it directly, you should just download it again and compile on the new one
