### ISSUE TITLE
Bug Report: Web Version is completely broken.

### ISSUE THREAD

**Issue by brandonapt** [KadeArchive/Kade-Engine#1492]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
HTML5 on FireFox (latest version) on windows 10

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.6 nightly web (on funkin.puyo.xyz or smthn like that)

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
go into any song. for my case, high. then play. you wont be able to hit any notes. the arrow animations wont play on press either.

## Please describe your issue. Provide extensive detail and images if possible.
see above.
(sorry for lag. im on my old laptop rn lol)
and for some reason in the video the rating isnt working either???
im also spam hitting the keys

https://user-images.githubusercontent.com/63559800/127238873-d24a0161-cc6c-4f66-9d6f-81fb1a83fe52.mp4

**Comment by Kade-github** [comment]
come again?

https://user-images.githubusercontent.com/26305836/127268884-0894314f-cb13-407c-b62f-87f362251645.mp4

**Comment by brandonapt** [comment]
then its probably my pc or firefox having a stroke with input. sorry for wasting your time!
