### ISSUE TITLE
Bug Report: Missing Text + Wacky Score Dip

### ISSUE THREAD

**Issue by LiquidMelons** [KadeArchive/Kade-Engine#15]
I'm not sure if this was intentional but it stood out to me. The text in the bottom left is not in every song (example: Milf Hard - KE 1.1.3) it is missing in all the songs from Week 2, 3, and 6, as well as Winter Horrorland. It also shows up very briefly in the tutorial but then is shot off the screen moments later.  

Video:
https://user-images.githubusercontent.com/80550765/111094264-8bfc6400-8500-11eb-9e6b-902160e954cb.mp4

Not anything major but I thought it would be something to take note of.

Secondly, I have been seeing my scores dip really low for no reason when I play. This does not happen all the time though it is still quite common. I notice it mostly during the beginning when my scores go into the negatives even if I haven't missed a single note. However, when I finish I notice myself having far lower scores than the original even when I FC, so it may happen throughout the entire song. It happens most often on low accuracy runs which made me believe that maybe low accuracy hits (i.e: "Bad" and "Shit") decrease score. But my scores go down by a couple thousand instead of a couple dozen points, and it can also happen in runs with +90% accuracy so I didn't think that was the case.
This also happens with both old and new input systems.

Old Input Video:
https://user-images.githubusercontent.com/80550765/111095703-a126c200-8503-11eb-8aa5-67e48ba45a53.mp4
New Input Video:
https://user-images.githubusercontent.com/80550765/111095769-c5829e80-8503-11eb-8786-8743bb1453d5.mp4

Thanks for making this great engine and I hope you have a good day. c:

**Comment by Kiffolisk** [comment]
"The text in the bottom left is not in every song"
this happens with something im making, which adds text in the bottom left. in week 2 and others it just doesnt appear. i don't really know why this happens

**Comment by Kade-github** [comment]
for the first issue, we already know.

For the second one, your accuracy was terrible. thus ur score is terrible. This is to prevent mashing.
