### ISSUE TITLE
Problem building game:

### ISSUE THREAD

**Issue by neddacat** [KadeArchive/Kade-Engine#1506]
I tried to run lime test windows in cmd then this happened: 
<img width="1920" alt="error" src="https://user-images.githubusercontent.com/88158513/127536931-d8f521d9-4521-4244-9da7-579336046014.png">

I have no idea what I'm doing or how to code so this is just gibberish to me
Does anybody know how to fix this? I've installed all the libraries.

**Comment by napstaa967** [comment]
read the building guide again

you're missing the windows build dependencies

**Comment by neddacat** [comment]
Thanks!
