### ISSUE TITLE
Bug Report: No animation called "static"

### ISSUE THREAD

**Issue by MarlowBl4ze** [KadeArchive/Kade-Engine#1508]
So, i builded the game and when i play a song it say No animation called "static" No animation called "purpleScroll" and stuff

**Comment by isakube** [comment]
lol your note xml is screwed up
try looking in Note.hx to see what the animation names are

**Comment by MarlowBl4ze** [comment]
i re-downloaded the note_assets png and copied and pasted the xml and it worked
