### ISSUE TITLE
Bug Report: game crashes after song ends

### ISSUE THREAD

**Issue by bbllank** [KadeArchive/Kade-Engine#151]
suddenly appeared out of nowhere when i was playing the x event mod then carried over to the other kade engine using mods (might be a keybind?? idk)

played on windows 10 home with version 10.0.19041 build 19041

version was 0.2.7.1 FNF - 1.2 Kade Engine

not tried anything to reproduce it

game just crashes after a song ends. might be something with the replays as the image shows
![image](https://user-images.githubusercontent.com/71555117/113674011-964df000-96b1-11eb-9ab3-87375be8fcd9.png)
(error message varies from each song)

**Comment by Kade-github** [comment]
Do you have the replays folder in assets?

**Comment by bbllank** [comment]
yep

**Comment by Kade-github** [comment]
yeah that only happens when you don't have that folder.

**Comment by Kade-github** [comment]
I also just realised you are on an outdated version of the game. So update.

**Comment by Rajbir98** [comment]
ok so this problem is with outdated version ok
