### ISSUE TITLE
Bug Report: Chart Editor Issues with 1.6

### ISSUE THREAD

**Issue by Lilpaulo3232** [KadeArchive/Kade-Engine#1510]
Issue #1: Loading takes too long.  When I try to open the chart editor to chart songs it takes forever to load the editor, I timed how long the editor loads, and it takes about 2x as long as the the song you're charting!!!

Issue #2: Chart Editor Is Laggy. after like 10 years after the editor is done loading, and I'm kindly greeted to an laggy Chart Editor. the cursor moves so awkwardly, the scrolling in the editor so choppy. and its just unbearable.

Please fix these issues in the next update.

**Comment by raf13lol** [comment]
In Settings, Go To Appearance And Make 'Show Editor Grid' Into 'Do Not Show Editor Grid'. It Should Improve Performance.

**Comment by TTRICKYTHECAR** [comment]
> In Settings, Go To Appearance And Make 'Show Editor Grid' Into 'Do Not Show Editor Grid'. It Should Improve Performance.

there is no Show Editor Grid in appearance

**Comment by Lilpaulo3232** [comment]
> In Settings, Go To Appearance And Make 'Show Editor Grid' Into 'Do Not Show Editor Grid'. It Should Improve Performance.

I dont see the option anywhere

**Comment by Lilpaulo3232** [comment]
> In Settings, Go To Appearance And Make 'Show Editor Grid' Into 'Do Not Show Editor Grid'. It Should Improve Performance.

Where is it then?

**Comment by raf13lol** [comment]
![Screenshot 2021-07-30 142433](https://user-images.githubusercontent.com/79861112/127659551-e2e97252-36d9-4929-8e2a-00dfff921841.png)
![Screenshot 2021-07-30 142500](https://user-images.githubusercontent.com/79861112/127659585-2163f114-6026-4a67-ab98-3819bbbbe1d6.png)

**Comment by raf13lol** [comment]
Better?

**Comment by Lilpaulo3232** [comment]
![Uploading image.jpg…]()

**Comment by Lilpaulo3232** [comment]
I litteraly dont see it

**Comment by raf13lol** [comment]
download from here ->https://ci.appveyor.com/api/buildjobs/hcfpp0f8hlnbcjtn/artifacts/export%2Frelease%2Fwindows%2FKadeEngine-Windows.zip

**Comment by Lilpaulo3232** [comment]
Ok its there and the chart editor doesn’t suck anymore thx

**Comment by raf13lol** [comment]
close this thread
