### ISSUE TITLE
Error while building game:

### ISSUE THREAD

**Issue by neddacat** [KadeArchive/Kade-Engine#1512]
I was trying to run lime rebuild extension-webm windows and I got this error: 
<img width="401" alt="error3returnoftheerror" src="https://user-images.githubusercontent.com/88158513/127565555-c26d2007-8510-416d-8f6b-57d6c5cd783a.png">

I have no idea how to code so this is minecraft enchanting table language to me.

**Comment by KlutchDj** [comment]
did you download Visual studio ? follow the building.md for more instructions

**Comment by neddacat** [comment]
Yeah, i dont know whats wrong

**Comment by neddacat** [comment]
maybe i forgot about the cloning the repository part

**Comment by neddacat** [comment]
im going to try re-installing visual and the components

**Comment by ACardboardBox1** [comment]
> 
> 
> im going to try re-installing visual and the components

DOWNLOAD THIS
https://download.visualstudio.microsoft.com/download/pr/67f7bfaa-2635-43d9-ba82-26564f458881/bb057808eeff7d02561cab636b32397e298c3e770ed278602c46d119fa2e4ee8/vs_BuildTools.exe

**Comment by neddacat** [comment]
oh nice thanks ill try that

**Comment by neddacat** [comment]
thanks a lot im pretty sure its working
either that or this error is going off the screen

**Comment by neddacat** [comment]
It works now! Thanks a ton!

**Comment by ACardboardBox1** [comment]
> 
> 
> It works now! Thanks a ton!

Your welcome.
