### ISSUE TITLE
Bug Report: Cant Compile Source Code

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#152]
So Everytime I Compile The Game On Windows I Keep Getting This Error

Missing (HXCPP_VARS) 
Missing MSVC.bat

how do i fix this

**Comment by theDetourist** [comment]
Did you follow the [README.md's](https://github.com/KadeDev/Kade-Engine/blob/master/README.md) instructions properly?

**Comment by puyoxyz** [comment]
> Missing MSVC

Sounds like you might be missing the "22GB of crap" (as the readme says) from Visual Studio. You should either download the "22GB of crap" (instructions in README) or just download an [AppVeyor build](https://ci.appveyor.com/project/KadeDev/kade-engine-windows/build/artifacts)

**Comment by Kiffolisk** [comment]
It's literally what it says. It's missing MSVC. You have to download VS 2017 (don't know if 2019 works).

**Comment by puyoxyz** [comment]
No, don't download 2017. The README specifies that you need 2019 and which components you need.
