### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by franjavierr** [KadeArchive/Kade-Engine#1523]
I can't compile the game
Error:
source/Character.hx:545: characters 51-55 : Too many arguments
source/Character.hx:553: characters 4-18 : Unknown identifier : loadOffsetFile
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
PS C:\Users\fran0\Documents\GitHub\Kade-Engine> lime test windows
source/Character.hx:545: characters 51-55 : Too many arguments
source/Character.hx:553: characters 4-18 : Unknown identifier : loadOffsetFile
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
PS C:\Users\fran0\Documents\GitHub\Kade-Engine>

![image](https://user-images.githubusercontent.com/84986458/127662021-92f9727c-5364-4711-801d-96d0ba52e0ff.png)

I use Windows x86

**Comment by FelipeBacana** [comment]
I use Windows x64 21H1
