### ISSUE TITLE
Kade Engine won't run: 

### ISSUE THREAD

**Issue by Msticol** [KadeArchive/Kade-Engine#1525]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows 10 x64
## What version of the game are you using? Look in the bottom left corner of the main menu.
1.6
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Run the game
## Please describe your issue. Provide extensive detail and images if possible.
Whenever I try to run the engine, a window pops up saying [lime.utils.Preloader] ERROR: There is no asset library with an ID of "Songs"
![Screenshot (1)](https://user-images.githubusercontent.com/88200366/127675629-a4708524-f9b4-4e22-912a-3d16900efc6c.png)

**Comment by napstaa967** [comment]
this happens when a songs' inst and voices are missing, make sure they're not, else try rebuilding the game

**Comment by Kade-github** [comment]
^
