### ISSUE TITLE
Bug Report: New songs in Freeplay crash the game

### ISSUE THREAD

**Issue by craftersshaft** [KadeArchive/Kade-Engine#1526]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Windows x86_64

## What version of the game are you using? Look in the bottom left corner of the main menu.

1.6 Kade Engine, Github releases version

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
- Add a new song to the assets/songs folder, and the assets/data folder. Make sure the json's song value is the same as the folder names.
- Add that song into the freeplaySonglist.txt file, then go into Freeplay and try to hover over the song.

## Please describe your issue. Provide extensive detail and images if possible.

The game immediately crashes on hovering over the song, and the console log ends at this:

`source/MainMenuState.hx:258: Freeplay Menu Selected
source/Song.hx:87: loading tutorial/tutorial-easy
source/Song.hx:87: loading tutorial/tutorial
source/Song.hx:87: loading tutorial/tutorial-hard
source/FreeplayState.hx:92: loaded diffs for Tutorial
source/Song.hx:87: loading brine/brine-easy
source/Song.hx:87: loading brine/brine
source/Song.hx:87: loading brine/brine-hard
source/FreeplayState.hx:92: loaded diffs for Brine
source/Song.hx:87: loading spookeez/spookeez-easy
source/Song.hx:87: loading spookeez/spookeez
source/Song.hx:87: loading spookeez/spookeez-hard
source/FreeplayState.hx:92: loaded diffs for Spookeez
source/Song.hx:87: loading south/south-easy
source/Song.hx:87: loading south/south
source/Song.hx:87: loading south/south-hard
source/FreeplayState.hx:92: loaded diffs for South
source/Song.hx:87: loading fortune/fortune-easy
source/Song.hx:87: loading fortune/fortune
source/Song.hx:87: loading fortune/fortune-hard
source/FreeplayState.hx:92: loaded diffs for Fortune
source/Song.hx:87: loading pico/pico-easy
source/Song.hx:87: loading pico/pico
source/Song.hx:87: loading pico/pico-hard
source/FreeplayState.hx:92: loaded diffs for Pico
source/Song.hx:87: loading philly/philly-easy
source/Song.hx:87: loading philly/philly
source/Song.hx:87: loading philly/philly-hard
source/FreeplayState.hx:92: loaded diffs for Philly Nice
source/Song.hx:87: loading blammed/blammed-easy
source/Song.hx:87: loading blammed/blammed
source/Song.hx:87: loading blammed/blammed-hard
source/FreeplayState.hx:92: loaded diffs for Blammed
source/Song.hx:87: loading satin-panties/satin-panties-easy
source/Song.hx:87: loading satin-panties/satin-panties
source/Song.hx:87: loading satin-panties/satin-panties-hard
source/FreeplayState.hx:92: loaded diffs for Satin Panties
source/Song.hx:87: loading high/high-easy
source/Song.hx:87: loading high/high
source/Song.hx:87: loading high/high-hard
source/FreeplayState.hx:92: loaded diffs for High
source/Song.hx:87: loading milf/milf-easy
source/Song.hx:87: loading milf/milf
source/Song.hx:87: loading milf/milf-hard
source/FreeplayState.hx:92: loaded diffs for Milf
source/Song.hx:87: loading cocoa/cocoa-easy
source/Song.hx:87: loading cocoa/cocoa
source/Song.hx:87: loading cocoa/cocoa-hard
source/FreeplayState.hx:92: loaded diffs for Cocoa
source/Song.hx:87: loading eggnog/eggnog-easy
source/Song.hx:87: loading eggnog/eggnog
source/Song.hx:87: loading eggnog/eggnog-hard
source/FreeplayState.hx:92: loaded diffs for Eggnog
source/Song.hx:87: loading winter-horrorland/winter-horrorland-easy
source/Song.hx:87: loading winter-horrorland/winter-horrorland
source/Song.hx:87: loading winter-horrorland/winter-horrorland-hard
source/FreeplayState.hx:92: loaded diffs for Winter Horrorland
source/FreeplayState.hx:96: tryin to load sm files
source/FreeplayState.hx:101: HOW TO ADD SM FILES.txt
source/DiffCalc.hx:26: calcuilafjwaf
source/DiffCalc.hx:48: 32 - playable notes
source/DiffCalc.hx:26: calcuilafjwaf
source/DiffCalc.hx:48: 32 - playable notes
source/MusicBeatState.hx:31: reg (x: -200 | y: -200 | w: 1792 | h: 1008)
source/DiffCalc.hx:26: calcuilafjwaf
source/DiffCalc.hx:48: 176 - playable notes
source/DiffCalc.hx:26: calcuilafjwaf
source/DiffCalc.hx:48: 32 - playable notes
source/DiffCalc.hx:26: calcuilafjwaf`

If i need to clarify any more, let me know.

**Comment by napstaa967** [comment]
if its the precompiled version then its normal

if you are compiling it make sure the json file has the correct names for player1, player2, gfVersion and stage

**Comment by Kade-github** [comment]
this should have been fixed

**Comment by craftersshaft** [comment]
im referring to precompiled and It Was Not, console when running from master source in debug mode says it can't find the assets under assets/songs/songname/Inst.ogg and assets/songs/songname/Voices.ogg

**Comment by napstaa967** [comment]
> im referring to precompiled and It Was Not, console when running from master source in debug mode says it can't find the assets under assets/songs/songname/Inst.ogg and assets/songs/songname/Voices.ogg

i've been looking at the files and apparently the way the game looks for the correct files existing is having them inside a manifest-json file

if the file is not inside the manifest it gets ignored

and you can't add files to the manifest easily
