### ISSUE TITLE
Bug Report: Null object data???

### ISSUE THREAD

**Issue by dartthe6th** [KadeArchive/Kade-Engine#1529]
when i switch my character, it says null object data

**Comment by FelipeBacana** [comment]
Why can't everybody help me on version

**Comment by greenec03** [comment]
the same happened to me, don't know why

**Comment by shaderw0lf** [comment]
> when i switch my character, it says null object data

how do you switch your character, where...

**Comment by Kade-github** [comment]
that's a lot of details
