### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by DaBlueNinja03** [KadeArchive/Kade-Engine#1533]
so when i try to add new icons in healthicons.hx, barely anything is there! does anyone know how to do this bc im trying to make a full week.

**Comment by DaBlueNinja03** [comment]
Btw its the newest version

**Comment by napstaa967** [comment]
> so when i try to add new icons in healthicons.hx, barely anything is there! does anyone know how to do this bc im trying to make a full week.

are you on master, stable or release (release is the downloadable zip source code)

**Comment by DaBlueNinja03** [comment]
Master

**Comment by napstaa967** [comment]
> Master

master now uses icon files instead of a sprite sheet thing
instead of modifying healthicon.hx you just go over to preload/images/icons and drop a file called "icon-< character name on character.hx >"

it should work

**Comment by Kade-github** [comment]
^
