### ISSUE TITLE
Bug Report: extension-webm not found

### ISSUE THREAD

**Issue by rain-stormy** [KadeArchive/Kade-Engine#1540]
id tryed installing this but this dosent installed

 C:\Users\User>haxelib git extension-webm https://github.com/KadeDev/extension-webm
You already have extension-webm version git installed.
Updating extension-webm version git ...
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths

![paths](https://user-images.githubusercontent.com/83602259/127784956-2f81fee0-533b-405b-800b-c7ff4c5437fd.png)

**Comment by dillonhowland** [comment]
this isnt even a bug this is something on your end
