### ISSUE TITLE
Enhancment: Middle Scroll (but more information is added(when i say more i mean only one sentence more))

### ISSUE THREAD

**Issue by NukeThief** [KadeArchive/Kade-Engine#1543]
The title speaks for itself: add a Middle Scroll option (only boyfriend arrows on the middle), but make it work that you can tweak how transparent the notes of your opponent are on your row so you will still be able to see them.

__Originally posted by @NukeThief in https://github.com/KadeDev/Kade-Engine/issues/1405__

I know that optimizations does this, but it sends you to fawking darkness, and i don't want that.
Concept image (opponents arrows are editied in but my aren't)
(https://user-images.githubusercontent.com/81801547/127906088-12524bc5-e0ff-4bc8-a8e2-adfe47c623cd.png)

**Comment by NukeThief** [comment]
HOW CAN I ADD A ENHANCMENT LABEL AFTER I POSTED THE ISSUE ON MOBILE HELP

**Comment by napstaa967** [comment]
> The title speaks for itself: add a Middle Scroll option (only boyfriend arrows on the middle), but make it work that you can tweak how transparent the notes of your opponent are on your row so you will still be able to see them.
> 
> **Originally posted by @NukeThief in #1405**
> 
> I know that optimizations does this, but it sends you to fawking darkness, and i don't want that.
> (currently im not home and i can't give concept images, but when i will be back i will give some)

if i remember correctly kade said on a closed enhancement that you can use modcharts for middlescroll

**Comment by NukeThief** [comment]
how can i do it??

**Comment by KlutchDj** [comment]
> how can i do it??

kade has a modchart tutorial [here](https://github.com/KadeDev/Kade-Engine/wiki). please close this issue when you have time

**Comment by NukeThief** [comment]
Im too lazy read the entire tutorial AND it will be just easier for a lot of people

**Comment by NukeThief** [comment]
i figured out the modchart
