### ISSUE TITLE
source/DiffCalc.hx:26: calcuilafjwafBug Report: 

### ISSUE THREAD

**Issue by Nikopol93** [KadeArchive/Kade-Engine#1544]
So I do every steps: I got the sprites, the code is good, I add the songs.

The problem is, when I launch freeplay in the game, the game detects my songs, but when I scroll to it, the game's crashing.

Did I miss a step?

**Comment by napstaa967** [comment]
> So I do every steps: I got the sprites, the code is good, I add the songs.
> 
> The problem is, when I launch freeplay in the game, the game detects my songs, but when I scroll to it, the game's crashing.
> 
> Did I miss a step?

this happens for 2 reasons:
-missing files (can be the song or one of the difficulties)
-there are no notes for boyfriend

make sure the char names inside the charts are the correct and that there are notes for bf

**Comment by Nikopol93** [comment]
> > So I do every steps: I got the sprites, the code is good, I add the songs.
> > The problem is, when I launch freeplay in the game, the game detects my songs, but when I scroll to it, the game's crashing.
> > Did I miss a step?
> 
> this happens for 2 reasons:
> -missing files (can be the song or one of the difficulties)
> -there are no notes for boyfriend
> 
> make sure the char names inside the charts are the correct and that there are notes for bf

I know it it's was because of boyfriend's notes.

How do I add without going into the game?
And are you sure the missing hard and easy difficulties are a problem for now?

PS: I copy the Json file of Boobepo into the folder of my song.

**Comment by Nikopol93** [comment]
Ok it's was the missing files, thank you man.

**Comment by isakube** [comment]
close
