### ISSUE TITLE
Question: How do you zoom in charter?

### ISSUE THREAD

**Issue by WaluigiBestGirl** [KadeArchive/Kade-Engine#1546]
I literally can't figure it out

**Comment by napstaa967** [comment]
you can't

**Comment by WaluigiBestGirl** [comment]
Figured it out, its control + mouse wheel. would be helpful if something told you that, instead of me having to look into the source code

**Comment by isakube** [comment]
> its control + mouse wheel

MacOS users are crying in assistance features

**Comment by ACardboardBox1** [comment]
zooming in on most stuff is control + mouse wheel so i would've thought so
