### ISSUE TITLE
Bug Report: is it possible to compile with Neko?

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#1547]
when trying to compile the game with "lime test neko" I get this error

lime test neko
C:/HaxeToolkit/haxe/lib/discord_rpc/git/discord_rpc/DiscordRpc.hx:4: characters 8-20 : You cannot access the cpp package while targeting neko (for cpp.Function)
source/Discord.hx:5: characters 8-30 :     referenced here
source/TitleState.hx:28: characters 8-15 :     referenced here
source/Main.hx:20: characters 37-47 :     referenced here

is there any way to make it work? Thanks
![imagen_2021-08-02_122148](https://user-images.githubusercontent.com/83238785/127900001-97e9dca8-31ba-46df-94d6-65e7238847b8.png)

Using google translate

**Comment by raf13lol** [comment]
No. Now Close It.

**Comment by Kade-github** [comment]
We don't support neko. BUT, I think the reason it isn't compiling is because we're the discord haxelib which I don't think supports neko either.
