### ISSUE TITLE
Is there a way I can make the character bigger? If I make the XML and png bigger, it just crashes. My character is too small.

### ISSUE THREAD

**Issue by dartthe6th** [KadeArchive/Kade-Engine#1553]
I feel like the title is self explanatory

**Comment by napstaa967** [comment]
> I feel like the title is self explanatory

the game shouldn't crash if you make the png bigger

i think if you add:

frameWidth="new width" frameHeight="new height"

it should work

**Comment by SuperGDPWYL** [comment]
Instead of increasing the size of the file, use setGraphicSize(Std.int(width * zoom)); in Character.hx. Maxe sure to replace "zoom" with a number like 1.5.

**Comment by Kade-github** [comment]
> Instead of increasing the size of the file, use setGraphicSize(Std.int(width * zoom)); in Character.hx. Maxe sure to replace "zoom" with a number like 1.5.

^
