### ISSUE TITLE
Bug Report: Custom Weeks Crashing on 1.4

### ISSUE THREAD

**Issue by PancakeMPEG** [KadeArchive/Kade-Engine#156]
The Custom Weeks i make in kade engine 1.4 just crashes the game and I need help

**Comment by Kade-github** [comment]
We cannot help you with programming mods. The only thing I can tell you is to make sure you have everything completely done. Including code in Character.hx, MenuItem.hx, StoryMainMenu.hx, FreeplayState.hx, Loadingstate.hx, and PlayState.hx
