### ISSUE TITLE
Bug Report: Crashes on Tutorial and Thorns in latest release

### ISSUE THREAD

**Issue by LukeZingale** [KadeArchive/Kade-Engine#1560]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
I run 64 bit windows.

## What version of the game are you using? Look in the bottom left corner of the main menu.
KadeEngine 1.6.1

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
- Playing through tutorial on multiple difficulties, in story mode and in freeplay, with and without multiple options toggled
- Trying to load Thorns in freeplay on several difficulties, with and without multiple options toggled

## Please describe your issue. Provide extensive detail and images if possible.
When the song Tutorial is finished, the game crashes instead of booting you to the menu (or without showing you the results screen if that option is on.) When you try to load the song Thorns, the game crashes. There is no error message when the game crashes in both of these ways, it simply closes.

**Comment by raf13lol** [comment]
Probably Due To PR #1539 , He Reported The Same Issues With Thorns.

**Comment by Kade-github** [comment]
already fixed
