### ISSUE TITLE
Bug Report: Thorns makes the game crash

### ISSUE THREAD

**Issue by MichelLaPerche** [KadeArchive/Kade-Engine#1564]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
-Windows('x86_64')

## What version of the game are you using? Look in the bottom left corner of the main menu.
-1.6.1

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
-Basically try and play Thorns, the game crashes, whether it's in freeplay or story mode.

## Please describe your issue. Provide extensive detail and images if possible.
-Well, i don't think the song is supposed to crash, unless it's a new feature to make thorns not playable ¯\_(ツ)_/¯

**Comment by Kade-github** [comment]
already fixed
