### ISSUE TITLE
Bug Report: Webm player messing with compiling

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#1565]
im using x64 windows with 1.6.1 of kade engine

so im trying to compile the game, right? ive **made sure** multiple times that i have all the right things installed, especially webm related, but it gives me these errors, refusing to compile 

source/WebmHandler.hx:12: characters 18-28 : Type not found : WebmPlayer

![Screenshot 2021-08-04 090510](https://user-images.githubusercontent.com/88397765/128145293-70e88ba7-2e42-4ce4-a8bb-5c694c077556.png)

deleting this line of code within webmhandler fixes it but i feel like this is the wrong thing to do, as tutorial crashes the exe file under completion so i dont know if it is related to this, im really not a code genuis so i would **not** know

**Comment by satellaview-dev** [comment]
i am foaming out of my mouth this one bug has caused so many problems for me

**Comment by Kade-github** [comment]
You can delete the line just fine, the tutorial crashing is already fixed.
