### ISSUE TITLE
Error in compiling kade engine 1.6.1

### ISSUE THREAD

**Issue by xLuigiGamerx** [KadeArchive/Kade-Engine#1566]
When I try compiling kade engine 1.6.1 on windows 11 I get this error:
obj\msvc1964-nc\a796b11e_ByteArray_Impl_.obj : fatal error LNK1107: invalid or corrupt file: cannot read at 0x62CCB

It"s not cuz I'm compiling it on windows 11 I have no problems compiling kade engine 1.6.

**Comment by Futuremappermydud** [comment]
Try Deleting obj folder, please close the issue if it’s resolved

**Comment by xLuigiGamerx** [comment]
> Try Deleting obj folder, please close the issue if it’s resolved

idk where the obj folder is
im kinda new to coding in haxe and also kade engine

**Comment by Futuremappermydud** [comment]
Export/platform

**Comment by xLuigiGamerx** [comment]
> Export/platform

thx for your help
