### ISSUE TITLE
Bug Report: play here missing

### ISSUE THREAD

**Issue by Toppat-dalek** [KadeArchive/Kade-Engine#1573]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows (`x86_64`)
## What version of the game are you using? Look in the bottom left corner of the main menu.
Kade 1.6 / 1.6.1
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
just play 1.6, look at the chart editor, the play 1.6.1, and look at the chart editor.
## Please describe your issue. Provide extensive detail and images if possible.
play here was removed, care to explain?
![Capture](https://user-images.githubusercontent.com/77013267/128103870-df390091-7728-45fc-985a-808ea3fb0f50.PNG)

**Comment by isakube** [comment]
*stickbug sound plays as PlayHere mysteriously disappears*

**Comment by Kade-github** [comment]
who removed my baby

**Comment by Kade-github** [comment]
https://github.com/KadeDev/Kade-Engine/commit/fa77122877ad915df2d3bbee997ac8251734104a
