### ISSUE TITLE
Bug Report: Kade Engine charter makes exported charts 100x larger than normal

### ISSUE THREAD

**Issue by i-winxd** [KadeArchive/Kade-Engine#1574]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows 10 64bit
## What version of the game are you using? Look in the bottom left corner of the main menu.
KE 1.6 (not 1.6.1) HOWEVER the same issue still exists in KE 1.6.1
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
With a chart made outside of Kade Engine, open the charter and hit save; the exported chart is WAY larger.
## Please describe your issue. Provide extensive detail and images if possible.
![image](https://user-images.githubusercontent.com/31808925/128111518-c80d32b8-8f66-4421-8949-f2c55b9f5be7.png)
Charts exported through the Kade Engine editor take up lots more space than charts exported through most other methods. This might be caused **by the massive number of whitespaces** caused by how the contents of an exported *.json chart is organized. **I'm pretty sure whitespaces take up storage space in \*.JSON files.** Should probably revert chart formats to how they looked like before.

![image](https://user-images.githubusercontent.com/31808925/128111856-62a8ec96-50dc-42d9-ad69-9004ed36e75e.png)
The image above is a peek at a *.json file exported with KE 1.6
![image](https://user-images.githubusercontent.com/31808925/128111894-b27f6edb-81bd-4655-ba2d-616937403bfb.png)
The image above is a peek at a *.json file exported in another program, similar to FnF vanilla.

**Comment by isakube** [comment]
whitespace :trollface:

**Comment by napstaa967** [comment]
its done like this to ~~piss you off~~ make the json file human-readable

its just all indentation so if someone opens the json file in a text editor they understand what it means more easily at the cost of some filesize

**Comment by i-winxd** [comment]
> its done like this to ~piss you off~ make the json file human-readable
> 
> its just all indentation so if someone opens the json file in a text editor they understand what it means more easily at the cost of some filesize

"some"
about 100× the file size

**Comment by napstaa967** [comment]
> > its done like this to ~piss you off~ make the json file human-readable
> > its just all indentation so if someone opens the json file in a text editor they understand what it means more easily at the cost of some filesize
> 
> "some"
> about 100× the file size

its barely a megabyte, it will cost you more disk space but compared to the assets its barely anything

**Comment by Kade-github** [comment]
smh, stinky \n's increasing my charts files from 10kb to 1mb.
