### ISSUE TITLE
Hello the kade engine has a bug The arrow tails pls fix it

### ISSUE THREAD

**Issue by Khwhw78** [KadeArchive/Kade-Engine#1576]
The arrow tails pls fix it
![Screenshot_20210804-092506](https://user-images.githubusercontent.com/76597226/128132617-305351d3-7784-490d-b821-e42455c5818c.png)

**Comment by napstaa967** [comment]
the bob mod uses a modified version of fnf ke

i don't know what version is it but it could be outdated (or a fast af chart) as the tail bug was fixed some time ago

**Comment by KlutchDj** [comment]
this bug was already fixed , and this is 1.4.2

**Comment by isakube** [comment]
what the sustrails doin
