### ISSUE TITLE
Bug Report: Difficulty Choice not appearing after playing a song

### ISSUE THREAD

**Issue by KlutchDj** [KadeArchive/Kade-Engine#1577]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below. 
windows 64bit

## What version of the game are you using? Look in the bottom left corner of the main menu. 
1.6.1

## Please describe your issue. Provide extensive detail and images if possible.
After playing a stepmania type chart , the difficulty choice does not appear on the top right corner anymore. heres a video of it : 

https://user-images.githubusercontent.com/81717689/128138999-73fe30e9-4330-4bc2-935b-8af5c4c180f9.mp4

**Comment by Kade-github** [comment]
https://github.com/KadeDev/Kade-Engine/commit/78b7faf83a2a0988ae6d76074404edf186e65c1a
