### ISSUE TITLE
Bug Report: Modcharts don't work well

### ISSUE THREAD

**Issue by olivier6513893** [KadeArchive/Kade-Engine#1578]
The Hud zoom doesn't work and when the song ends the game crash.
Here a video showing what i say: https://youtu.be/a-R24P1CC2k
![image](https://user-images.githubusercontent.com/87717028/128182749-b38653d3-4b22-4930-b2d9-de42c6db1f5a.png)

**Comment by Kade-github** [comment]
fixed https://github.com/KadeDev/Kade-Engine/commit/574d13eea89cf9e9ccd4b15d0d3d3d6b3b8e7a80
