### ISSUE TITLE
Bug Report: Thorns crashes the game.

### ISSUE THREAD

**Issue by hAck-3r64** [KadeArchive/Kade-Engine#1579]
I'm using Kade Engine version 1.6.1 on MacOS, and I know that this also happened on the 1.6 version.

If you load into Thorns in either Story Mode or Freeplay, It crashes the game.

**Comment by yet66** [comment]
This must be your computer cause Mine works fine on my Mac

**Comment by Kade-github** [comment]
https://github.com/KadeDev/Kade-Engine/commit/ca0245d772e9acae46ef53437c5a3c6ca5a7bff9
