### ISSUE TITLE
Appearently -2142 is out of any segs

### ISSUE THREAD

**Issue by Geezt435** [KadeArchive/Kade-Engine#1580]
https://github.com/KadeDev/Kade-Engine/issues/1476
Similiar Issue but I don't found the solution there

I tried deleting everything inside of export, but it keeps giving the same bug, tried to use the debug aswell and found the same bug aswell.

I used Windows64

with Kade Engine version 1.6.1

based on the error, I goes to TimingStruct.hx, new source file but I guess it connected to charting mechanism? I just update my previous mod which is Kade Engine 1.5.2 to 1.6.1 so I really need this to be done

**Comment by isakube** [comment]
this is literally just a trace why is this here

-2142 is out of any segments because it's before the song

**Comment by Geezt435** [comment]
> this is literally just a trace why is this here
> 
> -2142 is out of any segments because it's before the song

so it didn't cause the crash?

**Comment by Kade-github** [comment]
That is not a crash report, you are crashing because of something else. This is just telling you that the current time has no BPM Segments because it is before the start of the song.
