### ISSUE TITLE
Enhancement: This is more a question, where have the charcter lists disapeared?

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#1582]
Im using 1.6.1 of kade engine, and i cant seem to be able to add my character? in character.hx its just this, 
![image](https://user-images.githubusercontent.com/88397765/128206275-d8af06af-cf2c-407e-8d6e-c725d6e70972.png)
so, if anyone could tell me where i can access this health icon stuff? to add my character?

**Comment by isakube** [comment]
lol we changed how icons get loaded, you gotta move your character icons into a file in `shared/images/icons/icon-(char)`

**Comment by ghost** [comment]
> lol we changed how icons get loaded, you gotta move your character icons into a file in `shared/images/icons/icon-(char)`

ah thank you i didnt realise
