### ISSUE TITLE
How to add new health icons in 1.6.1

### ISSUE THREAD

**Issue by TheGamingCat89** [KadeArchive/Kade-Engine#1584]
Since there isn't a question label im opening a blank one lol

Well since in 1.6.1 Kade Engine they changed the way health icons work, I wanted to ask  if someone could tell me how to add them.

**Comment by napstaa967** [comment]
> Since there isn't a question label im opening a blank one lol
> 
> Well since in 1.6.1 Kade Engine they changed the way health icons work, I wanted to ask if someone could tell me how to add them.

i downloaded 161 and for some reason it doesn't change the way

but anyways you make a new file inside preload/images/icons called "icon-< your character >"
then place the 2 icons inside it
then compile

**Comment by TheGamingCat89** [comment]
> > Since there isn't a question label im opening a blank one lol
> > Well since in 1.6.1 Kade Engine they changed the way health icons work, I wanted to ask if someone could tell me how to add them.
> 
> i downloaded 161 and for some reason it doesn't change the way
> 
> but anyways you make a new file inside preload/images/icons called "icon-< your character >"
> then place the 2 icons inside it
> then compile

I tried that and it doesn't work at all

**Comment by bonduongchannel** [comment]
@napstaa967 this is character position changer! what i want is to change the character icon when the character is changed. For example, from one character to another, the icon will also change.
ex:
case 3:
remove(dad);
dad = new Character(400, 130, 'gf3');
add(dad);
iconP2.animation.play('gf3');
this is in the old mod. new mod 1.7 doesn't work
->
iconP2.animation.play ('gf3');
in mod 1.7 change icon path. so the command line must be faulty
