### ISSUE TITLE
can't compile game

### ISSUE THREAD

**Issue by yandelsucksatcoding** [KadeArchive/Kade-Engine#1586]
so i am using the 1.6.1 version of kade. and when i try to start up the game it says Source path "C:/HaxeToolkit/haxe/lib/extension-webm/git/ndll/Windows64/extension-webm.ndll" does not exist. and so i tried doing the lime rebuild extension-webm windows. but then another error occurs saying Error: mkvwriter.cpp
./libwebm/mkvwriter.cpp(9): fatal error C1083: Cannot open include file: 'mkvwriter.hpp': No such file or directory. PLEASE HELP

**Comment by napstaa967** [comment]
~~I SWEAR TO GOD NO ONE READS THE FUCKING GUIDE~~
read. https://kadedev.github.io/Kade-Engine/building

**Comment by napstaa967** [comment]
> so i am using the 1.6.1 version of kade. and when i try to start up the game it says Source path "C:/HaxeToolkit/haxe/lib/extension-webm/git/ndll/Windows64/extension-webm.ndll" does not exist. and so i tried doing the lime rebuild extension-webm windows. but then another error occurs saying Error: mkvwriter.cpp
> ./libwebm/mkvwriter.cpp(9): fatal error C1083: Cannot open include file: 'mkvwriter.hpp': No such file or directory. PLEASE HELP

do you have the windows building dependencies installed

**Comment by notmagniill** [comment]
you could take one mods extension-webm.ndll and on the HaxeToolkit/haxe/lib/extension-webm/ndll/Windows, copy the .gitignore.txt then make a folder called Windows64 then paste the 2 files, done!!!

**Comment by notmagniill** [comment]
> you could take one mods extension-webm.ndll and on the HaxeToolkit/haxe/lib/extension-webm/ndll/Windows, copy the .gitignore.txt then make a folder called Windows64 then paste the 2 files, done!!!

IT WILL WORK, I DID THIS TOO AND IT WORKED
