### ISSUE TITLE
add a new label for questions

### ISSUE THREAD

**Issue by napstaa967** [KadeArchive/Kade-Engine#1587]
apparently some people just ask questions here and leave them tagged as a bug or don't tag them
maybe add a new tag for questions if someone wants to ask how to do something

**Comment by theDetourist** [comment]
Questions shouldn't even be here in the first place, go to the [Discord server](https://discord.gg/GEnXqCmG) for that.

**Comment by KlutchDj** [comment]
> Questions shouldn't even be here in the first place, go to the [Discord server](https://discord.gg/GEnXqCmG) for that.

^^

**Comment by napstaa967** [comment]
> Questions shouldn't even be here in the first place, go to the [Discord server](https://discord.gg/GEnXqCmG) for that.

yeah but for some reason people still ask them here

**Comment by KlutchDj** [comment]
> > Questions shouldn't even be here in the first place, go to the [Discord server](https://discord.gg/GEnXqCmG) for that.
> 
> yeah but for some reason people still ask them here

doesn't mean we need to add one . the discord is there for a reason IMO

**Comment by isakube** [comment]
ever heard of a discussion OP?

**Comment by napstaa967** [comment]
> ever heard of a discussion OP?

i forgor
