### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by CatRass** [KadeArchive/Kade-Engine#159]
Upon compiling the game as debug or release for html5 out of the box (I am unable to test if this happens for windows as I do not have a compiler), the following error message appears (in image attached), with something to do with the Discord.hx file. I've tried copying this file from 1.3 versions of Kade, which all worked, and still work. I've tried the 1.4 and 1.4 nightly builds, all with the same results.

![image_2021-04-07_093634](https://user-images.githubusercontent.com/61177602/113790447-bc909000-9784-11eb-9a5a-ddff917a5e0d.png)

**Comment by theDetourist** [comment]
Don't build the game to HTML5, Discord RPC is exclusive to Windows builds from now on. If you still want to build it to HTML5, remove Discord.hx and any mentions to Discord RPC from the files.

**Comment by Jaduplex** [comment]
i think the discord rpc library should be included in all builds but only used in windows builds

**Comment by puyoxyz** [comment]
This has been fixed for a while. Please clone the master branch (not a nightly release) and try again.

@theDetourist: That's outdated information. HTML5 building got fixed in 8af197ab19d597a6c31f5e7d7460551e335d5c1e.

**Comment by CatRass** [comment]
@theDetourist that worked, thanks. I was using the release version which did not have those changes. Thanks for the help!
