### ISSUE TITLE
Week 7 QOL improvements

### ISSUE THREAD

**Issue by RobinYH** [KadeArchive/Kade-Engine#1592]
The week 7 update added many small QOL improvements, ex: Change difficulty button in pause menu, option to enable practice mode where you can't die, ect.

**Comment by theDetourist** [comment]
No, not until Week 7's source code drops officially.

**Comment by Kade-github** [comment]
![image](https://user-images.githubusercontent.com/26305836/128267004-f28f769e-05e0-4884-8650-bcc2caf89887.png)
