### ISSUE TITLE
Game crashes among selecting "Load Replays" in Options. 

### ISSUE THREAD

**Issue by Texzx** [KadeArchive/Kade-Engine#16]
Compiled on Mac OS Mojave 10.14.5. 

Current Master Build, everything works correctly, except (either) You select Load Replays, or whenever you finish a level, it doesn't matter if it is in story mode or freeplay, the console gives me 

"Error : [file_open,assets/replays/replay-Tutorial-time1615805586615.12.kadeReplay]" 
Turns out, that creating a replays folder in assets fixes it, currently the only reason why it crashed is because the game creates 2 folders that makes the game freak out, giving it errors because that asset folder/path is wrong. 
What I'm trying to say here is that the folders named 
\assets and \assets\replays Don't do anything except crash ones game, Load Replays option, on the other hand, will still crash ones game on current master build. Reasons why I still do not know.

**Comment by Kade-github** [comment]
I don't think the sys function for create directory works on macos. that's weird. I'll have to look into that.

**Comment by isakube** [comment]
i just run the exe in Wineskin but i guess thats kinda cheating?

**Comment by Kiffolisk** [comment]
cheating?? huh

**Comment by Kade-github** [comment]
mac os issue.
