### ISSUE TITLE
Bug Report: changeBoyfriendCharacter (BoyfriendCharacter animation bug)

### ISSUE THREAD

**Issue by lemz1** [KadeArchive/Kade-Engine#1603]
Kade Engine 1.6.1 (Windows 64bits)
I tried restarting the game and looking at the modchart but nothing is wrong there atleast if i'm not wrong.
Here's a video of the animation bug:
![Hnet com-image](https://user-images.githubusercontent.com/87707926/128366616-1f682447-bc5e-463d-bd0c-0d8194fea27a.gif)

Here's the code
![Screenshot (32)](https://user-images.githubusercontent.com/87707926/128367781-778dfaed-337a-487c-a26d-be1bb19fce5b.png)

**Comment by isakube** [comment]
everything here works correctly what u doin

**Comment by lemz1** [comment]
is it supposed to be like that while singing a long note? (I mean Mommy_Mearest - it seems weird to me)
