### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by TNHo** [KadeArchive/Kade-Engine#1616]
I can't test the game as I keep getting this error:
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/Character.hx:386: characters 14-18 : Type not found : Path

I am on Windows  x64
I believe this is version 1.6 since I downloaded it last week.

**Comment by napstaa967** [comment]
> I can't test the game as I keep getting this error:
> C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
> C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
> source/Character.hx:386: characters 14-18 : Type not found : Path
> 
> I am on Windows x64
> I believe this is version 1.6 since I downloaded it last week.

what is on line 384-387 in chracter.hx

**Comment by TNHo** [comment]
I realized I made a typo on that line.
I had "frames = Path.getSparrowAtlas"  on one of my lines. Correcting it to "frames = Paths.getSparrowAtlas" fixed it.
