### ISSUE TITLE
Bug Report: App Veyor says Acess Denied

### ISSUE THREAD

**Issue by Fancy2209** [KadeArchive/Kade-Engine#162]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Linux x64
## What version of the game are you using? Look in the bottom left corner of the main menu.
Didn't get to download
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Press the Linux download from the AppVeyor Realese
## Please describe your issue. Provide extensive detail and images if possible.
When I try to download the linux version trough AppVeyor it gives me an error:
![Captura de ecrã de 2021-04-07 14-58-25](https://user-images.githubusercontent.com/64917206/113888389-d5fc0100-97b1-11eb-82e4-dd0b6b69a073.png)
But if I go to the windows AppVeyor page it works
![Captura de ecrã de 2021-04-07 15-01-06](https://user-images.githubusercontent.com/64917206/113888690-19ef0600-97b2-11eb-9a8c-bbf11bdae4b7.png)

**Comment by Fancy2209** [comment]
who is weird because it was realesed yesterday

**Comment by Kade-github** [comment]
Oops I think I just fixed that.

**Comment by puyoxyz** [comment]
so kade closed this for no reason

the actual problem is appveyor won't let him make the linux project for some reason, you can download linux builds from [here](https://ci.appveyor.com/project/daniel11420/kade-engine-linux) while that's being resolved (as of posting this comment a build is running so you might need to wait for it to finish)

**Comment by Kade-github** [comment]
oh wait I actually just read this wrong lol. but yeah for now you can go to daniel's page.

**Comment by Fancy2209** [comment]
It seems once again this is broken

**Comment by Fancy2209** [comment]
Tough differently I should've not reopened this should've just made new issue

**Comment by puyoxyz** [comment]
> It seems once again this is broken

CI is now on GitHub actions, click the "actions" tab at the top of this page
