### ISSUE TITLE
Bug Report: various bugs

### ISSUE THREAD

**Issue by cacahuwek** [KadeArchive/Kade-Engine#1622]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

windows 10 64 bits and wine windows 10 64bits environnement(linux)

## What version of the game are you using? Look in the bottom left corner of the main menu.

version 1.6.1

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

replace data files by data of b-side

## Please describe your issue. Provide extensive detail and images if possible.

well, images will describe lol, also some animations on menu are missing (when i press a button like story mod etc) but only on windows 
![Screenshot_20210806_192056](https://user-images.githubusercontent.com/78932119/128549538-e3c682b4-bc1f-43d3-b342-78d87b3ea29e.png)
![Screenshot_20210806_192111](https://user-images.githubusercontent.com/78932119/128549551-4cf747a9-22ba-457d-9043-83e06d1014bc.png)

**Comment by KlutchDj** [comment]
this isnt a bug. you shouldn't replace the note assets since kade 1.6+ changed how arrow assets works. just replace it again with the 1.6 arrow asset and it should be fixed. close this once resolved

**Comment by cacahuwek** [comment]
yep, thanks but do you know about the menu animation? also the game crashes when i launch thorns, do you know why?

**Comment by cacahuwek** [comment]
Solved in 1.6.2
