### ISSUE TITLE
Bug Report: WebmHandler.hx preventing compiling 1.6.1

### ISSUE THREAD

**Issue by satellaview-dev** [KadeArchive/Kade-Engine#1629]
I am trying to compile a mod on 1.6.1 and WebmHandler.hx is giving me an error that says: "
![image](https://user-images.githubusercontent.com/45579861/128595845-ef3a9dc6-be79-4342-8b36-08985bfd5ea6.png)
(source/WebmHandler.hx:12: characters 18-28 : Type not found : WebmPlayer)"
I have tried to remove the said code and that only creates more problems, even removing the code that causes THOSE problems in turn causes more problems. 
I have re-installed actuate and rebuilt extension-webm multiple times. 
![image](https://user-images.githubusercontent.com/45579861/128595934-1f894639-866c-473a-8efd-09ed660bb8bd.png)
This has been bugging me for 4 days now and I would really like to continue working on my mod.

**Comment by DOGZ1234** [comment]
Which version of extension-webm do you have installed?

**Comment by satellaview-dev** [comment]
@DOGZ1234 the newest version from kade

**Comment by DOGZ1234** [comment]
try the newest version of the source code

**Comment by satellaview-dev** [comment]
tried that, doesnt work, i even tried just compiling the unmodified source code itself, and it doesnt work
