### ISSUE TITLE
Wiggle Shader for Lua Modcharts

### ISSUE THREAD

**Issue by DavidPootis** [KadeArchive/Kade-Engine#1636]
How do you create a wiggle shader With Lua modcharts?
Idk how to make it work lol.

**Comment by raf13lol** [comment]
function start(song) -- do nothing

end

function update(elapsed)
    if difficulty == 2 and curStep > 400 then
        local currentBeat = (songPos / 1000)*(bpm/60)
		for i=0,7 do
			setActorX(_G['defaultStrum'..i..'X'] + 32 * math.sin((currentBeat + i*0.25) * math.pi), i)
			setActorY(_G['defaultStrum'..i..'Y'] + 32 * math.cos((currentBeat + i*0.25) * math.pi), i)
		end
    end
end

function beatHit(beat) -- do nothing

end

function stepHit(step) -- do nothing

end

function playerTwoTurn()
    tweenCameraZoom(1.3,(crochet * 4) / 1000)
end

function playerOneTurn()
    tweenCameraZoom(1,(crochet * 4) / 1000)
end

alter it a bit and done :) so close it :|

**Comment by DavidPootis** [comment]
I meant making Wiggle shaders with a modchart.Not the default example modchart lmao.

**Comment by raf13lol** [comment]
oh then i dont know

**Comment by raf13lol** [comment]
but that does work

**Comment by p0008874** [comment]
Founded on Line 441 In ModchartState.hx

				Lua_helper.add_callback(lua,"setNoteWiggle", function(wiggleId) {
					PlayState.instance.camNotes.setFilters([new ShaderFilter(luaWiggles.get(wiggleId).shader)]);
				});
				
				Lua_helper.add_callback(lua,"setSustainWiggle", function(wiggleId) {
					PlayState.instance.camSustains.setFilters([new ShaderFilter(luaWiggles.get(wiggleId).shader)]);
				});

**Comment by DavidPootis** [comment]
Thanks you!

**Comment by raf13lol** [comment]
*Thank
