### ISSUE TITLE
Bug Report: The Freeplay,

### ISSUE THREAD

**Issue by nosamiii** [KadeArchive/Kade-Engine#164]
I just download and use the Kade Engine, and want to know if Tutorial is supposed to be the only freeplay song? am i the only one experiencing this? is there a way to fix it?

**Comment by Blantados** [comment]
Also had this. To fix it just go to assets\data\freeplaySongList.txt and add all the songs back in manually. They will all have the bf icon though.

**Comment by puyoxyz** [comment]
Which version is this on? If it's not a Nightly, can you try to download a build from AppVeyor if you're not already using one from there? https://ci.appveyor.com/project/KadeDev/kade-engine-windows/build/artifacts (It might already be fixed)
