### ISSUE TITLE
How can I set the camera's postion

### ISSUE THREAD

**Issue by lemz1** [KadeArchive/Kade-Engine#1656]
If I'm not wrong I have something to do with  setCamPosition(x:Int, y:Int) but I'm not sure what to put in since I don't get an error message when doing   setCamPosition(x'400', y'400') (When I tested it in the song nothing changed.). So can anyone show me what to put in.

(This is the function i used):
function update(elapsed)
    setCamPosition(x'400', y'400')
end
(also tried it with)
function playerOneTurn()
  setCamPosition(x'400', y'400')
end

**Comment by isakube** [comment]
the lua interpreter pisses itself whenever you're not on Windows so we only do modchart stuff on Windows
and in case you ARE on windows
```lua
setCamPosition(400, 400);
```

**Comment by lemz1** [comment]
thx
