### ISSUE TITLE
Bug Report: source/PlayState.hx:520: characters 3-7 : Expected }

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#1657]
#### Please check for duplicates, similar issues or closed issues with the same problem, as well performing simple troubleshooting steps (such as deleting the export folder if it's an issue with compiling, reinstalling Kade Engine) before submitting an issue.

1.6.1 of kade engine with windows 64

source/PlayState.hx:520: characters 3-7 : Expected } shows up when i try to lime test windows, this is because i added in a week, switch (storyWeek)
			{
				case 2:
					stageCheck = 'halloween';
				case 3:
					stageCheck = 'philly';
				case 4:
					stageCheck = 'limo';
				case 5:
					if (songLowercase == 'winter-horrorland')
					{
						stageCheck = 'mallEvil';
					}
					else
					{
						stageCheck = 'mall';
					}
				case 6:
					if (songLowercase == 'thorns')
					{
						stageCheck = 'schoolEvil';
					}
					else
					{
						stageCheck = 'school';
					}
					// i should check if its stage (but this is when none is found in chart anyway)
				case 7:
					stageCheck = 'faz';
					}

i have no idea how to fix this?
do i have to add a , or a ;? 
![image](https://user-images.githubusercontent.com/88397765/128635749-e70b8f93-82b2-4499-8d48-d8ec3118b783.png)

**Comment by raf13lol** [comment]
send the entire file

**Comment by isakube** [comment]
remove this (line 517)
![Screen Shot 2021-08-08 at 10 44 41 AM](https://user-images.githubusercontent.com/68293280/128640809-4b97af4b-92d7-4359-a655-cc93e8c0feab.png)
