### ISSUE TITLE
how can i change the camera postion

### ISSUE THREAD

**Issue by lemz1** [KadeArchive/Kade-Engine#1664]
1.6.1 Kade Engine (Windows 64bit)
Hi,
I would like to know how to change the camera postion from mommy_mearest since it is too low.

(Here's a video of how it looks like)
![Mommymearest](https://user-images.githubusercontent.com/87707926/128645189-c05671d5-3b6a-47ee-a2ca-bf46fe2081d0.gif)

Thanks in advance!

**Comment by raf13lol** [comment]
Modcharts.

**Comment by lemz1** [comment]
which command do i need to do since setCamPostion makes the borders black

**Comment by raf13lol** [comment]
setCamZoom

**Comment by lemz1** [comment]
i tried it with setCamZoom but it doesnt help it just zooms or do i have to do something else too?

**Comment by raf13lol** [comment]
send modchart

**Comment by lemz1** [comment]
[modchart.txt](https://github.com/KadeDev/Kade-Engine/files/6960757/modchart.txt)

I changed the .lua to .txt so I can send it

**Comment by raf13lol** [comment]
[modchart.txt](https://github.com/KadeDev/Kade-Engine/files/6960896/modchart.txt)
try this

**Comment by lemz1** [comment]
thx
