### ISSUE TITLE
Game crashes when it's bf's turn.

### ISSUE THREAD

**Issue by TheGamingCat89** [KadeArchive/Kade-Engine#1668]
![image](https://user-images.githubusercontent.com/81439207/128647598-ba04d6ff-0989-4531-a568-f1eb945510d7.png)
So this is the code that is causing it and I don't really know why or how is it crashing when it's bf's turn specifically
Any idea on what's going on?

**Comment by Spel0** [comment]
while true overload moment

**Comment by TheGamingCat89** [comment]
> while true overload moment

Some help is appreciated, I'm no genius 😔

**Comment by HastagGuigui** [comment]
He says that because while (true) seems to overload the game, for unknown (at least for me) reasons, and making it crash because of it
