### ISSUE TITLE
Can't play songs

### ISSUE THREAD

**Issue by LikeToCodeStreams** [KadeArchive/Kade-Engine#167]
whenever i boot the kade engine or any custom week, the game starts, doesnt show the intro. if i press enter on the intro the animation doesnt appear, and when i play a level, the animations dont work and the chart and song doesnt work.

**Comment by idkwhattowritehere** [comment]
same, i would say its actually the same problem ._. , also i think its more of a glitch than a bug

**Comment by LikeToCodeStreams** [comment]
I just randomly fixed itself
