### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by KPlayzlol** [KadeArchive/Kade-Engine#1677]
please help me setting it up the cmd panel said
Error: Could not find haxelib "actuate", does it need to be installed?
on the yt video i was watching this doesnt happened

**Comment by raf13lol** [comment]
when you forget to use the build guide that kade dev released 
(here is the link --> https://github.com/KadeDev/Kade-Engine/blob/stable/docs/building.md)

**Comment by FChesco** [comment]
put on your CMD haxelib install actuate

**Comment by KPlayzlol** [comment]
now the setup said this "Source path "C:/HaxeToolkit/haxe/lib/extension-webm/git/ndll/Windows64/extension-webm.ndll" does not exist"

**Comment by KPlayzlol** [comment]
what do i need to download now

**Comment by KPlayzlol** [comment]
i followed all download on https://github.com/KadeDev/Kade-Engine/blob/stable/docs/building.md
