### ISSUE TITLE
Bug Report: I'm unable to edit any charts. (only get rid of notes)

### ISSUE THREAD

**Issue by bruh331** [KadeArchive/Kade-Engine#168]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows (`x86_64`)
## What version of the game are you using? Look in the bottom left corner of the main menu.
1.4
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
No.
## Please describe your issue. Provide extensive detail and images if possible.
If I wanted to get rid of any notes in charts, it refuses, keeping the notes there. I don't know what is going on or why it's doing it.
I just want info on how to fix.

**Comment by Kade-github** [comment]
"I'm unable to edit any charts. (only get rid of notes)" "If I wanted to get rid of any notes in charts, it refuses, keeping the notes there. " those are 2 very different things. You're saying you can get rid of notes but can't place any, and then you're saying you cannot remove notes only place them.

bruh

**Comment by bruh331** [comment]
I meant the problem was I'm unable to remove notes.

**Comment by OryZenDev** [comment]
I also have the same problem, unable to remove notes.

**Comment by reedM2** [comment]
Same thing here.

**Comment by Kade-github** [comment]
fixed in the latest version
