### ISSUE TITLE
Bug Report: not compiling properly/

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#1680]
kade engine 1.6.1 with windows 64 bit.

so im compiling, right? trying to find out why a freeplay and story mode song crahses the game (i didnt make an issue for that as its probably my fault) but i went into the release folder, and found out its not actually compiling all the files in? i made a folder called week 7, probably whats causing the crash, and its not showing up in tge compliled versions folder, i tried deleting all the folders and lime test windows again, same problem

SOURCE CODE:
![image](https://user-images.githubusercontent.com/88397765/128748698-031ea8bb-101d-401a-a8c2-cfc2f8477032.png)

COMPILED VERSION:
![image](https://user-images.githubusercontent.com/88397765/128748752-ee98e933-7ab0-4b10-9da4-a63ad06dea0a.png)
 Any reason for this??

**Comment by raf13lol** [comment]
its to do with your project.xml file

**Comment by FelipeBacana** [comment]
> its to do with your project.xml file

Change export32bit to 64bit
