### ISSUE TITLE
Bug Report: You Can Die In Replays And The Notes In Them Are Weird When Pressed Down By The Replay Bot.

### ISSUE THREAD

**Issue by raf13lol** [KadeArchive/Kade-Engine#1681]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Windows x86_64

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.6.1 Development Build: https://ci.appveyor.com/api/buildjobs/7bn364eurq3ake7b/artifacts/export%2Frelease%2Fwindows%2FKadeEngine-Windows.zip

 Issue No.1:
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Just Load A Replay On Satin-Panties And Watch BF Die.

## Please describe your issue. Provide extensive detail and images if possible.
Hold Notes Make You Lose Health In A Replay.
[replay-Satin Panties-time1628537189481.txt](https://github.com/KadeDev/Kade-Engine/files/6956939/replay-Satin.Panties-time1628537189481.txt)
Here Is My Replay. Change .txt  To .kadeReplay

Issue No.2:
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Start A Replay And Look At The Notes.

## Please describe your issue. Provide extensive detail and images if possible.
The Notes When Pressed By The Replay Bot Go Down Weirdly.

**Comment by Dfvesf** [comment]
It is normal, replays are still in a beta phase

**Comment by raf13lol** [comment]
yes but it problemo

**Comment by raf13lol** [comment]
my bad old replay be sus
