### ISSUE TITLE
i need help again

### ISSUE THREAD

**Issue by KPlayzlol** [KadeArchive/Kade-Engine#1686]
what do i need to download when this happened

![image_2021-08-10_091737](https://user-images.githubusercontent.com/88667113/128798340-6950966e-391c-4b8c-b6cd-43ce3a80a7c3.png)

**Comment by KlutchDj** [comment]
did you download every component on the building.md ?

**Comment by KPlayzlol** [comment]
yea

**Comment by KPlayzlol** [comment]
i did

**Comment by KPlayzlol** [comment]
#

**Comment by KPlayzlol** [comment]
nobody will fix my problem :C

**Comment by raf13lol** [comment]
lime rebuild extension-webm windows

**Comment by raf13lol** [comment]
do that

**Comment by KPlayzlol** [comment]
i have done that but it says
![image_2021-08-11_223418](https://user-images.githubusercontent.com/88667113/129059105-7ede3d57-1d44-4a9e-b5e7-abdc8839183a.png)
it keep saying that 30 times

**Comment by raf13lol** [comment]
when you dont read the build guide by kade dev

**Comment by raf13lol** [comment]
do you have discord this can be quicker

**Comment by KPlayzlol** [comment]
i have discord

**Comment by KPlayzlol** [comment]
i read all the build guide too
and follow them

**Comment by raf13lol** [comment]
what is tag
i can add you
