### ISSUE TITLE
song is not working

### ISSUE THREAD

**Issue by HiroMizuki** [KadeArchive/Kade-Engine#1694]
well, i was working for my mod, and then, i've gone to add a song

i added the song folders in data and songs folders, also in freeplaySongList.txt

but, when i tried the song, the game freezes in a infinite and fast loop of bumping screen, and showing the song stage, characters, arrows, everything

please, help

**Comment by TNT-King** [comment]
Maybe restart your PC

**Comment by HiroMizuki** [comment]
> Maybe restart your PC

i'll try this

**Comment by HiroMizuki** [comment]
> Maybe restart your PC

now it's working, but idk if is necessary restart the pc, probably was the file size
anyway, thanks

**Comment by isakube** [comment]
congrats on being the 700th closed issue

**Comment by HastagGuigui** [comment]
i was about to say this

**Comment by HiroMizuki** [comment]
> congrats on being the 700th closed issue

thanks, i think
