### ISSUE TITLE
How do you finalize a mod?

### ISSUE THREAD

**Issue by Nikopol93** [KadeArchive/Kade-Engine#1695]
Y'know, with the icon and all.

**Comment by FChesco** [comment]
Go to art on ur KE source code, u will find "icon128.png icon16.png
icon256.png
icon32.png
icon512.png
icon64.png
icon8.png
iconOG.png"
And select ur custom icon (make sure the icon is the size o for example if I wanna change icon64.png I have to pt the icon in 64 bits format
And to finalize go to export>release>windows>bin and change the name of bin folder (optional) and then publish it and stuff
HOPE U FIND THIS HELPFUL!

**Comment by Nikopol93** [comment]
> Go to art on ur KE source code, u will find "icon128.png icon16.png
> icon256.png
> icon32.png
> icon512.png
> icon64.png
> icon8.png
> iconOG.png"
> And select ur custom icon (make sure the icon is the size o for example if I wanna change icon64.png I have to pt the icon in 64 bits format
> And to finalize go to export>release>windows>bin and change the name of bin folder (optional) and then publish it and stuff
> HOPE U FIND THIS HELPFUL!

Sorry to answer it THAT late, I already found the answer but thank anyway.
