### ISSUE TITLE
crashes after completing a level

### ISSUE THREAD

**Issue by lawrencfgsdfg** [KadeArchive/Kade-Engine#1696]
version: kade engine 1.6.1, played on windows x64
this happens on the downloaded version **and** [website](https://funkin.puyo.xyz/nightly/).

reproduce: literally just play the tutorial

https://user-images.githubusercontent.com/64938169/128914375-010636cc-ea1d-4524-b1d8-d51cb2fd1249.mp4
https://user-images.githubusercontent.com/64938169/128915307-557398c0-40df-4295-b56b-d11c1bedeceb.mp4

**Comment by raf13lol** [comment]
same

**Comment by KlutchDj** [comment]
this was already fixed here . https://github.com/KadeDev/Kade-Engine/commit/bbd8599c4675b9f2581c31bba31da411ff6ae70b . this issue can be closed now
