### ISSUE TITLE
Bug Report: No difficulties found for chart, skipping.

### ISSUE THREAD

**Issue by TechniGames** [KadeArchive/Kade-Engine#1698]
## When I try using charts for my custom song, it gives me an error stating "No difficulties found for chart, skipping." I:
Checked to make sure the song's folder was in the right place.
Checked to make sure the chart difficulties were marked correctly.
Checked to make sure the song names were spelled correctly.

I currently have no idea how it isn't detecting the charts inside the folder. Any help would be appreciated.

**Comment by raf13lol** [comment]
what is the names of all the .json files?

**Comment by flashintv** [comment]
did you compile with the jsons inside of the source code? if not recompile with files inside since if you don't do that the manifest file won't make them 'visible' for the game

**Comment by TechniGames** [comment]
nvm I was lied to turns out you actually need to put dashes instead of spaces in the json files even if the name has spaces in it
