### ISSUE TITLE
Bug Report: FreePlay song continues after leaving FreePlay.

### ISSUE THREAD

**Issue by libracrumbs** [KadeArchive/Kade-Engine#1704]
Windows (x86-x64)

KE 1.6.1 FNF 0.2.7.1

Go to FreePlay. Hover over a song and press ESC. The freeplay song will continue to play while on menu.

The chosen song in FreePlay continues after leaving FreePlay.

**Comment by raf13lol** [comment]
Intended, I Think.

**Comment by nahiassis** [comment]
this is normal, its on the original game too

**Comment by libracrumbs** [comment]
idk how to delete issues, so its gonna be here for a while
edit: i found it.
