### ISSUE TITLE
Completing Tutorial on hard crashes the game

### ISSUE THREAD

**Issue by BLJMan** [KadeArchive/Kade-Engine#1705]
don't know if it's because it's on hard or because the ending screen is broken or something, but just after you complete the tutorial the game freezes, then closes.
(playing on windows)
also week 6 songs crash as well, but i think this was already documented in another bug report

**Comment by raf13lol** [comment]
already fixed get latest development build

**Comment by KlutchDj** [comment]
this issue was already fixed on another bug report . Please close this . https://github.com/KadeDev/Kade-Engine/commit/bbd8599c4675b9f2581c31bba31da411ff6ae70b
