### ISSUE TITLE
Bug Report: Game crashing when on a mods song

### ISSUE THREAD

**Issue by Alt-Reality** [KadeArchive/Kade-Engine#1709]
So I'm working on a mod, and I made a song, and put it in freeplay. However whenever I scroll down and then hover over the song, the game instantly crashes. Here's a video of the issue: https://drive.google.com/file/d/1R_sAMcesHUZyFQGt7UgzJLkRhnTWjIYM/view?usp=sharing

**Comment by lunarcleint** [comment]
You need to Create the Charts for the song to load in free play This isnt A Bug!

**Comment by Alt-Reality** [comment]
> You need to Create the Charts for the song to load in free play This isnt A Bug!

I made a easy chart since that was the only one i didnt have, and it worked! Thank you
