### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by talesgreen** [KadeArchive/Kade-Engine#1725]
![image](https://user-images.githubusercontent.com/88807522/129277397-3af18449-6687-4ce4-a88d-bf60fd07b89c.png)
wHEN I COMPILE IT ALWAYS SHOW "PlayState.hx:537: characters 4-8 : Expected }" 

i already removed these } and {, it's not working

kade engine 1.3.1

**Comment by napstaa967** [comment]
> ![image](https://user-images.githubusercontent.com/88807522/129277397-3af18449-6687-4ce4-a88d-bf60fd07b89c.png)
> wHEN I COMPILE IT ALWAYS SHOW "PlayState.hx:537: characters 4-8 : Expected }"
> 
> i already removed these } and {, it's not working
> 
> kade engine 1.3.1

verify that the indentation of everything is correct
also this may mean you need to add a new } after line 536

**Comment by talesgreen** [comment]
Now it says 
"PlayState.hx:538: characters 4-8 : Expected }"
![image](https://user-images.githubusercontent.com/88807522/129291364-01a925c3-dbf3-4f5f-b862-e7a1a82d4e1e.png)

**Comment by napstaa967** [comment]
"expected }" means there should be another } before it

**Comment by talesgreen** [comment]
like this 
![image](https://user-images.githubusercontent.com/88807522/129391473-211a71e4-bf30-446d-9263-cdf6f0bf4c65.png)

**Comment by ACardboardBox1** [comment]
no i think they mean **after**

}
else if (song.song.tolowercase() == 'test4')
} 
   (cool bg shit)
{

**Comment by THALES243** [comment]
PlayState.hx:538: characters 4-8 : Expected }

**Comment by talesgreen** [comment]
now it says PlayState.hx:538: characters 13-17 : Expected }
