### ISSUE TITLE
Bug Report: character not working

### ISSUE THREAD

**Issue by meatloaf834** [KadeArchive/Kade-Engine#1726]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
windows x86
## What version of the game are you using? Look in the bottom left corner of the main menu.
1.6 (i think, it might be 1.6.1 because i downloaded 1.6.1 but it says im using 1.6 so shrug)
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
no, i tried and tried but it just doesnt work
## Please describe your issue. Provide extensive detail and images if possible.
when i try and go in bopeebo and go in debug mode i enter my character and it crashes the game when i exit debug mode. i made a grid icon and everything, it just doesnt work

**Comment by raf13lol** [comment]
send files

**Comment by HePpYPro** [comment]
You probably misspeled some of the names or files of the code

**Comment by meatloaf834** [comment]
> send files

![ninja](https://user-images.githubusercontent.com/88857608/129397802-85bd7c2b-ed54-4e50-b8ed-7890312df39f.png)

![iconGrid](https://user-images.githubusercontent.com/88857608/129397838-e85ec415-a9d8-4866-af93-c753f8915f6d.png)

**Comment by raf13lol** [comment]
send character.hx and the xml for your character

**Comment by meatloaf834** [comment]
i fixed it already, idk what was wrong.
