### ISSUE TITLE
Enhancement: when i put lime test windows.pls help me

### ISSUE THREAD

**Issue by panterllh** [KadeArchive/Kade-Engine#1728]
## What is your suggestion, and why should it be implemented
![image](https://user-images.githubusercontent.com/87934816/129307728-66ea77b5-7004-4d3d-89e3-58931f5f77d0.png)

**Comment by raf13lol** [comment]
this isnt an enhancement this is an issue close this thread and open a new one as a issue also no detail

**Comment by panterllh** [comment]
> #### Please check for duplicates or similar issues before creating this issue.
> ## What is your suggestion, and why should it be implemented
> ![image](https://user-images.githubusercontent.com/87934816/129307728-66ea77b5-7004-4d3d-89e3-58931f5f77

**Comment by panterllh** [comment]
ok thank you
