### ISSUE TITLE
Fnf Isn't in the files

### ISSUE THREAD

**Issue by Sleazy-Mac** [KadeArchive/Kade-Engine#173]
The title says it all. All assets. No Funk.

**Comment by myst-rblx** [comment]
you need lime installed, haxeflixel, haxe, discord RPC, polymod, git and I think that's all. afterward, make sure you have no folder selected, do FILE in the corner and open in powershell, then do lime test windows and wait.

**Comment by Jaduplex** [comment]
You have to be kidding, right? This is the source code.

**Comment by Kade-github** [comment]
bloat

**Comment by puyoxyz** [comment]
@Sleazy-Mac -> scroll down to the readme and download from one of the links under "Kade Engine" (i.e. "latest release"), you downloaded the source code
