### ISSUE TITLE
what is happing with this?

### ISSUE THREAD

**Issue by glowsoony** [KadeArchive/Kade-Engine#1733]
### Discussed in https://github.com/KadeDev/Kade-Engine/discussions/1610

<div type='discussions-op-text'>

<sup>Originally posted by **glowsoony** August  5, 2021</sup>
help i keep getting the same thing as Error: Source path "C:/HaxeToolkit/haxe/lib/extension-webm/git/ndll/Windows64/extension-webm.ndll" does not exist and i get this other one 
![image](https://user-images.githubusercontent.com/84847356/128451421-2b7563ec-05ff-4bb4-8ff6-3ad1aa17056d.png)
</div>

**Comment by lunarcleint** [comment]
don't have the right libraries downloaded would recommend going to a video

**Comment by glowsoony** [comment]
nah fam i fixed it with no help i found out the problem

**Comment by isakube** [comment]
close it then

**Comment by ghost** [comment]
wait i know
do
lime rebuild extension-webm windows
**for windows**
lime rebuild extension-webm linux
**for linux**
lime rebuild extension-webm macos
**for mac os**
do in a command propmt

**Comment by ghost** [comment]
or just build for web lol

**Comment by shulkus** [comment]
> wait i know do lime rebuild extension-webm windows **for windows** lime rebuild extension-webm linux **for linux** lime rebuild extension-webm macos **for mac os** do in a command propmt

Warning: Could not find environment variables for Visual Studio
Missing HXCPP_VARS
