### ISSUE TITLE
Swap Section not working.

### ISSUE THREAD

**Issue by Danny-SEP** [KadeArchive/Kade-Engine#1754]
The Swap Section button doesn't seem to do anything when you convert an sm file to a json and then bring it into the debug menu. The only way to fix this is by removing and replacing the notes it seems. I'm not sure if this is because the placement of notes when converting is a little off or what but it means I'll have to go back into arrowvortex and move them myself and then bring that sm back into kade engine to turn that into a json.

**Comment by Kade-github** [comment]
in 1.6.2 this should be fixed already
