### ISSUE TITLE
Bug Report: Snap intervals aren't lined up with the BPM in the new charter

### ISSUE THREAD

**Issue by CarsonKompon** [KadeArchive/Kade-Engine#1758]
### If you are playing a downloaded version of the game, what operating system are you using?

Windows 10 64-bit

## What version of the game are you using? Look in the bottom left corner of the main menu.

1.6.2 - Full Release (Built from the downloadable source found on the releases page)

## Please describe your issue. Provide extensive detail and images if possible.

As described in issue #1757, you can not change the bpm in-editor. So I changed the bpm value of the bopeebo normal chart from `100.0` to `127.0` directly from the json file. This seems to cause the intervals of the charter to get really out-of-place and do NOT line up with my song whatsoever.

I've made a video to more easily describe the issue: https://streamable.com/3ox2ir

**Comment by ExpnandBanana** [comment]
can confirm the issue is happening to me as well
https://streamable.com/5nhrvp

**Comment by Kade-github** [comment]
fixed https://github.com/KadeDev/Kade-Engine/commit/222ee4dbdad0e9df62a5f2eea3295d3b2c6a9513
