### ISSUE TITLE
Bug Report: How do I fix this error?

### ISSUE THREAD

**Issue by flaaws** [KadeArchive/Kade-Engine#1761]
Everytime I try to build, it gets pretty far but then this error message pops up.

Link: ApplicationMain.exe
obj\msvc19-arm64-nc\70e38311_Context3DElementType.obj : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'ARM64'

If anyone knows how to fix this, please tell me!

(Im using Kade Engine 1.5.2)

![image](https://user-images.githubusercontent.com/88951878/129463288-653e3268-8fc3-4295-bbc5-3edd239e626b.png)

**Comment by flaaws** [comment]
Please help I really want to make a mod with code :(

**Comment by ghost** [comment]
bro you on a mini-pc? kade aint ARM64 compatible

**Comment by flaaws** [comment]
> bro you on a mini-pc? kade aint ARM64 compatible

No, im not.. I'm on a regular 64 bit windows PC

**Comment by Timone06** [comment]
> > bro you on a mini-pc? kade aint ARM64 compatible
> 
> No, im not.. I'm on a regular 64 bit windows PC

It is because you didn't installed the right individual component in the Visual Studio Community Installation!
No worries! You can still fix this issue.

You have to return to the VSC installation and install the right component. It is the x64-x86 instead of ARM64.

Hope that helps!

**Comment by VICK-sys** [comment]
> 
> 
> > > bro you on a mini-pc? kade aint ARM64 compatible
> > 
> > 
> > No, im not.. I'm on a regular 64 bit windows PC
> 
> It is because you didn't installed the right individual component in the Visual Studio Community Installation!
> No worries! You can still fix this issue.
> 
> You have to return to the VSC installation and install the right component. It is the x64-x86 instead of ARM64.
> 
> Hope that helps!

Which x64-x86 component exactly?

**Comment by UnderCraft42** [comment]
im having the same issue.

**Comment by ghost** [comment]
he ment x86-64 lol

**Comment by Timone06** [comment]
> he ment x86-64 lol

Yuh! My bad! ^^

**Comment by Timone06** [comment]
> > > > bro you on a mini-pc? kade aint ARM64 compatible
> > > 
> > > 
> > > No, im not.. I'm on a regular 64 bit windows PC
> > 
> > 
> > It is because you didn't installed the right individual component in the Visual Studio Community Installation!
> > No worries! You can still fix this issue.
> > You have to return to the VSC installation and install the right component. It is the x64-x86 instead of ARM64.
> > Hope that helps!
> 
> Which x64-x86 component exactly?

Normally, the latest version (v142)

**Comment by flaaws** [comment]
> > > > > bro you on a mini-pc? kade aint ARM64 compatible
> > > > 
> > > > 
> > > > No, im not.. I'm on a regular 64 bit windows PC
> > > 
> > > 
> > > It is because you didn't installed the right individual component in the Visual Studio Community Installation!
> > > No worries! You can still fix this issue.
> > > You have to return to the VSC installation and install the right component. It is the x64-x86 instead of ARM64.
> > > Hope that helps!
> > 
> > 
> > Which x64-x86 component exactly?
> 
> Normally, the latest version (v142)

Still didnt work, checked that I installed the right components several times. I dunno what to do.

**Comment by Ardub92** [comment]
> > > > > > bro you on a mini-pc? kade aint ARM64 compatible
> > > > > 
> > > > > 
> > > > > No, im not.. I'm on a regular 64 bit windows PC
> > > > 
> > > > 
> > > > It is because you didn't installed the right individual component in the Visual Studio Community Installation!
> > > > No worries! You can still fix this issue.
> > > > You have to return to the VSC installation and install the right component. It is the x64-x86 instead of ARM64.
> > > > Hope that helps!
> > > 
> > > 
> > > Which x64-x86 component exactly?
> > 
> > 
> > Normally, the latest version (v142)
> 
> Still didnt work, checked that I installed the right components several times. I dunno what to do.

I think that Kade made a mistake. It worked for me until I updated

**Comment by ghost** [comment]
> > > > > > > bro you on a mini-pc? kade aint ARM64 compatible
> > > > > > 
> > > > > > 
> > > > > > No, im not.. I'm on a regular 64 bit windows PC
> > > > > 
> > > > > 
> > > > > It is because you didn't installed the right individual component in the Visual Studio Community Installation!
> > > > > No worries! You can still fix this issue.
> > > > > You have to return to the VSC installation and install the right component. It is the x64-x86 instead of ARM64.
> > > > > Hope that helps!
> > > > 
> > > > 
> > > > Which x64-x86 component exactly?
> > > 
> > > 
> > > Normally, the latest version (v142)
> > 
> > 
> > Still didnt work, checked that I installed the right components several times. I dunno what to do.
> 
> I think that Kade made a mistake. It worked for me until I updated

this is a huge quote chain lol

**Comment by NotIlulus** [comment]
this sucks bruh i got same problem

**Comment by ghost** [comment]
funny how kade isnt flagging comments as off-topic or spam

**Comment by NotIlulus** [comment]
i found my own fix. You might of accidently installed arm64 components on the vs installation lol so just go to the installer and delete anything with "arm" in general

**Comment by flaaws** [comment]
![image](https://user-images.githubusercontent.com/88951878/132285220-002637c9-cea3-4092-9d8c-dea088d74c73.png)

Im pretty sure these are the right components for 1.5.2 right? Please correct/tell me if they are not

**Comment by VICK-sys** [comment]
Okay, I found a fix that worked for me. Go to c:/users/YourUser and then delete the .lime folder and then compile the game.

**Comment by Ardub92** [comment]
> Okay, I found a fix that worked for me. Go to c:/users/YourUser and then delete the .lime folder and then compile the game.

GIVE ME YOUR PAYPAL AND I'LL SEND YOU A DOLLAR. YOU ARE A GOD TO ME

**Comment by VICK-sys** [comment]
> 
> 
> > Okay, I found a fix that worked for me. Go to c:/users/YourUser and then delete the .lime folder and then compile the game.
> 
> GIVE ME YOUR PAYPAL AND I'LL SEND YOU A DOLLAR. YOU ARE A GOD TO ME

lol, I don't have one. Thank the guy who found the fix in the comment section of this video https://youtu.be/v_nvt8JEnCA I'm just spreading the word.

**Comment by VICK-sys** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/88951878/132285220-002637c9-cea3-4092-9d8c-dea088d74c73.png)
> 
> Im pretty sure these are the right components for 1.5.2 right? Please correct/tell me if they are not

Your components are fine for that version of Kade Engine. Just use the method fix I commented on earlier and then compile. Sorry for not commenting on your components earlier.

**Comment by flaaws** [comment]
> Okay, I found a fix that worked for me. Go to c:/users/YourUser and then delete the .lime folder and then compile the game.

THANK YOU SO MUCH LOL

**Comment by windows10win7posreadywoeskio** [comment]
what
