### ISSUE TITLE
Bug Report: Still won't work on Linux (Caching issue)

### ISSUE THREAD

**Issue by ThatOneCalculator** [KadeArchive/Kade-Engine#1762]
After latest pull (yes, even after last night's stream), Linux still encounters the same bug with caching.

Building from source: Arch GNU/Linux

Kade-Engine on  stable > commit 68d2d7d99a40277631f5efd8a49f3e823797d0e1; commit 69af949c8f35c72d5f8398c028cc4d8209949fd6

Steps:
```
$ haxelib run lime build linux -release
$ cd export/release/linux/bin
$ ./Kade\ Engine
# Loads, stops at 20.21
```

**Comment by Kade-github** [comment]
fixed https://github.com/KadeDev/Kade-Engine/commit/325b5a92b5e2a9557d0737c09588d846970ac8d4
