### ISSUE TITLE
when i type lime test windows

### ISSUE THREAD

**Issue by talesgreen** [KadeArchive/Kade-Engine#1764]
it shows
![image](https://user-images.githubusercontent.com/88807522/129465863-a685766a-25f0-4811-8aa7-df37dd776f14.png)
![image](https://user-images.githubusercontent.com/88807522/129465879-716e9651-3c49-403e-a109-57d2455b7d71.png)

**Comment by BoloVEVO** [comment]
The "}" before line 538 is not connected with nothing. Probably you forgot to put the "{" up. 
EDIT = Don't do that. My bad

**Comment by talesgreen** [comment]
like this

![image](https://user-images.githubusercontent.com/88807522/129480823-47e22116-9be3-4ed9-9eaa-208af7aa5077.png)

**Comment by BoloVEVO** [comment]
What exactly do you want to do?

**Comment by talesgreen** [comment]
fixed
