### ISSUE TITLE
When I hit an arrow it misses

### ISSUE THREAD

**Issue by janechicken** [KadeArchive/Kade-Engine#1765]
## KE 1.4.2

When I am hitting an arrow, it doesn't hit the arrow it seems that it doesn't even register, it just misses.
The same happened in Whitty mod.
I am playing on the Starecrown mod.

https://user-images.githubusercontent.com/64870076/129467675-c7c43ff9-1ef1-481e-8521-1ca21f849445.mp4

**Comment by Kade-github** [comment]
this is not the latest version so???

**Comment by janechicken** [comment]
So there's no fix? Any version that isn't the latest version does this?
