### ISSUE TITLE
Bug Report: Instrument doesn't play in Story Mode if dialogues or any cutscenes functions were used.

### ISSUE THREAD

**Issue by FaultyTwo** [KadeArchive/Kade-Engine#1767]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows 10 x64

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.6.2

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
In KadeEngine 1.6.2. Any weeks that used functions for cutscenes or dialogues will not load any background music from 'dialogueBox.hx' or play instrument when dialogue or any cutscenes is done.

In 'PlayState.hx' around line 1251 (an if-else statement with switch function for loading cutscenes, dialogues and stuffs), if every cases were removed except for default case, instrument will play properly. 
Please fix this as fast as possible. Thank you.

Minimal Footage:

https://user-images.githubusercontent.com/25416809/129477924-153f92f6-c6f0-4a65-9ab2-9859361449bf.mp4

**Comment by cacahuwek** [comment]
well, same here but you can play it on free play

**Comment by FaultyTwo** [comment]
issue solved. closed.
