### ISSUE TITLE
Bug Report: Swap/Clear/Copy Section not working on notes that aren't synced to the BPM

### ISSUE THREAD

**Issue by ScarabWasTaken** [KadeArchive/Kade-Engine#1769]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86_64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.6.2
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Load Dadbattle. 
Change overall BPM (212) 
In my case I also added multiple different change BPM events 
## Please describe your issue. Provide extensive detail and images if possible.
Existing notes on a chart no longer get affected by the mentioned section buttons. Newly placed notes will be affected correctly.

**Comment by Danny-SEP** [comment]
I posted an issue which was pretty much the same as this, stating that when I converted an sm to a json, it wasn't synced and therefore the swap section did not work, but I forgot to mention I was on the latest version (1.6.2), and therefore it got closed as that version supposedly fixed the issue. I just commented here to clarify that I am also having this issue even on the latest version.

**Comment by Kade-github** [comment]
this was a bigger fix than It needed to be, it was a hard thing to fix. but here ya go. 

https://github.com/KadeDev/Kade-Engine/commit/6ba9973200497233675ed17333711d0da95e8542
