### ISSUE TITLE
Bug Report: The game crashes whenever the tutorial is beaten

### ISSUE THREAD

**Issue by Pyram1d-dev** [KadeArchive/Kade-Engine#1772]
I've encountered this bug in both my own compiled version and the downloaded version of 1.6.2. It's pretty simple to reproduce the bug -- just beat the tutorial and boom, the game closes. The video attached is of the release version of KE. No other weeks have this issue, it's only the tutorial that crashes.

I would like to add, the tutorial also crashes in freeplay.

https://user-images.githubusercontent.com/76640329/129488303-93a7294b-d479-418a-ad97-f4cdcb140fb3.mp4

**Comment by Kade-github** [comment]
already fixed in the latest master commit.
