### ISSUE TITLE
Bug Report: 3 new problems I noticed in 1.6.2

### ISSUE THREAD

**Issue by IComputerGood** [KadeArchive/Kade-Engine#1779]
First off, just wanted to say that I love Kade Engine, you have done amazing work with it so thanks so much for all the time and energy you have dedicated to the project. 

I am running Windows 10 X64 with a fresh 1.6.2 Kade Engine download to a fresh new folder (no mods etc)

issue 1: when launching a song and pressing 7 to enter the debug menu, the grid background is missing from the song.

issue2:  The section length option appears to be missing.

Screenshot of the first 2 issues:[]( https://imgur.com/EAuGID1)

issue3: grid is not in time with the BPM of the song

Thanks again for the help!

**Comment by isakube** [comment]
> First off, just wanted to say that I love Kade Engine, you have done amazing work with it so thanks so much for all the time and energy you have dedicated to the project.
> 
> I am running Windows 10 X64 with a fresh 1.6.2 Kade Engine download to a fresh new folder (no mods etc)
> 
> issue 1: when launching a song and pressing 7 to enter the debug menu, the grid background is missing from the song.
> 
> issue2: The section length option appears to be missing.
> 
> Screenshot of the first 2 issues:
> 
> issue3: grid is not in time with the BPM of the song
> 
> Thanks again for the help!

1 and 3 are intentional. theres an option in appearance to fix 1, but trust me you really don't want it

2 idfk

**Comment by Kade-github** [comment]
all are intentional.

1. you can reenable it in the settings
2. it has no use anyways so why add it
3. thats why it was removed
