### ISSUE TITLE
Enhancement: why was old input system removed

### ISSUE THREAD

**Issue by CBag23** [KadeArchive/Kade-Engine#178]
why was old input system removed

i dont like the new one and im going to continue to create my mod with 1.3.1 until the old input system is added back as an option

**Comment by Kade-github** [comment]
old input system pp

**Comment by CBag23** [comment]
i still want an option to enable it

removing the ability to choose it is cringe

**Comment by isakube** [comment]
you are the cringe my guy /j

**Comment by CBag23** [comment]
:'(

**Comment by puyoxyz** [comment]
A question: *why* do you need the old input system?

edit: Nevermind, saw that you made another issue

**Comment by blackm1n** [comment]
> why was old input system removed
> 
> i dont like the new one and im going to continue to create my mod with 1.3.1 until the old input system is added back as an option

Don't use 1.3.1, Old Input System is actually bugged there and acts as New Input. Use 1.3 instead

**Comment by CBag23** [comment]
so,..
