### ISSUE TITLE
hi i made a github account to report the issue that everytime i make custom icons,kade engine,mic'd up,fnf and fnf mods dont work. please fix this issue thanks.

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#1780]

**Comment by KlutchDj** [comment]
this is on you bro. follow tutorials of how to program properly

**Comment by ghost** [comment]
> this is on you bro. follow tutorials of how to program properly

i didnt do any programming i edited the bf icon file thing
