### ISSUE TITLE
Enhancement: i really want the old input system back as atleast an option

### ISSUE THREAD

**Issue by CBag23** [KadeArchive/Kade-Engine#179]
## What is your suggestion, and why should it be implemented?
i really dont like the new input system i want atleast an option to re enable the old one

**Comment by CBag23** [comment]
even if the new one is on by default i just want the ability to use the old one

**Comment by CBag23** [comment]
like this is a make or break for me when considering upgrading my kade engine version

**Comment by Jaduplex** [comment]
The old one was flawed and buggy. no.

**Comment by CBag23** [comment]
why remove it as an option entirely

people can use the new input system if they dont like it, and there are people who like the old input system better

**Comment by CBag23** [comment]
forcing the player to use the new one kinda sucks

**Comment by Jaduplex** [comment]
No, it doesn't. The old one misses inputs a lot. The new one literally doesn't do anything except fix the issues. If you're complaining about spamming not missing notes, then why? You can clearly see if someone is mashing.

**Comment by CBag23** [comment]
i like that if you press the wrong note at the wrong time, it punishes you for it.

whats the harm in atleast keeping it as an option?

**Comment by CBag23** [comment]
i dont care if other people mash, i like that i cant accidentally press the wrong note, i play a lot of rhythm games so the old input system making you miss if you press the note at the wrong time, helps me improve my accuracy

**Comment by Jaduplex** [comment]
> i like that if you press the wrong note at the wrong time, it punishes you for it.
> 
> whats the harm in atleast keeping it as an option?

Maintaining legacy stuff is a pain.

**Comment by CBag23** [comment]
the thing is it was already there as an option, i wish there was atleast a way to add it back yourself or something

i think the new input system is good, i just personally prefer the old input system

**Comment by Jaduplex** [comment]
> the thing is it was already there as an option, i wish there was atleast a way to add it back yourself or something
> 
> i think the new input system is good, i just personally prefer the old input system

It wasn't actively maintained. If something broke it, it could break the game heavily and go undetected because, spoiler alert, IT ISN'T MAINTAINED.

**Comment by CBag23** [comment]
Well, what about when the week 7 update drops? I'm sure it's input system is being worked on right now, so will that be implemented into a future Kade Engine version?

**Comment by Kade-github** [comment]
> > the thing is it was already there as an option, i wish there was atleast a way to add it back yourself or something
> > i think the new input system is good, i just personally prefer the old input system
> 
> It wasn't actively maintained. If something broke it, it could break the game heavily and go undetected because, spoiler alert, IT ISN'T MAINTAINED.

^ 

and yes we'll be adding the old input back in week 7 if its not that bad anymore
