### ISSUE TITLE
help with characters

### ISSUE THREAD

**Issue by HiroMizuki** [KadeArchive/Kade-Engine#1794]
so, what's going on is:

i'm trying to add a character (in the case, is meat boy), i've put it on Character.hx, shared/characters, the health icons on preload/icons, everything

but, when i try to put the character in a song, the game crashes, saying just: Null Object Reference

**help pls?**

**Comment by napstaa967** [comment]
null object refference means that it doesn't exist

the icons go on **preload**/images/icons

**Comment by HiroMizuki** [comment]
> null object refference means that it doesn't exist
> 
> the icons go on **preload**/images/icons

oh yeah, i got it wrong on the post, thanks

but, it still keeps getting the error

**Comment by napstaa967** [comment]
are you sure the file has the same name as the file in the code

**Comment by HiroMizuki** [comment]
> are you sure the file has the same name as the file in the code

yes

**Comment by ACardboardBox1** [comment]
this is more of a discussion, not a issue but
if the character's name is meat-boy in the code, icons-meat-boy wont work iirc.

**Comment by HiroMizuki** [comment]
> this is more of a discussion, not a issue but
> if the character's name is meat-boy in the code, icons-meat-boy wont work iirc.

**thank you bud**

i'll try it, if it works, i'll close the issue

**Comment by HiroMizuki** [comment]
> > this is more of a discussion, not a issue but
> > if the character's name is meat-boy in the code, icons-meat-boy wont work iirc.
> 
> **thank you bud**
> 
> i'll try it, if it works, i'll close the issue

ok, didn't worked too
![image](https://user-images.githubusercontent.com/72695242/129768203-f88c4e6f-9dce-4c09-9a76-1b1748567f07.png)

**Comment by HiroMizuki** [comment]
wait, i'll try to add Whitty as test. If it works, i need to talk with the animator and i close this

**Comment by HiroMizuki** [comment]
didn't worked, i think this is a bug on the engine. 

Nevermind, i'll close it
