### ISSUE TITLE
[MACOS ISSUE (NOT WINDOWS)] Game crashes after 1st song of week

### ISSUE THREAD

**Issue by GenericGaming** [KadeArchive/Kade-Engine#18]
Hi, I have Haxe on my mac, mainly because I at least have the ability to compile open source executable mods for games like Friday Night Funkin. So I was ecstatic when a game that used the new input system was made open source, even though I still can't play mods like Whitty and Tricky. What I was really looking forward to was an easier time FCing some songs, but when I compile the game, after the first song of any given week, it crashes, I redownload the source every update, but to no avail...
Is it something wrong with my computer, because i've compiled things like FNF modding+ and EXR with no crashes whatsoever.

**Comment by Kiffolisk** [comment]
Running "lime test" instead of "lime build", which trace(); message do you get before the crash? It can be useful to understand where it crashes.

**Comment by GenericGaming** [comment]
Oh, I was using the "Lime test mac -release" command, i'll see what string it outputs when the game crashes, one sec

**Comment by Kiffolisk** [comment]
Try running just "lime test mac" or "lime test mac -debug"

**Comment by GenericGaming** [comment]
Okay, trying that right now

**Comment by GenericGaming** [comment]
Okay, I did the debug command, and i don't know if it works, the debug console was constantly covering the screen, and the reason I was building it using the release command was because I wanted to be able to NOT have it crash my computer if I tried to open it without booting it from the console

**Comment by GenericGaming** [comment]
okay, here's the error I get when it crashes
Error : [file_open,assets/replays/replay-Tutorial-time1616193484364.64.kadeReplay]

**Comment by GenericGaming** [comment]
I just played the tutorial

**Comment by Kade-github** [comment]
Yeah macos doesn't like saving files for some reason, that's the issue. I'll look into it

**Comment by GenericGaming** [comment]
Wait.. I looked a bit at the error message and I THINK I see the issue, ya see, with a windows executable, folders and files are created outside the app, and an executable in itself can CREATE other files in the computer, a .app file can't do that, (for obvious reasons), so.. when I get THIS error: Error : [file_open,assets/replays/replay-Satin-Panties-time1616450535102.51.kadeReplay], I think it's due to there being no directory that the game can put the recorded file in, because there is no safety net for this error, the game doesn't know what to do and crashes, so, I have a suggestion, let players set whether they want it to record replays or not, and then if they do, let them set a destination folder for the replays to go, this might fix the issue, it may not but that's what I can think of.

**Comment by Kiffolisk** [comment]
it tries to create the replay file (or folder?), but on mac it fails apparently.
