### ISSUE TITLE
Bug Report: Pico Closes the Game (Both Freeplay and Story Mode)

### ISSUE THREAD

**Issue by KlutchDj** [KadeArchive/Kade-Engine#1806]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
windows 64bit

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.6.2 (Downloaded from Releases)

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Play Pico on Freeplay and Story Mode 

## Please describe your issue. Provide extensive detail and images if possible.

https://streamable.com/m1jgp5 (story Mode)

(freeplay) https://user-images.githubusercontent.com/81717689/129626000-eaec0011-e6fd-409f-a203-bb3fd207c811.mp4

**Comment by KlutchDj** [comment]
i will update this if this doesn't/does happen when i restart story mode progression.

**Comment by napstaa967** [comment]
just tested this and yeah it does happen

i tried resetting my week progress but it crashed as soon as i finished week 1

**Comment by KlutchDj** [comment]
> just tested this and yeah it does happen
> 
> i tried resetting my week progress but it crashed as soon as i finished week 1


probably try adding this as a bug label too ^^
and imma try if i can reproduce the week 1 bug like you said.
