### ISSUE TITLE
Bug Report: Resetting Story Progression Restricts Story Mode Completion.

### ISSUE THREAD

**Issue by KlutchDj** [KadeArchive/Kade-Engine#1808]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows 64bit

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.6.2 (Downloaded From Releases

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Reproducing the bug : Reset Story Progression 

## Please describe your issue. Provide extensive detail and images if possible. 
Resetting Story Mode Progression Blocks you from unlocking the following weeks by crashing the game at the end of the week.

https://user-images.githubusercontent.com/81717689/129631515-e87fb035-af2e-448d-b045-37570e130c38.mp4

**Comment by KlutchDj** [comment]
WRONG VIDEO

**Comment by KlutchDj** [comment]
UPDATE : apprently it doesn't do this crashing for optimization mode. only experienced on Pico.

**Comment by Kade-github** [comment]
this was because tutorial just crashed already, it's already fixed in master so.

**Comment by KlutchDj** [comment]
> this was because tutorial just crashed already, it's already fixed in master so.

it also crashes after completing week 1 , which prevents from actually unlocking week 2
