### ISSUE TITLE
Bug Report: KE 1.6.2 Linux Compiling Failing due to a error

### ISSUE THREAD

**Issue by knightryry** [KadeArchive/Kade-Engine#1812]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Linux (64Bit)
## What version of the game are you using? Look in the bottom left corner of the main menu.
Can't even build KE But Im sure its KE 1.6.2
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Just try to build KE 1.6.2 on Linux
## Please describe your issue. Provide extensive detail and images if possible.
When I try to build Ke 1.6.2 it spits out an error about lua helper 
`Error: In file included from include/llua/Lua_helper.h:11,
                 from ./src/__boot__.cpp:803:
/home/knightryry/haxelib/linc_luajit/0,0,2//linc/linc_lua.h:5:10: fatal error: /home/knightryry/Kade-Engine/export/release/linux/obj/obj/linux64/__pch/haxe/hxcpp.h: No such file or directory
    5 | #include <hxcpp.h>
      |          ^~~~~~~~~
compilation terminated.`
This also happened to the AppVeyor when building the release. [https://ci.appveyor.com/project/KadeDev/kade-engine-linux/builds/40401452](url) This Bug stops me from installing KE 1.6.2. Any Help?

**Comment by Kade-github** [comment]
currently i'm experimenting with modcharts so I can't help with this right now, i'll make sure too look at this when i'm done

**Comment by knightryry** [comment]
Hmmm, I Just Found These things. Is this right? Just saw this.
![image](https://user-images.githubusercontent.com/78123850/129668043-e9667f7e-b436-4513-af20-28d02eda4a07.png)
![image](https://user-images.githubusercontent.com/78123850/129668227-12e529ce-9ad3-43ec-9bef-544189f05471.png)
is the .gch supposed to be there? Just wondering.

**Comment by Aakodal** [comment]
I managed to build 1.6.2 on Linux. Make sure you actually changed linc_luajit haxe library to the git version (check for build instructions) and installed the correct system dependencies (I remembered that I had to install a libX package on my Linux Mint, and from what I see the appveyor does not install it, maybe the appveyor error comes from that)

**Comment by knightryry** [comment]
nope get this error (it's long a long one) `/home/knightryry/haxelib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
/home/knightryry/haxelib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/ModchartState.hx:16: characters 8-20 : Type not found : llua.Convert
source/ModchartState.hx:17: characters 8-16 : Type not found : llua.Lua
source/ModchartState.hx:18: characters 8-18 : Type not found : llua.State
source/ModchartState.hx:19: characters 8-17 : Type not found : llua.LuaL
source/ModchartState.hx:28: characters 24-29 : Type not found : State
source/Replay.hx:55: lines 55-145 : Defined in this class
source/PlayState.hx:1423: characters 32-51 : Class<ModchartState> has no field createModchartState
source/PlayState.hx:1424: characters 16-28 : ModchartState has no field executeState
source/PlayState.hx:4375: characters 17-29 : ModchartState has no field executeState
source/PlayState.hx:4223: characters 17-29 : ModchartState has no field executeState
source/PlayState.hx:3343: characters 16-19 : ModchartState has no field die
source/PlayState.hx:3421: characters 19-22 : ModchartState has no field die
source/PlayState.hx:2294: characters 16-22 : ModchartState has no field setVar
source/PlayState.hx:2295: characters 16-22 : ModchartState has no field setVar
source/PlayState.hx:2296: characters 16-22 : ModchartState has no field setVar
source/PlayState.hx:2297: characters 16-22 : ModchartState has no field setVar
source/PlayState.hx:2298: characters 16-28 : ModchartState has no field executeState
source/PlayState.hx:2300: characters 37-47 : ModchartState has no field luaWiggles
source/PlayState.hx:2300: characters 25-47 : You can't iterate on a Dynamic value, please specify KeyValueIterator or KeyValueIterable
source/PlayState.hx:2313: characters 36-42 : ModchartState has no field getVar
source/PlayState.hx:2314: characters 31-37 : ModchartState has no field getVar
source/PlayState.hx:2316: characters 20-26 : ModchartState has no field getVar
source/PlayState.hx:2335: characters 25-31 : ModchartState has no field getVar
source/PlayState.hx:2336: characters 25-31 : ModchartState has no field getVar
source/PlayState.hx:2443: characters 17-20 : ModchartState has no field die
source/PlayState.hx:2714: characters 17-23 : ModchartState has no field setVar
source/PlayState.hx:2724: characters 28-34 : ModchartState has no field getVar
source/PlayState.hx:2725: characters 28-34 : ModchartState has no field getVar
source/PlayState.hx:2731: characters 18-30 : ModchartState has no field executeState
source/PlayState.hx:2752: characters 28-34 : ModchartState has no field getVar
source/PlayState.hx:2753: characters 28-34 : ModchartState has no field getVar
source/PlayState.hx:2760: characters 18-30 : ModchartState has no field executeState
source/PlayState.hx:3071: characters 21-33 : ModchartState has no field executeState
source/PlayState.hx:3106: characters 21-33 : ModchartState has no field executeState
source/PlayState.hx:3834: characters 17-29 : ModchartState has no field executeState
source/PlayState.hx:3840: characters 17-29 : ModchartState has no field executeState 
source/PlayState.hx:4529: characters 16-22 : ModchartState has no field setVar
source/PlayState.hx:4530: characters 16-28 : ModchartState has no field executeState
source/PlayState.hx:4575: characters 16-28 : ModchartState has no field executeState`
Did not even try to build. That's all that popped out when I did `lime test linux`. but installing the git version did help produce that error.

**Comment by knightryry** [comment]
Just reinstalled Haxe and all of its apps and it seems happier BUT we aren't out of the woods yet. it is building at this second and got past the error point!

**Comment by knightryry** [comment]
Ugh more errors `./Kade Engine: error while loading shared libraries: libluajit-5.1.so.2: cannot open shared object file: No such file or directory`

**Comment by AbnormalPoof** [comment]
just a standard error
sudo apt-get install libluajit-5.1-2

**Comment by knightryry** [comment]
This worked! thanks! this is a temp fix i guess until Appveyer builds it :)
