### ISSUE TITLE
Bug Report: Highlighting song in Freeplay causes it to crash

### ISSUE THREAD

**Issue by Manicies** [KadeArchive/Kade-Engine#1815]
Me again. In engine 1.16.1, I'm now able to play a song I've imported with previous JSONs via the debug menu, and I've added that song to the freeplay list. However, I can't even highlight the song in the freeplay list, because as soon as I do, it immediately crashes. I wouldn't even begin to know what might be causing that to happen.

**Comment by Manicies** [comment]
Wait. It fixed itself. I. Never mind. I guess I did something right.

**Comment by RealReal334** [comment]
How Do you Fix it i'm having the same problem Please Help
