### ISSUE TITLE
Bug Report: Chart Editor doesnt play audio even if you reload the audio

### ISSUE THREAD

**Issue by Thehelper104** [KadeArchive/Kade-Engine#183]
The chart editor seems to have issues (including in engine mods like the kade engine), the issue usally is missing audio from the editor, even if you reload the audio.

 The bug can be recreated by literally going into the debug menu and nothing else, no audio plays and even if you reload audio the audio doesnt play, meaning that you would have to guess how the chart goes. 
 
 I would recommend fixing this.

**Comment by Kade-github** [comment]
I don't see this anywhere. What song are you trying to edit?

**Comment by Thehelper104** [comment]
im trying to edit some of the songs, however the audio doesn't play and i cant accurately chart them

**Comment by Thehelper104** [comment]
as proof, i will record the audio not working

**Comment by Thehelper104** [comment]
https://drive.google.com/file/d/1jHOSO-Ycv_QTHYhu0AsZWxKMaJMOivRr/view?usp=sharing

**Comment by Kade-github** [comment]
you aren't even like pressing space which is literally to unpause the song/pause the song lol.
