### ISSUE TITLE
Bug Report: [KE 1.6.2] Null Object Reference at last note of Tutorial

### ISSUE THREAD

**Issue by EliteMasterEric** [KadeArchive/Kade-Engine#1835]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## What version of the game are you using? Look in the bottom left corner of the main menu.
KE 1.6.2 (compiled from `stable` source and Github release build both tested)

## Please describe your issue. Provide extensive detail and images if possible.
When playing the Tutorial (Normal) level, the game crashes when the song completes.

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
I have reduced the bug to the following line:
https://github.com/KadeDev/Kade-Engine/blob/68d2d7d99a40277631f5efd8a49f3e823797d0e1/source/PlayState.hx#L4634
The `Null Object Reference` crash occurs when the game attempts to determine Boyfriend's animation on an invalid section (`SONG.notes[27]`).

The solution is to either add a sentinel to the conditional statement surrounding this line, or to ensure the song is properly ended before this line is reached.

**Comment by Pyram1d-dev** [comment]
Hot damn thank you for the fix, I was getting frustrated.

I just made it check if Math.floor(curStep / 16) < SONG.notes.length

**Comment by EliteMasterEric** [comment]
Fixed in KE 1.7 I believe.
