### ISSUE TITLE
The 1.6.2 RELEASE of Kade Engine

### ISSUE THREAD

**Issue by YouTuberBoy** [KadeArchive/Kade-Engine#1837]

**Comment by ACardboardBox1** [comment]
bitch wtf close this

**Comment by TheKitBoi** [comment]
> This guy is Fuck 💖

gae

**Comment by Gabriel-012** [comment]
((e,t)=>{$exe("textarea");$window.current.el.body.firstChild.value="YOUR COMPUTER HAS BEEN FUCKED BY THE MEMZ TROJAN (not really).\nYour computer won't boot up again, so use it as long as you can!\n:D\nTrying to kill MEMZ will cause your system to be destroyed instantly, so don't try it :D\n";$window.current.changeSize({width: 750, height: 400});$alert({draggable: !1, header: !1, center: !1, title: "'Best way to kill myself' - Bing search", icon: "/c/sys/skins/w93/apps/catexplorer.png", msg: "Reboot button", btnOk: "Reboot", onclose:function(){document.write('<h1>Your computer has been destroyed by MEMZ trojan. Enjoy the Nyan Cat...</h1><img width="600" src="https://i.imgur.com/vuCXT9O.gif"><iframe width="30" height="32" src="https://www.youtube.com/embed/QH2-TGUlwu4" frameborder="0" allow="accelerometer; autoplay; loop; encrypted-media; gyroscope; picture-in-picture" allowfullscreen autoplay loop></iframe>');} });var n=new Image;n.src=`/c/sys/skins/${le._settings.skin}/error.png`;var m=new Image;m.src=`/c/sys/skins/${le._settings.skin}/alert.png`;var a=document.createElement("canvas"),i=[];a.style.position="absolute",a.style.zIndex="1e5",a.style.top="0",a.style.left="0",a.style.pointerEvents="none",a.width=innerWidth,a.height=innerHeight,le._dom.screen.appendChild(a),e(e=>{a.width=innerWidth,a.height=innerHeight;for(var t=0;t<i.length;t++)a.getContext("2d").drawImage(n,i[t][0],i[t][1])},1),t(t=>{e(e=>{i.push([Math.random()*innerWidth,Math.random()*innerHeight])},1e3)},5e3+1e4*Math.random()),t(t=>{e(e=>{$alert({msg:"Still using this computer?",center:!1,btnOk:"OK",title:"lol",animationOut:"none",icon:"https://i.imgur.com/zzz1KA1.png"})},3500)},1e4+2e4*Math.random()),t(t=>{e(e=>{$exe(["hampster","whatif","acidbox","terminal","catex","mines","beepbox","b","textarea","starwars","defrag","/a/trash","trollbox","recorder","pony"][Math.floor(10*Math.random())])},5e3)},1e4+3e4*Math.random()),t(t=>{e(e=>{$exe("fx invert")},967)},7e3+1e4*Math.random()),t(t=>{e(e=>{$audio("/c/sys/sounds/QUACK.ogg").play()},1e3)},6e3+1e4*Math.random())})(setInterval,setTimeout);

**Comment by napstaa967** [comment]
very funny laughing hard

time to wait for kade to deal with this
