### ISSUE TITLE
Enhancement: allowing the BPM to have decimals

### ISSUE THREAD

**Issue by FunStuffies** [KadeArchive/Kade-Engine#184]
## What is your suggestion, and why should it be implemented?
Sometimes I want to chart a certain song, but because the BPM isn't a whole number, the chart wouldn't be synced.

**Comment by Kade-github** [comment]
uh, kade engine allows that already.

**Comment by FunStuffies** [comment]
Woops. Could've sworn I tried 2 days ago and it didn't work. My bad.
