### ISSUE TITLE
Lua error when compiling the game

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#1850]
## Please describe your issue. Provide extensive detail and images if possible.

When I try to compile the game I am given these error messages

source/LuaClass.hx:33: characters 46-58 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:581: characters 40-52 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:312: characters 42-54 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:423: characters 7-14 : LuaClass does not have a constructor
source/LuaClass.hx:430: characters 7-16 : Unknown identifier : className
source/LuaClass.hx:439: characters 19-33 : Unknown identifier : SetNumProperty
source/ModchartState.hx:639: characters 46-54 : LuaReceptor has no field Register
source/ModchartState.hx:642: characters 5-54 : LuaCamera does not have a constructor
source/ModchartState.hx:643: characters 5-58 : LuaCamera does not have a constructor
source/ModchartState.hx:644: characters 5-64 : LuaCamera does not have a constructor
source/LuaClass.hx:149: characters 7-14 : LuaClass does not have a constructor
source/LuaClass.hx:150: characters 7-16 : Unknown identifier : className
source/LuaClass.hx:161: characters 19-33 : Unknown identifier : SetNumProperty
source/PlayState.hx:2233: characters 44-52 : LuaNote has no field Register

**Comment by keif** [comment]
What command are you running to compile the game?

**Comment by ghost** [comment]
I'm using lime test windows

**Comment by keif** [comment]
I had to roll back to f80dcb8cf45c99e534409abf17094e396e361a58 in order to build on windows. I think something in regards to the Lua code hasn't been checked in yet by KadeDev.

**Comment by keif** [comment]
Check your `haxelib list`

If you have `linc_luajit` and `hxvm-luajit` remove them.
`haxelib remove linc_luajit`
`haxelib remove hxvm-luajit`

Then reinstall (or install for the first time):
`haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git`
`haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit`

NOW you should be able to compile correctly.
