### ISSUE TITLE
Bug Report: Compiling problem

### ISSUE THREAD

**Issue by Godnoob443** [KadeArchive/Kade-Engine#1851]
I get this when i try to compile it:
source/PlayState.hx:1622: characters 2-8 : Expected }

**Comment by keif** [comment]
What branch are you building from?
What command are you running to build it?

**Comment by Godnoob443** [comment]
> What branch are you building from?
> What command are you running to build it?

the command im using is lime test windows

**Comment by keif** [comment]
Okay, but what branch are you building the game from? Are you running from `master` or `stable`?

**Comment by Godnoob443** [comment]
> Okay, but what branch are you building the game from? Are you running from `master` or `stable`?

master

**Comment by keif** [comment]
I assume you've modified the code.
`PlayState.hx` on line 1622 it's wanting a closing bracket (`}`)

You have an opening bracket (`{`) that's missing a matching closing one.

**Comment by Godnoob443** [comment]
> I assume you've modified the code.
> `PlayState.hx` on line 1622 it's wanting a closing bracket (`}`)
> 
> You have an opening bracket (`{`) that's missing a matching closing one.

I tried but it doesnt seem to work and i dont know where to put it at
