### ISSUE TITLE
Bug Report: HTML5 Issue on 1.4.1

### ISSUE THREAD

**Issue by PancakeMPEG** [KadeArchive/Kade-Engine#186]
So basicly i try to port my fnf mod to chromebook/html5 on 1.4.1 but it wont work can someone help me out?

**Comment by puyoxyz** [comment]
you gave absolutely no information, so there is no way anyone can help you.

also, this should be a [discussion](https://github.com/KadeDev/Kade-Engine/discussions) as issues are for suggestions/bugs with kade engine itself, *not* with forks/mods of it.

**Comment by Kade-github** [comment]
^

**Comment by isakube** [comment]
HEYYYYYY I FOUND THE DESCRIPTION OF THE LINE BETWEEN ISSUE AND DISCUSSIONS AIGHT THX
