### ISSUE TITLE
Having trouble building from source code

### ISSUE THREAD

**Issue by The-Evil-Pickle** [KadeArchive/Kade-Engine#187]
I'm planning to make some code modifications for my mod I'm working on, but I'm having trouble building the program. I've not made any modifications yet, I'm just trying to build the source code for version 1.4.1. Here's the error I'm running into:

D:\Downloads\Kade-Engine-1.4.1-KE\Kade-Engine-1.4.1-KE> lime test html5 -debug
D:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/group/FlxGroup.hx:473: characters 80-91 : Type not found : ObjectClass
D:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
D:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
D:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/group/FlxGroup.hx:852: characters 19-30 : Type not found : ObjectClass
D:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/system/frontEnds/PluginFrontEnd.hx:47: characters 19-28 : Type not found : ClassType
D:/HaxeToolkit/haxe/lib/flixel/4,8,1/flixel/system/frontEnds/PluginFrontEnd.hx:94: characters 20-29 : Type not found : ClassType

Any advice would be greatly appreciated

**Comment by Kade-github** [comment]
This should be a [Discussion](https://github.com/KadeDev/Kade-Engine/discussions) as this is not a bug with Kade Engine.
