### ISSUE TITLE
Question revoling the speed thing in the debug menu in the new master github build

### ISSUE THREAD

**Issue by DeceptedPar** [KadeArchive/Kade-Engine#1882]
how do you change it?
I've tried nearly everything, and it's not changing

**Comment by DeceptedPar** [comment]
I managed to get it to work just hold shift and press left or right on the song in freeplay or debug menu

**Comment by Kade-github** [comment]
yeah

**Comment by DeceptedPar** [comment]
I have to say one last thing this has to be one of the best things you've added, well done and thank you
