### ISSUE TITLE
Enhancement: when rising the speed the scrollspeed goes up aswell

### ISSUE THREAD

**Issue by DeceptedPar** [KadeArchive/Kade-Engine#1885]
## What is your suggestion, and why should it be implemented?
when rising the speed thing in freeplay/debug menu the scrollspeed goes up aswell

reason being, if the speed thing gets rised too high the arrows will be smushed together and it wont be possible to tell out what arrow to press next

**Comment by isakube** [comment]
what are you saying

**Comment by KlutchDj** [comment]
context matters.

**Comment by DeceptedPar** [comment]
eh, doesn't matter, I'm not good at explaining so this can just be deleted

**Comment by bbpanzu** [comment]
he is suggesting increasing the song rate also increases the scroll speed as well.

**Comment by Kade-github** [comment]
just up ur scroll speed.  lol

**Comment by DeceptedPar** [comment]
last thing before I stop, when increasing the scroll speed the notes just dissapear, it's prob fixed by now but just wanted to say, was a fun challenge but eh,
