### ISSUE TITLE
Bug Report: The game crashes when you finish a song/week on a low-end computer even though the optimization option is applied

### ISSUE THREAD

**Issue by RobXol4535** [KadeArchive/Kade-Engine#1887]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by raf13lol** [comment]
are you on windows?

**Comment by RobXol4535** [comment]
Ye

**Comment by raf13lol** [comment]
64 bit?

**Comment by RobXol4535** [comment]
yep

**Comment by raf13lol** [comment]
can you press the windows key and r at the same time?

**Comment by RobXol4535** [comment]
what that do

**Comment by raf13lol** [comment]
opens run (NOT FROM BOB)

**Comment by raf13lol** [comment]
then type dxdiag.exe

**Comment by RobXol4535** [comment]
huh

**Comment by raf13lol** [comment]
what

**Comment by RobXol4535** [comment]
ok

**Comment by raf13lol** [comment]
do you see a window with lots of info

**Comment by RobXol4535** [comment]
yessir

**Comment by raf13lol** [comment]
click save all information

**Comment by raf13lol** [comment]
then click save

**Comment by raf13lol** [comment]
then upload it to your comment

**Comment by RobXol4535** [comment]
[DxDiag.txt](https://github.com/KadeDev/Kade-Engine/files/7026948/DxDiag.txt)
got it

**Comment by raf13lol** [comment]
what version of game are you on

**Comment by RobXol4535** [comment]
latest

**Comment by raf13lol** [comment]
1.6.2?

**Comment by RobXol4535** [comment]
yep

**Comment by raf13lol** [comment]
ok

**Comment by RobXol4535** [comment]
idk prob my pc sucks

**Comment by raf13lol** [comment]
could be but your computer doesnt look like it would crash and tbh thats not why your thing is crashing so try reinstalling the game

**Comment by RobXol4535** [comment]
or maybe the json file is just too much for the game to handle

**Comment by raf13lol** [comment]
no it is not

**Comment by RobXol4535** [comment]
monke
