### ISSUE TITLE
Bug Report: fix the arrows pls i beg you

### ISSUE THREAD

**Issue by ultraivan12** [KadeArchive/Kade-Engine#1894]
fix the arrow trails so that they do not overlap or separate

**Comment by Spel0** [comment]
ok

**Comment by ultraivan12** [comment]
r you a mod? or a developer?

**Comment by isakube** [comment]
we all are. also fixed

**Comment by ultraivan12** [comment]
you fixed it? i hope you include the arrows in a new update
