### ISSUE TITLE
Question: How to update without losing progress

### ISSUE THREAD

**Issue by edgardeivis** [KadeArchive/Kade-Engine#190]
Title says it all, how do i update it without losing my mod progress?

**Comment by theDetourist** [comment]
Compare the files, get the changes and apply them yourself to your mod files.

**Comment by edgardeivis** [comment]
oh, that's sad, i thought i could just update it lmao

**Comment by puyoxyz** [comment]
an actual tutorial:

1: `cd` into root folder of your fork
2: `git pull https://github.com/KadeDev/Kade-Engine --allow-unrelated-histories`
3: it might merge automatically, in which case you can just build to see if it works and it's done. if not, it'll show you in which files you need to solve conflicts. solve them and save, then commit the changes
4: `git push`

**Comment by edgardeivis** [comment]
thanks!

**Comment by edgardeivis** [comment]
> an actual tutorial:
> 
> 1: `cd` into root folder of your fork
> 2: `git pull https://github.com/KadeDev/Kade-Engine --allow-unrelated-histories`
> 3: it might merge automatically, in which case you can just build to see if it works and it's done. if not, it'll show you in which files you need to solve conflicts. solve them and save, then commit the changes
> 4: `git push`

why does it say "fatal: not a git repository (or any of the parent directories): .git" ???

**Comment by puyoxyz** [comment]
That means you don't have a git repository for your mod.

**Comment by edgardeivis** [comment]
how do i create one?

**Comment by puyoxyz** [comment]
> how do i create one?

Google
