### ISSUE TITLE
Lag Spikes when changing characters

### ISSUE THREAD

**Issue by lemz1** [KadeArchive/Kade-Engine#1900]
Kade Engine 1.6.2 (Windows 64bit)
Hi,
Whenever the characters at the end load they make it lag and I wanted to ask 
if anyone knows how to do something to prevent this from happening

Here's the video:

![Hnet-image(1)](https://user-images.githubusercontent.com/87707926/130378920-7a8b85ce-202b-4536-8624-9c9a45362a6f.gif)

Here's the code:

![Screenshot (42)](https://user-images.githubusercontent.com/87707926/130378612-f2dac200-5cf0-4241-9880-960302b166e9.png)

![Screenshot (43)](https://user-images.githubusercontent.com/87707926/130378620-76287f1b-f47d-43ed-92e1-31525b81bfb9.png)

![Screenshot (44)](https://user-images.githubusercontent.com/87707926/130378622-ebefa208-2131-4d89-a92b-dfe4018be50a.png)

![Screenshot (45)](https://user-images.githubusercontent.com/87707926/130378639-54c1cf56-e389-450c-b110-4c3b03f4c97b.png)

![Screenshot (46)](https://user-images.githubusercontent.com/87707926/130378652-407a4e58-4152-4a5f-8507-329e86295780.png)

![Screenshot (47)](https://user-images.githubusercontent.com/87707926/130378658-a55365a6-b132-45c3-b41a-8dbdb5debe29.png)

**Comment by loogchin** [comment]
add character in stage
![Capture](https://user-images.githubusercontent.com/87599145/130382907-44009bb3-35c4-41d8-b1df-94a28ebce18d.PNG)

**Comment by Kade-github** [comment]
^ that and turn on preload characters.
