### ISSUE TITLE
Bug Report: Compiling version 1.7 leads to error immediately

### ISSUE THREAD

**Issue by GlitchyGlyph** [KadeArchive/Kade-Engine#1905]
On compile for version 1.7, Windows PowerShell immediately give the same prompt. 

Error: Could not find haxelib "hxvm_luajit," does it need to be installed?

This does not happen when I compile the version before this. Any sort of fixes?

![image](https://user-images.githubusercontent.com/89369301/130384004-af753aa0-67d0-4b8f-bbe4-5325c86744d4.png)

**Comment by EliteMasterEric** [comment]
@GlitchyGlyph KadeEngine v1.7.0 added a new library dependency but didn't add it to the build documentation at `build.md`.

Run this in the command line:
```
haxelib git hxvm-luajit https://github.com/KadeDev/hxvm-luajit
```

**Comment by GlitchyGlyph** [comment]
> @GlitchyGlyph KadeEngine v1.7.0 added a new library dependency but didn't add it to the build documentation at `build.md`.
> 
> Run this in the command line:
> 
> ```
> haxelib git hxvm-luajit https://github.com/KadeDev/hxvm-luajit
> ```

Thank you, lemme give that a try.

**Comment by GlitchyGlyph** [comment]
Perfect! Thank you!

**Comment by GlitchyGlyph** [comment]
> @GlitchyGlyph KadeEngine v1.7.0 added a new library dependency but didn't add it to the build documentation at `build.md`.
> 
> Run this in the command line:
> 
> ```
> haxelib git hxvm-luajit https://github.com/KadeDev/hxvm-luajit
> ```

Okay, so I did it, but now it's breaking the code in some way? Idk
![image](https://user-images.githubusercontent.com/89369301/130385225-41f44516-a0fa-4d94-a875-398e65c5f2e6.png)

**Comment by EliteMasterEric** [comment]
Firstly, I had the wrong URL for LuaJIT, the correct one is `https://github.com/nebulazorua/hxvm-luajit`.

Secondly, when posting console errors, please select and copy the text and paste it here so people don't have to read a screenshot.

Thirdly, I am experiencing the same issue. It appears to be a duplicate of #1850. I am guessing the problem is that a new version of some library is mandatory.

**Comment by GlitchyGlyph** [comment]
> Firstly, I had the wrong URL for LuaJIT, the correct one is `https://github.com/nebulazorua/hxvm-luajit`.
> 
> Secondly, when posting console errors, please select and copy the text and paste it here so people don't have to read a screenshot.
> 
> Thirdly, I am experiencing the same issue. It appears to be a duplicate of #1850. I am guessing the problem is that a new version of some library is mandatory.

Firstly, thank you. I suck with coding biz, so it's nice to have some help with this.
Secondly, sorry about that. I'll make sure to copy/paste the errors from now on.
Thirdly, I wonder which one it is. I'll make sure to try what I can to fix it on my end.

**Comment by JMV8712** [comment]
YO! When you figure out or resolve the issue make sure to let me know what you did to solve it :)

**Comment by GlitchyGlyph** [comment]
> YO! When you figure out or resolve the issue make sure to let me know what you did to solve it :)

Gotcha, I've found no fix so far. All I know is that there was an update for git but, no dice for fixing the issue. :/

I'll be sticking with the 1.6 variants until then.

**Comment by JMV8712** [comment]
> > YO! When you figure out or resolve the issue make sure to let me know what you did to solve it :)
> 
> Gotcha, I've found no fix so far. All I know is that there was an update for git but, no dice for fixing the issue. :/
> 
> I'll be sticking with the 1.6 variants until then.

Speaking of 1.6 The version I'm trying to run on won't let me run it through cmd. I get these errors

source/PlayState.hx:3994: characters 14-29 : Cannot access private field SKIP_STEP_LIMIT
source/WebmHandler.hx:32: characters 10-26 : Not enough arguments, expected io:webm.WebmIo, soundEnabled:Bool
source/WebmHandler.hx:33: characters 8-12 : webm.WebmPlayer has no field fuck
source/WebmHandler.hx:96: characters 8-21 : webm.WebmPlayer has no field changePlaying
source/WebmHandler.hx:102: characters 8-21 : webm.WebmPlayer has no field changePlaying
source/WebmHandler.hx:53: characters 8-12 : webm.WebmPlayer has no field fuck
source/WebmHandler.hx:119: characters 8-19 : webm.WebmPlayer has no field removePause

Do you have any idea what the issue is here? I've tried different webm extensions, and I've tried rebuilding it multiple times.

**Comment by GlitchyGlyph** [comment]
Sorry man, I have no clue. I am completely new to coding and am sorta waddling through like a toddler. Might want to make a post about it maybe?

**Comment by JMV8712** [comment]
Yeah, I will thanks anyway though.

**Comment by keif** [comment]
Updated #1850 with the fix that worked for me, thanks to Spelo on discord.

**Comment by JMV8712** [comment]
> Updated #1850 with the fix that worked for me, thanks to Spelo on discord.

It worked! But I got the same error that I did with 1.6 and 1.6.2 

C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/WebmHandler.hx:32: characters 10-26 : Not enough arguments, expected io:webm.WebmIo, soundEnabled:Bool
source/WebmHandler.hx:33: characters 8-12 : webm.WebmPlayer has no field fuck
source/WebmHandler.hx:96: characters 8-21 : webm.WebmPlayer has no field changePlaying
source/WebmHandler.hx:102: characters 8-21 : webm.WebmPlayer has no field changePlaying
source/WebmHandler.hx:53: characters 8-12 : webm.WebmPlayer has no field fuck
source/WebmHandler.hx:119: characters 8-19 : webm.WebmPlayer has no field removePause

Do you know what to do here? @keif

**Comment by keif** [comment]
Did you install and compile webm?

`haxelib git extension-webm https://github.com/KadeDev/extension-webm`
`lime rebuild extension-webm windows`
(Assuming Windows OS)

**Comment by JMV8712** [comment]
I did, the same errors show up with no changes whatsoever

**Comment by JMV8712** [comment]
> I did, the same errors show up with no changes whatsoever

and yes it is on Windows OS

**Comment by JMV8712** [comment]
> > I did, the same errors show up with no changes whatsoever
> 
> and yes it is on Windows OS

WAIT I FIGURED IT OUT HOLY SHIT, it's taking a long time to compile stuff though but ITS COMPILING

**Comment by EliteMasterEric** [comment]
> Updated #1850 with the fix that worked for me, thanks to Spelo on discord.

I can confirm that performing these steps fixed the build for me.
