### ISSUE TITLE
Bug Report: i can't compile on linux again

### ISSUE THREAD

**Issue by Pietrodjaowjao** [KadeArchive/Kade-Engine#1915]
### If you are playing a downloaded version of the game, what operating system are you using?
Linux x64

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.7

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
![issue](https://user-images.githubusercontent.com/77608535/130400883-89deb385-8d25-4e6f-8204-5ae69e3a8a5e.png)

**Comment by Pietrodjaowjao** [comment]
fixed, closing issue

**Comment by Pietrodjaowjao** [comment]
false positive, 
![otherissue](https://user-images.githubusercontent.com/77608535/130401754-8d264fff-af2b-40d1-ac9e-c123d3f5df9e.png)
other error appeared

**Comment by Pietrodjaowjao** [comment]
#1911 and i tried this

**Comment by HommeBizarre** [comment]
How did fiwed the first issue?

**Comment by HommeBizarre** [comment]
How did you fixed the first issue?

**Comment by Sendan4** [comment]
the same for me, but it does not happen in all versions.
