### ISSUE TITLE
compiling error kade engine 1.7

### ISSUE THREAD

**Issue by xLuigiGamerx** [KadeArchive/Kade-Engine#1922]
compiling kade engine 1.7 doesn't compile and gives me this:
source/LuaClass.hx:35: characters 46-58 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:1669: characters 42-54 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:1469: characters 42-54 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:1144: characters 42-54 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:855: characters 41-53 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:635: characters 40-52 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:370: characters 42-54 : Type not found : StatePointer

**Comment by ghost** [comment]
Me too

**Comment by ghost** [comment]
For now use 1.6.2

**Comment by xLuigiGamerx** [comment]
> Me too

it's literally the same error as 1.6.2

**Comment by ghost** [comment]
Which is the latest working version

**Comment by ghost** [comment]
(for me)

**Comment by xLuigiGamerx** [comment]
1.6.1

**Comment by xLuigiGamerx** [comment]
for me

**Comment by ghost** [comment]
oh

**Comment by ghost** [comment]
use the latest version that works

**Comment by xLuigiGamerx** [comment]
k

**Comment by ghost** [comment]
> for me

ok use 1.6.1

**Comment by xLuigiGamerx** [comment]
if u find a fix comment here plz and thx

**Comment by MrPiskuvit** [comment]
https://github.com/KadeDev/Kade-Engine/issues/1942#issuecomment-904236679 I did what they said and it worked

**Comment by xLuigiGamerx** [comment]
> [#1942 (comment)](https://github.com/KadeDev/Kade-Engine/issues/1942#issuecomment-904236679) I did what they said and it worked

Thx for ur help it worked
