### ISSUE TITLE
Lag when changing Characters

### ISSUE THREAD

**Issue by lemz1** [KadeArchive/Kade-Engine#1923]
Kade Engine 1.6.2 (Windows 64bit)
Hi,
I already submitted the same issue and tried the fix but I still get Lags whenever
the character changes. (I have preload turned on)

Is there anything else I can/need to do or did I do something wrong?

![Hnet-image](https://user-images.githubusercontent.com/87707926/130466891-260aa194-8417-4d4c-81ce-0531063cb443.gif)

Here's the code:
![Screenshot (48)](https://user-images.githubusercontent.com/87707926/130468776-753b2371-c5d5-4fdd-a9a8-4309bf1fa3e0.png)
![Screenshot (49)](https://user-images.githubusercontent.com/87707926/130468786-239a7177-5bec-489a-a9c2-969e1118a494.png)

![Screenshot (42)](https://user-images.githubusercontent.com/87707926/130468806-becbffd8-3b07-4cb9-abd2-9900e13743fa.png)
![Screenshot (43)](https://user-images.githubusercontent.com/87707926/130468814-caf18b21-fe0b-4b6d-b6cd-cee49d104d26.png)
![Screenshot (44)](https://user-images.githubusercontent.com/87707926/130468817-0b113961-855a-4ce2-82ef-aeb4eba54f46.png)
![Screenshot (45)](https://user-images.githubusercontent.com/87707926/130468822-e6f59ccc-d611-4e04-9d65-b7030b3bf1b6.png)
![Screenshot (46)](https://user-images.githubusercontent.com/87707926/130468831-ff169c11-a7cb-4769-8254-7675dabdc820.png)
![Screenshot (47)](https://user-images.githubusercontent.com/87707926/130468837-0249bdef-c786-4426-9db5-7bcd84dc1411.png)

**Comment by ScarabWasTaken** [comment]
Lag happens any time a sprite is rendered for the first time. The only fix would be to preload all your sprites before the song starts.

**Comment by lemz1** [comment]
How do I preload them before the song starts?
