### ISSUE TITLE
Bug Report: Reloading Chart JSON for a file with a complex name (dad battle, satin panties, etc...) crashes

### ISSUE THREAD

**Issue by ScarabWasTaken** [KadeArchive/Kade-Engine#1925]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.7

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Load Dadbattle, open charter, press "Reload JSON"
## Please describe your issue. Provide extensive detail and images if possible.
Songs with names that don't exactly correspond to their chart files crash upon reloading the chart JSON.

**Comment by cuckydev** [comment]
hehe uhh this mightve been me when i fixed it to properly load -easy and -hard oops

**Comment by ScarabWasTaken** [comment]
Its a pretty old bug, I just never got around to reporting it, so if this was a recent change you made it probably wasn't the cause. My guess is this bug showed up when songs were renamed in I think 1.5

**Comment by Kade-github** [comment]
p sure this has been fixed.
