### ISSUE TITLE
Bug Report: Charting doesn't continue progress

### ISSUE THREAD

**Issue by ScarabWasTaken** [KadeArchive/Kade-Engine#1929]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86_64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.7
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Open chart editor
add/remove some notes near the start
Press Enter to play song
Notice edits made exist
Press 7 to load editor
Notice chart has been reloaded from file to pre-edited state
## Please describe your issue. Provide extensive detail and images if possible.
Previous charter would save current progress in a session, new charter requires saving all changes every time you want to play/check the song.

**Comment by Kade-github** [comment]
fixed
