### ISSUE TITLE
Enhancement: Support for other spritesheet data formats

### ISSUE THREAD

**Issue by crispyi2** [KadeArchive/Kade-Engine#193]
You should add support for other spritesheet data formats, you would still be able to use sparrow or starling but you could now use formats like json hash. I think this would make it esier for people who dont have access to programs that automaticly make sparrow and starling spritesheets

**Comment by Kade-github** [comment]
Or... hear me out. https://github.com/KadeDev/AdobeAnimate-Json-To-XML

**Comment by crispyi2** [comment]
thx for letting me know
