### ISSUE TITLE
Compilation errrors

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#1931]
**The error i have is this I cant explain it but i tried to compile the game and this happened**
[C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access]: **these two should be fix because of the ASIPSuff.hx file in sources but its not missing so I not sure whats wrong and the stuff below I dont know about****
source/LuaClass.hx:35: characters 46-58 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:1669: characters 42-54 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:1469: characters 42-54 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:1144: characters 42-54 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:855: characters 41-53 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:635: characters 40-52 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:370: characters 42-54 : Type not found : StatePointer
**Pls fix these issues I cant compile the game if their not fixed in the next update**

**Comment by DOGZ1234** [comment]
You need the linc_luajit library

**Comment by PhoenixFlared05** [comment]
how do you install that

**Comment by ghost** [comment]
Ya so how do I get that exactly

**Comment by Sendan4** [comment]
`haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git`

**Comment by ghost** [comment]
Thank You Very Much
