### ISSUE TITLE
Bug Report: Crash upon reaching end of chart

### ISSUE THREAD

**Issue by ScarabWasTaken** [KadeArchive/Kade-Engine#1933]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86_64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.7
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Open game
Open song
Open chart
Press Space
Reach end
Refuse to Elaborate
Crash
## Please describe your issue. Provide extensive detail and images if possible.
EDIT: When any chart reaches the song's end in the editor, the application crashes.

**Comment by Kade-github** [comment]
which chart, I don't get this.

**Comment by ScarabWasTaken** [comment]
Happened on both Fresh and Dad Battle on normal
When the chart reaches the end of the song the whole thing crashes
EDIT: Just tested bopeepo, crashes

**Comment by Luckyfishi** [comment]
have the same issue(using ke 1.7)
