### ISSUE TITLE
Bug Report: Can't Compile

### ISSUE THREAD

**Issue by SomeKindofGamer** [KadeArchive/Kade-Engine#1934]
Everytime i try to Compile Kade Engine 1.7 this shows up
"Could not find haxelib "hxvm-luajit", does it need to be installed?"

**Comment by ghost** [comment]
Here what you do you go to command prompt and then type haxelib git 
then it will say library name then type hxvm-luajit
after those two steps its going to ask you for the git path type this in https://github.com/nebulazorua/hxvm-luajit

**Comment by SomeKindofGamer** [comment]
Thank you so much!

**Comment by ghost** [comment]
Your welcome

**Comment by Jimmyboi123** [comment]
type in the link?
