### ISSUE TITLE
compile problem 

### ISSUE THREAD

**Issue by NK-523** [KadeArchive/Kade-Engine#1936]
When I try to compile kade engine I get this warning: "Program Files (x86)/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
Program Files (x86)/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access" and the compile stops, I'm on version 1.7 and this warning only started happening today.

**Comment by ghost** [comment]
do you have the ASIPStuff.Hx in the source folder

**Comment by nahiassis** [comment]
(`Program Files (x86)/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
Program Files (x86)/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access`) doesn't affect anything, its something on top of it, and also kade engine already comes with `APIStuff.hx`

**Comment by Kade-github** [comment]
those aren't errors
