### ISSUE TITLE
Bug Report: Compile Issue

### ISSUE THREAD

**Issue by SomeKindofGamer** [KadeArchive/Kade-Engine#1939]
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/LuaClass.hx:35: characters 46-58 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:1669: characters 42-54 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:1469: characters 42-54 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:1144: characters 42-54 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:855: characters 41-53 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:635: characters 40-52 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:370: characters 42-54 : Type not found : StatePointer

please help

**Comment by Kade-github** [comment]
building.md 
![image](https://user-images.githubusercontent.com/26305836/130533730-23c5d7e2-3661-4ab1-92e0-dc8a734ae1d5.png)

**Comment by SomeKindofGamer** [comment]
> building.md
> ![image](https://user-images.githubusercontent.com/26305836/130533730-23c5d7e2-3661-4ab1-92e0-dc8a734ae1d5.png)

I've just done that
I'm still having the issue
Should i try reinstall Haxe?

**Comment by SomeKindofGamer** [comment]
> > building.md
> > ![image](https://user-images.githubusercontent.com/26305836/130533730-23c5d7e2-3661-4ab1-92e0-dc8a734ae1d5.png)
> 
> I've just done that
> I'm still having the issue
> Should i try reinstall Haxe?

ok reinstalling haxe fixed the issue

**Comment by kvuimer** [comment]
> > > building.md
> > > ![image](https://user-images.githubusercontent.com/26305836/130533730-23c5d7e2-3661-4ab1-92e0-dc8a734ae1d5.png)
> > 
> > 
> > I've just done that
> > I'm still having the issue
> > Should i try reinstall Haxe?
> 
> ok reinstalling haxe fixed the issue
thank you dude

**Comment by kvuimer** [comment]
> > > building.md
> > > ![image](https://user-images.githubusercontent.com/26305836/130533730-23c5d7e2-3661-4ab1-92e0-dc8a734ae1d5.png)
> > 
> > 
> > I've just done that
> > I'm still having the issue
> > Should i try reinstall Haxe?
> 
> ok reinstalling haxe fixed the issue

thank you so much dude you are awesome
