### ISSUE TITLE
ur engine is so slow

### ISSUE THREAD

**Issue by aflacc** [KadeArchive/Kade-Engine#194]
seriously why do it take like 5 seconds to go from title screen to main menu

also dont just say i need better pc you already told me in the GB discord and that did not help at all

**Comment by theDetourist** [comment]
**5 seconds**. You're complaining about **5 seconds** of transition?

**Comment by Kade-github** [comment]
He literally @'ed me with a clip of it being slow and I @'ed back with a clip of it working fine. This is a joke issue, please stop making these.

**Comment by aflacc** [comment]
> He literally @'ed me with a clip of it being slow and I @'ed back with a clip of it working fine. This is a joke issue, please stop making these.

I DID and no its not a joke I generally don't like how slow it is

**Comment by Jaduplex** [comment]
IT'S NOT KADE ENGINE'S FAULT. It's because you have a shit pc. it works fine for me

**Comment by isakube** [comment]
cynda speaking facts, im even running it through Wine and it's cool

**Comment by Sebyal** [comment]
Toaster gang

**Comment by puyoxyz** [comment]
> cynda speaking facts, im even running it through Wine and it's cool

why wine? there are linux builds

**Comment by isakube** [comment]
> > cynda speaking facts, im even running it through Wine and it's cool
> 
> why wine? there are linux builds

I'm A mAc UsEr smH yOU gUys Act lIkE mAcOS dOEsn't EvEn ExIst

also i learned how to compile stuff so

**Comment by Jaduplex** [comment]
> > > cynda speaking facts, im even running it through Wine and it's cool
> > 
> > 
> > why wine? there are linux builds
> 
> I'm A mAc UsEr smH yOU gUys Act lIkE mAcOS dOEsn't EvEn ExIst
> 
> also i learned how to compile stuff so

you do realize mac os can. run linux stuff. right

**Comment by isakube** [comment]
i forget that some people dont capitalize all their vowels to express a lack of seriousness
