### ISSUE TITLE
sustain notes and lifegain

### ISSUE THREAD

**Issue by HiroMizuki** [KadeArchive/Kade-Engine#1940]
yknow, the sustain notes on kade engine have a different lifegain system from original fnf

it would be cool, cuz it's a little uncomfortable playing a fnf mod with non-sustaining health gain

but yea, this would be helpy for some inexperienced coders and modders

**Comment by ScarabWasTaken** [comment]
you havent actually said what you want

**Comment by napstaa967** [comment]
someone tried to add health gain from holding notes but kade closed the pr saying "no"

**Comment by HiroMizuki** [comment]
> someone tried to add health gain from holding notes but kade closed the pr saying "no"

shit
