### ISSUE TITLE
Slowmotion

### ISSUE THREAD

**Issue by tahiadz1962** [KadeArchive/Kade-Engine#196]
I would like an option to activate and deactivate a Slowmotion mode. It would help to clear very hard mods!
It needs to be slowed to be 2 times slower. It will slow down the music, the animations, the chart, and the chart's speed.
For the slowed-down music, I would like the pitch not to be changed.

**Comment by puyoxyz** [comment]
better suggestion: practice mode that lets you pick a % speed and which part of a song you want to practice (or the whole song)

**Comment by Kade-github** [comment]
> better suggestion: practice mode that lets you pick a % speed and which part of a song you want to practice (or the whole song)

probably going to end up adding a rate mod.

**Comment by tahiadz1962** [comment]
Replying to daniel11420: Actually, you're right.
Replying to Kade: I think it would be better to be in Kade Engine.

**Comment by Kade-github** [comment]
> Replying to daniel11420: Actually, you're right.
> Replying to Kade: I think it would be better to be in Kade Engine.

that's what I said. I'm going to add a rate mod to ke.

**Comment by tposejank** [comment]
poggers

**Comment by Kade-github** [comment]
I think we can just wait until this issue gets done since this is practically a dup of #196

**Comment by tahiadz1962** [comment]
> > Replying to daniel11420: Actually, you're right.
> > Replying to Kade: I think it would be better to be in Kade Engine.
> 
> that's what I said. I'm going to add a rate mod to ke.

Sorry, I meant you were gonna make a mod completely dedicated to that.
