### ISSUE TITLE
Bug Report: Error: Could not find haxelib "hxvm-luajit", does it need to be installed?

### ISSUE THREAD

**Issue by CheeseMaxT** [KadeArchive/Kade-Engine#1980]
When i do lime test windows on the latest version it pop this up Error: Could not find haxelib "hxvm-luajit", does it need to be installed? I did everything right

**Comment by napstaa967** [comment]
everyone keeps mentioning this

kade 1.7 uses a new lua package for modcharts

do this:

haxelib remove linc_luajit
haxelib remove hxvm-luajit
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git
haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit

**Comment by austinnorthington** [comment]
i also have a problem whenever i want to build my game and type lime test windows it always shows this:
Error: Source path "C:/HaxeToolkit/haxe/lib/extension-webm/git/ndll/Windows64/extension-webm.ndll" does not exist

**Comment by nicho01022** [comment]
> everyone keeps mentioning this
> 
> kade 1.7 uses a new lua package for modcharts
> 
> do this:
> 
> haxelib remove linc_luajit
> haxelib remove hxvm-luajit
> haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git
> haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit

**Comment by CheeseMaxT** [comment]
I have that too but I fix it by reinstalling everything
Also napstaa967 it work

**Comment by jestemzapis69-clo** [comment]
Hi! I made a fixers for this problem. Instruction and everything is there to download:
https://www.mediafire.com/file/7fx6dqg2j7e88rv/fixers.zip/file
:)

**Comment by austinnorthington** [comment]
i followed the instructions until i got to the Kade Engine.bat where it shows Error: Source path "C:/HaxeToolkit/haxe/lib/extension-webm/git/ndll/Windows64/extension-webm.ndll" does not exist
Press any key to continue . . .



this happened after i said y for debug mode

**Comment by nolanwhy** [comment]
tysm @jestemzapis69-clo for your fixers!

**Comment by libracrumbs** [comment]
hi, it just keeps saying error: could not clone git repository when i try to clone hxvm-luajit or linc-luajit
pls help it just started happening
