### ISSUE TITLE
Character hx file

### ISSUE THREAD

**Issue by NK-523** [KadeArchive/Kade-Engine#1984]
I think I found out how to stop the warnings people are running into (Program Files (x86)/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
Program Files (x86)/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access), and I found why I think kade engine stops compiling. This is the current reason: **source/Character.hx:438: characters 2-8 : Unexpected public**, but I ran into more than one of these.

**source/Character.hx:531: character 5 : Expected }**, the first one, this one I fixed easily.

**source/Stage.hx:429: characters 6-7 : Expected :**, the second one, fixed easily too.

Then there is the one I'm on now, **source/Character.hx:438: characters 2-8 : Unexpected public**, I don't know how to fix this one (The line of code: **public function loadOffsetFile(character:String, library:String = 'shared'**)) someone help me fix this please, (my Kade engine version is 1.7).

**Comment by xLuigiGamerx** [comment]
case 'urcharsname':
				tex = Paths.getSparrowAtlas('urcharsspritesheetname,'shared',true);
				frames = tex;
				animation.addByPrefix('idle', 'urcharsidleanim', 24, false);
				animation.addByPrefix('singUP', 'urcharsupanim', 24, false);
				animation.addByPrefix('singRIGHT', 'urcharsrightanim', 24, false);
				animation.addByPrefix('singDOWN', 'urcharsdownanim', 24, false);
				animation.addByPrefix('singLEFT', 'urcharsleftanim', 24, false);

				loadOffsetFile(curCharacter);

				playAnim('idle');
if ur making a custom character copy the code above and replace the custom character's code with this and replace "urchars" with its correct code

**Comment by NK-523** [comment]
fixed it by cloning the repository and pasting my character into the new character.hx file and it builds fine.
