### ISSUE TITLE
Bug Report: Game crashes every time i finish a track

### ISSUE THREAD

**Issue by MathsThundersz** [KadeArchive/Kade-Engine#199]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Windows 10 64-Bits

## What version of the game are you using? Look in the bottom left corner of the main menu.

1.4.1

## Please describe your issue. Provide extensive detail and images if possible.

Every time I finish a song, my game crashes with these pop-ups, it started about 2 weeks ago.
![image](https://user-images.githubusercontent.com/64690096/114476776-4ac7a480-9bd1-11eb-921b-0a9ae5c43b01.png)
This happens with every single mod that uses kade engine, and it really sucks having to re-open the game every time I finish a song

**Comment by puyoxyz** [comment]
This means the game can't write to the replay folder. This is either because the folder doesn't exist, or because you don't have permission to access it. Please make sure it exists (should be `assets/replay`)

**Comment by MathsThundersz** [comment]
> This means the game can't write to the replay folder. This is either because the folder doesn't exist, or because you don't have permission to access it. Please make sure it exists (should be `assets/replay`)

Bruh, that's it. I moved my FNF Folder into a administrator directory, gonna try to solve that. Thanks!!!
