### ISSUE TITLE
Bug Report: 'Null Pointer Function' error when using VideoState class in none debug build

### ISSUE THREAD

**Issue by FaultyTwo** [KadeArchive/Kade-Engine#1994]
## If you are playing a downloaded version of the game, what operating system are you using?
Windows x64

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.7 (After minor bugs fixed)
 
## Issue Description:
The debug build of 1.7 KE, VideoState class seems to work just fine.
However. In none debug build of 1.7 KE. Upon calling the class, it will pop 'Null Function Pointer' then just crash the game.

Audio seems to work just fine. But the video itself doesn't. I also can't debug this since.. well, it's only happen in none debug build. Any ideas what's the culprit that caused this?

*VideoState were used in StoryMenuState for first scene cutscene.

![dang](https://user-images.githubusercontent.com/25416809/130920377-a281a1c0-de21-4e80-87b7-f3ab8e662524.png)

**Comment by FaultyTwo** [comment]
Nope. The issues still persists.
I don't know what or where pointer is causing this error. If anyone could look into it, that would be nice.

**Comment by Luckyfishi** [comment]
yeah I met the same problem(using ke 1.7),dunno how to fix this

**Comment by FaultyTwo** [comment]
Reopening this to confirm it's KE 1.7 problem.
