### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by BlondyFmab1234** [KadeArchive/Kade-Engine#200]
I've installed everything for Haxe, Haxelib, and all of the added things, but no matter what I try, there's always this error while compiling the game for windows: 
```
Error: ShapeCache.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\crtdbg.h(2): fatal error C1014: too many include files: depth = 1024

Error: ThreadPoolMessage.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\crtdbg.h(2): fatal error C1014: too many include files: depth = 1024

Error: FlxSteamUpdater.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\crtdbg.h(2): fatal error C1014: too many include files: depth = 1024

Error: FlxPool_flixel_effects_FlxFlicker.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\crtdbg.h(2): fatal error C1014: too many include files: depth = 1024
```
This may have to do with me trying to create my own heading for the `crtdbg.h` file using predetermined code.
I've been working on this mod for a few weeks now but never was able to fix this awful issue.

**Comment by puyoxyz** [comment]
Google! https://stackoverflow.com/questions/2582521/fatal-error-c1014-too-many-include-files-depth-1024

(tl;dr: add `#pragma once` to your header(s))

**Comment by Kade-github** [comment]
header hell moment
