### ISSUE TITLE
Bug Report: Compiling error

### ISSUE THREAD

**Issue by LilithiumIonBattery** [KadeArchive/Kade-Engine#201]
Sys_error("export/debug/windows/obj/Options.txt: Permission denied") --- I get this when I try to compile to windows, I'm not sure what I did wrong? 
![image](https://user-images.githubusercontent.com/79330358/114512867-77aba400-9c31-11eb-8882-30616ef8ffce.png)

**Comment by Kade-github** [comment]
This should be a Discussion as this is not a bug with Kade Engine.

**Comment by Kade-github** [comment]
(also u need to make sure you have access to the file. aka, is the file even there?)

**Comment by LilithiumIonBattery** [comment]
I'm haven't removed it so it should be there

**Comment by LilithiumIonBattery** [comment]
ok i guess my version was botched, fixed now.
