### ISSUE TITLE
error while compiling 

### ISSUE THREAD

**Issue by Sazzria** [KadeArchive/Kade-Engine#2018]
Compiling group: haxe
cl.exe -Iinclude -IC:/HaxeToolkit/haxe/lib/discord_rpc/git/linc/ -IC:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/ -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdC:\Users\User\Downloads\Kade-Engine-1.5.4\Kade-Engine-1.5.4\export\release\windows\obj\obj/msvc1964-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -FS -Oy- -c -EHs -GS- -IC:/HaxeToolkit/haxe/lib/hxcpp/4,2,1/include -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - src/flixel/input/actions/_FlxSteamController/FlxSteamControllerMetadata.cpp
 - src/sys/io/_Process/Stdout.cpp
 - src/openfl/display/_internal/Context3DElementType.cpp
Error: Context3DElementType.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory

Error: FlxSteamControllerMetadata.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory

when i was compiling the code it showed me this, can anyone help me?

**Comment by notmagniill** [comment]
hmmmm, maybe you should send a picture so i could understand your problem

Regards, Magniill

**Comment by Sazzria** [comment]
> hmmmm, maybe you should send a picture so i could understand your problem
> 
> Regards, Magniill

C:\Users\User\Downloads\Kade-Engine-1.5.4\Kade-Engine-1.5.4>liime test windows
'liime' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\User\Downloads\Kade-Engine-1.5.4\Kade-Engine-1.5.4>lime test windows
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/PlayState.hx:329: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

Compiling group: haxe
cl.exe -Iinclude -IC:/HaxeToolkit/haxe/lib/discord_rpc/git/linc/ -IC:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/ -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdC:\Users\User\Downloads\Kade-Engine-1.5.4\Kade-Engine-1.5.4\export\release\windows\obj\obj/msvc1964-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -FS -Oy- -c -EHs -GS- -IC:/HaxeToolkit/haxe/lib/hxcpp/4,2,1/include -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - src/flixel/input/actions/_FlxSteamController/FlxSteamControllerMetadata.cpp
 - src/sys/io/_Process/Stdout.cpp
 - src/openfl/display/_internal/Context3DElementType.cpp
Error: Context3DElementType.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory

Error: FlxSteamControllerMetadata.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory

here's the error it showed me, i kinda understand the part that it says cannot open include file but when i tried to fix it, there was no file with the name 'crtdbg.h'

**Comment by Sazzria** [comment]
> > hmmmm, maybe you should send a picture so i could understand your problem
> > Regards, Magniill
> 
> C:\Users\User\Downloads\Kade-Engine-1.5.4\Kade-Engine-1.5.4>liime test windows
> 'liime' is not recognized as an internal or external command,
> operable program or batch file.
> 
> C:\Users\User\Downloads\Kade-Engine-1.5.4\Kade-Engine-1.5.4>lime test windows
> C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
> C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
> source/PlayState.hx:329: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
> 
> Compiling group: haxe
> cl.exe -Iinclude -IC:/HaxeToolkit/haxe/lib/discord_rpc/git/linc/ -IC:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/ -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdC:\Users\User\Downloads\Kade-Engine-1.5.4\Kade-Engine-1.5.4\export\release\windows\obj\obj/msvc1964-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -FS -Oy- -c -EHs -GS- -IC:/HaxeToolkit/haxe/lib/hxcpp/4,2,1/include -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
> 
> * src/flixel/input/actions/_FlxSteamController/FlxSteamControllerMetadata.cpp
> * src/sys/io/_Process/Stdout.cpp
> * src/openfl/display/_internal/Context3DElementType.cpp
>   Error: Context3DElementType.cpp
>   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory
> 
> Error: FlxSteamControllerMetadata.cpp
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory
> 
> here's the error it showed me, i kinda understand the part that it says cannot open include file but when i tried to fix it, there was no file with the name 'crtdbg.h'

C:\Users\User\Downloads\Kade-Engine-1.5.4\Kade-Engine-1.5.4>lime test windows
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/PlayState.hx:329: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead

Compiling group: haxe
cl.exe -Iinclude -IC:/HaxeToolkit/haxe/lib/discord_rpc/git/linc/ -IC:/HaxeToolkit/haxe/lib/linc_luajit/git//linc/ -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdC:\Users\User\Downloads\Kade-Engine-1.5.4\Kade-Engine-1.5.4\export\release\windows\obj\obj/msvc1964-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -FS -Oy- -c -EHs -GS- -IC:/HaxeToolkit/haxe/lib/hxcpp/4,2,1/include -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - src/sys/io/_Process/Stdout.cpp
 - src/flixel/input/actions/_FlxSteamController/FlxSteamControllerMetadata.cpp
 - src/openfl/display/_internal/Context3DElementType.cpp
Error: Stdout.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory

Error: Context3DElementType.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory

Error: FlxSteamControllerMetadata.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals.h(12): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory


(another attempt while trying to compile the code)

**Comment by PalanSecpw** [comment]
try to reinstall visual studio and including the unity workload
