### ISSUE TITLE
How to convert health icon back to old version 1.6

### ISSUE THREAD

**Issue by bonduongchannel** [KadeArchive/Kade-Engine#2026]
I want to change the health icon of version 1.7 back to version 1.6 where do I need to edit?
i mean want to use iconGrid.png on version 1.7
Thank you very much.
![iconGrid](https://user-images.githubusercontent.com/89579730/131202525-6179b0b9-1160-4628-a4c8-9bd3ff8f78f5.png)

**Comment by yeeterongithub** [comment]
Do you want me to help? You might have to rename the files to the character names, though,
