### ISSUE TITLE
Bug Report: Lua state is not compiling 

### ISSUE THREAD

**Issue by lunarcleint** [KadeArchive/Kade-Engine#2029]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows('x86_64')
## What version of the game are you using? Look in the bottom left corner of the main menu.
KE 1.7
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
lime test windows
## Please describe your issue. Provide extensive detail and images if possible.
![image](https://user-images.githubusercontent.com/88809950/131205763-ed154d16-8969-4585-bd15-41a8753df50a.png)

**Comment by DOGZ1234** [comment]
do you have linc_luajit

**Comment by lunarcleint** [comment]
yes i have all the libs in the kade engine dep it would say missing lib if i didnt have it this is problem with code

**Comment by CynicalJambo** [comment]
I have this exact issue. Has anyone found a fix?
