### ISSUE TITLE
Crash when trying to play audio using space in charter

### ISSUE THREAD

**Issue by uhidontkno** [KadeArchive/Kade-Engine#2036]
On KE 1.7 When i enter the charter by pressing `7` It works like usual but when i press space to play through the song it doesnt play and just crash. 

How to do this:

press 7 in any song
press space
watch your game crash and cry

**Comment by MrPiskuvit** [comment]
Having the same issue. Currently using 1.6.2 until it gets fixed/someone finds out why it happens.

**Comment by uhidontkno** [comment]
I actually fixed the issue by modifying the source code.
