### ISSUE TITLE
Zoomed out issue, Affects everything but the Notes.

### ISSUE THREAD

**Issue by MilkJug1** [KadeArchive/Kade-Engine#2056]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Arco Linux w/Wine, and BSPWM (Latest version)

## What version of the game are you using? Look in the bottom left corner of the main menu.

Kade Engine 1.6.1+ (Noticed this bug since the first version of 1.6+ Kade Engine came out, It has never happened to me pre-1.6)

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
When you launch the executable from mods that use Kade Engine, go into a song and try and play it, the entire play area will be zoom out like this: (Using Vs Imposter, and Vs Eteled as examples)
![image](https://user-images.githubusercontent.com/76970674/131266066-84fe0a13-650d-49fe-b7a6-daf9aaddb6ed.png)
and 
![image](https://user-images.githubusercontent.com/76970674/131266101-719fbf43-c61c-4c0a-ab37-5ef340b64b39.png)

## Please describe your issue. Provide extensive detail and images if possible.
Its just visual issue, and everything is zoomed out, game works fine. I'm able to pass all the charts without an issue, its just that is really annoying to see. I will try a build Kade on Arco Linux to see if these do still form but, from the couple of mods that I've played, the entire area will appear zoomed out, same with the note area, but not the actual notes themselves.

I will try a post a video to show you more of what it looks like. The mods run fine, but this is just annoying me.

**Comment by MilkJug1** [comment]
I really don't know where to post this, because I have no idea what is causing the issue. I can prove that wine isn't the issue, because before 1.5 game ran just as fine as it did on windows 10, no zooming out. I can't post this in every mods' issue page since its a common issue between mods, I can try to see if its my WM, but other wine apps and games work just fine with wine.

**Comment by MilkJug1** [comment]
[here](https://youtu.be/o1__LYyTWVY) is a video showing what it looks like when you start a song, I picked some of the more noticeable ones in VS Imposter since I already had it open.


So I downloaded the latest release of Kade Engine and saw that the weird note issue was fixed, but everything being zoomed out was not. 
![image](https://user-images.githubusercontent.com/76970674/131266803-73ec0cc5-aa7f-4705-94b1-67c17c7447bc.png)
see.

**Comment by Yuta12342** [comment]
This issue is easy to fix. It happens if you fullscreen Kade Engine before it finishes loading, as it mistakes the Game's Resolution. Waiting until it has finished loading fixes this issue.

**Comment by MilkJug1** [comment]
Ah, will have to try that out. Thanks for the info!

**Comment by MilkJug1** [comment]
Tried it out, issue still happened. Game is automatically resize to the entire window, I have to hit my keybind for unlocking the window/changing layout. Im not sure if I can put the game on a block list or something like that where it doesn't automatically resize it.

**Comment by MilkJug1** [comment]
Used KDE on it and it fixed the issue, I wonder if BSPWM is messing up something with the window. Since it resizes a new window as soon as you open it up.
