### ISSUE TITLE
story mode categories

### ISSUE THREAD

**Issue by HiroMizuki** [KadeArchive/Kade-Engine#2059]
something like:

Categorie 1:
- Week 1
- Week 4
- Week 5

Categorie 2:
- Week 2
- Week 3
- Week 6

**Comment by tofu111456** [comment]
you cant
but thats a good idea maybe you can make it an enhancement

**Comment by HiroMizuki** [comment]
> you cant
> but thats a good idea maybe you can make it an enhancement

yea dude, i'll make it
