### ISSUE TITLE
Bug Report: Error when compiling to windows

### ISSUE THREAD

**Issue by ASHere2021** [KadeArchive/Kade-Engine#2067]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.7
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
no
## Please describe your issue. Provide extensive detail and images if possible.
When I compile the game, I get this error:

C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/LuaClass.hx:10: characters 8-19 : You cannot access the sys package while targeting js (for sys.io.File)
source/PlayState.hx:4: characters 8-16 :     referenced here
source/Replay.hx:100: characters 16-25 :     referenced here

Also the .exe file doesn't appear and I downloaded visual studio 2019 and the individual components so how do I fix this?

**Comment by tofu111456** [comment]
If it fails the compile then it is intentional for the .exe file to not appear
Well I think for your case you need to download something else from haxe or git

**Comment by NK-523** [comment]
```
source/LuaClass.hx:10:` characters 8-19 : You cannot access the sys package while targeting js (for sys.io.File)
source/PlayState.hx:4: characters 8-16 : referenced here
source/Replay.hx: 100 : characters 16-25 : referenced here
```
there are errors at line 10 of luaclass.hx, line 4 of playstate.hx, and line 100 of replay.hx. I had error similar to these, how I fixed it was by doing these steps from https://github.com/KadeDev/Kade-Engine/blob/stable/docs/building.md

> 1. `cd` to where you want to store the source code (i.e.`C:\Users\username\Desktop` or `~/Desktop`)
> 2. `git clone https://github.com/KadeDev/Kade-Engine.git`
> 3. `cd` into the source code: `cd Kade-Engine `

and then building from the clone.

**Comment by AbnormalPoof** [comment]
1.7 is a disaster in terms of compiling
