### ISSUE TITLE
Enhancement: Anti-spam option

### ISSUE THREAD

**Issue by JmonkBoy** [KadeArchive/Kade-Engine#207]
In the original, you can't press the buttons unless there is a note to hit as it will be a miss, but in kade it allows you to press whenever without consequence. I think it would be good to have an option to swap between these ways of treating a random or "wrong" press, because currently if every button was pressed every frame then you would beat any song (not with a great score, but beaten nonetheless).

**Comment by Kade-github** [comment]
probably in week 7 we'll add back old input
