### ISSUE TITLE
Bug Report: Note offsets broken in latest update

### ISSUE THREAD

**Issue by skulldogged** [KadeArchive/Kade-Engine#2082]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows (`x86_64`)
## What version of the game are you using? Look in the bottom left corner of the main menu.
KE 1.7 (Issue is on latest release and latest dev build in master branch)
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
1. Change note offset in settings
2. Go into a song
## Please describe your issue. Provide extensive detail and images if possible.
Ever since the 1.7 release of Kade Engine, note offsets have been completely non-working. I usually play on ~120ms offset which is a very noticeable difference from none at all. Even trying to change the note offset for a specific song does nothing anymore.

**Comment by ScrubRTA** [comment]
set it to -120 instead of 120
