### ISSUE TITLE
Enhancement: optional story mode categories

### ISSUE THREAD

**Issue by HiroMizuki** [KadeArchive/Kade-Engine#2084]
add a option of activating or deactivating story mode categories

something like:

Categorie 1:
- Week 1
- Week 4
- Week 5

Categorie 2:
- Week 2
- Week 3
- Week 6

**Comment by KlutchDj** [comment]
clarify more on this please

**Comment by HiroMizuki** [comment]
> clarify more on this please

yknow, when you open the Story Mode section, when option is activated, there'll be the selections "Categorie 1" and "Categorie 2", and when you click one one of these, will open the "folder" of weeks and they'll be there for selection

i think this is a hardcode, idk if it would be something simple

**Comment by HiroMizuki** [comment]
bad shit
