### ISSUE TITLE
About blocked weeks with the 1.6

### ISSUE THREAD

**Issue by Nikopol93** [KadeArchive/Kade-Engine#2092]
For fixing that, I have to remove "#if debug' and '#end' in the paragraph:

#if debug
for(i in 0...weekNames.length)
weeks.push(true);
return weeks;
#end

Right?

**Comment by SomeKindofGamer** [comment]
It's not that easy.
I tried that
It doesn't work.

**Comment by ghost** [comment]
this is probably just for debugging, so no
