### ISSUE TITLE
Bug Report: Sustain note trails are bugged again (why)

### ISSUE THREAD

**Issue by nahiassis** [KadeArchive/Kade-Engine#2096]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Win10 x64

## What version of the game are you using? Look in the bottom left corner of the main menu.

1.7

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

Go to dad battle (coz i use that song for testing stuff so yea), press 7 to go to the charting menu, place a sustain note, then press enter

## Please describe your issue. Provide extensive detail and images if possible.

![image](https://user-images.githubusercontent.com/85742902/131668497-443600c8-555b-4d09-afee-6807a2d5c566.png)

i swear this was not a thing in 1.6.1 or 1.6.2

**Comment by NK-523** [comment]
I think this is a visual bug carried over from the original fnf. I checked it on a 1.6 1.7 version of kade engine and it is there on both.

**Comment by nahiassis** [comment]
this was litterally fixed in 1.6.1 and 1.6.2
how is this in 1.7?
idfk

**Comment by nahiassis** [comment]
even the original fnf dosn't have this anymore

**Comment by NK-523** [comment]
its in my 1.6, I think. I could be seeing things, or it may be there with up scroll in 1.6 and there with both scrolls in 1.7.
