### ISSUE TITLE
Custom character bug

### ISSUE THREAD

**Issue by NK-523** [KadeArchive/Kade-Engine#2098]
When I compile a test build with my custom character and go into a song and try to make dad my character it crashes saying "ERROR there is no TEXT asset with an ID of 'shared:assets/shared/images/characters/charOffsets.txt'", but there is, and I have no idea why it isn't registering.

**Comment by isakube** [comment]
'assets/shared/images/characters/`character name`Offsets.txt'

**Comment by NK-523** [comment]
> 'assets/shared/images/characters/`character name`Offsets.txt'

I have a character offset file. the problem is kade engine isn't detecting it.

**Comment by NK-523** [comment]
Turns out I just misspelt something in the .xml
