### ISSUE TITLE
Bug Report: Score Info Layers Over Previous Songs

### ISSUE THREAD

**Issue by EmSolaris** [KadeArchive/Kade-Engine#2099]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows x64

## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Happens every time I open Kade Engine.

## Please describe your issue. Provide extensive detail and images if possible.
So, when I play songs in Kade Engine, somehow my score info gets layered on top of the score info from the previous songs I've played that session, to the point where after 5 or 6 songs the score info screen is filled with notes.

First song I played after opening Kade, all looks normal:
![image](https://user-images.githubusercontent.com/89937266/131723722-92d1f9b1-8007-491e-bf23-89d0ef3b5ee3.png)

Second song-- as you can see, the red dots remain (it gets harder to tell which other notes are duplicated, so keep an eye on those ones).
![image](https://user-images.githubusercontent.com/89937266/131723786-55a62ffb-1e60-4bc8-816f-d57108548d30.png)

And finally, third and fourth. I had tried to turn on minimalized score info for the fourth song, but it didn't fix the issue, just added fewer notes on top of what was already there.
![image](https://user-images.githubusercontent.com/89937266/131723920-dbc723a7-bf99-4476-9438-1d8d564368f1.png)
![image](https://user-images.githubusercontent.com/89937266/131723939-32418f72-a3cc-4601-89e0-5f2e9dddd002.png)

**Comment by NK-523** [comment]
I had my own version of this bug, but it only affected judgements, I played week 6, and when I went to play the tutorial I had 505 sicks, when I replayed it it went to a normal 53 sicks.
