### ISSUE TITLE
Enhancement: convert base game json files into the kade-engine json.

### ISSUE THREAD

**Issue by ILuvGemz** [KadeArchive/Kade-Engine#21]
## What is your suggestion, and why should it be implemented?

I have tried porting my mod's json, which I made in the base game into the kade engine, but whenever I try to play that chart, it just caused it the Kade Engine mod to crash. I tried to modify the json to correct what is wrong with it, and I ended up failing. Is there any difference between the base game's json format and the kade engine json format?

So while I don't need a file conversion, it be best if it is easier to create a guide to convert the jsons. That way, it's much easier to clear my own songs that are insanely difficult.

**Comment by Kade-github** [comment]
Can you provide the json files so I can take a look?

**Comment by ILuvGemz** [comment]
[dadbattle.zip](https://github.com/KadeDev/Kade-Engine/files/6175055/dadbattle.zip)
Here's the json of the mod in the base game.

**Comment by Kade-github** [comment]
I just tested it, and it works fine for me. What version of Kade Engine are you on?

**Comment by ILuvGemz** [comment]
1.1.3

**Comment by ILuvGemz** [comment]
Oh you can close it now. It WORKS!

**Comment by ILuvGemz** [comment]
I'm in old version
