### ISSUE TITLE
Bug Report: 1.4.1 source code seems same with Nightly2

### ISSUE THREAD

**Issue by HumanKR** [KadeArchive/Kade-Engine#210]
![image](https://user-images.githubusercontent.com/45139720/114702147-a3787800-9d5e-11eb-98dc-e0d6c3a27613.png)
i was download source code that way
i checked the MainMenuState.hx but "var nightly" is still "-Nightly2". is not empty.

other code is nothing changed too, is same code in NIghtly2
what's happened?

**Comment by theDetourist** [comment]
Kade should fix this soon, in the meantime, [get the latest nightly version](https://github.com/KadeDev/Kade-Engine/releases/tag/AppVeyor) in the release below 1.4.1 instead for the latest changes and the right source code.

**Comment by actuallyasmartname** [comment]
Can confirm that Kade forgot to remove nightly from MainMenuState.hx, should be fixed soon. The code is different tho
