### ISSUE TITLE
Enhancement: Store the current kade engine version in the chart

### ISSUE THREAD

**Issue by cuzsie** [KadeArchive/Kade-Engine#2100]
Store the version of kade engine the chart was made in in the file, so that when you try to load charts from older kade engine into new kade engine, it shows a message like "This chart was made for an older version of kade engine, are you sure you want to continue?". Kinda like minecraft's: "This texture pack was made for an older version of minecraft", but with kade engine charts.

**Comment by KlutchDj** [comment]
you can put old charts into the newer kade engine. you just gotta rename them to the proper song name . all it does its just to load notes
