### ISSUE TITLE
Bug Report: Charting Resets And Zooming Breaks When Exiting Chart Editor And Then Re-Entering.

### ISSUE THREAD

**Issue by DatBogie** [KadeArchive/Kade-Engine#2105]
When I go into a song and then go into the chart editor I can zoom in, but if I exit the chart editor to test the chart I've made so far, not only does the chart reset, but I can no longer zoom in and the chart editor zoom speed is way too fast. (This only doesn't happen the first time I go into the chart editor on a song)

**Comment by AwesomeArab** [comment]
All changes must be saved before exiting the chart editor for the time being.
