### ISSUE TITLE
Enhancement: Stage Prop Debugger

### ISSUE THREAD

**Issue by EliteMasterEric** [KadeArchive/Kade-Engine#2117]
Currently, building a stage is a tedious process of moving props around. A new scene with tools very similar to the Stage Character Debugger (`8` key) could be used to help with this.

Press space to cycle between elements of the swagBacks array, mouse to drag the active element, Q/E to zoom, IJKL to pan. Coordinates visible in the upper left.

**Comment by EliteMasterEric** [comment]
Ok Google how to self assign an issue on GitHub when you aren't a contributor for the repo

**Comment by Spel0** [comment]
I'm not sure what u proposing here, like you want **every** stages BG to being able to cycle through so people could make a stage using different stages files?

**Comment by EliteMasterEric** [comment]
I'm proposing that people would go to a stage, open it up, see that one of the elements of the stage is misaligned (for example, the curtains on the stage), and have the ability to press a key to open the stage prop debugger. This would let them press space to cycle through, not the stages of the game, but the individual components of the stage, and move them around with the mouse.

For example, on the winter stage you could cycle between the background, the boppers, the escalator, the snow, and Santa, and if I thought Santa was in the wrong spot, I could drag him with the mouse, and the new coordinates for Santa would be displayed at the top left.

**Comment by Spel0** [comment]
So the thing we have right now when you press shift but named differently?

**Comment by EliteMasterEric** [comment]
> So the thing we have right now when you press shift but named differently?

...

*takes another look at the codebase*

Um...

Turns out the innovative feature I was suggesting was already implemented.

Maybe I'll add a text label to make the controls more clear
