### ISSUE TITLE
How do I fix this random compiling problem

### ISSUE THREAD

**Issue by DoomEternal** [KadeArchive/Kade-Engine#2123]
How do I fix 
"source/LuaClass.hx:35: characters 46-58 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:1669: characters 42-54 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:1469: characters 42-54 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:1144: characters 42-54 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:855: characters 41-53 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:635: characters 40-52 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:370: characters 42-54 : Type not found : StatePointer"

**Comment by NK-523** [comment]
run these 

`haxelib remove linc_luajit`

`haxelib remove hxvm-luajit`

`haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git`

`haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit` in command prompt.
