### ISSUE TITLE
Game crashes after finishing a week

### ISSUE THREAD

**Issue by PineappleCake99** [KadeArchive/Kade-Engine#2124]
Well, I've tried to finish the tutorial week to unlock the other weeks (i can't unlock them on StoryMenuState.hx for some reason) and when I finish the week, the game crashes. I've tried to replace tutorial with week 1 (deleting the tutorial week code) and it also crashed again.

**Comment by NK-523** [comment]
Try cloning the repository, follow the steps here https://github.com/KadeDev/Kade-Engine/blob/stable/docs/building.md
