### ISSUE TITLE
Bug Report: fix your compiling issue in 1.7

### ISSUE THREAD

**Issue by Real-Toonz** [KadeArchive/Kade-Engine#2127]
windows 64

![image](https://user-images.githubusercontent.com/84243645/132010340-d055a5e2-1825-407d-ae2a-251598e1ac6e.png)

**Comment by NK-523** [comment]
Run Haxelb list and compare what shows up to what you have to install here https://github.com/KadeDev/Kade-Engine/blob/stable/docs/building.md, to see if you have everything.

**Comment by somefnfplayerlol** [comment]
are you trying to compile for html5?

**Comment by SanicBTW** [comment]
I have the same issue, it pops up when trying to compile 1.7 to html5
