### ISSUE TITLE
Bug Report: Error when I use a command

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#2130]
So every time I try to run the "Lime test windows" command I get an error saying "Cannot copy to "export/release/windows/bin/extension-webm.ndll", is the file in use? Does anyone know how to fix this?

**Comment by gamerbross** [comment]
If you have a fnf game open, close it (also look in the task manager). And if it still doesn't work, delete the file "Kade Engine.exe" inside "export/[release or debug]/windows/bin"
