### ISSUE TITLE
can someone help me?

### ISSUE THREAD

**Issue by Chubbiboyo** [KadeArchive/Kade-Engine#2133]
I'm trying to make a mod, but when I try to add a custom character and .xml, the game wont load it. It just crashes. Has anyone else had this problem and knows how to fix it?

**Comment by NK-523** [comment]
does it crash with a error message?

**Comment by Chubbiboyo** [comment]
i have found the issue, thank you

**Comment by NK-523** [comment]
For future refence, and to help people who find this, what was the issue?

**Comment by Chubbiboyo** [comment]
sorry im new to coding. the issue was that a didnt have a health bar icon.
