### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by G4merz** [KadeArchive/Kade-Engine#2138]
#### Please check for duplicates, similar issues or closed issues with the same problem, as well performing simple troubleshooting steps (such as deleting the export folder if it's an issue with compiling, reinstalling Kade Engine) before submitting an issue.

ok

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

windows x86

## What version of the game are you using? Look in the bottom left corner of the main menu.

KE 1.7

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

idk

## Please describe your issue. Provide extensive detail and images if possible.

the game displays "null object reference" after caching all the songs and just crash. i verified the classes Paths.hx, Caching.hx and Main.hx and they arent changed

**Comment by NK-523** [comment]
were you trying to add a custom song?

**Comment by G4merz** [comment]
yes, only one for testing shit

**Comment by NK-523** [comment]
check the .JSON make sure every thing is spelt right. I misspelled the songs name in my song's .JSON and and it caused a crash, not during caching but when I tried to load in to it.

**Comment by NK-523** [comment]
and check the character you have in the .JSON's .xml make sure everything is correct there too.

**Comment by G4merz** [comment]
ok

**Comment by G4merz** [comment]
the JSON name matches the song and the characters are ok

**Comment by NK-523** [comment]
Does your song have gimick notes in it, like Pico's caution signs, or Tricky's fire notes?

**Comment by G4merz** [comment]
tricky notes

**Comment by NK-523** [comment]
were they added properly

**Comment by G4merz** [comment]
yes, they are working properly

**Comment by G4merz** [comment]
i mean, they WERE working properly until this

**Comment by NK-523** [comment]
is your build a -debug build, did you put -debug in your build command in powershell

**Comment by G4merz** [comment]
both builds dont work

**Comment by NK-523** [comment]
if you move everything related to your song, the .JSONs and the song's Inst and Voices out of your data and song folders, will it load?

**Comment by G4merz** [comment]
already did that, and the game didnt load in both build types

**Comment by NK-523** [comment]
does your song have a modchart.lua file?

**Comment by G4merz** [comment]
yes, and its not working as it should (the song im using is subjugation from cc boss rush but with my custom chart)

**Comment by NK-523** [comment]
what is the modchart meant to do?

**Comment by G4merz** [comment]
only some note and camera effects

**Comment by NK-523** [comment]
does the game get past the loading screen?

**Comment by G4merz** [comment]
no, right when it says "Loading... 21/22" it crashes and the cmd says it finished caching
![imagem_2021-09-04_135031](https://user-images.githubusercontent.com/86385054/132102311-ac5329dc-967a-4485-acb5-399022d9b2d0.png)
![imagem_2021-09-04_135044](https://user-images.githubusercontent.com/86385054/132102317-6803a94c-14b5-44ce-b562-6abab6fd9bc8.png)

**Comment by G4merz** [comment]
it says 3/22 because i clicked out of the window

**Comment by NK-523** [comment]
so it crashes at 22

**Comment by G4merz** [comment]
yes

**Comment by G4merz** [comment]
right when it finish caching

**Comment by NK-523** [comment]
did you add a custom character icon

**Comment by G4merz** [comment]
yes

**Comment by NK-523** [comment]
did you add the song to freeplaysonglist.txt like this `song:char:week`

**Comment by G4merz** [comment]
have the mod wip showcase link
https://www.youtube.com/watch?v=Hn_1UqCYQsk
actual mod is exactly as it shows in the video but with tricky notes

**Comment by G4merz** [comment]
and with some stage changes

**Comment by NK-523** [comment]
![image](https://user-images.githubusercontent.com/77185327/132102536-4da0301e-0cc4-49a0-85fc-dfa12d9b57ee.png)
what is the 183rd line in chaching.hx for you?

**Comment by G4merz** [comment]
trace(Assets.cache.hasBitmapData('GF_assets'));

**Comment by G4merz** [comment]
wait what the fuck
where the gf dance title xml go??

**Comment by G4merz** [comment]
i dont know when and how i acidentally deleted that but i think that might be the error

**Comment by G4merz** [comment]
WHY THE GFDANCETITLE.xml WAS DELETED

**Comment by G4merz** [comment]
thank you anyway master chief

**Comment by NK-523** [comment]
your welcome

**Comment by NK-523** [comment]
![image](https://user-images.githubusercontent.com/77185327/132102802-b4cde920-1806-4afe-b892-8e158f9e09f7.png)
tested and that is the error, can never be too sure
