### ISSUE TITLE
Bug Report: "tricky" notes are only down notes

### ISSUE THREAD

**Issue by G4merz** [KadeArchive/Kade-Engine#2139]
#### Please check for duplicates, similar issues or closed issues with the same problem, as well performing simple troubleshooting steps (such as deleting the export folder if it's an issue with compiling, reinstalling Kade Engine) before submitting an issue.

fuck u

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

windows x86

## What version of the game are you using? Look in the bottom left corner of the main menu.

KE 1.7

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

idk i just followed bbpanzu tutorial

## Please describe your issue. Provide extensive detail and images if possible.

https://user-images.githubusercontent.com/86385054/132103500-2b670183-412c-41ff-a917-4a946c11d6d3.mp4

as you can see, the notes are functional but dont appear in charting menu and its only down note in-game

![NOTE_danger](https://user-images.githubusercontent.com/86385054/132103520-c9526e09-df96-4d10-88b5-9af3dcfa3e18.png)
the spritesheet is ok i think and the xml too

XML CONTENT:
<?xml version="1.0" encoding="utf-8"?>
<TextureAtlas imagePath="NOTE_assets.png">
	
	
	<SubTexture name="arrow static0000" x="0" y="0" width="157" height="154"/>
	<SubTexture name="blue0000" x="157" y="0" width="157" height="154"/>
	<SubTexture name="blue hold end0000" x="314" y="0" width="50" height="64"/>
	<SubTexture name="blue hold piece0000" x="364" y="0" width="50" height="44"/>
	<SubTexture name="blueee0000" x="414" y="0" width="157" height="154"/>
	<SubTexture name="down confirm0000" x="571" y="0" width="238" height="235"/>
	<SubTexture name="down confirm0001" x="809" y="0" width="238" height="235"/>
	<SubTexture name="down confirm0002" x="1047" y="0" width="220" height="217" frameX="-6" frameY="-12" frameWidth="238" frameHeight="235"/>
	<SubTexture name="down confirm0003" x="1047" y="0" width="220" height="217" frameX="-6" frameY="-12" frameWidth="238" frameHeight="235"/>
	<SubTexture name="down press0000" x="1267" y="0" width="142" height="140" frameX="-4" frameY="-2" frameWidth="149" frameHeight="146"/>
	<SubTexture name="down press0001" x="1267" y="0" width="142" height="140" frameX="-4" frameY="-2" frameWidth="149" frameHeight="146"/>
	<SubTexture name="down press0002" x="1409" y="0" width="149" height="146"/>
	<SubTexture name="down press0003" x="1409" y="0" width="149" height="146"/>
	<SubTexture name="green0000" x="1558" y="0" width="157" height="154"/>
	<SubTexture name="green hold end0000" x="1715" y="0" width="50" height="64"/>
	<SubTexture name="green hold piece0000" x="1765" y="0" width="50" height="44"/>
	<SubTexture name="greennn0000" x="1815" y="0" width="157" height="154"/>
	<SubTexture name="left confirm0000" x="0" y="235" width="228" height="231"/>
	<SubTexture name="left confirm0001" x="228" y="235" width="218" height="221" frameX="-5" frameY="-5" frameWidth="228" frameHeight="231"/>
	<SubTexture name="left confirm0002" x="446" y="235" width="225" height="228" frameX="-2" frameY="-1" frameWidth="228" frameHeight="231"/>
	<SubTexture name="left confirm0003" x="446" y="235" width="225" height="228" frameX="-2" frameY="-1" frameWidth="228" frameHeight="231"/>
	<SubTexture name="left press0000" x="671" y="235" width="140" height="142" frameX="-3" frameY="-3" frameWidth="146" frameHeight="149"/>
	<SubTexture name="left press0001" x="671" y="235" width="140" height="142" frameX="-3" frameY="-3" frameWidth="146" frameHeight="149"/>
	<SubTexture name="left press0002" x="811" y="235" width="146" height="149"/>
	<SubTexture name="left press0003" x="811" y="235" width="146" height="149"/>
	<SubTexture name="left press0004" x="811" y="235" width="146" height="149"/>
	<SubTexture name="left press0005" x="811" y="235" width="146" height="149"/>
	<SubTexture name="left press0006" x="811" y="235" width="146" height="149"/>
	<SubTexture name="left press0007" x="811" y="235" width="146" height="149"/>
	<SubTexture name="left press0008" x="811" y="235" width="146" height="149"/>
	<SubTexture name="left press0009" x="811" y="235" width="146" height="149"/>
	<SubTexture name="left press0010" x="811" y="235" width="146" height="149"/>
	<SubTexture name="left press0011" x="811" y="235" width="146" height="149"/>
	<SubTexture name="left press0012" x="811" y="235" width="146" height="149"/>
	<SubTexture name="left press0013" x="811" y="235" width="146" height="149"/>
	<SubTexture name="left press0014" x="811" y="235" width="146" height="149"/>
	<SubTexture name="left press0015" x="811" y="235" width="146" height="149"/>
	<SubTexture name="left press0016" x="811" y="235" width="146" height="149"/>
	<SubTexture name="left press0017" x="811" y="235" width="146" height="149"/>
	<SubTexture name="left press0018" x="811" y="235" width="146" height="149"/>
	<SubTexture name="left press0019" x="811" y="235" width="146" height="149"/>
	<SubTexture name="pruiple0000" x="957" y="235" width="154" height="157"/>
	<SubTexture name="pruple end hold0000" x="1111" y="235" width="50" height="64"/>
	<SubTexture name="purple0000" x="1161" y="235" width="154" height="157"/>
	<SubTexture name="purple hold piece0000" x="1315" y="235" width="50" height="44"/>
	<SubTexture name="red0000" x="1365" y="235" width="154" height="157"/>
	<SubTexture name="red hold end0000" x="1519" y="235" width="50" height="64"/>
	<SubTexture name="red hold piece0000" x="1569" y="235" width="50" height="44"/>
	<SubTexture name="reddd0000" x="1619" y="235" width="154" height="157"/>
	<SubTexture name="right confirm0000" x="1773" y="235" width="223" height="226" frameX="-1" frameY="-3" frameWidth="226" frameHeight="230"/>
	<SubTexture name="right confirm0001" x="0" y="466" width="223" height="226" frameX="-1" frameY="-3" frameWidth="226" frameHeight="230"/>
	<SubTexture name="right confirm0002" x="223" y="466" width="226" height="230"/>
	<SubTexture name="right confirm0003" x="223" y="466" width="226" height="230"/>
	<SubTexture name="right press0000" x="449" y="466" width="138" height="141" frameX="-3" frameY="-7" frameWidth="148" frameHeight="151"/>
	<SubTexture name="right press0001" x="449" y="466" width="138" height="141" frameX="-3" frameY="-7" frameWidth="148" frameHeight="151"/>
	<SubTexture name="right press0002" x="587" y="466" width="148" height="151"/>
	<SubTexture name="right press0003" x="587" y="466" width="148" height="151"/>
	<SubTexture name="right press0004" x="587" y="466" width="148" height="151"/>
	<SubTexture name="right press0005" x="587" y="466" width="148" height="151"/>
	<SubTexture name="right press0006" x="587" y="466" width="148" height="151"/>
	<SubTexture name="right press0007" x="587" y="466" width="148" height="151"/>
	<SubTexture name="right press0008" x="587" y="466" width="148" height="151"/>
	<SubTexture name="right press0009" x="587" y="466" width="148" height="151"/>
	<SubTexture name="right press0010" x="587" y="466" width="148" height="151"/>
	<SubTexture name="right press0011" x="587" y="466" width="148" height="151"/>
	<SubTexture name="right press0012" x="587" y="466" width="148" height="151"/>
	<SubTexture name="right press0013" x="587" y="466" width="148" height="151"/>
	<SubTexture name="right press0014" x="587" y="466" width="148" height="151"/>
	<SubTexture name="right press0015" x="587" y="466" width="148" height="151"/>
	<SubTexture name="right press0016" x="587" y="466" width="148" height="151"/>
	<SubTexture name="right press0017" x="587" y="466" width="148" height="151"/>
	<SubTexture name="right press0018" x="587" y="466" width="148" height="151"/>
	<SubTexture name="right press0019" x="587" y="466" width="148" height="151"/>
	<SubTexture name="right press0020" x="587" y="466" width="148" height="151"/>
	<SubTexture name="right press0021" x="587" y="466" width="148" height="151"/>
	<SubTexture name="right press0022" x="587" y="466" width="148" height="151"/>
	<SubTexture name="right press0023" x="587" y="466" width="148" height="151"/>
	<SubTexture name="right press0024" x="587" y="466" width="148" height="151"/>
	<SubTexture name="right press0025" x="587" y="466" width="148" height="151"/>
	<SubTexture name="right press0026" x="587" y="466" width="148" height="151"/>
	<SubTexture name="up confirm0000" x="735" y="466" width="236" height="232"/>
	<SubTexture name="up confirm0001" x="971" y="466" width="236" height="232"/>
	<SubTexture name="up confirm0002" x="1207" y="466" width="214" height="211" frameX="-11" frameY="-10" frameWidth="236" frameHeight="232"/>
	<SubTexture name="up confirm0003" x="1207" y="466" width="214" height="211" frameX="-11" frameY="-10" frameWidth="236" frameHeight="232"/>
	<SubTexture name="up press0000" x="1421" y="466" width="144" height="141" frameX="-5" frameY="-4" frameWidth="153" frameHeight="150"/>
	<SubTexture name="up press0001" x="1421" y="466" width="144" height="141" frameX="-5" frameY="-4" frameWidth="153" frameHeight="150"/>
	<SubTexture name="up press0002" x="1565" y="466" width="153" height="150"/>
	<SubTexture name="up press0003" x="1565" y="466" width="153" height="150"/>
</TextureAtlas>

**Comment by G4merz** [comment]
ignore XML CONTENT ok

**Comment by NK-523** [comment]
It seems to be calling on only the down note sprite for all of your sprites.

**Comment by NK-523** [comment]
check the .xml, the borders for the sprite animations may all have the same parameters as the down note. (from my note sprites based off of the NOTES_assets sprite sheet) x="10" y="255" width="157" height="154

**Comment by NK-523** [comment]
also check your code in notes.hx

**Comment by G4merz** [comment]
the code in note.hx is okay
ill check the xml

**Comment by G4merz** [comment]
default:
				     var daPath:String = 'NOTE_assets';
				     switch(noteStyle){
					    case 'danger':
						      daPath = 'NOTE_danger';
					    default:
						      daPath = 'NOTE_assets';
					}

					frames = Paths.getSparrowAtlas(daPath);

**Comment by G4merz** [comment]
the line "default" is on line 164

**Comment by G4merz** [comment]
i checked the xml and it is ok

**Comment by NK-523** [comment]
![ALL_deathnotes](https://user-images.githubusercontent.com/77185327/132104235-afdf9e33-d167-455b-8cf0-3d7a68247b97.png)
this is the type of note your danger notes are replacing.

**Comment by NK-523** [comment]
judging by how it instantly kills you

**Comment by G4merz** [comment]
yes it is

**Comment by G4merz** [comment]
![NOTE_danger](https://user-images.githubusercontent.com/86385054/132104265-084ef072-6249-4e95-aa94-c21535cde2f3.png)
have this new spritesheet

XML CONTENT:
<?xml version="1.0" encoding="utf-8"?>
<TextureAtlas imagePath="FNOTE_assets.png">
	
	
	<SubTexture name="blue0000" x="0" y="0" width="134" height="148"/>
	<SubTexture name="blue hold end0000" x="134" y="0" width="50" height="64"/>
	<SubTexture name="blue hold piece0000" x="184" y="0" width="50" height="44"/>
	<SubTexture name="green0000" x="234" y="0" width="134" height="149"/>
	<SubTexture name="green hold end0000" x="368" y="0" width="50" height="64"/>
	<SubTexture name="green hold piece0000" x="418" y="0" width="50" height="44"/>
	<SubTexture name="pruple end hold0000" x="0" y="149" width="50" height="64"/>
	<SubTexture name="purple0000" x="50" y="149" width="149" height="134"/>
	<SubTexture name="purple hold piece0000" x="199" y="149" width="50" height="44"/>
	<SubTexture name="red0000" x="249" y="149" width="149" height="134"/>
	<SubTexture name="red hold end0000" x="398" y="149" width="50" height="64"/>
	<SubTexture name="red hold piece0000" x="448" y="149" width="50" height="44"/>
</TextureAtlas>

**Comment by G4merz** [comment]
why i cant send xml content

**Comment by G4merz** [comment]
<?xml version="1.0" encoding="utf-8"?>
<TextureAtlas imagePath="FNOTE_assets.png">
	
	
	<SubTexture name="blue0000" x="0" y="0" width="134" height="148"/>
	<SubTexture name="blue hold end0000" x="134" y="0" width="50" height="64"/>
	<SubTexture name="blue hold piece0000" x="184" y="0" width="50" height="44"/>
	<SubTexture name="green0000" x="234" y="0" width="134" height="149"/>
	<SubTexture name="green hold end0000" x="368" y="0" width="50" height="64"/>
	<SubTexture name="green hold piece0000" x="418" y="0" width="50" height="44"/>
	<SubTexture name="pruple end hold0000" x="0" y="149" width="50" height="64"/>
	<SubTexture name="purple0000" x="50" y="149" width="149" height="134"/>
	<SubTexture name="purple hold piece0000" x="199" y="149" width="50" height="44"/>
	<SubTexture name="red0000" x="249" y="149" width="149" height="134"/>
	<SubTexture name="red hold end0000" x="398" y="149" width="50" height="64"/>
	<SubTexture name="red hold piece0000" x="448" y="149" width="50" height="44"/>
</TextureAtlas>

**Comment by G4merz** [comment]
see

**Comment by G4merz** [comment]
/*
<?xml version="1.0" encoding="utf-8"?>
<TextureAtlas imagePath="FNOTE_assets.png">
	
	
	<SubTexture name="blue0000" x="0" y="0" width="134" height="148"/>
	<SubTexture name="blue hold end0000" x="134" y="0" width="50" height="64"/>
	<SubTexture name="blue hold piece0000" x="184" y="0" width="50" height="44"/>
	<SubTexture name="green0000" x="234" y="0" width="134" height="149"/>
	<SubTexture name="green hold end0000" x="368" y="0" width="50" height="64"/>
	<SubTexture name="green hold piece0000" x="418" y="0" width="50" height="44"/>
	<SubTexture name="pruple end hold0000" x="0" y="149" width="50" height="64"/>
	<SubTexture name="purple0000" x="50" y="149" width="149" height="134"/>
	<SubTexture name="purple hold piece0000" x="199" y="149" width="50" height="44"/>
	<SubTexture name="red0000" x="249" y="149" width="149" height="134"/>
	<SubTexture name="red hold end0000" x="398" y="149" width="50" height="64"/>
	<SubTexture name="red hold piece0000" x="448" y="149" width="50" height="44"/>
</TextureAtlas>
*/

**Comment by G4merz** [comment]
ok i cant post it here

**Comment by G4merz** [comment]
[NOTE_danger.txt](https://github.com/KadeDev/Kade-Engine/files/7110300/NOTE_danger.txt)

**Comment by G4merz** [comment]
ez

**Comment by NK-523** [comment]
Its not giving a null object reference, and the .xml and notes.hx are fine, so I think it is just calling on the wrong sprites. Do you know where the code that tells the game where the .png is in notes.hx?

**Comment by NK-523** [comment]
should look something like this `frames = Paths.getSparrowAtlas('note sprite name');`.

**Comment by G4merz** [comment]
in notes.hx it has 2 lines similar with this
the prints:
![imagem_2021-09-04_152510](https://user-images.githubusercontent.com/86385054/132104549-d5e423c8-e623-4175-86a0-829ad8edeb6e.png)
![imagem_2021-09-04_152535](https://user-images.githubusercontent.com/86385054/132104556-82375deb-d78c-4815-87df-e706e10e73ee.png)
first image is in else statement for "if(inCharter)" and second dont

**Comment by G4merz** [comment]
![imagem_2021-09-04_152752](https://user-images.githubusercontent.com/86385054/132104590-c4993864-3671-413a-9352-a2815881f80b.png)
here

**Comment by NK-523** [comment]
my note code 
case 'cusnotename':
frames = Paths.getSparrowAtlas('cus_notes');
for (i in 0...4)
animation.addByPrefix(dataColor[i] + 'Scroll', dataColor[i] + ' alone'); // Normal notes
animation.addByPrefix(dataColor[i] + 'hold', dataColor[i] + ' hold'); // Hold
animation.addByPrefix(dataColor[i] + 'holdend', dataColor[i] + ' tail'); // Tails

**Comment by G4merz** [comment]
what?

**Comment by G4merz** [comment]
can you send a print of the code because i didnt understand

**Comment by G4merz** [comment]
thanks, ill try that

**Comment by G4merz** [comment]
![image](https://user-images.githubusercontent.com/86385054/132104862-d3b4ee96-7c28-4a6b-a2a1-42d304428a45.png)
something like this?

**Comment by G4merz** [comment]
i fixed the "for (blablabla)" ok

**Comment by NK-523** [comment]
If your note .png is in preload/images. 

what we're doing is making a note style so we can debug, make sure its not the .xml

**Comment by NK-523** [comment]
then if its not, we can test a few more things.

**Comment by G4merz** [comment]
the note.png is on shared/images

**Comment by NK-523** [comment]
oh and this is the full thing
![image](https://user-images.githubusercontent.com/77185327/132105142-eb5a2422-fc2e-4ac8-a2b5-0d5c759899f8.png)

**Comment by G4merz** [comment]
a

**Comment by NK-523** [comment]
I'm currently testing something that may help

**Comment by G4merz** [comment]
didnt work

**Comment by Ninjakaiden523** [comment]
can you not find the note style?

**Comment by G4merz** [comment]
no the notes loaded in-game as normal notes

**Comment by NK-523** [comment]
remove that thing of code, I'm working on a solution that may work

**Comment by G4merz** [comment]
ok

**Comment by NK-523** [comment]
this is a kind of rushed sprite sheet. back up your current NOTE_danger .png and .xml just in case. Not sure if this will work though.
![NOTE_danger](https://user-images.githubusercontent.com/77185327/132105728-a39b1639-f4fa-496b-8aa1-af3dfede440c.png)

**Comment by NK-523** [comment]
have to upload the .xml to google drive

**Comment by G4merz** [comment]
ok

**Comment by G4merz** [comment]
what do i do with it?

**Comment by G4merz** [comment]
also, i need a thing that might be fast to do but idk how

**Comment by G4merz** [comment]
there is an noteStyle indicator at charting menu and i need it to display the current note style (0 for normal, 1 for danger
![image](https://user-images.githubusercontent.com/86385054/132105918-0db74991-d696-4b8b-ae3d-a7b1126e2157.png)
![image](https://user-images.githubusercontent.com/86385054/132105925-9ea65169-5306-4878-aaf9-ad504a2c0bc6.png)

**Comment by NK-523** [comment]
https://drive.google.com/file/d/1CVL8d4fhccpy4v72ZJYV39FE8vkkNyiP/view?usp=sharing .xml

**Comment by NK-523** [comment]
just move your current danger note's .png and .xml and put those two in place of them

**Comment by NK-523** [comment]
and remove the code I had you put into notes.hx earlier

**Comment by G4merz** [comment]
![image](https://user-images.githubusercontent.com/86385054/132106149-416a4d6b-2fbe-48b2-85e0-cb143058a981.png)
so it should look like this?

**Comment by NK-523** [comment]
should look the exact same as when you first posted this issue.

**Comment by G4merz** [comment]
its correct then

**Comment by G4merz** [comment]
what do i do now?

**Comment by G4merz** [comment]
now the notes are gray

**Comment by Ninjakaiden523** [comment]
if everything is the same as it was before, your old note sprite sheet and .xml moved and the one I put together and its .xml put where your note sprite sheet and .xml were, run the game and test the song.

**Comment by NK-523** [comment]
ok

**Comment by NK-523** [comment]
are they different arrows

**Comment by G4merz** [comment]
no, only down gray notes

**Comment by NK-523** [comment]
try putting this under the default note code
if(burning){
					if (daStage == 'urstage')
					{
						frames = Paths.getSparrowAtlas('NOTE_danger');
						animation.addByPrefix('greenScroll', 'arrowUP');
						animation.addByPrefix('redScroll', 'arrowRIGHT');
						animation.addByPrefix('blueScroll', 'arrowDOWN');
						animation.addByPrefix('purpleScroll', 'arrowLEFT');
						x -= 165;

**Comment by NK-523** [comment]
like this 
![image](https://user-images.githubusercontent.com/77185327/132106677-845cea2b-9e3d-42c9-b388-52375c6a2ff7.png)

**Comment by G4merz** [comment]
ok

**Comment by G4merz** [comment]
![image](https://user-images.githubusercontent.com/86385054/132106740-1767422d-b784-4ede-8efb-9e0801ac1249.png)

**Comment by NK-523** [comment]
I'm not positive if placement matters.

**Comment by NK-523** [comment]
if you build the game, don't forget the -debug at the end, could be giving you error messages.

**Comment by G4merz** [comment]
![image](https://user-images.githubusercontent.com/86385054/132106830-7b97a9c9-64d6-4553-bb9b-1984e92e18aa.png)
wat

**Comment by G4merz** [comment]
time to fix brackets >:(

**Comment by G4merz** [comment]
![image](https://user-images.githubusercontent.com/86385054/132106853-7841df54-ee8a-4db9-aa2d-416980f7ecdc.png)
hmm

**Comment by G4merz** [comment]
what do i put on "if()"?

**Comment by NK-523** [comment]
burning

add this to the top `	public var burning:Bool = false;` with all the other public variables.

**Comment by G4merz** [comment]
ok

**Comment by G4merz** [comment]
so, first of all, it says
[WARNING] No animation called "blueScroll"
[WARNING] No animation called "greenScroll"
[WARNING] No animation called "redScroll"
[WARNING] No animation called "purpleScroll"

second, the notes didn't change, its also gray down notes

third, sorry for causing you all that trouble master chief from famous microsoft videogame franchise halo

**Comment by NK-523** [comment]
did you back up your old .xml?

**Comment by G4merz** [comment]
yes

**Comment by NK-523** [comment]
If we put that in there we can tell if its just missing the animations

**Comment by G4merz** [comment]
ok

**Comment by NK-523** [comment]
were you using a -debug build before?

**Comment by G4merz** [comment]
yes

**Comment by NK-523** [comment]
ok, remove all of these from the if(burning) code
blueScroll
greenScroll
redScroll
purpleScroll

**Comment by G4merz** [comment]
ok

**Comment by G4merz** [comment]
removed

**Comment by NK-523** [comment]
![image](https://user-images.githubusercontent.com/77185327/132107409-9e61eeb9-f9cd-4505-b3c9-3195092dd2aa.png)
add this in too, just in case

**Comment by G4merz** [comment]
what line?

**Comment by NK-523** [comment]
![image](https://user-images.githubusercontent.com/77185327/132107590-d38f948d-3a3e-4788-ac27-5193b49224f5.png)

**Comment by G4merz** [comment]
thx

**Comment by G4merz** [comment]
now what?

**Comment by NK-523** [comment]
you've made a way to add the gimick notes via the editor is that how you added them into the song?

**Comment by G4merz** [comment]
yes

**Comment by NK-523** [comment]
try compiling the game.

**Comment by G4merz** [comment]
compiled, what now?

**Comment by NK-523** [comment]
play it

**Comment by G4merz** [comment]
nothing different, notes are still down

**Comment by NK-523** [comment]
I've ported the assets and .xml into vs tricky, and as you were describing 
![image](https://user-images.githubusercontent.com/77185327/132108091-a8b2d048-9f1f-4f03-b1b6-e51cecc49e20.png)

**Comment by NK-523** [comment]
so its not something wrong with any .hx files

**Comment by G4merz** [comment]
probably

**Comment by G4merz** [comment]
try to port this sprites

**Comment by G4merz** [comment]
![NOTE_danger](https://user-images.githubusercontent.com/86385054/132108182-538623f0-c6cc-478c-9ea6-00d6870f319e.png)
[NOTE_danger.txt](https://github.com/KadeDev/Kade-Engine/files/7110528/NOTE_danger.txt)
convert the txt to xml

**Comment by NK-523** [comment]
![image](https://user-images.githubusercontent.com/77185327/132108352-b1445650-cf00-4060-8549-304583966be2.png)
exact same thing at the exact same point in the exact same place mind you, the fire notes should be in the middle of the two up notes.

**Comment by NK-523** [comment]
her is what i think is happening, look at the image how the black part arrows seemingly move around.
![NOTE_fire](https://user-images.githubusercontent.com/77185327/132108392-58797a68-b025-40cc-b5f0-f1254c5b21dc.png)
I think you need to make your arrows do the same.

**Comment by G4merz** [comment]
wait lemme export tricky notes to see whats the problem

**Comment by G4merz** [comment]
wait lemme export tricky notes to see whats the problem

**Comment by NK-523** [comment]
I think that was what the "arrow scroll" meant.

**Comment by G4merz** [comment]
sorry for taking too long
i tried to put tricky notes into my mod and its still only the down notes

**Comment by NK-523** [comment]
did you try expurgation's notes too?

**Comment by G4merz** [comment]
yes and they are even worse

**Comment by G4merz** [comment]
their offsets isnt right

**Comment by NK-523** [comment]
try moving all the code I told you to add to a .txt and use the code you had before, see how the fire notes act then.

**Comment by G4merz** [comment]
but im using the same code i was using before

**Comment by NK-523** [comment]
try adding just this 
                               if(burning){
					if (daStage == 'auditorHell')
					{
						frames = Paths.getSparrowAtlas('fourth/mech/ALL_deathnotes', "clown");
						animation.addByPrefix('greenScroll', 'Green Arrow');
						animation.addByPrefix('redScroll', 'Red Arrow');
						animation.addByPrefix('blueScroll', 'Blue Arrow');
						animation.addByPrefix('purpleScroll', 'Purple Arrow');
						x -= 165;
					}
					else
					{
						frames = Paths.getSparrowAtlas('NOTE_fire', "clown");
						if(!FlxG.save.data.downscroll){
							animation.addByPrefix('blueScroll', 'blue fire');
							animation.addByPrefix('greenScroll', 'green fire');
						}
						else{
							animation.addByPrefix('greenScroll', 'blue fire');
							animation.addByPrefix('blueScroll', 'green fire');
						}
						animation.addByPrefix('redScroll', 'red fire');
						animation.addByPrefix('purpleScroll', 'purple fire');

						if(FlxG.save.data.downscroll)
						flipY = true;

						x -= 50;
					}
				}
![image](https://user-images.githubusercontent.com/77185327/132109419-bd3c580d-7cfd-4368-9543-9cf334d0301b.png)
Image for reference

**Comment by G4merz** [comment]
GUESS WHAT
didnt work too

**Comment by G4merz** [comment]
can you send tricky Note.hx?

**Comment by NK-523** [comment]
do be warned, this is a older kade engine.
[notes.txt](https://github.com/KadeDev/Kade-Engine/files/7110614/notes.txt)

**Comment by G4merz** [comment]
i know

**Comment by G4merz** [comment]
i didnt find anything new tho
