### ISSUE TITLE
Bug Report: mods cant be put be in the kade engine because its not a zip or rar 

### ISSUE THREAD

**Issue by Mayro64** [KadeArchive/Kade-Engine#214]
i use winrar to use all the mods and to use fnf ad stuff but when i try to add mods it only can put it in zip or rar idk what to do

**Comment by theDetourist** [comment]
Elaborate, what are you trying to do exactly? And what have you done to get to this point?

**Comment by Kade-github** [comment]
This is not an issue. This is a [discussion](https://github.com/KadeDev/Kade-Engine/discussions)
