### ISSUE TITLE
(fixed)cant add a custom character, even with sprites, xml, code, and icons. would appreciate some help.

### ISSUE THREAD

**Issue by luigi-budd** [KadeArchive/Kade-Engine#2144]
im trying to make a mod with kade engine, but the things i suspect that are halting my progression are the offset and icon files. i have no idea how to make these work, ive tried making the files "joeOffsets.txt" and "icon-joe" respectively, but they still wont work!

**Comment by KlutchDj** [comment]
who is joe ?

**Comment by NK-523** [comment]
do you have code in the characters.hx file and have your character added into the characterlist.txt

**Comment by Reycko** [comment]
> who is joe ?

That is not serious, If you want to comment something then try to help the user

**Comment by luigi-budd** [comment]
> do you have code in the characters.hx file and have your character added into the characterlist.txt

yes, i believe ive done all the correct steps for adding in a character, making the code, sprite sheet, and icon, but i still dont know why it wont work
![image](https://user-images.githubusercontent.com/90123055/132132732-aa8f944e-a74f-408c-9f57-5e9ca45f9e03.png)
![image](https://user-images.githubusercontent.com/90123055/132132756-423475f6-5ff9-458c-b07d-3db297ec632e.png)

**Comment by NK-523** [comment]
what about characterslist.txt in assets/preload/data?

**Comment by NK-523** [comment]
add "joe" to the bottom. If you haven't already.

**Comment by NK-523** [comment]
> yes, i believe ive done all the correct steps for adding in a character, making the code, sprite sheet, and icon, but i still dont know why it wont work

 ok, check the .xml for spelling mistakes. such as capitalization, or labeling down up, so on.

**Comment by NK-523** [comment]
and make sure the name for the .png is **THEjoe**, and you seem to be missing a line of code here 
![image](https://user-images.githubusercontent.com/77185327/132134369-59d4a207-d9da-44d1-998e-570d16a46011.png)

`loadOffsetFile(curCharacter);`  should go right above `playanim('dance right');`

![image](https://user-images.githubusercontent.com/77185327/132134401-9eb9a8fd-804c-4609-b954-dcc3dca5538b.png)

if you need a offset file then copy dad's and edit it in game by pressing 6 in a -debug build.

**Comment by luigi-budd** [comment]
> and make sure the name for the .png is **THEjoe**, and you seem to be missing a line of code here
> ![image](https://user-images.githubusercontent.com/77185327/132134369-59d4a207-d9da-44d1-998e-570d16a46011.png)
> 
> `loadOffsetFile(curCharacter);` should go right above `playanim('dance right');`
> 
> ![image](https://user-images.githubusercontent.com/77185327/132134401-9eb9a8fd-804c-4609-b954-dcc3dca5538b.png)
> 
> if you need a offset file then copy dad's and edit it in game by pressing 6 in a -debug build.

thanks for the help! i really appreciate it. but i cant seem to load him up. ive followed what youve said, i added the line of code and the offset file, but it shows an error message saying, "Null object reference". i believe its the icons that im having trouble with.

**Comment by NK-523** [comment]
"NULL object refence" means its trying to load something that doesn't exist, so check your .xml and every other .png to make sure if its a sprite there is a .xml with it.

**Comment by luigi-budd** [comment]
> "NULL object refence" means its trying to load something that doesn't exist, so check your .xml and every other .png to make sure if its a sprite there is a .xml with it.
ive checked all sprite sheets and they all have xml files with them, but i still have no idea why i cant load joe up

**Comment by NK-523** [comment]
do you have a song?

**Comment by luigi-budd** [comment]
> do you have a song?

no, ive been trying to load him in bopeebo, do i have to have a song to load him in?

**Comment by NK-523** [comment]
Not really, it is one reason why it would give a null object reference. Check your .xml (if you haven't) spelling mistakes can cause crashes.

**Comment by NK-523** [comment]
also to test your icon go to freeplaysonglist.txt and change this `Bopeebo:dad:1` to this `Bopeebo:joe:1`.

**Comment by NK-523** [comment]
I just realized something, does you character's .png or .xml name have any capitalized letters in it?

**Comment by NK-523** [comment]
because I don't think you can have capitalized letters in the .png or .xml names

**Comment by NK-523** [comment]
the stuff in the .xml is fine, you can have capitalized letters in there, but not the file names.

**Comment by luigi-budd** [comment]
> I just realized something, does you character's .png or .xml name have any capitalized letters in it?

no, i have all of my joe files in lowercase 
![image](https://user-images.githubusercontent.com/90123055/132145199-27286c04-6201-414a-b48c-4ebef9e6f7d3.png)
![image](https://user-images.githubusercontent.com/90123055/132145215-06a319a3-bfe0-49ab-8dcd-d6975abbd871.png)
and it turns out, the icon is the one that is crashing my game
![image](https://user-images.githubusercontent.com/90123055/132145349-da7194af-f088-4d49-b52a-0e19783c3692.png)

**Comment by NK-523** [comment]
your code from the characters.hx code has the name a "THEjoe" that's why your getting a null object reference its trying to load an image and xml that doesn't exist, also make sure your icon is named icon-joe.

**Comment by lunarcleint** [comment]
skill issue :/

**Comment by luigi-budd** [comment]
> your code from the characters.hx code has the name a "THEjoe" that's why your getting a null object reference its trying to load an image and xml that doesn't exist, also make sure your icon is named icon-joe.

ive already renamed the files to "joe.png" and "joe.xml" and "joe" in the character.hx,
![image](https://user-images.githubusercontent.com/90123055/132162987-e5903512-1491-4d21-bad9-e4f6f8b63aa3.png)
![image](https://user-images.githubusercontent.com/90123055/132162996-934055fa-49fe-4653-9ce0-33e043f0b3ed.png)
![image](https://user-images.githubusercontent.com/90123055/132163030-be4ab936-14bf-4299-8a8f-39e66cf4cb39.png)

but even then it **still** crashes.

*i think i have a skill issue :/*

**Comment by Ninjakaiden523** [comment]
wait, did you use gf as a base for your character.hx code?

**Comment by NK-523** [comment]
Did you use GF as a base for your characters.hx code

**Comment by NK-523** [comment]
try using dad's instead 
case 'dad':
				tex = Paths.getSparrowAtlas('DADDY_DEAREST','shared',true);
				frames = tex;
				animation.addByPrefix('idle', 'Dad idle dance', 24, false);
				animation.addByPrefix('singUP', 'Dad Sing Note UP', 24, false);
				animation.addByPrefix('singRIGHT', 'Dad Sing Note RIGHT', 24, false);
				animation.addByPrefix('singDOWN', 'Dad Sing Note DOWN', 24, false);
				animation.addByPrefix('singLEFT', 'Dad Sing Note LEFT', 24, false);

loadOffsetFile(curCharacter);

playAnim('idle');

just replace all of the "dad" with "joe"

**Comment by luigi-budd** [comment]
fixed it, turns out the icons were the wrong dimensions, had to be 300x150 :/
