### ISSUE TITLE
Enhancement: Cut Newgrounds Code Out

### ISSUE THREAD

**Issue by EliteMasterEric** [KadeArchive/Kade-Engine#2148]
Does Newgrounds allow uploading FnF mods?

If so, we should make a guide on how to do that. I researched and found no mods on there.

If not, we should cut out the dead code and remove the library dependency.

**Comment by KlutchDj** [comment]
Newgrounds does not allow modifications of FNF on newgrounds as it is against their rules.

**Comment by EliteMasterEric** [comment]
Resolved by #2183 and #2205.
