### ISSUE TITLE
is it possible to easily customize the background?

### ISSUE THREAD

**Issue by Rysik5318** [KadeArchive/Kade-Engine#2156]
I have a question, is it possible to somehow correctly put the background, as is done with the Characters.

**Comment by isakube** [comment]
AS IS DONE WITH THE PERSIANS GSGJFSDHFGJHKSDFJHDFSJHDFJHFDSHJGSDHGJFJGHFDGHJDDSJGKFHJ

**Comment by Rysik5318** [comment]
> AS IS DONE WITH THE PERSIANS GSGJFSDHFGJHKSDFJHDFSJHDFJHFDSHJGSDHGJFJGHFDGHJDDSJGKFHJ

Oh, sorry about my English. Lmao
