### ISSUE TITLE
Enhancement: Implement Lix

### ISSUE THREAD

**Issue by EliteMasterEric** [KadeArchive/Kade-Engine#2158]
lix is an easy-to-use package manager for Haxe: https://github.com/lix-pm/lix.client

lix is a package manager that makes it easy for you to track dependencies used in your Haxe project, and to make sure everyone always has the right versions when they build your app.

Once implemented, the build steps for new users will be significantly improved. Instead of having users run 20 different commands, they can just run

```
lix install
```

and it will install all the Haxe libraries the user needs.

If configured properly, we might even be able to stop the constant and annoying reports about people who forgot to build `extension-webm`.

**Comment by isakube** [comment]
this issue built like a Reddit ad

**Comment by EliteMasterEric** [comment]
lol sorry

once i get my workspace recovered i'm going to work on implementing all these suggestions myself but github doesn't let you assign issues, even to yourself, unless you have push rights for the repo

**Comment by EliteMasterEric** [comment]
I have this as WIP but it's pending on lix-pm/haxeshim#72 to allow running `lix lime rebuild extension-webm <platform>`
