### ISSUE TITLE
I can't seem to find how to open the actual game itself

### ISSUE THREAD

**Issue by TreePlays** [KadeArchive/Kade-Engine#216]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## Please describe your issue. Provide extensive detail and images if possible.

**Comment by theDetourist** [comment]
What is the issue?

**Comment by R-code-0** [comment]
Maybe you need to build game firstly?

**Comment by Kade-github** [comment]
This is not an issue. This is a [discussion](https://github.com/KadeDev/Kade-Engine/discussions)
