### ISSUE TITLE
Bug Report: Install links please

### ISSUE THREAD

**Issue by ZayanPlayz** [KadeArchive/Kade-Engine#2160]
I really need the install links of these. please do not ask anything like do it yourself its because I installed but some error is coming just please give me the install inks
![image](https://user-images.githubusercontent.com/78526458/132176478-56c53748-40d8-467d-9e28-2ac3fe68bc47.png)
BOTH OF THESE PLEASE

**Comment by napstaa967** [comment]
download the visual studio community installer then go to the individual components tab and select both of those

link:
https://visualstudio.microsoft.com/downloads/

**Comment by ZayanPlayz** [comment]
And How do I install MSVC z64 Build tools?

**Comment by napstaa967** [comment]
> And How do I install MSVC z64 Build tools?

go to the individual components tab, click the search box, and search for it

**Comment by ZayanPlayz** [comment]
alr thanks
