### ISSUE TITLE
Removing the game version verification system, lol

### ISSUE THREAD

**Issue by Rysik5318** [KadeArchive/Kade-Engine#2161]
Insert in TitleState.hx, line 309
(You can delete OutdatedSubState.hx)
Code:
```
			new FlxTimer().start(2, function(tmr:FlxTimer)
			{
				FlxG.switchState(new MainMenuState());
			});
			// FlxG.sound.play(Paths.music('titleShoot'), 0.7);
		}

		if (pressedEnter && !skippedIntro && initialized)
		{
			skipIntro();
		}

		super.update(elapsed);
	}

**Comment by isakube** [comment]
we use that for new versions of kade

**Comment by Rysik5318** [comment]
> we use that for new versions of kade

No, I used it in version 1.5.2. Tomorrow I'll see what's new in the new version and add the code for the new version here
