### ISSUE TITLE
"E:/Haxe ToolKit/haxe/lib/extension-webm/git/ndll/Windows64/extension-webm.ndll" does not exist

### ISSUE THREAD

**Issue by Uveltt** [KadeArchive/Kade-Engine#2162]
Kade Engine Version : 1.7

I am getting an error that when I try to run the "lime test windows" to see if the mod test will work, I keep getting this error : 

Error: Source path "E:/Haxe ToolKit/haxe/lib/extension-webm/git/ndll/Windows64/extension-webm.ndll" does not exist

![ErrorScreenshot](https://user-images.githubusercontent.com/68277748/132237181-0dee3907-619e-42c0-be5b-dcf9ff27e638.png)

There is also another error/problem
When I run "lime rebuild extension-webm windows"
I get this : 

E:\Haxe ToolKit\haxe\lib\extension-webm\git\project>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

**Comment by G4merz** [comment]
check if you installed visual studio dependecies right
and check if Haxe version is 4.1.5 because other versions may cause trouble

**Comment by nahiassis** [comment]
* MSVC v142 - VS 2019 C++ x64/x86 build tools
* Windows SDK (10.0.17763.0)
* C++ Profiling tools
* C++ CMake tools for windows
* C++ ATL for v142 build tools (x86 & x64)
* C++ MFC for v142 build tools (x86 & x64)
* C++/CLI support for v142 build tools (14.21)
* C++ Modules for v142 build tools (x64/x86)
* Clang Compiler for Windows
* Windows 10 SDK (10.0.17134.0)
* Windows 10 SDK (10.0.16299.0)
* MSVC v141 - VS 2017 C++ x64/x86 build tools
* MSVC v140 - VS 2015 C++ build tools (v14.00)

you forgot to install some of those

the building.md is kinda wrong but
here are all of the libs you need to install

**Comment by notmagniill** [comment]
first write on cmd `haxelib install actuate` then run `lime rebuild extension-webm windows` or something

**Comment by notmagniill** [comment]
> first write on cmd `haxelib install actuate` then run `lime rebuild extension-webm windows` or something

if you cannot then try seeing the older comments i made on other issues

**Comment by Uveltt** [comment]
@nintendofan44 where do i install those?

**Comment by Uveltt** [comment]
@Magniill i already have those installed.

**Comment by Generalisk** [comment]
> first write on cmd `haxelib install actuate` then run `lime rebuild extension-webm windows` or something

That fixed it for me. Thanks

**Comment by Uveltt** [comment]
@nintendofan44, a bit late to comment this, but it worked thanks for helping me 🙂
