### ISSUE TITLE
Bug Report: Error with lime test windows

### ISSUE THREAD

**Issue by Ruben3023** [KadeArchive/Kade-Engine#2166]
when i try lime test windows it says

source/Discord.hx:5: characters 8-30 : Type not found : discord_rpc.DiscordRpc
source/WebmHandler.hx:12: characters 18-28 : Type not found : WebmPlayer

**Comment by chlebeczeq** [comment]
i can fix the first one
haxelib git discord-rcp https://github.com/discord/discord-rpc
but the i have webm handler one and i cant fix it
