### ISSUE TITLE
Bug Report: error with lime test windows

### ISSUE THREAD

**Issue by Villena211** [KadeArchive/Kade-Engine#2167]
i was trying to build the games but i have this error:

C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/DiffOverview.hx:65: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/PlayState.hx:389: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:\Users\my user\Desktop\Kade-Engine-1.6\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

can some help me plz?

**Comment by notmagniill** [comment]
reinstall visual studio 2019 with using building.md at docs folder by kadedev
