### ISSUE TITLE
Bug Report: Cant build.

### ISSUE THREAD

**Issue by keseruthegod** [KadeArchive/Kade-Engine#217]
Installed everything.

source/PlayState.hx: 1234: characters 15-29 : You cannot access the sys package while targeting js (for sys.FileSystem)

**Comment by theDetourist** [comment]
Welp, there's another feature not compatible with HTML5 again.

I'll take a look at it, in the meantime, try to build for Desktop instead.

**Comment by Kade-github** [comment]
Should be fixed :)
