### ISSUE TITLE
Help!!! I am using Kade Engine 1.5.2 and it keeps giving me this error? I uninstalled all the haxelib libraries and reinstalled them and the error keeps showing up!! "obj\msvc19-arm64-nc\70e38311_Context3DElementType.obj : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'ARM64'" 

### ISSUE THREAD

**Issue by StickDeveloper** [KadeArchive/Kade-Engine#2170]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by nahiassis** [comment]
i think you installed the wrong versions of the visual studio 2019 libraries
or you installed msvc x64 on an arm64 device
or an arm64 on an x64

**Comment by nahiassis** [comment]
msvc19-arm64
yep

you have the wrong version of msvc

install the x64 one

**Comment by nahiassis** [comment]
* **MSVC v142 - VS 2019 C++ x64/x86 build tools**
you installed the arm64 version of this

**Comment by StickDeveloper** [comment]
So then how do I get the x64 version of this?

**Comment by Justine101213k** [comment]
i think u use this lime config HXCPP_ARM64 true dont use that you will get error

**Comment by StickDeveloper** [comment]
Yes, but how do get the x64 version of it.

**Comment by Justine101213k** [comment]
its bug

**Comment by ghost** [comment]
Try removing and reinstalling Visual studio

**Comment by ghost** [comment]
Are you using an ARM pc?

**Comment by Justine101213k** [comment]
no

**Comment by VICK-sys** [comment]
> 
> #### Please check for duplicates, similar issues or closed issues with the same problem, as well performing simple troubleshooting steps (such as deleting the export folder if it's an issue with compiling, reinstalling Kade Engine) before submitting an issue.
> ### If you are playing a downloaded version of the game, what operating system are you using?
> 
> Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
> ## What version of the game are you using? Look in the bottom left corner of the main menu.
> ## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
> ## Please describe your issue. Provide extensive detail and images if possible.

check what I commented here https://github.com/KadeDev/Kade-Engine/issues/1761#issuecomment-917443782 It'll probably fix your fatal error issue

**Comment by VICK-sys** [comment]
Also, make sure you have the correct individual components for Visual Studio. I'll list them below:
    ***MSVC v142 - VS 2019 C++ x64/x86 build tools***
    ***Windows SDK (10.0.17763.0)***

Other than that, you should be good to compile the game.
