### ISSUE TITLE
Bug Report: i am trying to run my mod on mac but i cant run the project.xml

### ISSUE THREAD

**Issue by CoolDoctorAidan** [KadeArchive/Kade-Engine#2171]
So on lime i cannot run my project because the source path in lime how do you change your source path? (in lime ofc)

**Comment by notmagniill** [comment]
can you suggest a picture??? i don't really understand your question.

Regards,
Magniill

**Comment by CoolDoctorAidan** [comment]
So i can build and everything now but the application is damaged and btw in
using 1.5.2 on Mac OSX
