### ISSUE TITLE
Enhancement: Modchart Events

### ISSUE THREAD

**Issue by FirneHHH** [KadeArchive/Kade-Engine#2172]
So with the new Events in charts, I think it'd be easier to make Modcharts with a new type called "Modchart Event" or something. When it's position is reached in the song, if it has a modchart then 'event' will be called with an argument equal to the event value.

How it might be able to work:

Chart.json
```json
"eventObjects": [
  {
    "name": "Name",
    "position": 0,
    "value": "Event in modchart.lua",
    "type": "Modchart Event"
  }
]
```

Modchart.lua
```lua
-- Any time an event is called, this function will be too
function event(name) -- The arg "name" would be equivalent to the event value
  if name == "Event in modchart.lua" then
    boyfriend:playAnim('hey')
  end
end
```

Oh yeah and make the animated lua sprite available?

**Comment by isakube** [comment]
goond
