### ISSUE TITLE
Bug Report: Could Not Find Haxelib "Extension" Does It Need To Be Installed?

### ISSUE THREAD

**Issue by Luwunaaa** [KadeArchive/Kade-Engine#2173]
![image](https://user-images.githubusercontent.com/90228032/132271292-22b05450-abe1-4ab9-b3ea-7442d6644ff5.png)
Hello!
I am having this problem when i try to lime build friday night funkin. 
i havent found any fixes on this, could some help?
Thanks.

**Comment by isakube** [comment]
extension-webm

**Comment by Luwunaaa** [comment]
> extension-webm
what do you mean? do i need to install it?

**Comment by Justine101213k** [comment]
installl extension-webm

haxelib install actaue
haxelib git extension-webm https://github.com/GrowtopiaFli/extension-webm
lime rebuild extension-webm [windows, linux, 'macOS]

**Comment by Luwunaaa** [comment]
> installl extension-webm
> 
> haxelib install actaue
> haxelib git extension-webm https://github.com/GrowtopiaFli/extension-webm
> lime rebuild extension-webm [windows, linux, 'macOS]

thanks!

**Comment by Luwunaaa** [comment]
> installl extension-webm
> 
> haxelib install actaue
> haxelib git extension-webm https://github.com/GrowtopiaFli/extension-webm
> lime rebuild extension-webm [windows, linux, 'macOS]

its giving me this error now. any help? 
![image](https://user-images.githubusercontent.com/90228032/132790641-54ec081b-923d-496b-a561-e21483617569.png)

**Comment by somefnfplayerlol** [comment]
no, wrong repository!
do this command:
`haxelib git extension-webm https://github.com/KadeDev/extension-webm`

**Comment by notmagniill** [comment]
> no, wrong repository!
> do this command:
> `haxelib git extension-webm https://github.com/KadeDev/extension-webm`

yes that is the correct code, the GrowtopiaFli is for .WEBM videos and KadeDev is for the game
justin you dumbass
