### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by Neptune-Sky** [KadeArchive/Kade-Engine#2175]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

windows x64

## What version of the game are you using? Look in the bottom left corner of the main menu.

0.2.7.1

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

Happens on any song on default settings.

## Please describe your issue. Provide extensive detail and images if possible.

Note movement is very choppy and looks like you are playing on 20 fps with random frame drops even though my machine is overpowered and the fps counter stays at 144. Tried on a 60hz display and same issue, except it stayed on 60 and appeared to be worse.

**Comment by KlutchDj** [comment]
thats because the notes are stuck on 60 frames for some reason. Kade dev doesnt experience it because he has a 60hz monitor

**Comment by Neptune-Sky** [comment]
> thats because the notes are stuck on 60 frames for some reason. Kade dev doesnt experience it because he has a 60hz monitor

That's not the issue, the issue is that the framerate of the arrows looks like 20fps with random lag spikes on 144hz _and_ 60hz. I tried it on both kinds of monitors. Also, are they really? because I noticed they are significantly smoother than 60hz on 144hz in previous versions of kade engine.

**Comment by Neptune-Sky** [comment]
Solved by restarting my pc and opening the game again, idk what was wrong
