### ISSUE TITLE
Bug Report: FPS drop in settings menu, version 1.4.7 and above.

### ISSUE THREAD

**Issue by salexsystem** [KadeArchive/Kade-Engine#2176]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Windows 10, 64-bit
Intel Core i7 9700F
NVIDIA GeForce 1060 Super

## What version of the game are you using? Look in the bottom left corner of the main menu.

All versions from 1.4.7 to 1.7 is affected by the same issue.

## Please describe your issue. Provide extensive detail and images if possible.

The settings menu, except for the keybinding menu, is locked to 10 fps.
This persists with many versions of kade engine, including modded versions.
https://imgur.com/a/rstSjIS

**Comment by isakube** [comment]
the fuck 1.4.7

**Comment by NukeThief** [comment]
tre fuck is ke 1.4.7

**Comment by EliteMasterEric** [comment]
they probably tested a wide range of versions to diagnose the issue
if it doesn't happen in 1.4.6 and does in 1.4.7 that's where the issue was added

**Comment by salexsystem** [comment]
whoops i meant 1.4.2
