### ISSUE TITLE
game crashing when hovering over a custom song 

### ISSUE THREAD

**Issue by Generalisk** [KadeArchive/Kade-Engine#2179]
Hi, I am working on a mod but when i hover over my custom song in freeplay mode the game just crashes for no reason. i have yet to recieve the art for the opponent and level so i used monster and the default stage and yet it crashes while previewing it in the freeplay menu. i then added that offset that i saw on every song but then it will just freeze when opening the freeplay menu. any solutions?

**Comment by NK-523** [comment]
check the .JSON make sure the song name in there is the exact same as the name in freeplaysonglist.txt, this one got me too.

**Comment by Uveltt** [comment]
i am having an issue like this but when I try to change my character from dad or others to the custom character i made.

**Comment by NK-523** [comment]
Make sure everything in the Characters.hx and your character's .XML are spelt right.

> i am having an issue like this but when I try to change my character from dad or others to the custom character i made.

**Comment by NK-523** [comment]
like this for the characters.hx
case 'char':
				tex = Paths.getSparrowAtlas('char.png's name','shared',true);
				frames = tex;
				animation.addByPrefix('idle', '.xml idle animation name', 24, false);
				animation.addByPrefix('singUP', '.xml up animation name', 24, false);
				animation.addByPrefix('singRIGHT', '.xml right animation name', 24, false);
				animation.addByPrefix('singDOWN', '.xml down animation name', 24, false);
				animation.addByPrefix('singLEFT', '.xml left animation name', 24, false);
