### ISSUE TITLE
How can I remove the outdated engine version screen?

### ISSUE THREAD

**Issue by Uveltt** [KadeArchive/Kade-Engine#2180]
I am using a older version of Kade Engine (1.5.2) since it works best for me but I keep getting this screen after the "Click enter to begin" screen, how can I remove this?

https://imgur.com/a/WyCe9an

**Comment by napstaa967** [comment]
> I am using a older version of Kade Engine (1.5.2) since it works best for me but I keep getting this screen after the "Click enter to begin" screen, how can I remove this?
> 
> https://imgur.com/a/WyCe9an

go to titlestate.hx
```hx
if (!MainMenuState.kadeEngineVer.contains(returnedData[0].trim()) && !OutdatedSubState.leftState)
					{
						trace('outdated lmao! ' + returnedData[0] + ' != ' + MainMenuState.kadeEngineVer);
						OutdatedSubState.needVer = returnedData[0];
						OutdatedSubState.currChanges = returnedData[1];
						FlxG.switchState(new OutdatedSubState());
						clean();
					}
```

remove "FlxG.switchState(new OutdatedSubState());"

**Comment by Uveltt** [comment]
@napstaa967, it worked ty
