### ISSUE TITLE
Where did the executable go?

### ISSUE THREAD

**Issue by Superdude4800** [KadeArchive/Kade-Engine#2182]
how come kade engine doesn't come with the exe file anymore i kinda needed that to actually make it function

**Comment by Superdude4800** [comment]
![image](https://user-images.githubusercontent.com/90289723/132420856-fd2a3aef-0cf6-4b29-a2e5-f0d27797db85.png)

this is what a freshly downloaded kade engine looks like, notice how the exe and icon files are missing?
not only that, i downloaded it like a week or two ago and it came with the exe file that time, what gives?

**Comment by lespylol** [comment]
uhhh, this is the game's source code

**Comment by lespylol** [comment]
to download the game you have to press the "K.E.1.7-SomeFixes.7z" button
![Captura de tela 2021-09-07 204331](https://user-images.githubusercontent.com/90264286/132423933-7c836f55-c348-41d8-818e-c55b5f3e7d34.png)

**Comment by PalanSecpw** [comment]
lmao
