### ISSUE TITLE
Bug Report: Crashes every time i select my song in freeplay

### ISSUE THREAD

**Issue by BlankDev16** [KadeArchive/Kade-Engine#2184]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Windows x64

## What version of the game are you using? Look in the bottom left corner of the main menu.

Kade Engine 1.5.2

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

1. Create a new song
2. Make a character
3. Finish charting the song
4. Go into freeplay
5. Select the song and hit enter to play it
6. Shit happens
7. ??????

## Please describe your issue. Provide extensive detail and images if possible.

Okay, so i added a new song to kade engine and every time i go to freplay and select it, it shows a black screen and crashes. No error logs, no messages, only a black screen and then it closes. I'm desperate.

Here's a complete log of my post-"lime test windows" in cmd
![image](https://user-images.githubusercontent.com/87280771/132427886-edb3a8e5-cc34-42fa-a031-c1b577634db1.png)

**Comment by BlankDev16** [comment]
ok i need some sleep if someone replies to this issue i will be in school ty for your comprehension bye aaa

**Comment by Ninjakaiden523** [comment]
https://github.com/KadeDev/Kade-Engine/issues/2118 I had the same problem here, check your songs name in the .JSON

**Comment by NK-523** [comment]
can you give me what you put into freeplaylist.txt

**Comment by BlankDev16** [comment]
Tutorial:gf:1
Bopeebo:dad:1
Fresh:dad:1
Dad Battle:dad:1
Spookeez:spooky:2
South:spooky:2
Monster:monster:2
Pico:pico:3
Philly Nice:pico:3
Blammed:pico:3
Satin Panties:mom:4
High:mom:4
Milf:mom:4
Cocoa:parents-christmas:5
Eggnog:parents-christmas:5
Winter Horrorland:monster-christmas:5
Senpai:senpai:6
Roses:senpai:6
Thorns:spirit:6
Underground:frisk:7

that's everything

**Comment by NK-523** [comment]
check characters.hx and your .xml, make sure everything is spelt right, also compile to a debug mode by putting -debug at the end of the command line.
