### ISSUE TITLE
Botplay BF notes are killed way too early

### ISSUE THREAD

**Issue by i-winxd** [KadeArchive/Kade-Engine#2187]
Version: KE 1.7.1 prerelease as of September 4th, 2021
Windows 10 64bit, very good computer (64GB ram, 3.70GHz processor)

## Botplay notes disappear way too early in botplay. This can easily be compared to the CPU's notes.
https://user-images.githubusercontent.com/31808925/132553242-2bc6b3ad-c858-4d32-b808-09857b5249d5.mp4

Note the reduced accuracy score:
![image](https://user-images.githubusercontent.com/31808925/132553390-a5d914b2-9ebb-4eed-b137-a6ef0a54bfe5.png)

This bug report aims to document this bug in a more visible way. The only way botplay can be perfected is to make the game think that BF is a CPU player.

**Comment by EliteMasterEric** [comment]
Off-topic: Is that Pokemon Mystery Dungeon music?

**Comment by somefnfplayerlol** [comment]
this is due to botplay checking whether the note is in the sick zone:
```
notes.forEachAlive(function(daNote:Note)
{
	var diff = -(daNote.strumTime - Conductor.songPosition);
	daNote.rating = Ratings.judgeNote(diff);
	diff /= songMultiplier;
		if (daNote.mustPress && daNote.rating == "sick" || (diff > 0 && daNote.mustPress))
```
look at the if condition

**Comment by EliteMasterEric** [comment]
Okay, I can confirm the issue myself.

By modifying the code to calculate and display note timings even when bot mode is enabled, we get this:

![Screenshot (2)](https://user-images.githubusercontent.com/4635334/132747061-a59b5b25-9da9-47c9-9738-7484b25761fc.png)

The bot consistently hits notes 41 ms early. Will do more analysis.

**Comment by EliteMasterEric** [comment]
I made a pull request that resolves the issue. Due to frame rate/update timings, the bot doesn't always hit exactly at 0ms but it gets within +/- 5 ms or so now.
