### ISSUE TITLE
custom difficulties not working

### ISSUE THREAD

**Issue by AnonymousSergal** [KadeArchive/Kade-Engine#2188]
Kade Engine 1.5 onwards has an issue where custom difficulties default back to normal mode when you enter the song. 

(song should not look like this)
![image](https://user-images.githubusercontent.com/51002790/132565301-01720d43-27d7-460a-9e25-e5b5d47d20b9.png)

(song should look like this on custom difficulty)
![image](https://user-images.githubusercontent.com/51002790/132565529-c1e3f6d1-e968-4a68-ae6c-1a40be16a7e0.png)

**Comment by prokube** [comment]
issue with ResultsScreen. look for "F2" in the search bar, and add your difficulty suffix as a clause in the if-else

**Comment by AnonymousSergal** [comment]
it was in HighScore.hx, but still, thank you. don't know why kade put it in
there tbh, but whatever.
