### ISSUE TITLE
Bug Report: Crashing and sometimes freezing my PC

### ISSUE THREAD

**Issue by DennisAnabones** [KadeArchive/Kade-Engine#219]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86_64`), Linux, or macOS? Specify below. Windows 10 64bit

## What version of the game are you using? Look in the bottom left corner of the main menu. 
Kade Engine 1.4 64bit

## Have you identified any steps to reproduce the bug? 
Each time I open a Kade Engine mod, also the original Kade Engine.

**Comment by Kade-github** [comment]
Specs?

**Comment by DennisAnabones** [comment]
AMD Radeon RX 580
AMD Ryzen 5 2600
16GB ram
1 TB SSD

**Comment by DennisAnabones** [comment]
FIxed by updating to 20h2
