### ISSUE TITLE
(Kade Engine 1.7) Background not loading because a "bitmap asset with an ID of '...' was not found"

### ISSUE THREAD

**Issue by Mystiff** [KadeArchive/Kade-Engine#2193]
So, I think the title is pretty self explanatory, but im having an issue where the backgrounds I made arent loading in the custom song. The song loads with a black background and nothing else. Its probably an issue with the code I put it; I used the week 5 bg for a base to work off of. Does anyone know how to fix this? Im on 1.7 btw
<img width="704" alt="Issue ss 3" src="https://user-images.githubusercontent.com/90362133/132604965-e048d8ba-b948-4607-8856-8fcaefca0caa.png">
<img width="941" alt="Issue ss 1" src="https://user-images.githubusercontent.com/90362133/132604701-94d53e83-9e21-4ed4-a198-519ae087c33e.png">
<img width="330" alt="Issue ss 2" src="https://user-images.githubusercontent.com/90362133/132604804-bb019b20-f2b0-43a9-940a-c49b6c8cd6a9.png">

**Comment by prokube** [comment]
unrelated but dude funny mod idea

i forgot to relearn stage creation for 1.7 so i cant really help lol
try basing it off week 1 instead, week 5 is fancier bc of the bops

**Comment by isakube** [comment]
put your stage images in shared and just do that instead

**Comment by Mystiff** [comment]
> put your stage images in shared and just do that instead

That worked, thanks!

**Comment by isakube** [comment]
close
