### ISSUE TITLE
Bug Report: Safe Frames don't actually change the judgements.

### ISSUE THREAD

**Issue by blackm1n** [KadeArchive/Kade-Engine#2195]
NEW VERSION OF BUG REPORT

I thought to myself maybe it was the Zardy's mod that somehow messed with the judgement system. It sounded ridiculous to me but I tried anyway. After trying I noticed something strange. The judgements don't change at all. You can still hit a 39 ms Sick on 5 Safe Frames. Heck you can hit a **26** ms Sick on 1 SF! (you have 16 ms total hit in 1 direction on 1 SF. **IT DOESN'T EVEN MAKE SENSE HOW I HIT A 26 MS SICK**). Not only did Zardy mod funked with the Safe Frame feature, but I also found another bug! Kade, please fix, this game is unplayable.

[https://www.youtube.com/watch?v=X2WzdL324S0](https://www.youtube.com/watch?v=X2WzdL324S0)

OLD VERSION OF BUG REPORT, WHEN NOT TESTED ON ORIGINAL KE V1.7

Was playing 5 Safe Frames Bushwhack. Noticed that I had hit all Sicks. Yet had over 200 combo breaks. all caused by hitting a Shit. That kinda confused me, as where are the Greats and Bads. Sick is the highest rating, while Shit is the worst rating. Went on Foolhardy to test. -22 ms - Sick, 23 ms - Shit. from 23 ms it was supposed to be a Great! Greats on 5 Safe Frames have 45 ms range in both ways. Anywhere from 23 to 45 it should have be a Great. But apparently it isn't. Even recorded a video as a proof.

[https://www.youtube.com/watch?v=OZMAMben2oU](https://www.youtube.com/watch?v=OZMAMben2oU)

**Comment by Spel0** [comment]
Kade still didn't add safe frames fix in zardy repo, fml

**Comment by blackm1n** [comment]
both versions seem to be fucked up though. unless there's a commit that fixes safe frames in normal KE.

**Comment by ScrubRTA** [comment]
"you have 16 ms total hit in 1 direction on 1 SF"
4.5 ms actually. 16 ms is somewhere between 3 and 4 SF

**Comment by blackm1n** [comment]
4.5 for Sick only. 16 if you include all the other judgements. But you can hit a 26 ms Sick on 1 SF. It should be like literally impossible to hit a 26 ms smth on 1 SF.

**Comment by somefnfplayerlol** [comment]
i made an attempt for fixing the safe frames
https://github.com/KadeDev/Kade-Engine/pull/2194/commits/cb95133b9a8633a17cb8e1e5938c1a360ff9824c

**Comment by Kade-github** [comment]
it already does that???
![image](https://user-images.githubusercontent.com/26305836/132795161-42854613-f1fa-456c-ba3e-f0c9e29662a2.png)

**Comment by blackm1n** [comment]
The judgement issue is still not fixed though? Downloaded latest development version - 14 ms Sick on 1 SF which should be impossible, as that would be a Shit.

The master release fixed it actually. Why is it not in the latest developmet I do not understand.

**Comment by Spel0** [comment]
> it already does that???

Kade, we're talking about safe frames bug which we talked in Twitter DMs about, it's still not in Zardy repo
