### ISSUE TITLE
Bug Report: Charting Issue

### ISSUE THREAD

**Issue by tgotkgortkhorjthojo** [KadeArchive/Kade-Engine#2199]
When I press space in the charting area it crashes the game

**Comment by EliteMasterEric** [comment]
I can't seem to reproduce this. Is it only occurring on a specific song? Please provide more details so we can diagnose.

Double check the song's voice and music tracks match up (in terms of length), I had a crash at one point that was caused by that.

**Comment by ghost** [comment]
what version of kade engine
