### ISSUE TITLE
Bug Report: Invalid Character in Playstate file 

### ISSUE THREAD

**Issue by BoxOfGolds** [KadeArchive/Kade-Engine#2208]
Hi! Just wanted to say that whenever I try to test the window for my mod, an error comes up in the "Playstate" file saying "Invalid Character 0x01" and I can't get rid of it, no matter what I do. I'm assuming it's this but if anyone can help, that'll be greatly [appreciated.
![The one thing causing me trouble](https://user-images.githubusercontent.com/90431413/132785198-f2264a7c-7f67-4f5c-b1bc-a0a6d66f7dbf.PNG)

**Comment by Burger-Gaming** [comment]
I don't think thats a bug for KE, that's a bug for HaxeDevelop if you're using that

**Comment by isakube** [comment]
well uhh it's a Start Of Header. that shit generally goes at the START of the HEADER. where all the Cool Info™ is. not the end of the file. lmao what is this
