### ISSUE TITLE
can't add character in state on ke 1.7

### ISSUE THREAD

**Issue by loogchin** [KadeArchive/Kade-Engine#2209]
can't add character in state on ke 1.7
I'm trying to add a character to the state. to fix the delay after changing the character 
But it can't.
![image](https://user-images.githubusercontent.com/87599145/132813877-322bd02c-fccc-43b8-bed3-183edec30475.png)

**Comment by Justine101213k** [comment]
wrong not in stage.hx
go in PlayState
