### ISSUE TITLE
Bug Report: Cant find export folder

### ISSUE THREAD

**Issue by unknownfnfmodder** [KadeArchive/Kade-Engine#221]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
I'm not playing a downloaded version
## What version of the game are you using? Look in the bottom left corner of the main menu.
I cant find the game, that's the bug
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
I've tried everything but nothing works
## Please describe your issue. Provide extensive detail and images if possible.
well you see usually In mod videos there's an export folder but when i download this the folder isn't there

**Comment by R-code-0** [comment]
Export is for export build artifacts and build product.
You need to compile game.

**Comment by ACardboardBox1** [comment]
You need to run cd (directory) then lime test html5, mac, or windows -debug for a export folder to appear.

**Comment by Kade-github** [comment]
This is not an issue. This is a [discussion](https://github.com/KadeDev/Kade-Engine/discussions)

**Comment by unknownfnfmodder** [comment]
yeah im just a dumbass sorry
