### ISSUE TITLE
The amount of memory and CPU Kade Engine consumes can get out of control real quick

### ISSUE THREAD

**Issue by EmpyreumCode** [KadeArchive/Kade-Engine#2211]
I've had some issues with Kade Engine running slower than usual, so today I decided to check for what was happening a few times. I ended up finding out the engine itself was taking quite a bit of CPU and Memory from my PC. 

![unknown](https://user-images.githubusercontent.com/75784856/132854443-7a5e538c-dd89-4224-bfa3-24aabf746427.png)
![unknown (3)](https://user-images.githubusercontent.com/75784856/132854472-e7fb610a-b20a-4c6a-b173-0ffdaf9c4d2f.png)
![unknown (1)](https://user-images.githubusercontent.com/75784856/132854960-143c16ea-0249-4b38-92d8-375b65ebdac2.png)
![unknown (2)](https://user-images.githubusercontent.com/75784856/132855303-06420d82-daaf-4397-8167-a9eb5fe6fece.png)

Mostly seems to happen when assets are loading, on the title screen and on specific situations, then yet again when choosing a week, this can happen for a second:
![unknown (4)](https://user-images.githubusercontent.com/75784856/132855660-08c9ebe0-844b-4355-8348-f8bbe73569f9.png)

Though that's not even the most worrying thing. The average performance while playing a full week is the one shown in the following picture. Note that this was taken while running THE TUTORIAL WEEK.
![unknown (5)](https://user-images.githubusercontent.com/75784856/132855911-c4b115b9-2144-490d-ab79-90a93e357571.png)

KE sure has potential to be the best out of them all, but all of its features cause it to be poorly optimized. It's quite literally one of the only things it's missing as of now. Thanks for checking out on this.

EDIT: Right after finishing a week you're left with this on the title screen:
![unknown (6)](https://user-images.githubusercontent.com/75784856/132856771-ddd810fe-93c9-44d5-8e1f-74b268829db7.png)

**Comment by Kade-github** [comment]
I fail to see how 1gb of memory is a lot of memory.

this is memory that an average game instance uses on vanilla as well (probably more honestly)
also with 1.8 it should be minimized
