### ISSUE TITLE
Bug Report: Games keeps crashing whenever playing a custom song

### ISSUE THREAD

**Issue by tofu111456** [KadeArchive/Kade-Engine#2214]
(i use 1.4.2 and i use windows 10)

so whenever i try to play a custom song thats fully charted and with all the inst and voices in the correct folders, the game just crashes, i also made sure every single name of the xml and the path is correct, and it is. anyone knows why and how to fix this?

**Comment by NK-523** [comment]
Check the character, (if you have a custom one) the song name in the .JSON make sure it lines up with the song name in freeplaylist.txt and the folder holding the Inst a voices.

**Comment by tofu111456** [comment]
> 
> 
> Check the character, (if you have a custom one) the song name in the .JSON make sure it lines up with the song name in freeplaylist.txt and the folder holding the Inst a voices.

all of it is correct

**Comment by tofu111456** [comment]
ok you know what switching versions if its still breaking ill tell again
