### ISSUE TITLE
Enhancement: like guitar hero and osu if you miss a sustain note it doesn't keep damaging you

### ISSUE THREAD

**Issue by DeceptedPar** [KadeArchive/Kade-Engine#2215]
## What is your suggestion, and why should it be implemented?
like guitar hero and osu if you miss a sustain note it doesn't keep damaging you like nearly version of fnf does
reason why I want this being added in is it'd fit more with how rythm games handle sustain notes

**Comment by NK-523** [comment]
I think in 1.7 (maybe earlier) they changed it to where you get damaged one or two times then the note grays out.
