### ISSUE TITLE
Bug Report: Difficulty icons not showing in story mode

### ISSUE THREAD

**Issue by OtisSchwarze** [KadeArchive/Kade-Engine#2217]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Im using Windows (`x86_64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.7 Kade Engine

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
![grafik](https://user-images.githubusercontent.com/65111975/132872972-f0490d45-e781-4140-9757-1929e90e343d.png)

## Please describe your issue. Provide extensive detail and images if possible.
in the story mode menu no difficulty icons are showing

**Comment by NK-523** [comment]
Did you try to add a custom difficulty?

**Comment by NK-523** [comment]
Can I see you campaign_menu_UI_assets in /assets/images.

**Comment by OtisSchwarze** [comment]
> 
> 
> Can I see you campaign_menu_UI_assets in /assets/images.

![grafik](https://user-images.githubusercontent.com/65111975/132956676-63fd995c-8942-48ad-a251-8320781ba0b2.png)

**Comment by NK-523** [comment]
does your .xml look like this 
![image](https://user-images.githubusercontent.com/77185327/133007953-8b253501-0477-490d-84fa-eeaaaead1c11.png)
