### ISSUE TITLE
Bug Report: cant compile kade engine.

### ISSUE THREAD

**Issue by prockscac** [KadeArchive/Kade-Engine#222]
On the newest update whenever I try and compile kade engine in terminal it keeps on saying " error: linker command failed with exit code 1 (use -v to see invocation)" . is there anyway on how to fix it?

**Comment by puyoxyz** [comment]
yay, people who can't read error messages

add `-verbose` to your build command and show us what it says (i.e. `lime build windows -verbose`)

**Comment by Jaduplex** [comment]
> yay, people who can't read error messages
> 
> add `-verbose` to your build command and show us what it says (i.e. `lime build windows -verbose`)

I actually didn't know lime had a verbose switch. thanks for letting me know! I'm obviously not the OP but still thanks

**Comment by prockscac** [comment]
now it says Error: Error while running command with no reason either.

**Comment by prockscac** [comment]
> yay, people who can't read error messages
> 
> add `-verbose` to your build command and show us what it says (i.e. `lime build windows -verbose`)
now it says Error: Error while running command with no reason .

**Comment by Kade-github** [comment]
this is a [discussion](https://github.com/KadeDev/Kade-Engine/discussions)
