### ISSUE TITLE
Enhancement: Press 7 in Freeplay menu while a song in selection to open that song straight into the editor...

### ISSUE THREAD

**Issue by JOELwindows7** [KadeArchive/Kade-Engine#2221]
## What is your suggestion, and why should it be implemented?
rather than have to play the song first then press 7.

It's simple. When you have to go to editor, you must play a song first. **AND** since this 1.7, you have to wait for countdown to finish in order for `7` key to work, because now entering the editor goes to the position where the song at.

Now how about, just pecking straight to editor in free play menu? Yes! simply go to freeplay menu, select a song but don't play it. instead just press `7` immediately **to go straight to editor immediately, skipping playing the song first** or other respective button (such as open character debug which debugs character according to the song JSON data).

**Comment by NK-523** [comment]
This would save me a lot of time charting.

**Comment by RagdollClash** [comment]
This is already in the latest master build of Kade Engine

**Comment by JOELwindows7** [comment]
> This is already in the latest master build of Kade Engine

Cool and good. amazing awesome!!!
uh btw, which commit was it?

yeah just close it by the next release.

**Comment by RagdollClash** [comment]
it was PR #2087

**Comment by JOELwindows7** [comment]
> it was PR #2087

cool and good thancc for info. Will close when new version release (merge to stable)
