### ISSUE TITLE
kade dev should add these 

### ISSUE THREAD

**Issue by foxcool119** [KadeArchive/Kade-Engine#2224]

**Comment by foxcool119** [comment]
![image](https://user-images.githubusercontent.com/89747510/132944713-19527287-4277-4580-ab3f-63c4088f6734.png)
 i wish kade dev add this on kade engine its cool tho

**Comment by TheKitBoi** [comment]
That idea is week 7 so they ain't gonna do that

**Comment by NotSorena** [comment]
development for kade engine is cancelled
