### ISSUE TITLE
Enhancement: 

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#2225]
## What is your suggestion, and why should it be implemented?

Event named 'Player 2 Change'
Lua modcharts on Mac

**Comment by isakube** [comment]
> Event named 'Player 2 Change'

being PRed by someone not you
> Lua modcharts on Mac

man i wish
> Online server (i can host it)

for what

**Comment by LevitoDev** [comment]
the third prokube was my mind but i realized i DO NOT HAVE A DOMAIN LOL

**Comment by LevitoDev** [comment]
I mean Online server (i can host it)
