### ISSUE TITLE
stuck

### ISSUE THREAD

**Issue by yeahyeahyeahss** [KadeArchive/Kade-Engine#2231]
it keeps saying 

source/WebmHandler.hx:32: characters 10-26 : Not enough arguments, expected io:webm.WebmIo, soundEnabled:Bool
source/WebmHandler.hx:33: characters 8-12 : webm.WebmPlayer has no field fuck
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/WebmHandler.hx:96: characters 8-21 : webm.WebmPlayer has no field changePlaying
source/WebmHandler.hx:102: characters 8-21 : webm.WebmPlayer has no field changePlaying
source/WebmHandler.hx:53: characters 8-12 : webm.WebmPlayer has no field fuck
source/WebmHandler.hx:119: characters 8-19 : webm.WebmPlayer has no field removePause

**Comment by yeahyeahyeahss** [comment]
help

**Comment by somefnfplayerlol** [comment]
do in order:
`haxelib remove extension-webm`
`haxelib git extension-webm https://github.com/KadeDev/extension-webm`
`lime rebuild extension-webm`
