### ISSUE TITLE
Bug Report: Arrow keys don't work in the HTML version

### ISSUE THREAD

**Issue by D3MONSLAY3R101** [KadeArchive/Kade-Engine#2240]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.6.2
## Please describe your issue. Provide extensive detail and images if possible.
The arrow keys don't work in the HTML version for some reason. I played a mod ported into browser that uses an old version of Kade Engine and the arrow keys work on there. But here... nope the arrow keys don't work :(

**Comment by Kade-github** [comment]
this has been fixed for awhile
