### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by willboyz92nd** [KadeArchive/Kade-Engine#2241]
## 1 load up kade engine 1.7
      2 Add a custom song (code a new one or replace an already existing one)
      3  Press space to test the song (the song will start for a split second then crash)

## My game crashes when I press space on a custom song in the chart editor
yes i am using a ogg file

**Comment by NK-523** [comment]
Just a question: what do you mean "code" a new song? you don't have to code to get a new song in the game, save for stages, characters, and note styles.
