### ISSUE TITLE
Enhancement: Stage Positioning Debug (not the characters)

### ISSUE THREAD

**Issue by G4merz** [KadeArchive/Kade-Engine#2243]
#### Please check for duplicates or similar issues before creating this issue.
no
## What is your suggestion, and why should it be implemented?
there is already a stage positioning debug menu (avaiable in debug build) but its only for the characters, so a stage positioning for the actual stage elements (like floor, wall or some shit) would me awesome because set stage elements position SUCKS

**Comment by EliteMasterEric** [comment]
LOL this is already a thing, press Shift in the stage debugger to toggle between characters and objects.

**Comment by G4merz** [comment]
I DIDNT KNEW THAT HOLY SHIT
tanks

**Comment by G4merz** [comment]
i didnt find nobody saying that

**Comment by EliteMasterEric** [comment]
> 
> I DIDNT KNEW THAT HOLY SHIT
>

Pull request #2233 adds additional help text that explains this and more.
