### ISSUE TITLE
Bug Report: no idle animations playing + bg elements not playing too

### ISSUE THREAD

**Issue by G4merz** [KadeArchive/Kade-Engine#2245]
#### Please check for duplicates, similar issues or closed issues with the same problem, as well performing simple troubleshooting steps (such as deleting the export folder if it's an issue with compiling, reinstalling Kade Engine) before submitting an issue.

already did, didnt help me

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

windows x64

## What version of the game are you using? Look in the bottom left corner of the main menu.

KE 1.7

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

idk, i've just added the song as i added the first one

## Please describe your issue. Provide extensive detail and images if possible.

idle animations of both player and enemy not playing in the second week's song (song 1 is normal, song 2 is messed up) but if you load the song in freeplay it normally plays the animations. also i added second song exactly how i added the first

**Comment by G4merz** [comment]
IMPORTANT: camera dont move too, it stay fixed on boyfriend

**Comment by Luckyfishi** [comment]
Yeah I met the same issue...

**Comment by luigi-budd** [comment]
maybe try seeing if you have a BPM on the song's .json?

**Comment by Luckyfishi** [comment]
> maybe try seeing if you have a BPM on the song's .json?

Yeah all my .json files have BPMs in them, and only songs after the first song in story mode will have this issue, the first song works just fine. If you swap the play order of the first song(song A) and the second song(song B), it is still the second song(now is song A) that will go wrong, the first song(now is song B)works fine.

**Comment by Sesor33** [comment]
I'm having a similar issue. Loading the song in freeplay works just fine. Loading the first song of the week works just fine, but loading any subsequent songs in the week causes idle animations to not play, and the camera stays fixed on boyfriend.
