### ISSUE TITLE
Bug Report: Help

### ISSUE THREAD

**Issue by EcoVeni** [KadeArchive/Kade-Engine#2247]
do someone know how to fix game not going onto the main screen when you know where you click enter to play to get there i need to press enter to skip the opening cutscene that is not working also the gf dance sprite is just stuck unmoving there is no music at all and when i play a song the opponent can hit first notes but then the song just softlocks. Kade engine version: 1.4.2, Windows 64 bit. The game worked perfectly fine but in the project.xml i changed the file from "Kade Engine" to my mod name then the error accoured when i reversed the process the bug was still there i deleted the release folder but it didn't help also! Please help me with this.

**Comment by EliteMasterEric** [comment]
> Kade engine version: 1.4.2

Please use a newer version of Kade Engine, these issues are likely fixed there.

Links: **[GameBanana mod page](https://gamebanana.com/gamefiles/16761) ⋅ [play in browser](https://funkin.puyo.xyz) ⋅ [latest stable release](https://github.com/KadeDev/Kade-Engine/releases/latest) ⋅ [latest development build (windows)](https://ci.appveyor.com/project/KadeDev/kade-engine-windows/branch/master/artifacts) ⋅ [latest development build (macOS)](https://ci.appveyor.com/project/KadeDev/kade-engine-macos/branch/master/artifacts) ⋅ [latest development build (linux)](https://ci.appveyor.com/project/KadeDev/kade-engine-linux/branch/master/artifacts)**
