### ISSUE TITLE
when i do the command haxelib git extension-webm github.com/KadeDev/extension-webm it says  Error: Could not clone Git repository.

### ISSUE THREAD

**Issue by help-meplease** [KadeArchive/Kade-Engine#2248]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by help-meplease** [comment]
also i have 1.7

**Comment by G4merz** [comment]
you sure you have haxe 4.1.5, git and lime installed? git and lime should be up to date too

**Comment by EliteMasterEric** [comment]
Does the error say anything else? `Could not clone Git repository` isn't enough info for us to help. Could you paste the logs?
