### ISSUE TITLE
Bug Report: Why is the Copy Last feature in the editor not there in recent releases like 1.7?

### ISSUE THREAD

**Issue by TheBeast9417** [KadeArchive/Kade-Engine#2249]
I was recharting a song in Kade Engine 1.7, when I noticed the Copy Last feature to recopy sections wasn't in the editor. So why is it not there?

The version of the executable was normal Windows 64-bit.

As stated before, this issue is only present in versions with the new charting system.

Going to Section Data (which is where Copy Last is in other versions) or Note Data shows no trace of the feature either.

**Comment by G4merz** [comment]
i think they added CTRL+C CTRL+V support

**Comment by EliteMasterEric** [comment]
@TheBeast94YT In Kade Engine v1.7, there is a Copy and Paste feature. One of the PRs in development includes better in-game documentation for this.

In the meantime, here are the steps to do it:

* Hold the Control key and drag the mouse to select one or more notes.
* Hold the Control key and press C to copy the selected notes.
* Scroll to the section of the song where you want to paste (the gray song position line should be where you want the first note to be).
* Hold the Control key and press V to paste the notes you copied previously.

Hope this helps!

**Comment by TheBeast9417** [comment]
@MasterEric i feel stupid now

**Comment by EliteMasterEric** [comment]
> @MasterEric i feel stupid now

Don't feel stupid, without #2233 you would have no way of knowing about it. I made an issue asking about adding Stage Props to the Stage Debug view until someone replied the feature already existed.
