### ISSUE TITLE
Bug Report: Where is Lua state

### ISSUE THREAD

**Issue by HumanKR** [KadeArchive/Kade-Engine#227]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows (`x86_64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.4.2

## Please describe your issue. Provide extensive detail and images if possible.
There is some problem on PlayState
![image](https://user-images.githubusercontent.com/45139720/115036707-b62eb080-9f08-11eb-819e-33a9f1270564.png)
uh... where is Lua.hx?
or there is something another problem?
I can't build FNF cuz that problem.

**Comment by puyoxyz** [comment]
does the build actually fail or is vscode just showing errors cuz its dumb?

**Comment by HumanKR** [comment]
> does the build actually fail or is vscode just showing errors cuz its dumb?

actually fail. yea
I'm build with cmd but same problem about Lua codes

**Comment by Kade-github** [comment]
Did you follow the new build instructions? https://github.com/KadeDev/Kade-Engine/blob/master/BUILDING.md
`haxelib install linc_luajit`

**Comment by HumanKR** [comment]
> Did you follow the new build instructions? https://github.com/KadeDev/Kade-Engine/blob/master/BUILDING.md
> `haxelib install linc_luajit`

omg i wasn't know the build instructions updated.
so i install now and... is finally works!
thank for help!
and apologize my bad IQ
