### ISSUE TITLE
Bug Report: Compiling Issue

### ISSUE THREAD

**Issue by caserreal** [KadeArchive/Kade-Engine#228]
Everytime i try to Compile the game, I have this error message:
![image](https://user-images.githubusercontent.com/82672666/115064165-9a042280-9eba-11eb-86b9-5bbac01d1c6e.png)
I've downloaded everything i've needed, Including the 22gb of pain, but everytime it gives me this response.
Even before writing this, I've been looking at the closed issues on github but everything I've tried hasn't worked.

I have the most recent version of KadeEngine Github code, and FYI: This is my first time modding the game. 

Please let me know what I'm doing wrong if you have a solution!

**Comment by theDetourist** [comment]
There's a new version of the source code available, try that one and update us.

**Comment by caserreal** [comment]
> There's a new version of the source code available, try that one and update us.

I updated it, and i still have the same problem
![image](https://user-images.githubusercontent.com/82672666/115071365-2b2bc700-9ec4-11eb-99bd-0cdb36a3bf21.png)
Could it be something about the paths.hx ? It says "Unknown Identifier: paths " on the error message.
Also I made sure to install the new linc luajit and hxcpp debugger required for the new update

**Comment by theDetourist** [comment]
Don't know what your custom source code looks like but, try capitalizing ```paths```.

**Comment by Fefe543** [comment]
did you try replacing the character.hx file with the new one?

**Comment by caserreal** [comment]
I downloaded the new update so yes, I have the new character.hx file

**Comment by caserreal** [comment]
> Don't know what your custom source code looks like but, try capitalizing `paths`.

Sorry, I don't actually know what you mean by that; could you clarify?

**Comment by Kade-github** [comment]
Change paths to Paths

**Comment by caserreal** [comment]
nope, still didn't work

**Comment by theDetourist** [comment]
Show us that line (along with a couple others around it) from your ```Character.hx```.

**Comment by caserreal** [comment]
![image](https://user-images.githubusercontent.com/82672666/115076897-36362580-9ecb-11eb-82f7-9041035d4d70.png)
aight i had mine below the christmas-parents

**Comment by theDetourist** [comment]
Change the ```frames =```'s ```paths``` to ```Paths```, it's a class (and file inside the source folder) and has to be capitalized for its functions to work (such as _getSparrowAtlas_).

**Comment by caserreal** [comment]
also, Is the positions of animations and Offsets right?

**Comment by theDetourist** [comment]
Dunno, it's your code. Also, might as well move this to the [discussions page](https://github.com/KadeDev/Kade-Engine/discussions), since it's related to custom code.

**Comment by caserreal** [comment]
Hey! It worked! Thank you so much! I Just needed to make the Path capital!
