### ISSUE TITLE
Bug Report: Switching to my Custom character Crashes the Game

### ISSUE THREAD

**Issue by caserreal** [KadeArchive/Kade-Engine#231]
Now, I already submitted an issue earlier, but this shouldn't be as difficult. I have my Character sprite sheet, Xml file, and code in the characters.hx file, but when i try to test it in the debug menu, my game crashes. I shall provide My Character sprites, icon grid code, and a screenshot of my char.hx

![jan_sprites](https://user-images.githubusercontent.com/82672666/115084423-e2c9d480-9ed6-11eb-8b18-c6043b460e0f.png)
![image](https://user-images.githubusercontent.com/82672666/115084459-f37a4a80-9ed6-11eb-88ec-465a7135f2ac.png)
![image](https://user-images.githubusercontent.com/82672666/115084760-4f44d380-9ed7-11eb-91b4-dd6dace260bf.png)

If there's any solution you can recommend, please let me know as soon as possible!

**Comment by Kade-github** [comment]
p sure this is a [discussion](https://github.com/KadeDev/Kade-Engine/discussions)

**Comment by caserreal** [comment]
Oh sorry, I'll move this there
