### ISSUE TITLE
Bug Report: GF Randomly cheers on Philly.

### ISSUE THREAD

**Issue by SoffiMeower** [KadeArchive/Kade-Engine#239]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (64-Bit)

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.4.2

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Simply play Philly.

## Please describe your issue. Provide extensive detail and images if possible.
After playing for the first couple of lyrics, you'll see Girlfriend randomly cheer between every transition for a split second... Since this is never used in a song, this could make GF asset mods disappear. *Seen it disappear with the Moony over GF mod.*
![image](https://user-images.githubusercontent.com/45863583/115125605-461b3b80-9f97-11eb-8df2-91595c1aebe7.png)
Original assets randomly cheering ^
![image](https://user-images.githubusercontent.com/45863583/115125629-74991680-9f97-11eb-93ca-3fbee34bf6ed.png)
And why it can be an issue with custom assets ^

**Comment by theDetourist** [comment]
It's a feature that has been added recently and is hardcoded for the original songs based on the name of the song. To prevent that, you'll have to create a new week by recompiling the code.

**Comment by SoffiMeower** [comment]
_I don't agree with it being a feature but 'ight._

**Comment by theDetourist** [comment]
[Bruh](https://github.com/KadeDev/Kade-Engine/pull/132)...

Did you even play the latest vanilla Kade Engine builds?

**Comment by SoffiMeower** [comment]
@theDetourist Well calm down man, jeez! There's something called personal opinions! Don't have to be such a prick about it. And if I didn't play the latest vanilla Kade Engine, I sure wouldn't have made an issue for this!

**Comment by theDetourist** [comment]
I'm trying to understand what's happening to help you, I don't have a reason to be a "prick" lol

I asked if you played the vanilla version because if you did, you'd know that she doesn't "cheer at random", she cheers to the "Hey"s in the songs.

**Comment by SoffiMeower** [comment]
...Philly doesn't have any "Heys!" from what I've heard.

Edit: Just listened to Philly_Voices, no Heys in it.

**Comment by theDetourist** [comment]
["Hey's" @ Philly](https://www.youtube.com/watch?v=fwZ8jLFFL1Y): 0.02, 0.08, 0.13, etc...

**Comment by Kade-github** [comment]
> ...Philly doesn't have any "Heys!" from what I've heard.
> 
> Edit: Just listened to Philly_Voices, no Heys in it.

hey's are in the instrumental

edit liteartly this https://youtu.be/fwZ8jLFFL1Y?t=13

**Comment by Jaduplex** [comment]
Why isn't this closed? it's blatantly not an issue
