### ISSUE TITLE
Question: Debug crash errors

### ISSUE THREAD

**Issue by keseruthegod** [KadeArchive/Kade-Engine#240]
Is it possible to debug the error lines or something if my game crash?
Im trying to add a new character, done all the steps with the Character.hx + character.xml but still crashing.

**Comment by theDetourist** [comment]
Are you compiling the game? If you are, they should appear in the console.

If they don't, you'll have to ```trace()``` every step you made to add the character in your Character.hx to see where's it failing.

**Comment by keseruthegod** [comment]
Thank you for the fast response, i need to build the game with the 'lime test windows -debug' command or without the '-debug'?

**Comment by keseruthegod** [comment]
Error: 'Null Object Reference'

Called from hxcpp::__hxcpp_main
Called from ApplicationMain::main ApplicationMain.hx line 25
Called from ApplicationMain::create ApplicationMain.hx line 130
Called from lime.app.Application::exec lime/app/Application.hx line 150
Called from lime._internal.backend.native.NativeApplication::exec lime/_internal/backend/native/NativeApplication.hx line 146
Called from lime._internal.backend.native.NativeApplication::handleRenderEvent lime/_internal/backend/native/NativeApplication.hx line 370
Called from lime.app._Event_lime_graphics_RenderContext_Void::dispatch lime/_internal/macros/EventMacro.hx line 91
Called from openfl.display.Stage::__onLimeRender openfl/display/Stage.hx line 1950
Called from openfl.display.Stage::__broadcastEvent openfl/display/Stage.hx line 1166
Called from openfl.display.DisplayObject::__dispatch openfl/display/DisplayObject.hx line 1399
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 402
Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 551
Called from flixel.FlxGame::step flixel/FlxGame.hx line 677
Called from flixel.FlxGame::update flixel/FlxGame.hx line 747
Called from flixel.FlxState::tryUpdate flixel/FlxState.hx line 202
Called from PlayState::update PlayState.hx line 2257

**Comment by theDetourist** [comment]
How does your PlayState.hx looks like @ line 2257 and some lines before/after?

**Comment by keseruthegod** [comment]
![Untitled](https://user-images.githubusercontent.com/45968245/115126840-ecab1080-9f86-11eb-9209-6216b0054ab6.png)

**Comment by theDetourist** [comment]
1. Have you ever compiled the source code before?
2. Are you using the latest source code available?
3. (If yes to the last question) Can you post your PlayState.hx @ [Pastebin ](https://pastebin.com/) so we can see it properly?

**Comment by keseruthegod** [comment]
1. Yes
2. Yes
Im using the latest version, i already fixed the issue, i forget to add a healthbar icon for the custom character thats why it crashed in the healthbar line.
