### ISSUE TITLE
Add a Wiki for FAQ's and other utilities

### ISSUE THREAD

**Issue by theDetourist** [KadeArchive/Kade-Engine#241]
Since there's so many repeated questions with the same usual answers, might as well use that as one of the reasons to open a wiki for simplified access to FAQ's related to common problems with the engine, as well as a proper place for the ModChart documentation.

Also, with it, we could implement a section with streamlined methods of adding common things to the engine such as characters and weeks in a "official" way. This could make the process of troubleshooting faster and might also prevent more duplicated/easily fixable issues such as "why does the engine do that" when it was already fixed or "how to add this" when there's no "official" way of doing it with the latest source code (since it might change drastically every official release or nightly version).

**Comment by isakube** [comment]
yes

**Comment by puyoxyz** [comment]
+1

@KadeDev needs to enable the wiki feature though 

(also we could probably move BUILDING.md and ModCharts.md to the wiki)

**Comment by isakube** [comment]
actually i'm gonna convert the Pages environment into a wiki because rn it's just fnf's Pages environment

so uhh wish me luck??

**Comment by puyoxyz** [comment]
prokube wait no i was already working on that please no wait

**Comment by puyoxyz** [comment]
added in #428
