### ISSUE TITLE
Bug Report: freeplay menu

### ISSUE THREAD

**Issue by hatim237** [KadeArchive/Kade-Engine#244]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

 I'm on Windows (x86_64)

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.4.2
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
I put the (Duo Pack) mod on the game .
## Please describe your issue. Provide extensive detail and images if possible.
 It works great but, when I enter Freeplay I only see 
The Tutorial and Week 1.
![Friday Night Funkin' Kade Engine 18_04_21 01_11_09](https://user-images.githubusercontent.com/82734515/115128212-d59b0b80-9fe4-11eb-93d5-1f22609ea5a7.png)

**Comment by theDetourist** [comment]
Grab the [freeplaySongList.txt](https://github.com/KadeDev/Kade-Engine/blob/master/assets/preload/data/freeplaySonglist.txt) from the latest source code here and drop it on your game.

**Comment by Kade-github** [comment]
^
