### ISSUE TITLE
Enhancement: Remove code for tutorial camera panning and instead make it be a part of a default modchart for tutorial

### ISSUE THREAD

**Issue by Jaduplex** [KadeArchive/Kade-Engine#245]
## What is your suggestion, and why should it be implemented?
Unhardcoding it would allow for easier changing of it by modders and also porting of this camera panning to modded songs. Would also allow it to be removed for lower-end users that it might cause lag for.

**Comment by Kade-github** [comment]
[done](https://twitter.com/KadeDeveloper/status/1383812607212089360)
