### ISSUE TITLE
Bug Report: Not only settings, but progress also resets on 1.4.2

### ISSUE THREAD

**Issue by Freddie-06** [KadeArchive/Kade-Engine#247]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows 10, 64 bit

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
1) complete any song in freeplay on vanilla or Kade 1.4.1
2) Go into 1.4.2 and it will be gone

First time writing a bug report on Github, so no images, sorry

## Please describe your issue. Provide extensive detail and images if possible.

The progress is gone after 1.4.2
A simple fix would be, to write where progress is saved in Kade 1.4.1, so it can easily be recovered

Still no images

**Comment by Kade-github** [comment]
saves are located in `C:\Users\user\AppData\Roaming\ninjamuffin99\Kade Engine\ninjamuffin99` (where ever the fuck that is in other operating systems. and the default is `C:\Users\user\AppData\Roaming\ninjamuffin99\Funkin\ninjamuffin99`

Just copy over the Funkin.sol file into the new directory.

**Comment by Freddie-06** [comment]
> saves are located in `C:\Users\user\AppData\Roaming\ninjamuffin99\Kade Engine\ninjamuffin99` (where ever the fuck that is in other operating systems. and the default is `C:\Users\user\AppData\Roaming\ninjamuffin99\Funkin\ninjamuffin99`
> 
> Just copy over the Funkin.sol file into the new directory.

That worked. Thank you
