### ISSUE TITLE
you broke linux builds, again

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#248]
[Working Build](https://ci.appveyor.com/project/daniel11420/kade-engine-linux/builds/38646918/artifacts)
[Broken build (no artifacts)](https://ci.appveyor.com/project/daniel11420/kade-engine-linux/builds/38723713)
so commit "update appveyor's" broke it, great

**Comment by puyoxyz** [comment]
kade figured out the issue with not being able to make more appveyor projects, linux builds are no longer on daniel11420/kade-engine-linux

**Comment by Kade-github** [comment]
i'll have to look at what it says again idk, p sure its still failing so.
