### ISSUE TITLE
Bug Report: Notes aren't registering only on kade engine 1.4.1

### ISSUE THREAD

**Issue by DJA3791** [KadeArchive/Kade-Engine#253]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Windows (`x86`) 
## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1 FNF - 1.4.1 Kade Engine
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
I have no idea what causes the bug, I only know that it happens to me on version 1.4.1 as no other versions have this issue.

## Please describe your issue. Provide extensive detail and images if possible.
https://user-images.githubusercontent.com/82780865/115161006-294f3880-a069-11eb-8cfe-09f2bfcc574e.mp4

My notes don't register on Kade Engine 1.4.1 and only 1.4.1. 

I have no idea why but I would love to receive help from anyone that can fix this issue, thank you for reading this.

**Comment by DJA3791** [comment]
Another example

https://user-images.githubusercontent.com/82780865/115161263-b777ee80-a06a-11eb-9b73-85e9d376951f.mp4

**Comment by theDetourist** [comment]
Your offsets and safe frames are...?

**Comment by DJA3791** [comment]
offset is at 1.1 and safe frames are at 1

**Comment by DJA3791** [comment]
Leaving this hear if anyone else has a similar problem set your safe frames to 20.
