### ISSUE TITLE
is there a way for ya to add week 7?

### ISSUE THREAD

**Issue by stageclown** [KadeArchive/Kade-Engine#259]
this is more of a general question than an issue but,
i've been having trouble accessing week 7 due to newgrounds bein fuckin broken, is there a possibility that this 'newgrounds exclusive' week will be.. possible to add into kade-engine? since i know that due to the fact that 1. newgrounds is dead thanks to week 7 and 2. it wont be on ninjamuffins itch.io, i just want to ask if itll be possible at all to put week 7 in kade engine?
i, as a dfjk downscroll player, so very much do _not_ want to play with arrow keys on the newgrounds engine that has shit input and no options

**Comment by dragonchem** [comment]
the source code for week 7 has not been revealed, so kadedev can't import it yet

**Comment by Kade-github** [comment]
https://github.com/KadeDev/Kade-Engine/releases/tag/1.4.2-TANKMAN-PRE
