### ISSUE TITLE
i think its gonna be hard to do and long to do (enhancement)

### ISSUE THREAD

**Issue by UnknownSkid** [KadeArchive/Kade-Engine#260]
in game cutscene editor
Middle Scroll:you gonna see only your arrows
Translation
Character Fix:if you choose other character like dad its weirdly placed like he is in ground
Loading Screen
add Week:create your own week
Note Color Change
Week 7 Options Menu
Fullscreen option (I KNOW THAT THERE IS A BUTTON THAT MAKE YOU FULLSCREEN BUT SOME OF PEOPLES DONT KNOW ABOUT IT)

**Comment by Kade-github** [comment]
1. no
2. modcharts
3. modcharts
4. week 7 fixes this I think
5. there is one, but on windows you don't see it.
6. no that would just bloat shit
7. week 7 already has that
8. when week 7 release
9. maybe

**Comment by UnknownSkid** [comment]
> 1. no
> 2. modcharts
> 3. modcharts
> 4. week 7 fixes this I think
> 5. there is one, but on windows you don't see it.
> 6. no that would just bloat shit
> 7. week 7 already has that
> 8. when week 7 release
> 9. maybe

1. i mean only dialouge
2. but im not god at modchart
3. how is translation a modchart?
4. MAYBE
5. umm ok?
6. **B**
7. but its still not on itch.io
8. E
9. w h a t

**Comment by Kade-github** [comment]
In Euclidean geometry, a translation is a geometric transformation that moves every point of a figure or a space by the same distance in a given direction.

**Comment by UnknownSkid** [comment]
> In Euclidean geometry, a translation is a geometric transformation that moves every point of a figure or a space by the same distance in a given direction.

TRANSLATION
example:
English:hello!
Polish:Dzieńdobry!

**Comment by Kade-github** [comment]
oh you meant like an actual language? lol, that's probably never going to happen without other contributors cuz I don't know any language.

**Comment by UnknownSkid** [comment]
> oh you meant like an actual language? lol, that's probably never going to happen without other contributors cuz I don't know any language.

im polish and i know english (not very well) so i can translate you things

**Comment by puyoxyz** [comment]
i can translate to polish and spanish i guess BUT if we do translations we should set up crowdin and a good language system

**Comment by UnknownSkid** [comment]
> i can translate to polish and spanish i guess BUT if we do translations we should set up crowdin and a good language system

jak naprawde zansz polski to co powiedziałem?

**Comment by puyoxyz** [comment]
> > i can translate to polish and spanish i guess BUT if we do translations we should set up crowdin and a good language system
> 
> jak naprawde zansz polski to co powiedziałem?

if you really know polish then what did i say?
