### ISSUE TITLE
Enhancement: Since there is not a discord help channel I will ask here

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#263]
My inputs are terribly delayed in Kade Engine. I recall using an older version which allowed you to change input systems. In the latest version you cannot. It is unplayable for me on the latest version. I have tried the original vanilla friday night funkin from itch io. That captures input flawlessly.

**Comment by theDetourist** [comment]
Care to record a video of it happening so we can see what exactly is going on?

**Comment by doubledge-spec** [comment]
It is as I describe. My on version 1.3.1 which allows me to change input systems. I can play properly with the older input system. The newer one is completely borked for me. I assume that timing is different between the two systems? I will try to record a video

**Comment by ghost** [comment]
I have been mistaken. The issue is not with the input systems. both input systems work on the older version of the engine. It is just on version 1.4.2 the game is somehow unplayable. I have tried windowed and fullscreen mode. tried changing the frame limiter.

**Comment by ghost** [comment]
https://streamable.com/7rsyfb this is version 1.3.1. In the video shows gameplay with both input systems. Both work but newer one is more precise. https://streamable.com/mdha94 this is version 1.4.2. here it shows the frame limiter set to 120. and there is no option to change input systems.

**Comment by theDetourist** [comment]
Yeah, old input was dropped with the release of 1.4, might come back now with the Tankman week.

Where is your offset and safe frames set at?

**Comment by ghost** [comment]
offset is 0 and safe frames is default. don't know what the default value is I just didn't touch the setting

**Comment by doubledge-spec** [comment]
I have tried that it does not work

**Comment by theDetourist** [comment]
The default value for safe frames is 10, also, tweaking the offset (both globally and chart specific @ the pause menu) didn't work?

Also, are you using a released version of the engine or is that a build you yourself compiled?

**Comment by ghost** [comment]
released version. 1.4.2 without tankman. also the tankman version captures inputs but for some reason registers it as a miss

**Comment by ghost** [comment]
Safe frames fixed the issue. Don't know why it was so low when I downloaded it. it was set to 2 lmao

**Comment by theDetourist** [comment]
Glad you fixed it.

**Comment by puyoxyz** [comment]
@KadeDev close this
