### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by mrmubbz** [KadeArchive/Kade-Engine#273]
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
i have no idea how this bug works as it is a smaller bug and i have no idea how it could possibly reproduce 
## Please describe your issue. Provide extensive detail and images if possible.
my issue is every single time I try to use the kade engine in every single fnf mod the notes are always delayed to the songs and it is oh so slightly off to the music i have no idea if this even resonates within the kade engine it could be something else entirely but this bug only happens when i use the kade engine so I am assuming that kade engine is the problem so if you have any idea as to why this could be happening at all it would be appreciated to let me know how to fix it.

**Comment by theDetourist** [comment]
Adjust your global offset in the options, also check your safe frames if they're @ 10.

**Comment by mrmubbz** [comment]
alright I had set my global off set correctly and that had fixed my problem thank you very much

**Comment by theDetourist** [comment]
Glad you fixed it, also, don't forget to close the issue too.
