### ISSUE TITLE
When testing as html5 it gives a error

### ISSUE THREAD

**Issue by Tannermanner2008** [KadeArchive/Kade-Engine#274]
when ever i try and test kade engine in browser it gives me an error

error: "C:/HaxeToolkit/haxe/lib/linc_luajit/0,0,2/llua/Lua.hx:492: characters 43-61 : cpp.Callable has no field fromStaticFunction
  C:/HaxeToolkit/haxe/lib/linc_luajit/0,0,2/llua/Lua.hx:526: characters 42-60 : cpp.Callable has no field fromStaticFunction"
  i havent modified anything in the code yet

my laptop is a Windows 10 64 bit

**Comment by actuallyasmartname** [comment]
something with llua try downgrading

**Comment by sydenlous** [comment]
> something with llua try downgrading

I already tried that, still does not work.

**Comment by puyoxyz** [comment]
html5 and linux builds seem to be broken right now because of lua

**Comment by actuallyasmartname** [comment]
yeah

**Comment by george2781** [comment]
I get a (sort of?) similar issue, whenever I try to compile the game (unmodified, windows x64 desktop pc, html5 version) a file that the game needs (specifically Kade Engine.js) is always missing, Upon firther inspection I get this: `source/PlayState.hx:2319: characters 8-11 : Unknown identifier : lua` likely meaning that the problem is indeed lua

**Comment by puyoxyz** [comment]
> I get a (sort of?) similar issue, whenever I try to compile the game (unmodified, windows x64 desktop pc, html5 version) a file that the game needs (specifically Kade Engine.js) is always missing, Upon firther inspection I get this: `source/PlayState.hx:2319: characters 8-11 : Unknown identifier : lua` likely meaning that the problem is indeed lua

your issue is different, you forgot to install linc_luajit, see BUILDING.md

**Comment by george2781** [comment]
> 
> 
> > I get a (sort of?) similar issue, whenever I try to compile the game (unmodified, windows x64 desktop pc, html5 version) a file that the game needs (specifically Kade Engine.js) is always missing, Upon firther inspection I get this: `source/PlayState.hx:2319: characters 8-11 : Unknown identifier : lua` likely meaning that the problem is indeed lua
> 
> your issue is different, you forgot to install linc_luajit, see BUILDING.md

Ah ok, thanks for the help with my issue, good luck with yours

**Comment by actuallyasmartname** [comment]
`source/PlayState.hx:2319: characters 8-11 : Unknown identifier : lua` i get this even with linc_luajit

**Comment by george2781** [comment]
> 
> 
> `source/PlayState.hx:2319: characters 8-11 : Unknown identifier : lua` i get this even with linc_luajit

Yeah, also I don't think this is the kind of stuff I should be seeing when opening vscode
![error](https://user-images.githubusercontent.com/42376099/115958790-ca723f00-a500-11eb-9bd6-e5342d927229.PNG)
![debug info](https://user-images.githubusercontent.com/42376099/115958797-d4943d80-a500-11eb-87f4-51fbe7f166ff.PNG)

**Comment by Kade-github** [comment]
fixed
