### ISSUE TITLE
Bug Report: Monster's Neck doesn't collide correctly

### ISSUE THREAD

**Issue by inkayye** [KadeArchive/Kade-Engine#275]
I was playing in the latest version of the Kade Engine when I found out that Monster's neck on Week 2 doesn't show correctly.
It might be a problem on my end tho, but I wanted to be sure so yeah.

![Screenshot_1](https://user-images.githubusercontent.com/78197308/115454814-7d048200-a221-11eb-97a1-d4efa34ebc58.png)

**Comment by Kade-github** [comment]
thats base game lol. p sure week 7 fixes that so it'll be fixed when it gets open sourced
