### ISSUE TITLE
Missing .bat file

### ISSUE THREAD

**Issue by catte-cloud** [KadeArchive/Kade-Engine#276]
The build.bat is missing _completely_, its not in the art folder at all.

![image](https://user-images.githubusercontent.com/78244937/115477706-80dcd800-a212-11eb-8a4c-c5bdb638e1ea.png)

**Comment by catte-cloud** [comment]
i've looked in other places and have found nothing.

**Comment by Kade-github** [comment]
build manually. `lime test windows -release`
