### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by PizzaRolls12** [KadeArchive/Kade-Engine#277]
I tried to update and now it says haxelib/linc_luajit/0,0,2//linc/linc_lua.h:5:10: fatal error: Kade-Engine/export/release/linux/obj/obj/linux64/__pch/haxe/hxcpp.h: No such file or directory
    5 | #include <hxcpp.h>
      |          ^~~~~~~~~
compilation terminated.

**Comment by PizzaRolls12** [comment]
to update it I deleted the folder I downloaded and the folder it made and tried to recompile

**Comment by Kade-github** [comment]
did it work?

**Comment by PizzaRolls12** [comment]
> did it work?

no thats how i got the error

**Comment by puyoxyz** [comment]
this got fixed yeah

**Comment by ghost** [comment]
not anymore, with latest `master` commit, the error appears
