### ISSUE TITLE
Enhancement:WEEK 7 client (dont need to add week 7 to game)

### ISSUE THREAD

**Issue by UnknownSkid** [KadeArchive/Kade-Engine#278]
w e e k  7  c l i e n t
![image](https://user-images.githubusercontent.com/81253195/115543199-656cde00-a2a1-11eb-862f-ae4a1267175f.png)
![image](https://user-images.githubusercontent.com/81253195/115543259-73226380-a2a1-11eb-8bbd-a7631ad29bb7.png)
![image](https://user-images.githubusercontent.com/81253195/115543288-803f5280-a2a1-11eb-8b9b-9fe2247c1777.png)
![image](https://user-images.githubusercontent.com/81253195/115543320-87fef700-a2a1-11eb-8eba-49954972995f.png)

**Comment by Kade-github** [comment]
No.
https://twitter.com/ninja_muffin99/status/1384190488920551426

**Comment by UnknownSkid** [comment]
> No.
> https://twitter.com/ninja_muffin99/status/1384190488920551426

);
