### ISSUE TITLE
How to make two keys prefix in one? (fusion keybinds)

### ISSUE THREAD

**Issue by RealPogMe** [KadeArchive/Kade-Engine#28]
Hey, i need some help here, i have an almost finished mod but i still want to know how to make two key prefixes on one, i mean 
like _WASD + HJKL_ for saying something, editing the file called **Controls.hx** i could make that the keys changed, but i couldn't make them be in the same bind, instead of being  _my own prefix+my other own prefix_ it was  _My own prefix + up,right,down and left_ i really want to make a "fusioned" prefix cause for me its so more comfy to play like that, anyways thx for the attention

**Comment by Kade-github** [comment]
You can just keep adding more keys by appending a `, ` and then the key to the control bind.

**Comment by RealPogMe** [comment]
thx
