### ISSUE TITLE
Enhancement: Option to switch to original Sicks, Goods, etc.

### ISSUE THREAD

**Issue by actuallyasmartname** [KadeArchive/Kade-Engine#283]
## What is your suggestion, and why should it be implemented?
basically this suggestion says that there should be some sorta option for change to the original, sicks, goods, etc..

**Comment by theDetourist** [comment]
What do you mean by that, you mean using the old sprites, old timings from the vanilla game..?

**Comment by AlexGamingSW** [comment]
> What do you mean by that, you mean using the old sprites, old timings from the vanilla game..?

It means having the normal sick, good, bad, shit because they have a recolor in the Kade Engine

**Comment by actuallyasmartname** [comment]
> > What do you mean by that, you mean using the old sprites, old timings from the vanilla game..?
> 
> It means having the normal sick, good, bad, shit because they have a recolor in the Kade Engine

Yeah some setting for it to change it to rainbow or vanilla since there's also an option for rainbow fps and shit

**Comment by puyoxyz** [comment]
@KadeDev rename to `Enhancement: Option to switch between old and new judgement (sick, good, bad, shit) sprites` pls

**Comment by Kade-github** [comment]
just... switch the sprites lol. I'd rather not bloat the assets with 10 more files.

**Comment by actuallyasmartname** [comment]
hehe ok
