### ISSUE TITLE
Enhancement: Add health bar to Customize Gameplay

### ISSUE THREAD

**Issue by UnknownSkid** [KadeArchive/Kade-Engine#284]
All The Things Are made in paint.net
Add Health Bar in "Customize Gameplay" (im lazy to add music bar)
![image](https://user-images.githubusercontent.com/81253195/115690257-2a2fe500-a35d-11eb-9752-e7917c0dc180.png)
Rename Song
![image](https://user-images.githubusercontent.com/81253195/115691035-f2756d00-a35d-11eb-9eb1-a90084a5f195.png)
Character Select
![image](https://user-images.githubusercontent.com/81253195/115693083-dffc3300-a35f-11eb-9bec-be9b63c707ab.png)
Results. Other Details:The Notes Will Be Rainbow When You Get 10000-500000, Texts:When you have 0 misses "Wow no Misses You Are Good!!" when you have 1-25 misses "god not 45 misses" when you have 45-100 misses "you are so trash" when you got 100 - 5000 score "how?" when you got 1000-6500 score "Teach and you will be better!" when you got 10000-500000 score "You Are Good!"
![image](https://user-images.githubusercontent.com/81253195/115695696-4da95e80-a362-11eb-9c32-1bbfc5778b9f.png)

**Comment by ggsalman** [comment]
YES YES YES!

**Comment by puyoxyz** [comment]
- character select: probably won't happen since it's more of a mod thing anyways *and* that's gonna happen in the full ass game
- results screen is already planned 

renamed issue to "Enhancement: Add health bar to Customize Gameplay"

**Comment by puyoxyz** [comment]
""""merging"""" this (idk whats the right word) into #339
