### ISSUE TITLE
Bug Report: the imput is glitched,i tap the note right when its in the arrow and it doesent count

### ISSUE THREAD

**Issue by FullDenisX** [KadeArchive/Kade-Engine#285]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
windows (x86_64)
## What version of the game are you using? Look in the bottom left corner of the main menu.
the newest version
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
no
## Please describe your issue. Provide extensive detail and images if possible.
the imputs are glitchy as hell

**Comment by theDetourist** [comment]
Have you tried messing with the global offset in the Options? Are you sure your safe frames are at 10?

It's probably not the engine, you need to calibrate the game.

**Comment by Kade-github** [comment]
This issue gave literal nothing other than "I don't like the input."
