### ISSUE TITLE
Bug Report: Cannot compile: Could not find haxelib "lime"

### ISSUE THREAD

**Issue by hex0x0000** [KadeArchive/Kade-Engine#287]
### If you are playing a downloaded version of the game, what operating system are you using?
Arch Linux

## What version of the game are you using? Look in the bottom left corner of the main menu.
Latest

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
0. Be on Linux (specifically Arch Linux)
1. Download Haxe 4.1.5
2. Setup HaxeLib (both in local or in /usr/share/haxe/lib don't work)
3. Install lime, openfl, and flixel
4. Run `haxelib run lime setup`

## Please describe your issue. Provide extensive detail and images if possible.
```
$ ./haxe --version
4.1.5
$ ./haxelib version
4.0.2
$ sudo ./haxelib list
flixel: [4.9.0]
lime: [7.9.0]
openfl: [9.1.0]
$ sudo ./haxelib run lime setup
Error: Could not find haxelib "lime", does it need to be installed?  
```

**Comment by puyoxyz** [comment]
This is a problem with lime and/or haxelib, not Kade-Engine...
(Make a [discussion](https://github.com/KadeDev/Kade-Engine/discussions) or ask elsewhere)

**Comment by hex0x0000** [comment]
Ok
