### ISSUE TITLE
Bug Report: Downloading Master Code

### ISSUE THREAD

**Issue by ZenusPurity** [KadeArchive/Kade-Engine#288]
If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Windows 10

What version of the game are you using? Look in the bottom left corner of the main menu.

---

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

---

## Please describe your issue. Provide extensive detail and images if possible.

Hello there, I am having trouble downloading the source code to the latest version of KE. This screen keeps popping up whenever I try to peek inside the .zip file: 
![image](https://user-images.githubusercontent.com/82642362/115889935-0072dd00-a487-11eb-9d19-ec591905491c.png)

But I was able to extract it, though that didn't turn out so good as there were several folders missing: 
![image](https://user-images.githubusercontent.com/82642362/115890037-18e2f780-a487-11eb-88e8-f3535d071f31.png)

This also pops up when I'm extracting it: 
![image](https://user-images.githubusercontent.com/82642362/115890120-2f894e80-a487-11eb-936a-2bf92a4a5fbb.png)

I'm not sure whether it's on my end or Github's, but I'd like to know the reason if you know! Thanks!

**Comment by george2781** [comment]
Try redownloading the zip file

**Comment by Kade-github** [comment]
`git clone https://github.com/KadeDev/Kade-Engine.git` never trust github to download files manually.
