### ISSUE TITLE
fix the fucking game

### ISSUE THREAD

**Issue by TheIdiotNearYou** [KadeArchive/Kade-Engine#290]
when i press a note the game fucking dosent work and makes me miss everysingle note

fix this you motherfucker

**Comment by Sebyal** [comment]
Cry about it :troll:

**Comment by theDetourist** [comment]
I was about to help but then I thought: it's either an egocentric idiot or a bored asshole trolling.

One you can fix with a bit more kindness, the other might get you a "fuck off" as a response. The choice is yours.

**Comment by actuallyasmartname** [comment]
:trollface: be more kind then we might help

**Comment by puyoxyz** [comment]
@TheIdiotNearYou check your safe frames in the options, they should be 10

**Comment by Kade-github** [comment]
:trollface: github is a chad for adding this emoji

**Comment by puyoxyz** [comment]
:trolleybus: oh my god im crying

**Comment by puyoxyz** [comment]
WAIT NO I MEANT :trollface:
