### ISSUE TITLE
Bug Report: The "monster" (not to be mistaken with "monster-christmas") assets crash on any other song other than it's own.

### ISSUE THREAD

**Issue by AN0MALEZ** [KadeArchive/Kade-Engine#293]
I kind of discovered this over how lazy I am, I didn't want to draw over two PNG files of the same character I was going to mod into the game, so yeah, there's that. Correct me if this has already been fixed, I don't have the latest version.

**Comment by Kade-github** [comment]
Already fixed in the latest source/nightly.

**Comment by Travdev24** [comment]
Well.. he's called monster for a reason ¯\_(ツ)_/¯
