### ISSUE TITLE
Automatic/Manual Screenshot System

### ISSUE THREAD

**Issue by Rudyrue** [KadeArchive/Kade-Engine#297]
Since Bopeebo ends on you almost instantly, i was thinkin' you could make an automatic/manual screenshot system. This is how it would work:

AUTOMATIC: You beat a chart and the game takes a screenshot of your screen right before it ends. The screenshots are saved in a folder called "screenshots". The image name has the chart name, the difficulty, and the score, so that it's easy to find.

MANUAL: basically steam's screenshot system lol

**Comment by puyoxyz** [comment]
~~or we add a results screen~~

**Comment by Jaduplex** [comment]
> ~or we add a results screen~

yeah that's already been confirmed to be added

**Comment by isakube** [comment]
OR the literal replay system which is practically VIDEO PROOF of your achievements
idk just me

**Comment by puyoxyz** [comment]
> OR the literal replay system which is practically VIDEO PROOF of your achievements
> idk just me

replay system kinda bad :/

**Comment by Kade-github** [comment]
> > OR the literal replay system which is practically VIDEO PROOF of your achievements
> > idk just me
> 
> replay system kinda bad :/

give me slack I'm working on it in the back :(((

**Comment by daniel11420** [comment]
> > > OR the literal replay system which is practically VIDEO PROOF of your achievements
> > > idk just me
> > 
> > 
> > replay system kinda bad :/
> 
> give me slack I'm working on it in the back :(((

work on me in the back ;) >~< :flushed:

**Comment by puyoxyz** [comment]
Replay system good now. Yeah. Closing
