### ISSUE TITLE
Bug Report:  After I open options, the notes slowed

### ISSUE THREAD

**Issue by 1cicles** [KadeArchive/Kade-Engine#298]
As the title said, after I open options, and play one of the songs. The notes started to get slower. This occurs with every song.

It happens in the 1.4.1 and 1.4.2 version.

**Comment by puyoxyz** [comment]
did you change your scroll speed by accident? make sure it's on 1.0 if you want the default scroll speed

**Comment by 1cicles** [comment]
No. The only thing I did was accidentally selecting options, then go back to menu. And I can't change the scroll speed for some reason.

I noticed that it happened when I go to the “gameplay” section after I accidentally did the same thing with 1.4.1

**Comment by theDetourist** [comment]
1. Your OS?
2. Can you give us a video of everything happening? Also the inability to change scroll speed thing.

**Comment by puyoxyz** [comment]
Did you *actually* check your scroll speed (whether it changed from 1.0 or not)?
// This could be a bug where the default scroll speed is for some reason not 1.0 or the 1.0 from the settings menu is different from the default 1.0 somehow

**Comment by 1cicles** [comment]
> 1. Your OS?
> 2. Can you give us a video of everything happening? Also the inability to change scroll speed thing.

I'm a moron holy shit I just realize I didn't read the bottom text

**Comment by 1cicles** [comment]
I'm a moron.

I forgot to read the bottom text.

For the people who are reading this and/or trying to help me, I'm sorry for wasting your time
