### ISSUE TITLE
Bug Report: game super slow on 60fps

### ISSUE THREAD

**Issue by BopperDuppet** [KadeArchive/Kade-Engine#30]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86_64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.1.3 
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
have a 60hz monitor lol
## Please describe your issue. Provide extensive detail and images if possible.
so, my pc is dogshit and the screen is 60hz meaning that the game only really runs at 60fps, and because it's 60fps everything runs incredibly slow when in the title screen, it fixes itself when you go into a menu and back out though for some reason

**Comment by Kade-github** [comment]
theres no way I can fix this for you.
