### ISSUE TITLE
Undo PR #292

### ISSUE THREAD

**Issue by aflacc** [KadeArchive/Kade-Engine#301]
Its all stuff from my engine ProjectFNF, your stealing my people and I didn't even give him permission to do this. I really do not want this stuff being used without my permission

**Comment by theDetourist** [comment]
@brightfyregit, you might wanna comment on this.

**Comment by brightfyregit** [comment]
yeah, im completely fine with getting rid of the features from project fnf, but the other things, such as no freeplay lag, freeplay menu color changes, and updating health icons in charting state is my stuff

**Comment by theDetourist** [comment]
I'd say it's fine so long as it doesn't happen again, both engines are open source and both are public projects. They also share the same license as required by the original Ninjamuffin99 base so this is just a matter of giving credit so no one's wronged.

If you don't want people getting code from you, you might wanna reconsider using Kade Engine or the main base game as your source code and your project being open source.

**Comment by UniversePM** [comment]
> I'd say it's fine so long as it doesn't happen again, both engines are open source and both are public projects. They also share the same license as required by the original Ninjamuffin99 base so this is just a matter of giving credit so no one's wronged.
> 
> If you don't want people getting code from you, you might wanna reconsider using Kade Engine or the main base game as your source code and your project being open source.

Aflac is kind of against kade engine..

**Comment by UniversePM** [comment]
> > I'd say it's fine so long as it doesn't happen again, both engines are open source and both are public projects. They also share the same license as required by the original Ninjamuffin99 base so this is just a matter of giving credit so no one's wronged.
> > If you don't want people getting code from you, you might wanna reconsider using Kade Engine or the main base game as your source code and your project being open source.
> 
> Aflac is kind of against kade engine..

Plus im not sure if aflac got any credit for it..
