### ISSUE TITLE
Enhancement: Toggling week 6 notes

### ISSUE THREAD

**Issue by Sebyal** [KadeArchive/Kade-Engine#303]
Being able to toggle on options the week 6 note textures to the default textures, to me atleast it can be a little harder to hit arrows normally on week 6 or week 6 based mods, because it is pixelated, it does look better but it might help the gameplay itself which i think is more important

(would be poggers pogchamp pog 😳)

**Comment by puyoxyz** [comment]
or like a noteskin selector so that if new noteskins are added it can use the same option and mods can have custom ones there like for example mfm gospel noteskin

**Comment by Jaduplex** [comment]
ive already done this on the "fnf as it was always meant to be" branch of my kade engine fork. its in a mod im working on. could probably port that over to vanilla kade engine with relative ease so this could be added

**Comment by puyoxyz** [comment]
> ive already done this on the "fnf as it was always meant to be" branch of my kade engine fork. its in a mod im working on. could probably port that over to vanilla kade engine with relative ease so this could be added

week 6 was always meant to be as it is the whole point of fnf is that each week is a new thing and that includes changes not just limited to the scenery and enemy and songs. fnf with the default noteskin is not how it was "meant to be" how it was "meant to be" is to have normal noteskin weeks 1-5 but 6 has its own one because that fits the theme of 6 oh my god

**Comment by Jaduplex** [comment]
> > ive already done this on the "fnf as it was always meant to be" branch of my kade engine fork. its in a mod im working on. could probably port that over to vanilla kade engine with relative ease so this could be added
> 
> week 6 was always meant to be as it is the whole point of fnf is that each week is a new thing and that includes changes not just limited to the scenery and enemy and songs. fnf with the default noteskin is not how it was "meant to be" how it was "meant to be" is to have normal noteskin weeks 1-5 but 6 has its own one because that fits the theme of 6 oh my god

uh. you do realize i just meant that i unhardcoded the noteskins. not that it is "meant to be" the normal one. that's just the fucking name of the mod. i added a select to the debug menu that lets you change noteskins. that's it. im not braindead and think that it isnt meant to have the noteskin.

**Comment by Jaduplex** [comment]
you don't need to treat me like a braindead moron. i know what stylistic changes are

**Comment by Jaduplex** [comment]
#334 adds a noteskin dropdown

**Comment by arceuss** [comment]
how would i be able to add my own noteskin
i wanna make a itg pack

**Comment by Jaduplex** [comment]
> how would i be able to add my own noteskin
> i wanna make a itg pack

you cannot without recompiling.

**Comment by puyoxyz** [comment]
resolved by #334 why did noone close this
