### ISSUE TITLE
Bug Report: Only showing 2 songs on tracks (week menu)

### ISSUE THREAD

**Issue by LexoMagnum** [KadeArchive/Kade-Engine#304]
### Build and Testing on :
 Windows (`x86_64`)

## I enter story mode menu, and in tracks section, only appears 2 of them, is kinda weird cause in-game all the tracks are there (3 or more), i have installed everything, even uninstalled everything and reinstalled, it seems to be the same, also i tested almost all the version of the engine, but nothing, the real problem is that like 2 weeks ago, nothing of that happened.
![Friday Night Funkin evidence](https://user-images.githubusercontent.com/83183569/116006077-64a0b880-a5cf-11eb-9c13-6f4fb1e765bf.png)

**Comment by CliveDev0413** [comment]
Go to `StoryMenuState.hx` and scroll all the way to the bottom and add this line of code: `txtTracklist.text += "\n";` right after this line of code: 
``` 
for (i in stringThing)
{
	txtTracklist.text += "\n" + i;
}
```

**Comment by LexoMagnum** [comment]
thank you so much it worked

**Comment by Fefe543** [comment]
yo @CliveDev0413 so basically mine when i paste it, it will appear wayyyyyyyyyyyy more tracks, not 3
![image](https://user-images.githubusercontent.com/77512259/116149777-ee788080-a6b8-11eb-8203-0343791cd71d.png)
and here how I pasted it 
![image](https://user-images.githubusercontent.com/77512259/116149907-1667e400-a6b9-11eb-9ada-44ea8e22be16.png)

**Comment by LexoMagnum** [comment]
@Fefecomitre 
![code](https://user-images.githubusercontent.com/83183569/116435178-b3896080-a810-11eb-9290-67ae6728bbd6.png)
this is the code 

	for (i in stringThing)
		{
			txtTracklist.text += "\n" + i;
		}
		txtTracklist.text += "\n";

**Comment by Fefe543** [comment]
yo! sorry, but i have found a way to fix it without that, I just needed to fix lime version and other things

**Comment by OMGcheese997** [comment]
what line is "for i in string thing" on or whatever it is

**Comment by puyoxyz** [comment]
@OMGcheese997 this is already fixed in the latest source you don't need to do it yourself. 

also, locking this. basically, you either have the wrong lime version, or you don't have the latest source code, something like that
