### ISSUE TITLE
double notes/arrows aren't working

### ISSUE THREAD

**Issue by Marbels** [KadeArchive/Kade-Engine#311]
attempting to hit 2 notes at the same time causes a miss.

probably something to do with this(what appears when missing a double note):
![image](https://user-images.githubusercontent.com/18653303/116018846-c70daf00-a5f7-11eb-83ca-737fc55b4a70.png)
relates back to this:
![image](https://user-images.githubusercontent.com/18653303/116018926-ead0f500-a5f7-11eb-8e4e-d98912ee7c93.png)

**Comment by Travdev24** [comment]
yeah sometimes i experience the exact same issue, though i've passed the 1st part of satin panties (which consists of a wall of notes)

**Comment by Kade-github** [comment]
> attempting to hit 2 notes at the same time causes a miss.
> 
> probably something to do with this(what appears when missing a double note):
> ![image](https://user-images.githubusercontent.com/18653303/116018846-c70daf00-a5f7-11eb-83ca-737fc55b4a70.png)
> relates back to this:
> ![image](https://user-images.githubusercontent.com/18653303/116018926-ead0f500-a5f7-11eb-8e4e-d98912ee7c93.png)

That function gets the current amount of key presses needed, if you go over it. it'll give you mash violation. You get 2 you're not going to be able to hit notes until you hit notes legit
