### ISSUE TITLE
Accuracy goes to 0

### ISSUE THREAD

**Issue by Alespic** [KadeArchive/Kade-Engine#313]
Alright, my acc is really trash, but I don't think it's supposed to go to zero, especially if I manage to finish the song...

I think it's how the accuracy is subtracted that it's the problem. Probably doesn't account for how many notes already went by.

**Comment by Kade-github** [comment]
no it is. ur just so trash the game doesn't count it.

**Comment by puyoxyz** [comment]
check if your safe frames are 10 (that's the default)
