### ISSUE TITLE
Add option to make it so game does not zoom in.

### ISSUE THREAD

**Issue by KooAdv** [KadeArchive/Kade-Engine#321]
Basically, when the game zooms in on the enemy it will just make me unable to see half the health bar and will completely not let me see the combo bar below the health bar. The only way I can bypass this is downscroll. I've tried making the window smaller. Nope. Only downscroll will let me see it but I do not prefer downscroll.

I want an option so that you can choose if you want it to zoom in at the enemy turn or not.

<img width="567" alt="Capture" src="https://user-images.githubusercontent.com/83254898/116166817-c85cdb80-a6cc-11eb-9cee-1593bba48773.PNG">
<img width="539" alt="Capture8" src="https://user-images.githubusercontent.com/83254898/116166749-a95e4980-a6cc-11eb-9f3d-bafc19c3bbc2.PNG">

**Comment by DizzyJune** [comment]
I've heard about this suggestion a couple times but I don't think Kade really cares about adding it since it isn't a huge issue.

**Comment by Kade-github** [comment]
this would be in week 7, since week 7 already does that
