### ISSUE TITLE
error while compiling for mac

### ISSUE THREAD

**Issue by EnvyBun** [KadeArchive/Kade-Engine#323]
i just downloaded the newest version of kade engine and i get the error
"source/PlayState.hx:437: characters 21-31 : Type not found : FileSystem
source/PauseSubState.hx:4: characters 8-16 : Type not found : llua.Lua
source/PauseSubState.hx:186: characters 20-23 : Class<PlayState> has no field lua
source/PauseSubState.hx:188: characters 7-10 : Type not found : Lua
source/PauseSubState.hx:189: characters 17-20 : Class<PlayState> has no field lua"
i did not mess with these files i just downloaded the newest version of kade engine and tried to compile it

**Comment by puyoxyz** [comment]
html5 and linux builds are broken because of modcharts. this is a known issue

**Comment by Kade-github** [comment]
fixed
