### ISSUE TITLE
Discord.hx Compilation Error.

### ISSUE THREAD

**Issue by jelleejamm** [KadeArchive/Kade-Engine#324]
Hi, I've been trying to build Kade for a little mod I was making, however I keep getting this error when compiling, while I have the Discord Rpc library:
"source/Discord.hx:5: characters 8-30 : Type not found : discord_rpc.DiscordRpc
source/Discord.hx:14: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:24: characters 4-14 : Type not found : DiscordRpc
source/Discord.hx:29: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:34: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:39: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:75: characters 3-13 : Type not found : DiscordRpc"
Any way to fix this??

**Comment by theDetourist** [comment]
Make sure you [installed all of the dependencies](https://github.com/KadeDev/Kade-Engine/blob/master/BUILDING.md#dependencies) properly.
