### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by SpeedyFlash05** [KadeArchive/Kade-Engine#327]
After finishing a song using the Kade Engine the game crashes, giving me an error telling me that there is something wrong with the replays.

I'm using Windows x64.

I'm using version 0.2.7.1 of the game.
![Capture](https://user-images.githubusercontent.com/83341682/116383578-50bcb700-a85a-11eb-8f3f-c9aa175ee182.PNG)

**Comment by puyoxyz** [comment]
go to `assets` folder and make a folder called `replays`. if there is already a folder called `replays` in `assets` then you don't have permission to access it -- move the game to somewhere in your user directory, like desktop or documents (NOT program files or a different user's directory)

**Comment by SpeedyFlash05** [comment]
Oh thanks. I'm not great with messing around in files so thanks for the help.
