### ISSUE TITLE
Bug Report: Stage crashes the game

### ISSUE THREAD

**Issue by Maverick-73584** [KadeArchive/Kade-Engine#329]
If you replace the dad with anyone else via the debug menu, the game crashes.

**Comment by MarioLuigi124** [comment]
same on every other song

**Comment by Kade-github** [comment]
no?

On the latest (nightly/source) version its fine.

https://user-images.githubusercontent.com/26305836/116465876-a9705d80-a822-11eb-9545-1a353061891d.mp4

**Comment by RagdollClash** [comment]
This issue only happens to me on web, desktop is fine.

**Comment by Kade-github** [comment]
p sure this is an issue with the base game html5 as well. since this would be a preloading issue.
