### ISSUE TITLE
Bug Report: Lime failed to test this app

### ISSUE THREAD

**Issue by lewisdevelop** [KadeArchive/Kade-Engine#33]
#### Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.
i tried everything but got the same error

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
windows 10 x64 
## What version of the game are you using? Look in the bottom left corner of the main menu.
1.2.1 Kade-Engine

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
1.run lime test windows -debug with the new version 
## Please describe your issue. Provide extensive detail and images if possible.
"ApplicationMain-debug.exe : fatal error LNK1120: 1 unresolved externals" is the error
![io](https://user-images.githubusercontent.com/44608738/111896087-fb95b600-8a0e-11eb-9d9f-8087d761d6b4.PNG)

**Comment by Kade-github** [comment]
Delete the export folder and recompile, this isn't a bug.
