### ISSUE TITLE
 If i run it, it says its a Virus

### ISSUE THREAD

**Issue by PaulILG** [KadeArchive/Kade-Engine#333]
I have the problem that if i run Funkin.exe it tells me its a virus. Usually, it just runs the game, but now it thinks its a virus. Got the page hacked or anything? I dont wanna run because im a bit scared

**Comment by Jaduplex** [comment]
I hope you're kidding. It's not a virus, it just doesn't have a valid signature, so it thinks it's a virus.

**Comment by Kade-github** [comment]
no
