### ISSUE TITLE
Enhancement: rolls?

### ISSUE THREAD

**Issue by arceuss** [KadeArchive/Kade-Engine#335]
idk itd make some charts more fun i guess

**Comment by isakube** [comment]
detail, people
detail for the inexperienced

**Comment by arceuss** [comment]
https://step-mania.fandom.com/wiki/Rolls
does this help

**Comment by haya3218** [comment]
so something like keep tapping note instead of hold note?
I've seen those

**Comment by Kade-github** [comment]
yeah but the problem with adding a new gameplay mechanic would mean that you can't play this in the og game...

**Comment by isakube** [comment]
> yeah but the problem with adding a new gameplay mechanic would mean that you can't play this in the og game...

**Comment by arceuss** [comment]
> 
> 
> yeah but the problem with adding a new gameplay mechanic would mean that you can't play this in the og game...

you could just do what converters do and make them holds if in the og game

**Comment by isakube** [comment]
tru tru
but it's not like Kade Engine to add a new gameplay mechanic like that

**Comment by raf13lol** [comment]
close this because there is no point in having this up
