### ISSUE TITLE
Bug Report: game just crashes if i select the pixel noteskin on anything other than week 6

### ISSUE THREAD

**Issue by arceuss** [KadeArchive/Kade-Engine#336]
trying it with darksheep and the game just crashes after trying to use it with the pixel noteskin

**Comment by Jaduplex** [comment]
this is because the pixel noteskin is located in the week 6 folder, and cannot be loaded by any other weeks.

**Comment by isakube** [comment]
i feel like if I try to fix this it's gonna ruin the whole point of the new loading system

What I would've tried is making a folder in shared/images named ui-packs and then just put the types in separate appropriately-named folders. BUT it doesnt make much sense for just the noteskins to be global, which would lead me to either cancelling the whole pr or making the new loading system completely obsolete. I guess noteskins and stages etc. will just have to be local until somebody smarter than me comes along and figures something out

**Comment by puyoxyz** [comment]
pixel noteskin is a week specific asset, other weeks can't load it, this is intended, copy it to another week's folder if you want to use it there
