### ISSUE TITLE
Bug Report: Reset/kill key doesn't work; Player takes no damage when pressing wrong keys (possible feature?)

### ISSUE THREAD

**Issue by flopnut** [KadeArchive/Kade-Engine#342]
kade master 1.4.2, windows x86 64

my haxe dependency versions:
![image](https://user-images.githubusercontent.com/83429677/116664912-f3099700-a94d-11eb-9e75-b1328ce07444.png)

I thought this was an issue on my end but it seems like it's part of the source code going a couple releases back. I compared control source files from kade to the base game source, pretty much the same except for like 1 line or smth. Not sure what to look for...

is there a way to toggle between the old/new input systems in the current build? mod builds like hex, tricky, and whitty have a toggle feature. i dig how whitty did theirs

this isnt a groundbreaking issue but i feel like that damage is a core part of the gameplay.
w/o it the metagame changes and you can do stuff like this:
https://user-images.githubusercontent.com/83429677/116669225-2e5a9480-a953-11eb-8925-ceada65e556b.mp4

Kill key works on older kade releases like 1.1 sometimes
Toggle input damage works on release <1.3, but no kill key
1.1.3 doesnt detect inaccuracy but gives negative score for spamming (is this a feature? read some abstract comments in the code somewhere)
Current release 1.4.2 detects inaccuracy % but no damage

thanks :)

**Comment by ACardboardBox1** [comment]
#179 i think they might work back on it when the week 7 source code comes out 👍

**Comment by Kade-github** [comment]
First, ghost tapping is one of the best features in most people's opinions. There's also a toggle in the latest nightly version. R has been taken out because there's no reason to ever have it, it's terrible.

**Comment by prokube** [comment]
this single Issue and Kade's response to it will be the sole reason every fork of Kade Engine that is mine will have the R key function implemented
