### ISSUE TITLE
[Enhancement] The ability to choose whatever keys we want | AR changer

### ISSUE THREAD

**Issue by GamingInfinite** [KadeArchive/Kade-Engine#345]
(I didn't see anything similar in the other issues, please correct me if I'm wrong)

2 Things:

1. Please add full customization of the keys.  The main rhythm games I play other than FNF are "osu!" (a nonentity in this case) and Clone Hero (Guitar Hero on pc).  I'd really enjoy being able to use the osu!mania controls as well as the clone hero keyboard controls or any other key layout that I feel like will help me play better.

2. Add customization for the approach rate of keys.  Like yes, it's meant to be a fast paced game, but for people who are bad like me, it'd help to see the notes a bit longer to process and hit the right key.  A lot of my combo breaks, even in clone hero, are from just hitting a button when it shows up as I picked up osu a lot more recently and have been drilling it.

I know that from the way I'm describing it, it seems like a niche issue, but I feel like for a lot of people this would give them more control over the difficulty of the game.  Like I enjoy playing hard mode, but the QoL, or lack there of, is very apparent when you play on that diff

**Comment by theDetourist** [comment]
1. Coming with Week 7.
2. Already here, check out Scroll Speed on the Options.

**Comment by ggsalman** [comment]
Yes 😃👍

**Comment by Kade-github** [comment]
> 1. Coming with Week 7.
> 2. Already here, check out Scroll Speed on the Options.

^
