### ISSUE TITLE
Ok... I get how to mod the opposing characters into each week, but how about bf + gf? (Also tutorial background)

### ISSUE THREAD

**Issue by Msp030909** [KadeArchive/Kade-Engine#35]
I couldn't find my other issue so I just made another one. It doesn't seem like there is a bf/gf sprite in the images section of tutorial/week6 which is a big problem.

**Comment by WorstAquaPlayer** [comment]
Boyfriend and Girlfriend assets are in **assets/shared/images** by the name of **BOYFRIEND.png/.xml** and **GF_assets.png/.xml**
Week 6 BF and GF assets are in **assets/week6/images/weeb**

**Comment by Kade-github** [comment]
^

**Comment by Msp030909** [comment]
I did that. it didn't work?

**Comment by Msp030909** [comment]
nvm it worked

**Comment by Msp030909** [comment]
just not with week 4??? I put bfCar in there. What am I doing wrong?

**Comment by UnknownSkid** [comment]
> just not with week 4??? I put bfCar in there. What am I doing wrong?

idunno
