### ISSUE TITLE
Enhancement: ayo hitsounds though? 😳 

### ISSUE THREAD

**Issue by Sebyal** [KadeArchive/Kade-Engine#353]
Optional hitsounds on options and debug menu for better sync (a.k.a when note hit white line = note go click 😎)

**Comment by puyoxyz** [comment]
doesn't really fit fnf because the point is the bf singing *is* what's telling you that you pressed it good

**Comment by Sebyal** [comment]
Well fuck now im not pogging :(

**Comment by puyoxyz** [comment]
Oh sorry I misunderstood the issue, if it's for syncing charts as in when you're making a chart, then this may be useful? But it may be more useful to implement something like Etterna's clap assist (which plays a sound every time there's a note, not when you hit one) for that.
