### ISSUE TITLE
Bug Report: compiler error

### ISSUE THREAD

**Issue by TheRealDood** [KadeArchive/Kade-Engine#356]
so I'm trying to compile the game and I'm getting these
![Capture](https://user-images.githubusercontent.com/83540641/116813446-bd5cdd80-ab08-11eb-978f-6a7cc731d8a8.PNG)
I'm kinda stumped as I'm new to this and have no idea what to do.

**Comment by isakube** [comment]
There is no `assistance` here, hand over your `library versions`

also try comparing your source code to the repo. if you got all the right library versions then you might've tweaked some things before compiling.

**Comment by TheRealDood** [comment]
i had tweaked some things, but tired the unedited source code. I did the same thing and it gave me this error.

**Comment by puyoxyz** [comment]
this should be a [discussion](https://github.com/KadeDev/Kade-Engine/discussions)

@KadeDev close pls
