### ISSUE TITLE
Enhancement: add file path to Background Dancers

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#358]
add a file path to the Background Dancers. I'm making a mod and I'm making M.I.L.F have a different stage, and I'm changing the way the Background Dancers look, but I can't because there is no file path in the code 

`loadGraphic(Paths.image('limo/limoSunset','week4'));`

`var dancer:BackgroundDancer = new BackgroundDancer((370 * i) + 130, bgLimo.y - 400);`      

I can't pick a new file for the dancers

**Comment by puyoxyz** [comment]
Closing because answered in https://github.com/KadeDev/Kade-Engine/discussions/272
