### ISSUE TITLE
Idle animations not playing before the first arrow

### ISSUE THREAD

**Issue by N-Master789** [KadeArchive/Kade-Engine#368]
Discord: Floppa Gaming#8406
(This is just for note)
Operating system: Windows 7 x64
In the kade engine 1.4.2 there is issue that makes your opponent not play its idle animation before it hits first arrow

Looks like this glitch affects every instance of kade engine 1.4.2, because in the dark sheep tutorial mod, gf was not moving.
In my case when i loaded spookeez, kids were not moving until arrows start to drop. Looks like that happens randomly, because in the dadbattle, dad was moving and playing its idle animation as intended

I think this glitch happens when you compile mod and comes along with issue like described here ---> #251
There must be some kind of fix for this :/

**Comment by puyoxyz** [comment]
> I think this glitch happens when you compile mod

what do you mean by this? if you mean that you get the glitch when you compile it yourself but not when downloading a build from CI/releases, you have the wrong dependency versions or changed something in the code

**Comment by N-Master789** [comment]
> > I think this glitch happens when you compile mod
> 
> what do you mean by this? if you mean that you get the glitch when you compile it yourself but not when downloading a build from CI/releases, you have the wrong dependency versions or changed something in the code

I mean animation of the enemy character is not playing until there will be non-Must hit section
You know?

**Comment by puyoxyz** [comment]
nonono i get what you're saying i'm asking about specifically what i quoted but i get what the bug is

**Comment by N-Master789** [comment]
> nonono i get what you're saying i'm asking about specifically what i quoted but i get what the bug is

Bruh, i mean this seems to happen in modded version of KE, not vanilla or compiled one with untouched code. That glitch happened when i played my mod (code was touched) and Dark Sheep mod

**Comment by puyoxyz** [comment]
can you send the output of `haxelib list` pls?

**Comment by N-Master789** [comment]
> can you send the output of `haxelib list` pls?

![thing](https://user-images.githubusercontent.com/83514627/117102834-f14f3180-ad9a-11eb-8891-660f33096ea4.PNG)

**Comment by puyoxyz** [comment]
does the bug happen on builds from [appveyor](https://ci.appveyor.com/project/KadeDev/kade-engine-windows/build/artifacts)?

**Comment by N-Master789** [comment]
> does the bug happen on builds from [appveyor](https://ci.appveyor.com/project/KadeDev/kade-engine-windows/build/artifacts)?

1) I cannot download the build
2) That glitch does not happen in the gamebanana kade engine (Vanilla
)

**Comment by puyoxyz** [comment]
> > does the bug happen on builds from [appveyor](https://ci.appveyor.com/project/KadeDev/kade-engine-windows/build/artifacts)?
> 
>     1. I cannot download the build
> 
>     2. That glitch does not happen in the gamebanana kade engine (Vanilla
>        )

gamebanana hasn't been updated in years

**Comment by puyoxyz** [comment]
download this build instead since that one is still going https://ci.appveyor.com/project/KadeDev/kade-engine-windows/builds/39009397/artifacts

**Comment by haya3218** [comment]
someone did some messups and put the code in the SONG.notes[curStep/16] != null if statement
it should be OUTSIDE of that if statement for some reason

**Comment by puyoxyz** [comment]
> someone did some messups and put the code in the SONG.notes[curStep/16] != null if statement
> it should be OUTSIDE of that if statement for some reason

cool, make a pr?

**Comment by puyoxyz** [comment]
tested, this happens sometimes, but it's more like the idle animation goes for a little bit then stops looping. possible duplicate of #319

**Comment by haya3218** [comment]
> > someone did some messups and put the code in the SONG.notes[curStep/16] != null if statement
> > it should be OUTSIDE of that if statement for some reason
> 
> cool, make a pr?

cant github doesnt want me to but yeah ill try
