### ISSUE TITLE
Idea of making song parts

### ISSUE THREAD

**Issue by N-Master789** [KadeArchive/Kade-Engine#369]
Song part randomizer:
I mean like you have instrumental and voices version of starting part, that will make song always start from that part (without it all parts will be appearing randomly) , and then other parts the of song will be used randomly (And also this must be connected to song chart). Also there should be settings file that will manage connection of song parts to charts and will configure other things like possible repeats of some parts and etc.
I think also there must be fixed song part that will always appear in one moment and will not be affected by randomizing

That feature will definitely make songs more interesting because of different results.

**Comment by puyoxyz** [comment]
no vanilla song is made for this. the only place it'd make sense is a mod and if a mod requires that they can implement it themselves. -1

**Comment by theDetourist** [comment]
> 
> 
> no vanilla song is made for this. the only place it'd make sense is a mod and if a mod requires that they can implement it themselves. -1

This.

Also implementing that would be a goddamn nightmare.

**Comment by puyoxyz** [comment]
ok so we all agree this is no
