### ISSUE TITLE
Enhancement: Make artificially increasing features toggleable

### ISSUE THREAD

**Issue by kolleden** [KadeArchive/Kade-Engine#37]
I'm talking about 2 features here: the anti-mash system and modifying the HP gain/loss for inputs.

I feel like force changing the amount of HP you gain/loss for inputs is artificially increasing the difficulty of songs that use your engine. I'm willing to let mods like "Whitty", "Tricky" and "Hex" go because the changes are _somewhat_ balanced, but with the recent "Zardy - Foolhardly" mod the flaws of the system are shown:
 
You gain little to no HP from inputs, and lose alot by misses, it makes a somewhat challenging level basically impossible unless you near FC it. Allow in the Options menu to function by the normal HP gain/loss ratio the base game has to offer.

I dislike the anti-mash system, if someone wants to mash, let them mash. The mashing is always visible so its not like they fool anyone.
If that is such a problem for you, at least make the anti-mash system toggleable in the Options menu as well.

You made a hell of an engine, but as a mod creator you shouldn't force the playerbase to play by your own standards, let the engine be enjoyed by everyone, skilled or unskilled.

**Comment by Kade-github** [comment]
Currently, these values will be set in stone, but there will be some other things that will make the game easier/harder depending on a playstyle. Dw.
