### ISSUE TITLE
Bug Report:Chart Unplayable

### ISSUE THREAD

**Issue by UnknownSkid** [KadeArchive/Kade-Engine#370]
i downloaded test chart and voices but this pop up when i click "reload json"
![image](https://user-images.githubusercontent.com/81253195/116970688-b7a5fa00-acb8-11eb-8382-9307b5a2f52d.png)
and when i look into "freeplaysonglist" there are numbers i dont know what are these numbers doing

**Comment by Kade-github** [comment]
test.json doesn't exist or it wasn't there at compile time.

**Comment by UnknownSkid** [comment]
> test.json doesn't exist or it wasn't there at compile  
time.

No I mean I added the chart to data and I can't play it

**Comment by Kade-github** [comment]
you probably didn't do it RIGHT

**Comment by Kade-github** [comment]
you should make this a [discussion](https://github.com/KadeDev/Kade-Engine/discussions)

**Comment by UnknownSkid** [comment]
> you probably didn't do it RIGHT

Then tell me how do I do it

**Comment by UnknownSkid** [comment]
> you should make this a [discussion](https://github.com/KadeDev/Kade-Engine/discussions)

?
