### ISSUE TITLE
Bug Report: Switching must hit sections doesn't work (Chart State)

### ISSUE THREAD

**Issue by ItsJayPM** [KadeArchive/Kade-Engine#375]
## What version of the game are you using? Look in the bottom left corner of the main menu.
1.4.2 (Latest GitHub Commit)
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Switching the must hit section no longer works.
## Please describe your issue. Provide extensive detail and images if possible.
Switching must hit section doesn't work. I know how to fix this bug, just not feeling like cloning the repo on github for a 1 line fix. At some point the label for the must hit sections was changed, however the case switch that handles it being pressed was not updated in accordance. Simply update that and it will work again.

**Comment by puyoxyz** [comment]
> just not feeling like cloning the repo on github for a 1 line fix.

you can go to the file on github, press the edit button, edit it and make a pr without cloning it lol

**Comment by ItsJayPM** [comment]
oh, my mistake. Here's a pull request then https://github.com/KadeDev/Kade-Engine/pull/376
