### ISSUE TITLE
[TO ADD] Enhancement: a bar to show how far you are into the song or something

### ISSUE THREAD

**Issue by arceuss** [KadeArchive/Kade-Engine#38]
![image](https://user-images.githubusercontent.com/28229451/111929238-62e94f80-8a7b-11eb-9bf5-1b220723f365.png)
image taken from stepmania but it can be something like this

**Comment by Sebyal** [comment]
Sir, your reddit gold? where is it? you deserve it

**Comment by Kade-github** [comment]
ye probably going to add this

**Comment by arceuss** [comment]
awesom

**Comment by Kade-github** [comment]
Complete in 1.2.2
