### ISSUE TITLE
Bug Report: Modcharts aren't working.

### ISSUE THREAD

**Issue by ILuvGemz** [KadeArchive/Kade-Engine#389]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## Please describe your issue. Provide extensive detail and images if possible.

I have done exactly what the Modcharts.md told me to do. I had put the modchart into assets\data\(song name), then named it modchart.lua, with spelling double-checked, but I wasn't able to make the mods work. I have tried to find the problem, but it didn't work. I couldn't find the issue here. Is there something I had done wrong, or is an actual issue?

![image](https://user-images.githubusercontent.com/76889022/117529556-5bb5db00-b002-11eb-9ce9-23794e6f01d0.png)

https://user-images.githubusercontent.com/76889022/117529599-915ac400-b002-11eb-83ff-852e942cf8cc.mp4

**Comment by Kade-github** [comment]
can you send the modchart.lua?
