### ISSUE TITLE
[TO ADD] Enhancement: Start from section

### ISSUE THREAD

**Issue by Toppat-dalek** [KadeArchive/Kade-Engine#39]
I want to be able to start the song at a specific section so that I don't have to go through the entire song every time. It's been a pain to make mods for my friends and I talked with other modders about it on the fnf modding discord server (I'll be it briefly) and it seems this is a common annoyance. I was thinking it might be some sort of button with a text box next to it saying which section you want to start at. I don't know how hard that would be though, and it's understandable if you have a lot on your plate. I also don't know how hard this would be, so if it's too hard, no sweat. I just taught I'd chuck my two sents in.

**Comment by Jaduplex** [comment]
IMO i think this would be better if there was just a "clear song" button and there was like a tick box next to it to CONFIRM you wanted to do it

**Comment by Kade-github** [comment]
when week7
