### ISSUE TITLE
File Report:No Modchart

### ISSUE THREAD

**Issue by UnknownSkid** [KadeArchive/Kade-Engine#393]
All files **are located in** `assets/data/song/`

Modchart Lua File should be in `assets/data/song/modchart.lua` **exactly**

i cant find modchart.lua in songs

**Comment by puyoxyz** [comment]
You have to create it, and song refers to the name of the song (i.e. `assets/data/milf/modchart.lua`

**Comment by UnknownSkid** [comment]
> You have to create it, and song refers to the name of the song (i.e. `assets/data/milf/modchart.lua`

Oh ok

**Comment by ooor28** [comment]
i just typed this so i can get a shoutout on github-updates

**Comment by isakube** [comment]
> i just typed this so i can get a shoutout on github-updates

lol
