### ISSUE TITLE
Bug Report&Enchantment

### ISSUE THREAD

**Issue by UnknownSkid** [KadeArchive/Kade-Engine#397]
1.When i Change Character it Crashes The Game
2.add an option to hide girlfriend
3.icons for:senpai,bfpixel,MADsenpai,spirit,girlfriend
4.PLS ADD THIS PLSSS ADD AN OPTION TO HIDE OPPONENT ARROWS
5.add logo
6.custom notes speed
7.i dont know where is "week names.txt" or whatever its named so please add it
8.week 7 dont fix the in ground glitch character so fix that
9.d e l e t e  p a u s e  a l t
10.
![spirit](https://user-images.githubusercontent.com/81253195/117540404-8d816e80-b00f-11eb-97c9-d02e428f0455.png)
remake spirit

**Comment by puyoxyz** [comment]
you've listed about 10 separate things in one issue. that's not how issues work. make a separate issue for each bug/suggestion

**Comment by isakube** [comment]
0. daniel's right.
1. f.
2. eh maybe
3. if you mean death icons, not how it was in the original.
4. but why
5. what do you mean? in the title screen? i think there was a pr for that somewhere but idk
6. Options > Gameplay > Scroll Speed
7. The week names are hardcoded. You need to download and compile the source code to change week names. (Opera stop red squigglying week)
8. i literally have no idea
9. how dare you, do not disrespect the pauseAlt
10. how would we remake spirit?

**Comment by UnknownSkid** [comment]
> 1. daniel's right.
> 2. f.
> 3. eh maybe
> 4. if you mean death icons, not how it was in the original.
> 5. but why
> 6. what do you mean? in the title screen? i think there was a pr for that somewhere but idk
> 7. Options > Gameplay > Scroll Speed
> 8. The week names are hardcoded. You need to download and compile the source code to change week names. (Opera stop red squigglying week)
> 9. i literally have no idea
> 10. how dare you, do not disrespect the pauseAlt
> 11. how would we remake spirit?

Why are gae
