### ISSUE TITLE
[TO ADD] Enhancement: Input recorder

### ISSUE THREAD

**Issue by Sebyal** [KadeArchive/Kade-Engine#40]
A button that plays the song on the debug menu, but it records the inputs made until you make it stop (maybe put a keybind for it) and puts it on the chart, specifically for making it easier to sync up charts

**Comment by Kade-github** [comment]
oh thats neat. sure

**Comment by Sebyal** [comment]
Only problem might be the long notes

**Comment by Kade-github** [comment]
Done in the latest commit
