### ISSUE TITLE
Bug Report: Alt Animation in charting state doesn't stay checked after going to another section then back

### ISSUE THREAD

**Issue by Dergoshka** [KadeArchive/Kade-Engine#404]
Hello, today I downloaded the source code of this mod and saw an error that bothers me.
I created my own character and added animation to it, there are also alt animations. The problem I encountered was when I needed to edit the notes for a level. I need the character's animation to change at a certain point, and to do this, in the debug mode, which turns on when you press the number 7 on the keyboard, when the week is selected, in the "section data" tab, put a check mark on "Alternate Animation". The problem is that this check mark disappears and is not saved when exiting the debug mode or when switching the Section to the A and D keys.
Also, if in the fifth week at the level of "Cocoa" in the debug mode, press the spacebar to listen to music, the game freezes dead.

I also tried to do this in the normal version of this mod, without its own materials, everything also happens. The mod was exported for the browser.

**Comment by puyoxyz** [comment]
the checkmark is per section

**Comment by puyoxyz** [comment]
from #439:

> when charting and enabling altAnim, it disables after moving sections
> 
> seems in Charting.hx on line 502 you put
> 
> `case "Alt Animation":`
> instead of
> `case "Alternate Animation":`

(@bbpanzu)

**Comment by Dergoshka** [comment]
Thank you for the help, everything works now!
In ChartingState.hx I changed on line  `case "Alt Animation"` to `case "Alternate Animation"` and the bug disappeared.

**Comment by puyoxyz** [comment]
Just because that fix worked for you doesn't mean it has been implemented into the source code. Reopening
