### ISSUE TITLE
Resume button disappears if you move from it in the pause menu so you can only restart or exit to menu 

### ISSUE THREAD

**Issue by PixelExplorer** [KadeArchive/Kade-Engine#419]
It's hella annoying, if i accidentally scroll down from resume, it just disappears and now i have to restart a whole song or exit

**Comment by theDetourist** [comment]
The Resume button would only disappear if you changed the Offset @ the Pause Menu, if that's exactly what's happening, it's on purpose.

**Comment by puyoxyz** [comment]
(closing, see theDetourist's comment. reopen if you're sure that you aren't changing the offset (left arrow/right arrow))
