### ISSUE TITLE
Bug Report: Week 6 Wrong start speech

### ISSUE THREAD

**Issue by Toppat-dalek** [KadeArchive/Kade-Engine#42]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows (`x86_64`)
## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1 FNF 1.2.2 Kade Engine
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Just play week 6
## Please describe your issue. Provide extensive detail and images if possible.
nothing big, It's just that whenever you play week 6 it says "1, 2, 3, Go!" instead of "1, 2, 3, Date!". I would assume it's some sort of error with the UI.

**Comment by Kiffolisk** [comment]
wait a second please

**Comment by Kiffolisk** [comment]
huh. i looked at the code and its not meant to do that

**Comment by WorstAquaPlayer** [comment]
Can be fixed by merging https://github.com/ninjamuffin99/Funkin/pull/499

**Comment by Kade-github** [comment]
Fixed in the latest commit
