### ISSUE TITLE
Bug Report: FlxBar: max cannot be less than or equal to min, im new to coding and don't know how to fix this

### ISSUE THREAD

**Issue by Cuph3ad-tech** [KadeArchive/Kade-Engine#422]
kade engine 1.4.2 version. windows 10 x64, i have started learning to code kade engine recently, and i found this issue, is there any fix?

**Comment by theDetourist** [comment]
Does that happen when you play MILF or the Tutorial? If so, update to the [latest nightly version](https://ci.appveyor.com/project/KadeDev/kade-engine-windows/build/artifacts).
