### ISSUE TITLE
Enhancement: autoplay if not in the game already

### ISSUE THREAD

**Issue by arceuss** [KadeArchive/Kade-Engine#44]
since most 4k games include it
ik fnfbot exists but it can be clunky to setup and itd be nice to have similar ingame

**Comment by Kiffolisk** [comment]
huh

**Comment by LiquidMelons** [comment]
> huh

Autoplay is just that-
autoplay.
In other words, automatically playing. :)

**Comment by Kade-github** [comment]
im good, if you want an autoplay https://github.com/KadeDev/FNFBot is good for literally everything.

Kade Engine is meant for competitive use and playing.
