### ISSUE TITLE
Bug Report: Copy Last not working correctly

### ISSUE THREAD

**Issue by SkyanUltra** [KadeArchive/Kade-Engine#450]
Hi there, i'm trying to do a rechart on a kade engine port of mid-fight masses which is on 1.4.2, the current latest version.

Using copy last (i noticed it started happening around when i was on charts that were on a higher section length (32, for me specifically) causes notes to just not show up where they're supposed to, most of the time appearing later in the chart for seemingly no reason. To fix it, I had to replace all of the notes by hand.

I have a version of the chart before i fixed it, it happens around section 26 of the song specifically. You'll notice the chart itself in the debug menu is perfectly normal, but in testing it bugs out and shows up much later meshed with part of the chart i hadn't done yet.
[casanova-easy.zip](https://github.com/KadeDev/Kade-Engine/files/6472920/casanova-easy.zip)

**Comment by SkyanUltra** [comment]
there's also an issue with whenever you remove a note on the player's side, the CPU's side with the same note also gets deleted.

**Comment by puyoxyz** [comment]
> there's also an issue with whenever you remove a note on the player's side, the CPU's side with the same note also gets deleted.

make separate issue 4 this

**Comment by Kade-github** [comment]
> there's also an issue with whenever you remove a note on the player's side, the CPU's side with the same note also gets deleted.

same thing with og fnf
