### ISSUE TITLE
Everytime, this pop up message

### ISSUE THREAD

**Issue by ZenusPurity** [KadeArchive/Kade-Engine#451]
If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Windows x86

## What version of the game are you using? Look in the bottom left corner of the main menu.

KE 1.4.2 latest commit

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

I try to compile the code

## Please describe your issue. Provide extensive detail and images if possible.

Hello, I've been getting this pop up every time I try and compile the source code. 
![image](https://user-images.githubusercontent.com/82642362/118137439-c8343e00-b437-11eb-9744-7a8eca4bd53f.png)

The only thing I changed from the code is that I added CHANGELOG.md back into the main folder. Otherwise, I just compiled the thing up as normal.

**Comment by puyoxyz** [comment]
try again with latest source we fixed the changelog thing

**Comment by ZenusPurity** [comment]
> try again with latest source we fixed the changelog thing

Do I have to download it again?

**Comment by puyoxyz** [comment]
Yes

**Comment by ZenusPurity** [comment]
Alright thank you!
