### ISSUE TITLE
The application was unable to start correctly (0xc0000142). Click OK to close the application.

### ISSUE THREAD

**Issue by ZenusPurity** [KadeArchive/Kade-Engine#453]
Same pop up 
![image](https://user-images.githubusercontent.com/82642362/118153189-31bc4880-b448-11eb-8c83-9bd472982020.png)

I downloaded the latest thing and it still didn't work

**Comment by puyoxyz** [comment]
are you on a 32-bit or 64-bit os?

**Comment by ZenusPurity** [comment]
> are you on a 32-bit or 64-bit os?

64bit

**Comment by ZenusPurity** [comment]
Anything I could maybe have done wrong? I installed all necessary components for it, it still keeps appearing with that pop up

**Comment by puyoxyz** [comment]
Can you send a screenshot of the output after running it?

**Comment by ZenusPurity** [comment]
![image](https://user-images.githubusercontent.com/82642362/118299608-8a0c4c80-b513-11eb-9b47-64ea9b6bb701.png)
Uh I don't know what happened but it ran, though the pop up still happened?? I don't fucking know what's happening lol

**Comment by isakube** [comment]
Okay somebody else has this issue we need to figure this out lol

**Comment by theDetourist** [comment]
The other issue mentioned also talks about issues with the audio driver failing (and breaking the game, as expected), besides, 0x0142 is a very common problem that a lot of Windows users have with many different programs so it's probably not a "Kade Engine" issue, but an issue with your defective Windows copy.

Other than trying /sfc scannow, I'd recommend you to return to a Restore Point so you rollback recent updates or complex programs you installed recently and try again. If that doesn't work, I don't really know what will.

**Comment by puyoxyz** [comment]
> The other issue mentioned also talks about issues with the audio driver failing (and breaking the game, as expected), besides, 0x0142 is a very common problem that a lot of Windows users have with many different programs so it's probably not a "Kade Engine" issue, but an issue with your defective Windows copy.
> 
> Other than trying /sfc scannow, I'd recommend you to return to a Restore Point so you rollback recent updates or complex programs you installed recently and try again. If that doesn't work, I don't really know what will.

`sfc /scannow`*, also `DISM /Online /Cleanup-Image /CheckHealth`
