### ISSUE TITLE
Bug Report: Kade Engine 1.2.2 and above not compiling on Windows properly due to Discord RPC, even when everything is installed correctly.

### ISSUE THREAD

**Issue by jelleejamm** [KadeArchive/Kade-Engine#465]
Title says it all. I installed everything correctly, every haxe library, every VS2019 dependency, everything. Nothing fixes this damn compiling issue that reads:
"source/Discord.hx:5: characters 8-30 : Type not found : discord_rpc.DiscordRpc
source/Discord.hx:14: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:24: characters 4-14 : Type not found : DiscordRpc
source/Discord.hx:29: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:34: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:39: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:75: characters 3-13 : Type not found : DiscordRpc"

If there is no way to fix this, you should make a Discord RPC-less Kade Engine for those who can't compile the engine with Discord RPC.

**Comment by puyoxyz** [comment]
This was fixed in ~~1.4.3~~ 1.4.2.

**Comment by jelleejamm** [comment]
1.4.3 doesn't exist though??

**Comment by puyoxyz** [comment]
Sorry, I'm really dumb, I meant 1.4.2. Edited

**Comment by jelleejamm** [comment]
I was compiling 1.4.2 however.

**Comment by jelleejamm** [comment]
![image](https://user-images.githubusercontent.com/78974994/118386918-7f40dd00-b623-11eb-85c8-6d75ea1c2d9c.png)

**Comment by puyoxyz** [comment]
did you follow the [building instructions](https://kadedev.github.io/Kade-Engine/building) correctly? you might not have installed discord_rpc right (you do it through git, not `haxelib install discord_rpc`)

and does it work if you just build the latest commit/source? (if that doesn't fix it)

**Comment by jelleejamm** [comment]
I did git install discord_rpc, the current master source code has the exact same error.
![image](https://user-images.githubusercontent.com/78974994/118406289-176eae80-b684-11eb-8643-d6c7be32ee9b.png)

**Comment by puyoxyz** [comment]
No, that's not what I meant, oh my god, look at the building instructions, I'm going to cry

**Comment by jelleejamm** [comment]
I legit followed them all
what the fuck am I doing wrong I am going to lose my fucking mind

**Comment by ghost** [comment]
```
haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
```
Run this.

**Comment by jelleejamm** [comment]
I did run it before, same error.

**Comment by ghost** [comment]
Run it again.
