### ISSUE TITLE
Enhancement: Option to enable/disable the R reset button

### ISSUE THREAD

**Issue by arthu-rguo** [KadeArchive/Kade-Engine#468]
From what I understand, this feature was disabled because people kept hitting it by accident when mashing buttons very intensely. However, I think the option to die instantly without having to go through a menu is a pretty convenient thing to have. So, I suggest it be brought back as soon as possible, either made toggleable through options or simply rebound to a safer key.

Also, if there are no plans to bring the blue balls button back, could someone tell me if there's a way to enable it for myself in the code? I'm really missing this feature, but I'm new at Haxe and I wasn't able to figure it out myself. Thanks.

**Comment by Jaduplex** [comment]
on it

**Comment by puyoxyz** [comment]
Also maybe an option to set it to either R or ~ because ~ is what people might be used to from osu

**Comment by Jaduplex** [comment]
#490 done

**Comment by Jaduplex** [comment]
> Also maybe an option to set it to either R or ~ because ~ is what people might be used to from osu

we'll probably do that when we merge in week 7 shit

**Comment by puyoxyz** [comment]
resolved by #490
