### ISSUE TITLE
Bug Report: Kade Engine.exe doesn't open.

### ISSUE THREAD

**Issue by IndigoVoidigo** [KadeArchive/Kade-Engine#469]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Windows x86_64

## What version of the game are you using? Look in the bottom left corner of the main menu.

KE 1.4.2

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

I executed "lime test windows", and the terminal just went back to the directory after
"Link: ApplicationMain.exe
   Creating library ApplicationMain.lib and object ApplicationMain.exp".

## Please describe your issue. Provide extensive detail and images if possible.

I thought it was storage, so I freed some. It didn't work. I know I have a bunch of shit on my desktop.

https://user-images.githubusercontent.com/78701030/118344841-79051080-b4fe-11eb-8234-f245fa48235e.mp4

**Comment by puyoxyz** [comment]
what happens if you open it with the commandline? (`cd export/windows/bin` while in source code dir then `"Kade Engine.exe"`)

**Comment by IndigoVoidigo** [comment]
> what happens if you open it with the commandline? (`cd export/windows/bin` while in source code dir then `"Kade Engine.exe"`)

Tried just now. Nothing.

**Comment by shaderw0lf** [comment]
i had similar issue but fixed it
try to download source code and replace some files from downloaded sc to your (better just drag your files to some temp folder than replace)
do it until game will start
maybe you will find .hx file what do troubles

i hope i explained clearly

**Comment by puyoxyz** [comment]
oh, is this a modified version of the source code? (i should've asked that first, sorry)

if it is, can you try compiling unmodified source code and see if that works? if it works, it's not an issue with kade engine

**Comment by shaderw0lf** [comment]
honestly idk it's modified version or not but usually games don't working when you something tried to add... )
(like in my situation)

**Comment by puyoxyz** [comment]
well;;;; can you;;;; try compiling unmodified source code;;;; and see if that works;;;

**Comment by IndigoVoidigo** [comment]
16 days later, still doesn't open.

**Comment by puyoxyz** [comment]
Yes, 16 days later, because I **asked you a question and added the question label**. We **cannot help you if we ask you something and you don't respond**. Locking since you clearly are not willing to help us help you.
