### ISSUE TITLE
Bug Report: Outdated when latest

### ISSUE THREAD

**Issue by getkirill** [KadeArchive/Kade-Engine#471]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
x86_64

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.4.2

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Download latest. And get outdated message right after pressing enter

## Please describe your issue. Provide extensive detail and images if possible.
Outdated message when latest version

**Comment by isakube** [comment]
this is because of #447, we're planning on releasing 1.4.3 soon.

**Comment by puyoxyz** [comment]
as prokube said, caused by #447, use latest appveyor CI/development build if you don't want to get this message
