### ISSUE TITLE
Bug Report:  Hold notes look weird on faster scroll speeds.

### ISSUE THREAD

**Issue by Fgm320-9** [KadeArchive/Kade-Engine#473]
My OS is windows 10 pro 64 bit.

Im using kade engine ver 1.4.1-nightly2

I hate looking at it, Please fix

https://cdn.discordapp.com/attachments/577123863125688359/843125611190288384/bandicam_2021-05-15_09-50-44-593.jpg

**Comment by puyoxyz** [comment]
This has already been fixed in the latest version(s)
