### ISSUE TITLE
Bug Report: arrows do not glowing when hit

### ISSUE THREAD

**Issue by edgardeivis** [KadeArchive/Kade-Engine#475]
i don't know why, instead of glowing they just play the note pressed without the glow
i don't know if i said this right, my english is getting bad

**Comment by Kade-github** [comment]
fixed in https://github.com/KadeDev/Kade-Engine/commit/6b809a9a971632a4c547d20e9d2e6ef76a89ec8b

**Comment by edgardeivis** [comment]
thank you kade
