### ISSUE TITLE
[MAYBE?] Enhancement: FPS Option

### ISSUE THREAD

**Issue by LiquidMelons** [KadeArchive/Kade-Engine#48]
What the title says, an option to change FPS from 120 to 60. Some of us have potato PC's which have a stroke running a game at 120 FPS so it would be a nice feature. Even if 120 FPS is much better (especially for those aiming for high acc) the extra frames won't do a person any good if their pc freaks out. There could even be a 240 FPS option for those who want higher precision and have computers that can handle it which I think is possible since I've seen other mods with a 240 framerate I believe. Not sure if any other options like 30 or 360 FPS would be needed but it's your engine so you do you.

Have a good day :p

**Comment by Kade-github** [comment]
Already done.
