### ISSUE TITLE
Misses don't show up on the counter & Old Input glitches as New Input.

### ISSUE THREAD

**Issue by Blantados** [KadeArchive/Kade-Engine#49]
Title speaks for itself. This started happening after updating to 1.3

![image](https://user-images.githubusercontent.com/22408850/112102719-a8289100-8be3-11eb-918e-8318e04941e6.png)

**Comment by Kiffolisk** [comment]
dunno. try actually hitting notes incorrectly instead of waiting and see if they count as misses

**Comment by Kiffolisk** [comment]
checked the code. it's meant to work correctly.

**Comment by Blantados** [comment]
Wait so does this mean it's fixed or is it supposed to be like this? I can't hit notes incorrectly either since it uses the new input even though I selected old input in the settings.

**Comment by Kiffolisk** [comment]
it says "old input" because you have new input on. also its meant to be like that it seems

**Comment by Kiffolisk** [comment]
its pretty confusing, in the options menu for some reason the options are reversed

**Comment by LiquidMelons** [comment]
> its pretty confusing, in the options menu for some reason the options are reversed

It used to be like that before but it shouldn't anymore, If it says "New Input," you are using the new input. Check if you're updated to 1.3
As for the Input glitch that Blantados was talking about, I have no idea

**Comment by Kiffolisk** [comment]
it's not an input glitch. its literally how it works

**Comment by Kade-github** [comment]
Bads and Shits count as combo drops, but they are not misses.
