### ISSUE TITLE
camera zooming in

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#496]
just when i hit the first note the camera zooms in and the arrows plus the healthbar is half visible.

before:
![before](https://user-images.githubusercontent.com/55812082/118476637-6ebd5f00-b716-11eb-9666-c156802a52d5.png)
after:
![after](https://user-images.githubusercontent.com/55812082/118476664-77159a00-b716-11eb-9126-4ee593bd77aa.png)

**Comment by puyoxyz** [comment]
probably a bug with the mod you're playing. report the bug to mod creators first and if they say it's a KE bug then reopen the issue and include their reply
