### ISSUE TITLE
Bug Report: Skipping Notes

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#498]
So I Been Seeing This Problem Which Is Kinda Annoying For People That Try FC Mods Made In Kade Engine
You Know What It Is.Its Double Notes For Some Reason It Doesn't Register Them And It Counts As A Combo Break Can You Fix That KadeDev

**Comment by puyoxyz** [comment]
if you mean chords, those are fixed. you're using an old version of Kade Engine. reopen if this issue still happens on the latest development builds
