### ISSUE TITLE
Bug Report: Each week is missing one song from the track list

### ISSUE THREAD

**Issue by Purrpy** [KadeArchive/Kade-Engine#499]
Hello

I am very new to this and not sure what I'm doing, but I feel like this isn't how it's supposed to be? I didn't edit anything even near the track list, but for some reason every week is missing a track in the list of tracks. They're still there if you play the week or go to freeplay, but not in the tracks list in the week selection menu.

To see if this was something I did, I tried to redownload the source code but my computer said the file was invalid and wouldn't let me open it. I eventually got it to let me do that, but each time I tried there was a random set of files missing? So now I'm back to trying to fix this issue instead of starting over. I have no idea what to do or how to fix this.

**Comment by puyoxyz** [comment]
You seem to be having some issues with downloading the source code; please use `git clone https://github.com/KadeDev/Kade-Engine.git` instead to clone the source code. (If you are on Windows, download git [here](http://git-scm.com/). If you are on macOS, type `git` and macOS will install it for you. If you are on Linux, install it with your package manager)

Also, download the latest source code, not 1.4.2's source code. (the clone command above does that for you). 1.4.2 is very outdated right now.

Reopen if bug still happens on **latest source code, cloned using `git` and not downloading the zip from GitHub's website**
