### ISSUE TITLE
Cant Delete Notes

### ISSUE THREAD

**Issue by UnknownSkid** [KadeArchive/Kade-Engine#50]
im clickin on a note and i cant delete it pls fix that

**Comment by Kiffolisk** [comment]
time to fix !!!!

**Comment by UnknownSkid** [comment]
> time to fix !!!!

are you the developer?

**Comment by Kiffolisk** [comment]
i am contributor

**Comment by UnknownSkid** [comment]
> i am contributor

umm
idk (i dont know) what that means

**Comment by Kade-github** [comment]
fixed in the latest commit

**Comment by UnknownSkid** [comment]
> fixed in the latest commit

what?

**Comment by xiiixvv** [comment]
Are you like an idiot when it comes to Github? lmao
