### ISSUE TITLE
Bug Report: I can't test by open the app(I used soure code)

### ISSUE THREAD

**Issue by TON-Games** [KadeArchive/Kade-Engine#510]
I was making my mod when I want to test it I type "lime test windows" in command prompt(I download haxelib and haxe pixle already)
and it look like this:
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/PlayState.hx:249: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:145: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:180: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:221: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:515: characters 8-18 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:483: characters 37-56 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:484: characters 31-47 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/hscript/2,4,0/hscript/Interp.hx:646: characters 10-42 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/newgrounds/1,1,4/lib/Source/io/newgrounds/components/ScoreBoardComponent.hx:55: characters 24-44 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/newgrounds/1,1,4/lib/Source/io/newgrounds/components/ScoreBoardComponent.hx:55: characters 49-66 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/CSV.hx:140: characters 7-27 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/JsonHelp.hx:93: characters 21-38 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/ParseRules.hx:635: characters 7-32 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/ParseRules.hx:748: characters 16-33 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/ParseRules.hx:766: characters 7-22 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/ParseRules.hx:766: characters 26-41 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/ParseRules.hx:771: characters 18-33 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/ParseRules.hx:771: characters 38-53 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/ParseRules.hx:809: characters 24-39 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/ParseRules.hx:810: characters 24-39 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/ParseRules.hx:819: characters 12-25 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/ParseRules.hx:820: characters 12-27 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/ParseRules.hx:821: characters 12-28 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/ParseRules.hx:822: characters 12-26 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/ParseRules.hx:829: characters 12-28 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/ParseRules.hx:830: characters 12-27 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/ParseRules.hx:831: characters 12-25 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/ParseRules.hx:832: characters 12-26 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/ParseRules.hx:863: characters 16-34 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/ParseRules.hx:878: characters 28-46 : Warning : Std.is is deprecated. Use Std.isOfType instead.
C:\Users\panup\Downloads\kine\Kade-Engine-1.4-KE\export\release\windows\obj>setlocal enabledelayedexpansion
Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths
Error: Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths

PLZ FIX IT

**Comment by puyoxyz** [comment]
you're missing some visual studio components and/or need to update them. see [this part of the building instructions](https://kadedev.github.io/Kade-Engine/building#windows-only-dependencies-only-for-building-to-windows-building-html5-on-windows-does-not-require-this)
