### ISSUE TITLE
Enhancement: Add a fixed scroll speed for notes.

### ISSUE THREAD

**Issue by xiiixvv** [KadeArchive/Kade-Engine#52]
FNF always changes the scroll speed of its notes based off of a song's BPM. In other rythm games I play, like osu!mania and etterna, there is a option to have a fixed scroll speed that applies to any and all songs. Adding this feature would make certain charts (Like from both whitty and tricky mods) easier to read as the notes come at a fixed pace that I set up instead of it being based off of the BPM.

**Comment by blackm1n** [comment]
BPM and Note Speed are 2 different things in FNF. BPM doesn't mean how fast the notes go. That's the job for Note Speed.
Examples:
Milf (Hard): BPM - 180, Note Speed - 2.6
Ballistic (Hard): BPM - 210, Note Speed - 2.6 (same as Milf)
Madness (Hard): BPM - 212 (practically same as Ballistic), Note Speed - 3
As you can see they're all rather similar, and I doubt the fixed Note Speed will get added.

**Comment by Kade-github** [comment]
pr is being worked on
