### ISSUE TITLE
Master File zip is corrutped.

### ISSUE THREAD

**Issue by HyperXinon** [KadeArchive/Kade-Engine#526]
Im trying to download the master of kade engine but the file is broken, i tried it 2 times now which both give out the same error

![Problem 1](https://user-images.githubusercontent.com/62767605/119160837-f5e13e80-ba58-11eb-92da-b2bd57483d46.PNG)
![Problem 2](https://user-images.githubusercontent.com/62767605/119160841-f679d500-ba58-11eb-90d4-f066a61f1c1e.PNG)

On the Problem 2.png file the translation means:
This Folder cannot be opened.

The Zip-Compromised Folder "File Path" Is Invalid.

**Comment by shaderw0lf** [comment]
try to redownload or unzip with 7zip...??
