### ISSUE TITLE
Options i Want To Be Added 

### ISSUE THREAD

**Issue by UnknownSkid** [KadeArchive/Kade-Engine#53]
Fullscreen Option
Notes Speed Option (When On Normal:Level Speed Notes)
oh yea must be charting menu in pause (because some of people dont know about the charting menu)
New icons (that must be an option) (like FNFFPSPlus Have. For Example:Winning icon,Lose icon (for the icons that dont have Losing icon))
Only Your Notes Option (this will show only notes that go to you not to the enemy)
No Combos Option (hide combos)
Reset To Default Chart in Chart Menu (this will reset everything to normal when you did something wrong i mean when you are charting a level and you dont want to be charting just reset to the original chart (MUST NOT BE SAVED OR THIS WILL NOT WORK))
Old icons Options (Only Dad And The Old Boyfriend icon)
Controls Option (Changes The Keybinds)

**Comment by blackm1n** [comment]
Fullscreen: Press Alt+Enter
Note Speed: Press 7, go to song and change it yourself
Reset to Default Chart: Press "Reload JSON"

**Comment by Kiffolisk** [comment]
also fullscreen already exists iirc

**Comment by LiquidMelons** [comment]
Fullscreen already exists manz

**Comment by UnknownSkid** [comment]
> also fullscreen already exists iirc

where?

**Comment by Kiffolisk** [comment]
there's a key you can press. forgot what it was but i think it was like F11 or whatever

**Comment by blackm1n** [comment]
> > also fullscreen already exists iirc
> 
> where?

Alt+Enter, I literally said it

**Comment by LiquidMelons** [comment]
F11 doesn't work for FNF
Press F (Only works during the startup however)
Or Alt + Enter
Dont know how you've been playing without fullscreen this whole time tho

**Comment by Kade-github** [comment]
1. already in the game
2. already being worked on
3. maybe? but that would be an incredibly low priority.
4. no
5. I would add an entire hide everything option tbh
6. already in the game
7. why? I don't get that one
8. that's going to be added in week 7 so we're just waiting for that.

**Comment by UnknownSkid** [comment]
> 1. already in the game
> 2. already being worked on
> 3. maybe? but that would be an incredibly low priority.
> 4. no
> 5. I would add an entire hide everything option tbh
> 6. already in the game
> 7. why? I don't get that one
> 8. that's going to be added in week 7 so we're just waiting for that.

there is no combo option.you can just smear the textures (i dont understand english very well)

**Comment by UnknownSkid** [comment]
> F11 doesn't work for FNF
> Press F (Only works during the startup however)
> Or Alt + Enter
> Dont know how you've been playing without fullscreen this whole time tho

its working
