### ISSUE TITLE
Bug Report: I don't know how to fix pleas help

### ISSUE THREAD

**Issue by A1foostbit** [KadeArchive/Kade-Engine#537]
so I was building the game and It said this D:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
D:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access...... I don't know how to fix it pleas help

**Comment by ghost** [comment]
It's not an error.
Game should still compile fine.
