### ISSUE TITLE
Bug Report: Debug menu not working properly 

### ISSUE THREAD

**Issue by Weege3** [KadeArchive/Kade-Engine#55]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86_64)

## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
no

## Please describe your issue. Provide extensive detail and images if possible.
whenever I try to change the character in the debug menu the game just crashes, not displaying any error messages

**Comment by Kiffolisk** [comment]
.

**Comment by Kade-github** [comment]
cool.

**Comment by UnknownSkid** [comment]
> cool.

COOL???? NOT DELETING NOTES IS COOL??????!!!!!!

**Comment by Sebyal** [comment]
yes.

**Comment by xiiixvv** [comment]
> 
> 
> > cool.
> 
> COOL???? NOT DELETING NOTES IS COOL??????!!!!!!

Jesus can you shut up?
