### ISSUE TITLE
Game crashes creating or finding an offset file.

### ISSUE THREAD

**Issue by Burger-Gaming** [KadeArchive/Kade-Engine#557]
Unfortunately, I don't know exactly how this happened, but I was trying to load a song but it crashed and when I looked at the logs it said that it could or could not find an offset file. This happens either way. I changed absolutely nothing in the code to cause the crash to happen, but I might think its something else.

**Comment by theDetourist** [comment]
OS? Game version? Platform (desktop, html5) ?Did you change something, if so, what?

**Comment by Burger-Gaming** [comment]
This was on Windows 10, version 1.4.2, and on desktop. I don't recall changing anything but it might have been something to do with PlayState.hx.

**Comment by puyoxyz** [comment]
**if this happens every crash, not just the first time (try again to see if it still appears, if not then it's a different issue that has nothing to do with the offset file**: You don't have permissions to access the `assets` directory. If you're on Windows, make sure your game is NOT inside another user's directory. (or just move the game inside your user directory to be sure. this includes Desktop, My Documents, Downloads, etc...)

Reopen if you're *sure* this isn't a permission issue
