### ISSUE TITLE
Enhancement: Make it Possible to Toggle Modcharts in Settings

### ISSUE THREAD

**Issue by NoiceBroice** [KadeArchive/Kade-Engine#558]
For mods up and coming, they can include very fun and insane modded effects during the chart

However, some people could want to play the mod and not have their eyes incinerated by flashy lights or they want to be able to see the chart for whatever reason
They also may just prefer normal gameplay to enjoy the mod 
But maybe they do want to try it with them every now and then, you know, so just a quick lil toggle :)

**Comment by puyoxyz** [comment]
The **whole point** of a modchart **is** the modchart. This will not be added.
