### ISSUE TITLE
Enhancement: Compile the game without Visual Studio.

### ISSUE THREAD

**Issue by MrGenie151** [KadeArchive/Kade-Engine#559]
#### Please check for duplicates or similar issues before creating this issue.
I don't think there are any... But also i read that u needed to do this for windows on the github page but i cant be sure
## What is your suggestion, and why should it be implemented?
I am going to use Atom as my editor of choice to edit the .hx files and according to the github page i have to install Visual Studio Code 2019 in order to build to windows. however, i **REALLY** do not want to do this as something i will not even use will take up space on my computer. Is there a way around this that you could tell me or can you patch it out in the next update?

**Comment by isakube** [comment]
no. vsc is pretty much the only way, and if it isn't then it's the simplest.
