### ISSUE TITLE
Bug Report: Spooky Month (Pump and Skid) idle animations not working properly

### ISSUE THREAD

**Issue by MartianBinonwangan** [KadeArchive/Kade-Engine#560]
(NOTE: I'm pretty new to modding FNF. I understand some of the code but not much) I installed Kade Engine yesterday and tried testing some of the songs. When I got to Spookeez, I noticed that Skid and Pump's animation sequence was not working properly once the song started playing (before the game said GO!. Note, Skid and Pump's idle animation seems to work fine before this point). After the game/song officially starts, Pump and Skid get stuck in a loop that only shows them dancing to the right (think the normal Pump and Skid idle animation but only the half when they look to the right). Sometimes this changes after they sing a section, but Pump and Skid still get stuck executing either their right or left animation in a loop until they move onto the next section of the song.  I tried looking in the code and implemented different things including an integer counting system and editing things in the playAnim and dance functions to no avail. I tried redownloading the Kade-Engine source code and still had the same issue. Looking at the code, I know that Skid and Pump's idle animation works the same way that gf's does (if you've already danced movement, more to the next one (left and right)). However, gf doesn't seem to be having any problem with her idle animation like Skid and Pump are. Any ideas?

Extra details:
Operating System: Windows 10 (64 bit, 86x)

Kade-Engine Version:  1.4.2

Development: Desktop

Code Editor: Visual Studio Code 2019 (installed via the specifications found in building.md)

Code Compiler: Windows Powershell

**Comment by puyoxyz** [comment]
Duplicate of #319 or #495 or both I don't know???????? *starts crying*
