### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by guizinhomartinez** [KadeArchive/Kade-Engine#566]
1.1.3 is broken source code is wrong. game says 1.1.2 and accuracy is broken, every song it starts at 1 miss and if you miss 1 more time and restart song it says 2 miss.
and there is no watermark

**Comment by isakube** [comment]
1.1.3 old. we ain't fixing lol

**Comment by guizinhomartinez** [comment]
thanks i guess

**Comment by puyoxyz** [comment]
not only "we ain't fixing" but we literally can't because that's not possible in git
