### ISSUE TITLE
Enhancement: Option to toggle the new 2x health gain

### ISSUE THREAD

**Issue by guizinhomartinez** [KadeArchive/Kade-Engine#567]
there would be nice if you could change to the new 2x healthbar gain and the slow and original healthbar system on options, that would be pretty nice and probally a lot of modders would use that
(or maybe there is and i am just bothering who is reading it)
and i think a lot of people would like a option on kade engine because the game becomes easy when you press 4 buttons and the enemy bar is alredy over

**Comment by puyoxyz** [comment]
oh my god do people not know how to write issue titles??

**Comment by guizinhomartinez** [comment]
i'm new to coding srry

**Comment by guizinhomartinez** [comment]
sorry I hadn't thought of the title

**Comment by guizinhomartinez** [comment]
but anyway is there a way to i code this in?

**Comment by Kade-github** [comment]
health modifier is planned

**Comment by guizinhomartinez** [comment]
i've discovered how, basically you need to put some stuff into the code
first: go into visual studio code and press ctrl+f and search sick and go into the 4 result change this:
![image](https://user-images.githubusercontent.com/81656897/120220800-b1516200-c213-11eb-9b8a-fa383b6f6e40.png)
to this:
![image](https://user-images.githubusercontent.com/81656897/120220842-c4fcc880-c213-11eb-84d2-6d709fb2be28.png)
(to be more easy here the code to copy)
case 'shit':
					score = -10;
					combo = 0;
					misses++;
					health -= 0.0475;
					ss = false;
					shits++;
					if (FlxG.save.data.accuracyMod == 0)
						totalNotesHit += 0.25;
				case 'bad':
					daRating = 'bad';
					score = 0;
					if (health < MaxHP)
					{	
						if (daNote.noteData >= 0)
							health += 0.023;
						else
							health += 0.004;
					}
					ss = false;
					bads++;
					if (FlxG.save.data.accuracyMod == 0)
						totalNotesHit += 0.50;
				case 'good':
					daRating = 'good';
					score = 200;
					ss = false;
					goods++;
					if (health < MaxHP)
					{	
						if (daNote.noteData >= 0)
							health += 0.023;
						else
							health += 0.004;
					}
					if (FlxG.save.data.accuracyMod == 0)
						totalNotesHit += 0.75;
				case 'sick':
					if (health < MaxHP)
					{	
						if (daNote.noteData >= 0)
							health += 0.023;
						else
							health += 0.004;
					}
					if (FlxG.save.data.accuracyMod == 0)
						totalNotesHit += 1;
					sicks++;
now press ctrl+f again and type health and go into the first result, after fiding it type this:
![image](https://user-images.githubusercontent.com/81656897/120220976-00979280-c214-11eb-8435-d06008e20960.png)

press ctrl+f and type this in the search this: function goodNoteHit(note:Note, resetMashViolation = true):Void
change this:
![image](https://user-images.githubusercontent.com/81656897/120221159-48b6b500-c214-11eb-8ba4-158d50d891dd.png)
to this:
 {

				if (mashing != 0)
					mashing = 0;

				var noteDiff:Float = Math.abs(note.strumTime - Conductor.songPosition);


				note.rating = Ratings.CalculateRating(noteDiff);

				if (!note.isSustainNote)
					notesHitArray.push(Date.now());

				if (!resetMashViolation && mashViolations >= 1)
					mashViolations--;

				if (mashViolations < 0)
					mashViolations = 0;

				if (note.isSustainNote)
				{
					health += 0.004;
				}

				if (!note.wasGoodHit)
				{
					if (!note.isSustainNote)
					{
						popUpScore(note);
						combo += 1;
					}
					else
					{
						if (health < MaxHP)
							health += 0.02;
						
						totalNotesHit += 1;
					}
	

					switch (note.noteData)
					{
						case 2:
							boyfriend.playAnim('singUP', true);
						case 3:
							boyfriend.playAnim('singRIGHT', true);
						case 1:
							boyfriend.playAnim('singDOWN', true);
						case 0:
							boyfriend.playAnim('singLEFT', true);
					}
		
					#if windows
					if (luaModchart != null)
						luaModchart.executeState('playerOneSing', [note.noteData, Conductor.songPosition]);
					#end


					if (!loadRep)
						playerStrums.forEach(function(spr:FlxSprite)
						{
							if (Math.abs(note.noteData) == spr.ID)
							{
								spr.animation.play('confirm', true);
							}
						});
		
					note.wasGoodHit = true;
					vocals.volume = 1;
		
					note.kill();
					notes.remove(note, true);
					note.destroy();
					
					updateAccuracy();
				}
			}




now type on the search menu (ctrl+f) health and go into the 58 result and on health -= 0.075 change to health -= 0.475
