### ISSUE TITLE
Enhancement: whitty source code

### ISSUE THREAD

**Issue by guizinhomartinez** [KadeArchive/Kade-Engine#569]
whitty is kinda old now but there is one thing that i would like, source code, due ninjamuffin99 new rules, new mods has to be source code but whitty has he's own engine wich is like a prototype of kade engine. and i prefer the whitty kade engine then the normal kade engine

**Comment by puyoxyz** [comment]
kade said something about whitty source code once in some issue have fun trying to find it but there's a reason it's not out

if you want old versions of KE you can see the source code of any release by clicking the tag icon (for example, https://github.com/KadeDev/Kade-Engine/tree/1.0-KE for 1.0)

**Comment by ghost** [comment]
I mainly want Whitty source so I can use WASD, which isn't in vs Whitty

**Comment by puyoxyz** [comment]
WASD *is* in Kade Engine. If DFJK is off, the layout is WASD and Arrow keys.

**Comment by ghost** [comment]
In Whitty, it's DFJK even when WASD is selected

**Comment by theDetourist** [comment]
[There you go](https://github.com/KadeDev/vswhitty-public), now let this issue die.
