### ISSUE TITLE
Enhancement: make the combo asset used

### ISSUE THREAD

**Issue by arceuss** [KadeArchive/Kade-Engine#57]
just put it above the combo number or something
![image](https://user-images.githubusercontent.com/28229451/112402257-cd93c880-8cd1-11eb-8ccd-33f3f217b08c.png)
example taken from mungyodance 3

**Comment by Kade-github** [comment]
it is already used?

**Comment by arceuss** [comment]
where
i dont see it

**Comment by haya3218** [comment]
the add call function for combo is disabled iirc but its easy to restore
