### ISSUE TITLE
Enhancement: Put the combo in the backround instead of foreground

### ISSUE THREAD

**Issue by hoodshine** [KadeArchive/Kade-Engine#574]
## What is your suggestion, and why should it be implemented?
if you're playing upscroll because that's the original way, good luck seeing the two notes of the left side because you're getting cockblocked and will most likely miss it or not see a double note. I don't understand why this was a decision where the combo was moved into the foreground. Yeah I know you can reposition it but it still looks stupid as hell. Make it an option or something to put it in the background idk. The best kade engine was the one used in the tricky mod, it had the combo in the background and had the controls of both wasd, dfjk which is in the newer version and askl which in my opinion is the best since with dfjk, the wrists are more angled which can lead to the wrist hurting.

**Comment by Kade-github** [comment]
ez fix, customize gameplay. Intentional.
