### ISSUE TITLE
Enhancement: new enemy notes option

### ISSUE THREAD

**Issue by guizinhomartinez** [KadeArchive/Kade-Engine#576]
i downloaded the kade engine new version but there is one thing i like and at the same time i don't like, this thing is that you can see when enemy is pressing the notes like in vs tabi but it would be nice to have a option to desactivate because at least in my case it destract me and make me lose my combo and in my vision the both version are good enough to be a option to activate and desactivate

**Comment by puyoxyz** [comment]
...what? do you mean the enemy's notes being highlighted??? how does that distract you any more than it did before when they didn't get highlighted??
put a piece of paper on ur screen if it bothers u THAT MUCH

**Comment by Kade-github** [comment]
already done in the latest source
