### ISSUE TITLE
Bug Report: Game not running full speed with FlxG.fixedTimestep = true;

### ISSUE THREAD

**Issue by yasabigdays** [KadeArchive/Kade-Engine#580]
## Description
`FlxG.fixedTimestep` is true by default. In my laptop, both hxcpp and HTML5 builds of the game, it did not run full speed. Proposed fix is to set `FlxG.fixedTimestep` to false in Main.hx. This can also potentially fix other issues, like linear interpolation being frame rate dependent.

## Specifications
Windows (`x86_64`)
Friday Night Funkin' Kade Engine e02d9a546f1a3a13189de123e95d3c965810e87d

**Comment by dardisperse** [comment]
where exactly would this main.hx file be? i searched my pc drive for it and nothing came up via the search. do keep in mind im not necessarily savvy when it comes to things like this. # @gedehari

**Comment by ghost** [comment]
main.hx would be in the `source` folder of the source code

**Comment by ghost** [comment]
`FlxG.fixedTimestep` isn't on Main.hx yet, the proposed fix is to add that line somewhere after `FlxGame` is added to Stage.

**Comment by ghost** [comment]
Wait is this the "menu goes at half speed until song started" bug?

**Comment by ghost** [comment]
> Wait is this the "menu goes at half speed until song started" bug?

Yeah. Wait, it's been fixed?

**Comment by ghost** [comment]
Didn't say that. Just really annoys me when playing mods on KBH Games

**Comment by ghost** [comment]
> Didn't say that. Just really annoys me when playing mods on KBH Games

Ah I see. This should fix it.

**Comment by dardisperse** [comment]
ah alrighty, thank y'all kindly

**Comment by moglol** [comment]
> where exactly would this main.hx file be? i searched my pc drive for it and nothing came up via the search. do keep in mind im not necessarily savvy when it comes to things like this. # @gedehari

its kinda hard just get the source code and its in the source folder but to build it you have to go to the fnf repo and read the tutorial on building fnf in the desc.
