### ISSUE TITLE
Enhancement: Customize Gamplay

### ISSUE THREAD

**Issue by Black-Water1** [KadeArchive/Kade-Engine#581]
my suggestion is that the click and drag box is enlarged to surround the whole sprite for sick, if you accidentally drag it up without knowing there is no way to bring it down from what I can tell. I decided to do it just to see if there was any way to bring it back down and i do not think that there currently is one available on the customize gameplay section.

![Friday Night Funkin' 5_25_2021 11_15_47 AM](https://user-images.githubusercontent.com/84805784/119548070-af3a5f80-bd4a-11eb-9e73-11809e65c2da.png)

**Comment by puyoxyz** [comment]
Added to #339
