### ISSUE TITLE
Bug Report: Week 6 Got Crashed

### ISSUE THREAD

**Issue by afeefflox** [KadeArchive/Kade-Engine#598]
So Went I test for Week 6 they crash Because Of Notes Pixel I think they Need Note Style With  Rating Style

**Comment by Jaduplex** [comment]
please clarify i cant understand this

**Comment by afeefflox** [comment]
This Mean The Note Style Are not responding in-game

**Comment by craftersshaft** [comment]
basically when the note style is set to pixel, it tries to load an asset that doesn't exist but then immediately crashes i think

**Comment by Jaduplex** [comment]
> basically when the note style is set to pixel, it tries to load an asset that doesn't exist but then immediately crashes i think

It does exist, just only in the week 6 folder

**Comment by craftersshaft** [comment]
the source code apparently only points to a weeb/ folder and not week6

**Comment by afeefflox** [comment]
> the source code apparently only points to a weeb/ folder and not week6

So  I Cannot Types Such As Roses And Senpai Also Thorn  in Chart State It Because It Still Crashed

**Comment by Lucky-56** [comment]
isn't this fixed ?
if so, please close

**Comment by puyoxyz** [comment]
pretty sure this is fixed?
