### ISSUE TITLE
Enhancement: Anti spam and its problems

### ISSUE THREAD

**Issue by gapplar** [KadeArchive/Kade-Engine#606]
So basically the new kade engine has anti spam built in witch was poorly implemented. This would have been fine if it was toggleable. Now when i go to play ballistic/whitty mod as a whole on the new kade engine the accuracy and the rest of the bar turns red. Why this is a problem? well I was playing ballistic like I normally and because of the anti spam witch shouldn't affect me because i do not spam, however it made me lose my entire health bar in a few misses. This should at least be toggleable on and off and not just be chosen if the dev says so.

**Comment by NoiceBroice** [comment]
You can already toggle it in Options: Ghost Tapping

**Comment by Kade-github** [comment]
> So basically the new kade engine has anti spam built in witch was poorly implemented. This would have been fine if it was toggleable. Now when i go to play ballistic/whitty mod as a whole on the new kade engine the accuracy and the rest of the bar turns red. Why this is a problem? well I was playing ballistic like I normally and because of the anti spam witch shouldn't affect me because i do not spam, however it made me lose my entire health bar in a few misses. This should at least be toggleable on and off and not just be chosen if the dev says so.

whitty's anti-spam is buffed and this has nothing to do with kade engine, please take that into https://github.com/KadeDev/vswhitty-public and also, if you're seeing the health bar turn red. you're mashing. trust me. you are.
