### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by aladairmaxwell** [KadeArchive/Kade-Engine#609]
After all libs, reinstall of Visual Studio 2019 and everything else I tried to compile game for the first time and this is what I got. 
![image](https://user-images.githubusercontent.com/69295711/120040018-8944e180-c00e-11eb-9788-f770ba4b3c34.png)

```
PS D:\Kade-Dev> lime test windows
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/PlayState.hx:478: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
D:\Kade-Dev\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC
PS D:\Kade-Dev>
```

I was using this guide: https://youtu.be/CKNfu8G9EOc

Any solutions?

**Comment by Alittletrolling** [comment]
When installing Visual Studio 2019 go to the individual components tab and choose the following:

MSVC v142 - VS 2019 C++ x64/x86 build tools
Windows SDK (10.0.17763.0)
C++ Profiling tools
C++ CMake tools for windows
C++ ATL for v142 build tools (x86 & x64)
C++ MFC for v142 build tools (x86 & x64)
C++/CLI support for v142 build tools (14.21)
C++ Modules for v142 build tools (x64/x86)
Clang Compiler for Windows
Windows 10 SDK (10.0.17134.0)
Windows 10 SDK (10.0.16299.0)
MSVC v141 - VS 2017 C++ x64/x86 build tools
MSVC v140 - VS 2015 C++ build tools (v14.00)

**Comment by ghost** [comment]
> When installing Visual Studio 2019 go to the individual components tab and choose the following:
> 
> MSVC v142 - VS 2019 C++ x64/x86 build tools
> Windows SDK (10.0.17763.0)
> C++ Profiling tools
> C++ CMake tools for windows
> C++ ATL for v142 build tools (x86 & x64)
> C++ MFC for v142 build tools (x86 & x64)
> C++/CLI support for v142 build tools (14.21)
> C++ Modules for v142 build tools (x64/x86)
> Clang Compiler for Windows
> Windows 10 SDK (10.0.17134.0)
> Windows 10 SDK (10.0.16299.0)
> MSVC v141 - VS 2017 C++ x64/x86 build tools
> MSVC v140 - VS 2015 C++ build tools (v14.00)

VS Buils tools 2017 is also needed. I required to log in to my Microsoft account, would I be allowed to share the direct link?
