### ISSUE TITLE
Bug Report: cant compile kade engine

### ISSUE THREAD

**Issue by arrodev** [KadeArchive/Kade-Engine#610]
![image](https://user-images.githubusercontent.com/84995943/120043791-3d744700-bfd2-11eb-8593-737247c58f36.png)

when trying to compile the engine i get these errors. I installed all of the required libraries and it still gives me this. Please help!

**Comment by Alittletrolling** [comment]
Type haxelib git discord_rpc in command prompt

**Comment by isakube** [comment]
`haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc`

**Comment by Bukaboi** [comment]
i typed the link, and tried installing discord_rpc yet it just says "Updating discord_rpc version git ..." and its stayed like that for 2 hours, i need help with that
