### ISSUE TITLE
Many many problems that need fixing and changing

### ISSUE THREAD

**Issue by UckyDuckyYT** [KadeArchive/Kade-Engine#615]
my first problem is with the charting system it makes charting a nightmare if you mess up in a chart you have to clear that section because you cant delete a single note just by it's self and another thing the note system that shows you how off you were with a note well its cool but I cant turn it off I swear there is no option for it and Whitty recently got an update and now it has this engine running it and I thought I could replace the Whitty character with a color swapped version of him and nothing else and then it changes the whole background from the streets to the week 1 stage and if that doesn't happen then it makes the camera zoom out Kade please fix all of these problems they are pretty huge and besides those problems its a decent engine but for now its over used and over rated for how many problems there are.

**Comment by Alittletrolling** [comment]
Bro chill out the note issue will be fixed and Whitty has always used Kade engine lol. Also changing the background will cause issues with the camera. Most of these issues are on you rather than kade. Also Kade engine isn't overused, trust me lmao.

**Comment by Burger-Gaming** [comment]
um you can delete single notes, you just have to click on that note and it will delete for you???

**Comment by isakube** [comment]
what. version. are you playing. where you can't delete notes? That was fixed in like 1.3* or something. Update to a newer version my guy. Also most of this is on you trust me


* It's 1.4.1 actually, still not too recent i guess

**Comment by UckyDuckyYT** [comment]
for all the mods I have that run Kade engine in all of them it has the arrow option and what Whitty always ran on Kade engine? damn well now I can't change Whitty sprites even if it was still on Kade engine before it has this problem now well I hope they get fixed : P

**Comment by UckyDuckyYT** [comment]
> Bro chill out the note issue will be fixed and Whitty has always used Kade engine lol. Also changing the background will cause issues with the camera. Most of these issues are on you rather than kade. Also Kade engine isn't overused, trust me lmao.

Uhh also if it isn't over used then how come most of the mods are running Kade engine lol.

**Comment by puyoxyz** [comment]
hi. issues are supposed to have one problem, not multiple

- deleting notes while charting: you *can* delete notes individually
- disabling hit error text: yes, this should be an option. make a separate issue for this
- whitty: add your new character name to the switch case that chooses the stage based on the characters i think? in playstate
