### ISSUE TITLE
Error compiling the game due to Discord Rich Presence.

### ISSUE THREAD

**Issue by WaluigiBestGirl** [KadeArchive/Kade-Engine#62]
I've installed two different gits already, https://github.com/Aidan63/linc_discord-rpc and https://github.com/discord/discord-rpc
But when I try to compile I always get this error
`Error: __boot__.cpp
C:/HaxeToolkit/haxe/lib/discord_rpc/git/linc/linc_discord_rpc.h(7): fatal error C1083: Cannot open include file: '../lib/discord-rpc/include/discord-rpc.h': No such file or directory`

I have no clue what I'm doing wrong

Edit: I am trying to compile it on windows

**Comment by Kade-github** [comment]
look at the readme

**Comment by WaluigiBestGirl** [comment]
> look at the readme

I did, it says nothing about Discord Rich Presence. Unless I'm reading the wrong readme.
README.md is the one I'm looking at.

**Comment by Kade-github** [comment]
![image](https://user-images.githubusercontent.com/26305836/112553885-903b4380-8d82-11eb-9611-10b0a74c6985.png)
read harder

**Comment by WaluigiBestGirl** [comment]
How... the heck did I miss that?
