### ISSUE TITLE
Enhancement: In game bot

### ISSUE THREAD

**Issue by Godnoob443** [KadeArchive/Kade-Engine#621]
I the in game bot going to be added to the newest kade engine?

**Comment by guizinhomartinez** [comment]
welp i think you never update your kade engine master because there is alredy a in game bot

**Comment by Godnoob443** [comment]
I do update my kade engine they only have a in game bot in the whitty mod

**Comment by Godnoob443** [comment]
> welp i think you never update your kade engine master because there is alredy a in game bot

There  is only a in game bot for the whitty mod but not for just kade engine without whitty

**Comment by Burger-Gaming** [comment]
you can also just use FNFBot

**Comment by Godnoob443** [comment]
> you can also just use FNFBot

But its really hard to do, what if someone wants to do more then one song and cant keep on changing the song in the fnfbot

**Comment by isakube** [comment]
theres BotPlay. latest source code, Options / Misc / BotPlay.

**Comment by Godnoob443** [comment]
> theres BotPlay. latest source code, Options / Misc / BotPlay.

Is it in this source code?

**Comment by Godnoob443** [comment]
> theres BotPlay. latest source code, Options / Misc / BotPlay.

i think i found it

**Comment by Godnoob443** [comment]
> theres BotPlay. latest source code, Options / Misc / BotPlay.

How do i build the source code?

**Comment by isakube** [comment]
https://kadedev.github.io/Kade-Engine/building

**Comment by RagdollClash** [comment]
> > theres BotPlay. latest source code, Options / Misc / BotPlay.
> 
> How do i build the source code?

Builds are automatically built by Appveyor, you can grab the latest developer build by going to the [README](https://github.com/KadeDev/Kade-Engine#kade-engine) and clicking `latest development build (windows)`

**Comment by Godnoob443** [comment]
> > > theres BotPlay. latest source code, Options / Misc / BotPlay.
> > 
> > 
> > How do i build the source code?
> 
> Builds are automatically built by Appveyor, you can grab the latest developer build by going to the [README](https://github.com/KadeDev/Kade-Engine#kade-engine) and clicking `latest development build (windows)`

How do i download it from there?
