### ISSUE TITLE
FPS limiter doesn't save after restarting game

### ISSUE THREAD

**Issue by UckyDuckyYT** [KadeArchive/Kade-Engine#625]
So this enhancement for me is mostly for fps because when I change it and then close the game it changes back to the 126 fps also can you add unlimited fps setting too?

**Comment by Lucky-56** [comment]
wdym with that.
unlimited fps would I think crash the game and for that reason there's a hard coded max of 285 fps.

**Comment by puyoxyz** [comment]
will look into this latr

**Comment by Lucky-56** [comment]
wow I just accidentally figured out what happens on `null` FPS caps... and everything is so weird

**Comment by UckyDuckyYT** [comment]
Lucky on some mods using Kade Engine there is an unlimited fps option and some times id close the game and re open it and then it would go back down to 126 and even in the normal download of kade engine if you change the fps i think it changes back to 126 when the game is closed.

**Comment by Lucky-56** [comment]
i already said there is a hard coded limit to 285 fps when youre over that limit it resets your fps cap to 120 (being 126fps)

![image](https://user-images.githubusercontent.com/55949451/121894669-b3d9ae80-cd1f-11eb-9ac9-209989732fef.png)

meaning if your FPS cap is over 285 or under 60 it resets to 120

**Comment by puyoxyz** [comment]
seems that this was about the 285 fps cap cap. closing.
