### ISSUE TITLE
Bug Report: Scoring system is broken

### ISSUE THREAD

**Issue by Z-Liv** [KadeArchive/Kade-Engine#63]
My score keeps going into the negative area, i thought it had to do with the anti-mash, but the anti-mash is literally non-funtional, i can mash all i want, but it seems getting anything below a good makes my score drop a lot, even more than missing a note, fix this please

![image](https://user-images.githubusercontent.com/81391034/112547427-7f49fc80-8d99-11eb-8767-d82b5585b0fb.png)

**Comment by Sebyal** [comment]
Just hit the notes bro holy shit

**Comment by Sebyal** [comment]
Damn

**Comment by Sebyal** [comment]
Kade made it like that its about accuracy

**Comment by theDetourist** [comment]
Might as well update Zardy Foolhardy to 1.3 or to the next update, it is also ignoring Global Offsets too (at least for me).

**Comment by Kade-github** [comment]
huh? you mash you get a negative score lol. Thats intended.
