### ISSUE TITLE
Bug Report: Game crashing

### ISSUE THREAD

**Issue by thecatontheceiling** [KadeArchive/Kade-Engine#632]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows 10 x64 20H2
## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
launch game
drink water
go to any song
crash
## Please describe your issue. Provide extensive detail and images if possible.
game is crash lmao i dont know what else to put here

**Comment by puyoxyz** [comment]
~~hi does the bug still happen if you drink pepsi? thanks~~

send console output pls

**Comment by sabaasa** [comment]
how do i send console output

**Comment by sabaasa** [comment]
> ~hi does the bug still happen if you drink pepsi? thanks~
> 
> send console output pls
how do i send console output

**Comment by thecatontheceiling** [comment]
> ~hi does the bug still happen if you drink pepsi? thanks~
> 
> send console output pls

how do i send console output

**Comment by puyoxyz** [comment]
run the game through the console

if building it urself `lime run windows -debug -verbose`

if running a downloaded build navigate to where the exe is (kade engine folder) and do `"Kade Engine.exe"`

**Comment by thecatontheceiling** [comment]
> run the game through the console
> 
> if building it urself `lime run windows -debug -verbose`
> 
> if running a downloaded build navigate to where the exe is (kade engine folder) and do `"Kade Engine.exe"`

how do i do that

**Comment by sabaasa** [comment]
where are you

**Comment by thecatontheceiling** [comment]
> run the game through the console
> 
> if building it urself `lime run windows -debug -verbose`
> 
> if running a downloaded build navigate to where the exe is (kade engine folder) and do `"Kade Engine.exe"`

bro u here

**Comment by thecatontheceiling** [comment]
the problem is still not fixed btw

**Comment by thecatontheceiling** [comment]
so the problem was i downloaded from the totally normal download mirror lmao why is that even a thing
