### ISSUE TITLE
Bug Report:Problem with the songs

### ISSUE THREAD

**Issue by Egor80157** [KadeArchive/Kade-Engine#633]
On first note zooms in, so I can't even see arrows. My resolution 1024x768 Windows 7 64bit
![image](https://user-images.githubusercontent.com/85062145/120102981-48b0a980-c16f-11eb-9660-e0a1342a0a62.png)

**Comment by Egor80157** [comment]
Can u help with this problem without changing resolution? Because I don't want to change it

**Comment by puyoxyz** [comment]
Workaround: Don't be in full screen, make window smaller vertically

**Comment by Egor80157** [comment]
no lol
![Uploading image.png…]()

**Comment by Egor80157** [comment]
It's not working

**Comment by puyoxyz** [comment]
oh oops sorry i didn't notice ur resolution

the minimum resolution for friday night funkin is 1280 by 720. nothing we can do about that. sorry
