### ISSUE TITLE
Names of first week tracks disappeared 

### ISSUE THREAD

**Issue by aladairmaxwell** [KadeArchive/Kade-Engine#637]
Found strange detail about Story Mode menu. There are no names of first songs in a week. I don't know why. I rebuilt the game from zero and this is still here. Is this my problem or Kade Engine one?

![image](https://user-images.githubusercontent.com/69295711/120110604-d5129a80-c176-11eb-91bb-429adf124eac.png)
![image](https://user-images.githubusercontent.com/69295711/120110611-d80d8b00-c176-11eb-9880-42fc7077eb0b.png)

**Comment by ghost** [comment]
Bug in the original Funkin source that cuts off the last song.

**Comment by aladairmaxwell** [comment]
Will this thing will be somehow fixed in future? Cause I saw that many mods which used Kade don't have such an error.

**Comment by ghost** [comment]
It will be fixed. There's already a fix in Funkin's PRs

**Comment by isakube** [comment]
This is already fixed for the most part. Probably you.

**Comment by shaderw0lf** [comment]
budget how-to-fix-this-bug method if you lazy to redownload source code

![изображение](https://user-images.githubusercontent.com/55358751/120111972-97187500-c17c-11eb-856a-61b81852522e.png)

**Comment by aladairmaxwell** [comment]
Oh,  I see, I redownloaded source code and get plenty of new things, including this fix. Thanks!
