### ISSUE TITLE
Bug Report: hxcpp.h not found

### ISSUE THREAD

**Issue by Maritsu** [KadeArchive/Kade-Engine#639]
#### Please check for duplicates, similar issues or closed issues with the same problem, as well as performing simple troubleshooting steps (such as deleting the export folder if it's an issue with compiling, reinstalling Kade Engine) before submitting an issue.
Done.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Compiling on Linux

## What version of the game are you using? Look in the bottom left corner of the main menu.
KE 1.4.2, source code straight from the GH release.

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
1. Download the source code (`tar.gz`) from the [1.4.2 release](https://github.com/KadeDev/Kade-Engine/releases/tag/1.4.2)
2. `cd` into the mod folder and ```$ lime test linux -debug```
3. Error pops up while compiling.

## Please describe your issue. Provide extensive detail and images if possible.
I've tried to compile slightly modified KE source code, but after a while, this error message pops up and the compilation process stops. I don't know what causes the problem, I have `hxcpp` installed.
```
Creating /home/bittheprotogen/Projekty/RAMstore/export/release/linux/obj/obj/linux64/__pch/haxe/hxcpp.h.gch...

Compiling group: haxe
g++ -Iinclude -I/home/bittheprotogen/haxelib/linc_luajit/0,0,2//linc/ -c -fvisibility=hidden -O2 -fpic -fPIC -Wno-overflow -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHXCPP_DEBUGGER(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -m64 -DHXCPP_M64 -I/home/bittheprotogen/haxelib/hxcpp/4,2,1/include ... tags=[haxe,static]
 - src/__boot__.cpp 
 - src/openfl/net/URLRequestDefaults.cpp  [haxe,release]
 - src/lime/graphics/_WebGL2RenderContext/WebGL2RenderContext_Impl_.cpp 
 - src/hxcpp/debug/jsonrpc/eval/Error.cpp 
 - src/openfl/display/_internal/_DrawCommandReader/OverrideBlendModeView_Impl_.cpp 
 - src/lime/media/WebAudioContext.cpp 
 - src/openfl/display/_StageAlign/StageAlign_Impl_.cpp 
 - src/AccuracyOption.cpp 
Error: In file included from include/llua/Lua_helper.h:11,
                 from ./src/__boot__.cpp:806:
/home/bittheprotogen/haxelib/linc_luajit/0,0,2//linc/linc_lua.h:5:10: fatal error: /home/bittheprotogen/Projekty/RAMstore/export/release/linux/obj/obj/linux64/__pch/haxe/hxcpp.h: Nie ma takiego pliku ani katalogu
    5 | #include <hxcpp.h>
      |          ^~~~~~~~~
compilation terminated.
```

![Terminal screenshot](https://user-images.githubusercontent.com/66056347/120111894-f920ac80-c173-11eb-9e6a-02c5014d3fc3.png)

**Comment by ghost** [comment]
Make sure you use the **website instructions** and **do NOT just use Haxe from your distro's repos**

**Comment by puyoxyz** [comment]
Already fixed. Build master instead of 1.4.2.
