### ISSUE TITLE
Enhancement: nps display

### ISSUE THREAD

**Issue by arceuss** [KadeArchive/Kade-Engine#64]
![image](https://user-images.githubusercontent.com/28229451/112548041-3ab26700-8d81-11eb-8172-bb29ee007355.png)
from etterna spawncamping wallhack
would be nice considering how kade engine is meant for competitive use and play

**Comment by Kade-github** [comment]
i was thinking about that yeah

**Comment by arceuss** [comment]
awesome

**Comment by Kade-github** [comment]
Added in Nightly 3
