### ISSUE TITLE
Haxelib Broken, I can't compile the game

### ISSUE THREAD

**Issue by Sendan4** [KadeArchive/Kade-Engine#648]
I want to compile the game on my distribution **(Debian Bullseye)**
I can't, because haxelib gives me an error when downloading and trying to install any library `Error: std@date_set_day`
**(the date on my computer and operating system is correct)**

![Captura de pantalla de 2021-05-31 10-42-19](https://user-images.githubusercontent.com/60526375/120209632-e7cfb280-c1fc-11eb-9b8b-67eed9cf1367.png)

I have tried a fresh install on a virtual machine on **Debian bullseye** and **Fedora**. I keep getting the same error.

I do not know what will be the cause of this error, I have already been able to compile the game without problems in Windows, haxelib worked without problems.

now i am trying to compile haxe, hoping that this can be fixed, but currently i am having trouble with that, i keep trying.

I have also written in the haxelib repository https://github.com/HaxeFoundation/haxelib/issues/513

**Comment by ghost** [comment]
Make sure you use the PPA and not your distro's version.

**Comment by Sendan4** [comment]
@VMGuy23 
I can't install it, it needs **libc6** equal to or greater than 2.32, on **Debian Bullseye** 2.31-12 is installed.

dpkg says that it might break something if I install a higher version.

**Comment by puyoxyz** [comment]
this is a problem with haxelib and not kade engine

**Comment by ghost** [comment]
> @VMGuy23
> I can't install it, it needs **libc6** equal to or greater than 2.32, on **Debian Bullseye** 2.31-12 is installed.
> 
> dpkg says that it might break something if I install a higher version.

What does it say it might break? I'm on ubuntu 21.04 and all works fine

**Comment by Sendan4** [comment]
> > dpkg dice que podría romper algo si instalo una versión superior.
> 
> ¿Qué dice que podría romperse? Estoy en ubuntu 21.04 y todo funciona bien

For Debian it is something else, you should test it on a virtual machine.
just to make sure I don't really break something

**Comment by Sendan4** [comment]
@VMGuy23
![imagen](https://user-images.githubusercontent.com/60526375/123887816-23ef5380-d920-11eb-9e8d-459c5460e6a5.png)

I tried it on kubuntu 21.04, and I have the same problem.

**Comment by ghost** [comment]
make sure you got all the updates

**Comment by Sendan4** [comment]
> make sure you got all the updates

I keep it up to date

**Comment by ghost** [comment]
thats weird. I'm on Ubuntu 21.04, withthe Haxe PPA, and everything works great

**Comment by Sendan4** [comment]
![asd](https://user-images.githubusercontent.com/60526375/126507556-d431a252-a483-4faf-a63d-52f6853ece15.png)
![adds](https://user-images.githubusercontent.com/60526375/126507565-6eee12bd-f35a-4cf6-abd0-217580813408.png)

I think he is not taking it from the ppa

(in a virtual machine)

**Comment by Sendan4** [comment]
![imagen](https://user-images.githubusercontent.com/60526375/126539207-00dd5c77-7b54-4a76-8d32-72336e042f7e.png)

there are directories that do not exist

**Comment by ghost** [comment]
```
sudo add-apt-repository ppa:haxe/releases -y
sudo apt-get update
sudo apt-get install haxe -y
mkdir ~/haxelib && haxelib setup ~/haxelib
```

**Comment by Sendan4** [comment]
> ```
> sudo add-apt-repository ppa:haxe/releases -y
> sudo apt-get update
> sudo apt-get install haxe -y
> mkdir ~/haxelib && haxelib setup ~/haxelib
> ```

already tried that, but it did not work.

I am going to try a new installation on a real machine, this one is from the other PC that already died.

**Comment by Sendan4** [comment]
that didn't work, I will try **Ubuntu 21.04** on real machine.

**Comment by Sendan4** [comment]
definitely did not work.

I will borrow a friend's PC.

**Comment by Sendan4** [comment]
@VMGuy23 now it works, but I am **not using the correct time**, **nor the correct time zone for my country**.

thank you for helping me.

I will not set the correct time, it may fail again.

![imagen](https://user-images.githubusercontent.com/60526375/127221539-c969f9ac-0b71-46e4-89fe-33bbf2e8aa4e.png)
