### ISSUE TITLE
Bug Report: Sounds(Miss sound/volume up/down sound) playing during the successful hit of a note.

### ISSUE THREAD

**Issue by knifecat35** [KadeArchive/Kade-Engine#651]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows x86_64
## What version of the game are you using? Look in the bottom left corner of the main menu.
1.4.2, I've also expierenced this issue with 1.3

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
The only way I've that's it's happened is when the sound happens a little, I can't tell why or how it happens but sometimes in the middel of playing my song It just happesn
## Please describe your issue. Provide extensive detail and images if possible.

I am expierencing an issue with playing songs, where as If any outside sound (Primary example: Volume up and down or player miss note) Will play on random arrows. I am charting a longer song than normal, Could that be stimming off my issue? I am currently using windowsx86_64. And using kade engine 1.4 (latest version) But I expierenced this issue with 1.3 as well. It just seems to happen when ever that kind of sound happens to much and sometimes it's fine and other times it does it. I don't understand what the issue is happening here. And when the Bug does start happening when ever I puase and unpause the game, the sound that seem to be taking up plays twice or once.

**Comment by Kade-github** [comment]
p sure this was fixed in 1.5
