### ISSUE TITLE
Always get this error when ever i try to compile kade engine

### ISSUE THREAD

**Issue by Godnoob443** [KadeArchive/Kade-Engine#657]
I keep getting this error while compiling kade engine 

C:\Users\user\Desktop\test3\Kade-Engine>lime build windows
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/PlayState.hx:299: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:\Users\user\Desktop\test3\Kade-Engine\export\release\windows\obj>setlocal enabledelayedexpansion
Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths
Error: Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths

**Comment by ghost** [comment]
what bit do you have 32 or 64

**Comment by puyoxyz** [comment]
you installed 32 bit visual studio instead of 64 bit visual studio i THINK *or* you got the wrong components of visual studio

**Comment by ghost** [comment]
VS 2019 isn't avaliable in 64-bit.

**Comment by Godnoob443** [comment]
> VS 2019 isn't avaliable in 64-bit.

how do i get one that has 64 bit?

**Comment by ghost** [comment]
I just said it isn't avaliable in 64 bit.

**Comment by Godnoob443** [comment]
> I just said it isn't avaliable in 64 bit.

Yeah i know i mean how do get the thing to work then

**Comment by ghost** [comment]
Add `-64bit` to the command and try again
