### ISSUE TITLE
add the note press animation for the opponent

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#658]
add the animation for pressing a note when the opponent sings instead of the notes just disappearing.

example: FNF Multiplayer

https://user-images.githubusercontent.com/61301511/120357424-6e56c380-c2d3-11eb-9251-39a49b8ffad2.mp4

**Comment by guizinhomartinez** [comment]
your kinda late because there is alredy

**Comment by ghost** [comment]
> your kinda late because there is alredy

a development release or the 1.4.2 release?

**Comment by guizinhomartinez** [comment]
github kade engine master

**Comment by ghost** [comment]
dev release

**Comment by ghost** [comment]
1.4.2 is _really_ old

**Comment by guizinhomartinez** [comment]
yes at this point its just like kade engine 1.0
