### ISSUE TITLE
Compiler Issue

### ISSUE THREAD

**Issue by donutmp3** [KadeArchive/Kade-Engine#66]
So I'm having an Issue where the compiler says the following:
source/Note.hx:127: characters 12-16 : Class<flixel.FlxG> has no field data
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access

After that. It goes back to the Documents\GitHub\Kade-Engine

**Comment by Kade-github** [comment]
probably didn't install haxe right, consult the readme but otherwise we cannot help you.

**Comment by Kade-github** [comment]
oh actually nevermind it was fixed already that's why i couldn't find it.

**Comment by quicciee** [comment]
hey. this problem is now showing up with my kade engine in the newest release
![image](https://user-images.githubusercontent.com/84537461/119584475-9bb4e600-bd96-11eb-823a-02bdb7086688.png)
