### ISSUE TITLE
Bug Report: Can't be in the Old Input and weird arrows in downscreen.

### ISSUE THREAD

**Issue by SuperGion915** [KadeArchive/Kade-Engine#67]
Hello, I'm currently in Kade Engine 1.3.1 but I've had some problems compared to the 1.3 I downloaded just one day before; 
1. It is always in the New Input, I prefer the Old Input because its more challenging but it doesn't work now, when I put the Old Input I get instead the New Input and when I put the New Input it's just the New Input with silence when you let a note pass, I would like this to be fixed because I just don't like the New Input.
2. Weird arrows in downscreen, now up and down are in different places from where they should be, up arrows are going where down is and down arrows are going where up is, it is mostly a visual bug but if you can also fix it please.

**Comment by Kade-github** [comment]
1. old input is probably going to be removed, the support for it has went down a hell of a lot.
2. Uhh screenshot?

**Comment by Kadoodly** [comment]
> 1. old input is probably going to be removed, the support for it has went down a hell of a lot.
> 2. Uhh screenshot?

I have the same inverse arrow keys problem as well
[edit note] The left and right arrows are normal, only the up and down arrows are inversed.
![arrows](https://user-images.githubusercontent.com/35438066/112709254-b695d780-8e85-11eb-98c4-2a07b9bb068d.PNG)

**Comment by LiquidMelons** [comment]
My controls are fine but the anti-mashing that the old input had is gone. I mainly play with fixed inputs but I thought it was worth mentioning.

**Comment by Kade-github** [comment]
should be fixed in the latest commit.
