### ISSUE TITLE
I can't download the master/zip folder without parts missing.

### ISSUE THREAD

**Issue by BrotherDoStuffYT** [KadeArchive/Kade-Engine#673]
I can't download the Kade-Engine-master.zip/Code folder of it without folders missing.
I'm using WINDOWS 10 64-BIT
I don't know what version my download was
I have 2 images that I made.
![What I Should Have Exported](https://user-images.githubusercontent.com/85245345/120519199-5c8f2200-c3a0-11eb-80e4-880bc9503dae.png)
![What I Exported](https://user-images.githubusercontent.com/85245345/120520726-23f04800-c3a2-11eb-96b8-223383a0aa61.png)

**Comment by isakube** [comment]
i think this is github being dumb again

**Comment by haya3218** [comment]
yep. this is github being a bitch.
use github desktop or git cli to get the files instead
