### ISSUE TITLE
Enhancement: health on accuracy display

### ISSUE THREAD

**Issue by guizinhomartinez** [KadeArchive/Kade-Engine#674]
it would be awesome if there is a health option on accuracy, idk if its a good idea

**Comment by isakube** [comment]
oh yeahhh like the percent of the bar you own
that would be cool

**Comment by guizinhomartinez** [comment]
like on vs tabi

**Comment by Lucky-56** [comment]
sadly won't add since Kade hates Health display, so if you want to use it, you sadly need to code it in for yourself

**Comment by puyoxyz** [comment]
kade went like Noooooooooooooooooo
