### ISSUE TITLE
Bug Report: When building, I am getting an error that has nothing to do with my code.

### ISSUE THREAD

**Issue by brandonapt** [KadeArchive/Kade-Engine#676]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windowsx64

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.4.2 latest release
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
build the game. idk what else
## Please describe your issue. Provide extensive detail and images if possible.
when building the game I am getting this error: idk how to fix it and it wasn't there yesterday when I compiled.

https://justpaste.it/7ggje

**Comment by MoezTrigui** [comment]
this is not an error lamo
it is a warning

**Comment by isakube** [comment]
oooooooooooo

All of that's from flixel-addons. try reinstalling / updating your haxelibs.

Also MoezTrigui:
There are unidentified types, those arent just warnings
