### ISSUE TITLE
Bug Report: Downscroll not working.

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#68]
In the game, sometimes it completely stops reading my inputs when on downscroll.

**Comment by theDetourist** [comment]
What doesn't work, the hit detection or the buttons themselves? Can you send a video of it?

**Comment by ghost** [comment]
The hit detection

**Comment by Kade-github** [comment]
uhh, thats weird. It works fine for everyone else, I've never seen this. Can you record a video?

**Comment by ghost** [comment]
weird, it detects my notes now

**Comment by ItzYaBoiJosh** [comment]
So, when I open the phase/song the misses counter and all things are there but when it's the opponent's round it just turns off like I turned accuracy mode off but I didn't

Pictures : (when a note from the opponent didn't appear https://user-images.githubusercontent.com/68428075/120905226-741b1480-c605-11eb-9f46-046325f1f7a3.png)
(When a note appeared : https://user-images.githubusercontent.com/68428075/120905248-a88ed080-c605-11eb-8c70-2f08d94b979a.png)
