### ISSUE TITLE
Enhancement: Modchart support for platforms other than Windows

### ISSUE THREAD

**Issue by backhop** [KadeArchive/Kade-Engine#687]
## What is your suggestion, and why should it be implemented?
I've been working with KE recently, and wanted to figure out modcharts. It's all put behind `#if windows` statements, and when I tried to make changes to both ModchartState and PlayState, I wasn't able to get it working. Adding modchart support for Mac would be amazing!

**Comment by ghost** [comment]
Or Linux!
(although I can just compile for Windows and use WINE)

**Comment by isakube** [comment]
^ ^ ^

I don't think modchart support is possible for Mac but maybe it is, im not good with Lua in the first place lol

**Comment by ACrazyTown** [comment]
I'm unsure if this is possible as linc_luajit belongs to linc, a bunch of libraries for the Haxe C++ target. After googling a bit, from what I see, Haxe supports building C++ libraries on Mac/Linux, you just have to install the required compilers.

**Comment by ghost** [comment]
I have the required compilers, however, it seems that modcharts are disabled on Mac/Linux

**Comment by ACrazyTown** [comment]
Oh yeah my bad, totally missed the section that referenced the #if windows statements

**Comment by MagnusStrom** [comment]
Heya, Modchart support won't work for Mac due to the LUA binaries. However, there are alternative engines, like [ProjectFNF](https://github.com/aflacc/ProjectFNF) which support Mac modcharting

**Comment by puyoxyz** [comment]
~~This needs to be looked into -- it seems that macOS/Linux is building to neko by default, it should be changed to build to c++ by default. Assigning myself and I'll look into it tomorrow~~

Nah I'm just dumb =)

**Comment by ghost** [comment]
I'm not sure - apparently Neko builds don't work for vanilla Funkin but I can build fine.

**Comment by isakube** [comment]
> Nah I'm just dumb =)

Wait, so does that mean Lua can be run on other platforms? I'm gonna try removing the `#if windows ` stuff just real quick

EDIT: Upon further inspection of the linc_luajit library itself, the `lib` folder doesn't have Mac folders. big sad

**Comment by ghost** [comment]
> > Nah I'm just dumb =)
> 
> Wait, so does that mean Lua can be run on other platforms? I'm gonna try removing the `#if windows ` stuff just real quick
> 
> EDIT: Upon further inspection of the linc_luajit library itself, the `lib` folder doesn't have Mac folders. big sad

Yeah it seems like a linc luajit issue

**Comment by isakube** [comment]
yeah

*time to write a lua interpreter :classy:*

**Comment by ghost** [comment]
Or `lime rebuild linc_luajit macos` and see what happen

**Comment by isakube** [comment]
OH

interesting ok

**Comment by isakube** [comment]
> Or `lime rebuild linc_luajit macos` and see what happen

DUDE IT FUCKING WORKEDDDDDD

IT GENERATED SOME ERRORS BUT IT WORKED
ILL SEE WHAT THE ERRORS SAY AFTER

edit: fuck. never celebrate too early.
![Screen Shot 2021-07-15 at 10 50 57 AM](https://user-images.githubusercontent.com/68293280/125834343-27ac1daf-ddbb-41ea-95b1-d8406056b9ec.png)
![Screen Shot 2021-07-15 at 10 51 05 AM](https://user-images.githubusercontent.com/68293280/125834352-3ffd3486-0650-4a5a-a674-64196f29f19d.png)
![Screen Shot 2021-07-15 at 10 51 12 AM](https://user-images.githubusercontent.com/68293280/125834358-b4cd8220-ac97-467a-b31e-5df9e9ad1af3.png)
![Screen Shot 2021-07-15 at 10 51 21 AM](https://user-images.githubusercontent.com/68293280/125834361-4981f683-a8da-40d5-b716-5db22cc6fecf.png)

**Comment by uncreative-avis** [comment]
so is there _any_ way to get Lua mod charts working on mac? ((I'm on macOS and Lua mod charting looks really cool **_AAAA_**)

**Comment by MagnusStrom** [comment]
dont think so. use hscript on mic’d up or pfnf

**Comment by ghost** [comment]
if you already have charts from kade use mic'd up, if not use projectfnf

**Comment by haya3218** [comment]
It IS possible to build mac and linux binaries using lime, but idk how

Edit: Theres a parameter that allows it to build for neko on windows mac or linux, why not replace -neko with -cpp?

**Comment by ghost** [comment]
> It IS possible to build mac and linux binaries using lime, but idk how
> 
> Edit: Theres a parameter that allows it to build for neko on windows mac or linux, why not replace -neko with -cpp?

its not really possible to build windows to cpp on linux

**Comment by ThatOneCalculator** [comment]
> It IS possible to build mac and linux binaries using lime, but idk how
> 
> Edit: Theres a parameter that allows it to build for neko on windows mac or linux, why not replace -neko with -cpp?

just `haxelib run lime build linux`

**Comment by Kade-github** [comment]
Complete for linux, mac soon? No idea.
