### ISSUE TITLE
Replay Error

### ISSUE THREAD

**Issue by Ianlox419** [KadeArchive/Kade-Engine#688]
I have this error when the song ends.

OS: Windows 10 x64

Kade Engine Ver: 1.4.2

![Error Replay](https://user-images.githubusercontent.com/85002548/120728505-12469780-c4ab-11eb-9540-8d712d30d246.png)

It's the same with other mods (Whitty,Kris,Tricky,Hex,Flexy,Sans)

**Comment by isakube** [comment]
make sure Kade Engine has access to the replays folder

**Comment by Ianlox419** [comment]
> make sure Kade Engine has access to the replays folder

how i do that?

**Comment by puyoxyz** [comment]
> > make sure Kade Engine has access to the replays folder
> 
> how i do that?

make sure it's in your user directory. user directory is stuff like desktop, downloads, documents. and *not* another user's user dir, specifically *yours* (so YOUR desktop, not someone elses, for example)

also make sure the folder exists

**Comment by Ianlox419** [comment]
don't works

**Comment by Rajbir98** [comment]
help me i am having this error too
