### ISSUE TITLE
Bug Report: Removing Notes still not working

### ISSUE THREAD

**Issue by 111robloxdude** [KadeArchive/Kade-Engine#69]
Whenever i right click a note in the editor it does absolutely nothing i don't think there's a way currently to get rid of any notes without clearing or resetting. pretty huge bug

**Comment by blackm1n** [comment]
Reminder: you're supposed to left click... not right click...

**Comment by Kade-github** [comment]
First, you don't right click you just click a note, and again it works just fine for me.
