### ISSUE TITLE
mfw customize gameplay button crashes kade 1.5 

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#697]
shit don't work, fix it g

**Comment by sskadff23** [comment]
was just gonna make this post, it indeed crashes.

**Comment by mayo78** [comment]
do it from k to j to f to d

**Comment by puyoxyz** [comment]
can someone run it through a terminal (with `-debug` flag, like `lime test windows -debug`) and see if it outputs anything when it crashes?

**Comment by puyoxyz** [comment]
nevermind this is same thing as https://github.com/KadeDev/Kade-Engine/issues/698 so closing
