### ISSUE TITLE
Bug Report: Clown Sounds being pulled from Tiky

### ISSUE THREAD

**Issue by NoiceBroice** [KadeArchive/Kade-Engine#698]
You get errors when you assign new keybinds since it is trying to pull clown/sounds/Hover.ogg

silly kade pasting from tiky

**Comment by Kade-github** [comment]
man i'm lazy gimme a break :( https://github.com/KadeDev/Kade-Engine/commit/9fabd2408f1ba1059f5a137f0ac9d50a97ceea0d
