### ISSUE TITLE
the note offset option doesn't actually do anything

### ISSUE THREAD

**Issue by PolyDrawn** [KadeArchive/Kade-Engine#7]
i tried it many times, from -50, -100, 50, 100, anything, and the notes never actually changed their timings. perhaps this is just a problem with my installation but i wanted to report it to make sure

**Comment by Kiffolisk** [comment]
let me find what it actually does rq

**Comment by Kiffolisk** [comment]
"Does your headphones have an audio delay? Well you can set a note offset in the options menu!"

**Comment by PolyDrawn** [comment]
well logically i would eventually be able to press the notes on time, fps+ worked perfectly when i set the audio delay to about 90
but on this one the option doesnt actually do anything i dont think

**Comment by Kade-github** [comment]
fixed

**Comment by PolyDrawn** [comment]
poggers, thank u for hearin me out :)

**Comment by PolyDrawn** [comment]
(and for making a pretty great mod)
