### ISSUE TITLE
Enhancement: Offset Tetser

### ISSUE THREAD

**Issue by Kadoodly** [KadeArchive/Kade-Engine#70]
## What is your suggestion, and why should it be implemented?
An offset tester to find out what offset you need (kind of like how quaver finds your offset by tapping to the beat and suggests what your offset needs to be).

Since theirs features you've already implemented such as ms timing, and the new acc system I think that all that's missing now is a offset tester/helper.

**Comment by Kade-github** [comment]
Added in nightly 3
