### ISSUE TITLE
Bug Report: Going into key bindings and mapping Enter or Backspace can sometimes crash the game

### ISSUE THREAD

**Issue by dxpperwoke** [KadeArchive/Kade-Engine#700]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by Kade-github** [comment]
Fixed in https://github.com/KadeDev/Kade-Engine/commit/39d52b9e0b9de55e05a36fa2306a3ec51aa748dc
