### ISSUE TITLE
Game not loading

### ISSUE THREAD

**Issue by epicbobmanbob** [KadeArchive/Kade-Engine#702]
When I test with HTML5 on 1.5 for some reason it gets stuck on loading compared to 1.4.1 which worked fine.
I have tried with and without debug mode enabled but it doesn't do anything.
![badloadingscreen](https://user-images.githubusercontent.com/78581658/120882551-6fb31500-c58d-11eb-8138-40bd8a8719ee.PNG)

**Comment by darshytheplayer** [comment]
Same thing here, something's up.

Guessing a 1.5.1 fix might come soon

**Comment by puyoxyz** [comment]
![image](https://user-images.githubusercontent.com/15311104/120888935-2e594e80-c5fb-11eb-8152-4e9105016a52.png)

this might have something to do with it (WHO BROKE ALPHABET!!!!)

@KadeDev: someone broke alphabet on html5 THIS IS WHY WE TEST BEFORE MERGING!!!

**Comment by epicbobmanbob** [comment]
also, if anyone asks I'm using the source code to test, not the website.

**Comment by epicbobmanbob** [comment]
> ![image](https://user-images.githubusercontent.com/15311104/120888935-2e594e80-c5fb-11eb-8152-4e9105016a52.png)
> 
> this might have something to do with it (WHO BROKE ALPHABET!!!!)
> 
> @KadeDev: someone broke alphabet on html5 THIS IS WHY WE TEST BEFORE MERGING!!!

I think I know the issue. When I load up alphabet.xml, there are red "&" symbols.
![hint](https://user-images.githubusercontent.com/78581658/120901322-f0562d80-c5ee-11eb-9158-0bb529ac9302.PNG)

**Comment by Kade-github** [comment]
fixed in https://github.com/KadeDev/Kade-Engine/commit/de35797a37acbb4cff43d8c639f74c43a494f0fa

**Comment by epicbobmanbob** [comment]
> > ![image](https://user-images.githubusercontent.com/15311104/120888935-2e594e80-c5fb-11eb-8152-4e9105016a52.png)
> > this might have something to do with it (WHO BROKE ALPHABET!!!!)
> > @KadeDev: someone broke alphabet on html5 THIS IS WHY WE TEST BEFORE MERGING!!!
> 
> I think I know the issue. When I load up alphabet.xml, there are red "&" symbols.
> ![hint](https://user-images.githubusercontent.com/78581658/120901322-f0562d80-c5ee-11eb-9158-0bb529ac9302.PNG)

Well I discovered the actual issue.
![hint2](https://user-images.githubusercontent.com/78581658/120901552-96eefe00-c5f0-11eb-904c-9d60088b7643.PNG)
@KadeDev FIX THE UPPERCASE LETTERS
