### ISSUE TITLE
Compiling to linux from windows

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#704]
I'm on windows 
basically im trying to compile a mod i made to Linux for my friend who doesn't use windows
but then this appears and i don't know how to fix it...
![image](https://user-images.githubusercontent.com/79254366/120886634-26a8a280-c619-11eb-850e-6d5b51b9f0ad.png)

**Comment by Keoiki** [comment]
Those are just warning, I get the same ones all the time and I just ignore them.

**Comment by puyoxyz** [comment]
You can't build to linux if you aren't on linux, use Windows Subsystem for Linux

**Comment by ghost** [comment]
Or ask me. I can build to Linux on request.
