### ISSUE TITLE
Mapping keys doesn't work on linux 

### ISSUE THREAD

**Issue by LukeeMan** [KadeArchive/Kade-Engine#705]
basically, i went into the keybind menu, pressed enter, then pressed my preferred keybind. it just showed "?" and didn't register my keybind. tried this multiple times, different keys, same result. Another thing is when i "saved" these "keybinds" it just permanently mashed them without me touching anything, i'm going to add a video later with my phone because my computer is absolute trash

edit: https://imgur.com/a/uiET6qC

**Comment by Kade-github** [comment]
naw seem to not work on any platform, but I realized the issue.
fixed in https://github.com/KadeDev/Kade-Engine/commit/28699426a42b683d9d09b1d5e165a79539349580

**Comment by ghost** [comment]
Mint? That's just Ubuntu without snaps! I don't understand why it's popular.

**Comment by LukeeMan** [comment]
> Mint? That's just Ubuntu without snaps! I don't understand why it's popular.

ubunt more lag, mint no lag

**Comment by ghost** [comment]
Cinnamon on Ubuntu, same as Mint

**Comment by LukeeMan** [comment]
WAIT GITHUB HAS REAL TIME REPLIES

**Comment by LukeeMan** [comment]
holy shit

**Comment by LukeeMan** [comment]
anyway im gonna try it

**Comment by ghost** [comment]
> WAIT GITHUB HAS REAL TIME REPLIES

I have a notification counter
