### ISSUE TITLE
Custom week issue

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#707]
![Capture](https://user-images.githubusercontent.com/82577051/120890922-531fe700-c638-11eb-927e-dbb999dbe65a.PNG)

im addin a custom week but it says source/StoryMenuState.hx:48: characters 9-10 : Expected ].

If anyone knows the problem, please let me know :) (im new to this crap)

**Comment by puyoxyz** [comment]
show ur code?
