### ISSUE TITLE
Bug Report: FlxBar

### ISSUE THREAD

**Issue by TaeYai** [KadeArchive/Kade-Engine#709]
So I complain the game and this happen my 2 weeks of making mods is now lost please help me

![image](https://user-images.githubusercontent.com/82447519/120891101-e35a2e00-c630-11eb-8133-813b4d6c6fd7.png)

**Comment by puyoxyz** [comment]
you have something wrong with your audio file (maybe toggle Has voice track in song data?)

**Comment by isakube** [comment]
this also happened when somebody renamed their mp3 to .ogg. just saying

**Comment by Kade-github** [comment]
not an issue on our part, please convert your audio files correctly.
