### ISSUE TITLE
still not fixed/not working

### ISSUE THREAD

**Issue by UnknownSkid** [KadeArchive/Kade-Engine#71]
i cant delete notes and i cant be on old input

**Comment by blackm1n** [comment]
you left click to delete notes. it's fixed.

**Comment by theDetourist** [comment]
As mentioned by Kade @ #67, "Old input is probably going to be removed, the support for it has went down a hell of a lot." so, I'm sorry but I think you're better off getting used to the new one.

**Comment by Kade-github** [comment]
I can delete notes just fine I have no idea man.
