### ISSUE TITLE
Bug Report: Pressing R on an dialogue crashes the game

### ISSUE THREAD

**Issue by Maks7594** [KadeArchive/Kade-Engine#711]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows x86_64
## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1 KE 1.5
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
press r on an dialogue
## Please describe your issue. Provide extensive detail and images if possible.
idk i just want kade engine to not crash and normal fnf to crash

**Comment by Maks7594** [comment]
\

**Comment by ghost** [comment]
Hi - Here's my explanation to why this happens: It's probably trying to kill you but can't handle it while in dialogue.
