### ISSUE TITLE
Some moving parts (e.g. distractions) don't work

### ISSUE THREAD

**Issue by aladairmaxwell** [KadeArchive/Kade-Engine#714]
Ok, so, I noticed that there is completely no background train in Week 3. Neither Story Mode nor Freeplay.

![image](https://user-images.githubusercontent.com/69295711/120898956-ee638d00-c635-11eb-8599-de1aa7743115.png)

Also for some reason Limo Dancers only visible in vanilla Week 4, but if you set "limo" as your stage for custom level, there will be only small Flixel logos floating. Though, fast background cars work fine. Distractions: ON. I'm using up to date Kade 1.5. How do I fix this problem? 

![image](https://user-images.githubusercontent.com/69295711/120899000-279bfd00-c636-11eb-937b-3431e28c8358.png)

**Comment by Kade-github** [comment]
fixed in https://github.com/KadeDev/Kade-Engine/commit/3bd5a2d3125214bb09d54fc7c219f1893a1b4561

**Comment by aladairmaxwell** [comment]
Hey, I'm sorry, but this fix didn't help for train for Philly levels. But dancers works okie-dokie now. What should I do now?

**Comment by ghost** [comment]
Hi - Try downloading 1.5.1 stable. Flixel logos are normally due to missing assets and redownloading might solve the issue.

**Comment by aladairmaxwell** [comment]
I've already using stable 1.5.1, but I'm talking about Pico week trains. They are not working.

**Comment by ghost** [comment]
Try redownloading 1.5.1. Redownload.
