### ISSUE TITLE
Spooky Kids Animation

### ISSUE THREAD

**Issue by JordanSantiagoYT** [KadeArchive/Kade-Engine#719]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows ('x86_64')

## What version of the game are you using? Look in the bottom left corner of the main menu.
Kade Engine V1.5, Vanilla game v0.2.7.1

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Step 1: Play Week 2 
Step 2: Watch the Spooky Kids' animation
Step 3: They will loop.
## Please describe your issue. Provide extensive detail and images if possible.
I was making a FNF charting mod but then I found that the spooky kids' animation looped, but only on one side. It can alternate after their turns however.
The YouTube video linked below is proof.
https://www.youtube.com/watch?v=B381VQ7Msao

**Comment by puyoxyz** [comment]
fixed already in master

**Comment by ghost** [comment]
Hi -  try 1.5.1 and see if it works. It appears to be fixed in master, so it might be part of 1.5.1. The below comment may help:


> fixed already in master
