### ISSUE TITLE
toLowerCase() stopping loading

### ISSUE THREAD

**Issue by epicbobmanbob** [KadeArchive/Kade-Engine#720]
(This a extension of #702)
When I use the [website](https://funkin.puyo.xyz/nightly/) or compile with the source code, it gets stuck on 80% and when I check with Inspect (Element) it says "Cannot read property toUpperCase() of undefined". I don't know how to fix this even after editing the source code.
![hint2](https://user-images.githubusercontent.com/78581658/120902680-8b063a80-c5f6-11eb-9b7c-733bbc0b1b8a.PNG)

**Comment by epicbobmanbob** [comment]
Just checked and @KadeDev fixed the bug. Gonna close this.

**Comment by epicbobmanbob** [comment]
So the fix is only in 1.5.1 which isn't out yet. So when the update comes out I will re-close the issue.

**Comment by Kade-github** [comment]
dw I gotchu

**Comment by epicbobmanbob** [comment]
Thanks!

**Comment by epicbobmanbob** [comment]
@KadeDev No more thanks I guess since it's STILL broken.

**Comment by oketariq** [comment]
You sure you have the latest git code?
