### ISSUE TITLE
Bug Report: Kade Engine stating an outdated version despite being on latest release

### ISSUE THREAD

**Issue by GGianniTheGG** [KadeArchive/Kade-Engine#724]
(OS: Windows (x86)) Kade Engine Version: 1.5.0

When booting up the latest release of Kade Engine, I get an alert that should appear when playing an outdated version, and this particular one suggests a new version that is 1.5.1, even if that version doesn't exist, as I've looked everywhere for it to no avail.

 How to recreate: Download Kade Engine 1.5.0, and boot up the game. You should get a message that looks like this;
![bad kade](https://user-images.githubusercontent.com/85413661/120903407-d02c6b80-c5fa-11eb-9740-adcf6b821141.png)
I'm not sure if this is a bug through the code that detects a new version, or if this version was removed for bug fixes, but I just thought it was weird and don't want to see this message every time I boot Kade Engine until there is a new release. Please fix this. Thank you.

**Comment by outofthecoral** [comment]
That version actually does exist as of a few minutes ago

**Comment by Kade-github** [comment]
just we just released.

**Comment by ghost** [comment]
Hi - 1.5.1 exists.

**Comment by GGianniTheGG** [comment]
Thank you, this was made moments before the release of 1.5.1, just to clarify.
