### ISSUE TITLE
Can't change Satin panties, Philly nice, Dad battle and Winter horrorland

### ISSUE THREAD

**Issue by Prod-42** [KadeArchive/Kade-Engine#725]
I changed Satin panties to b side and when i was starting the song the game crashed and the same to Philly, Dad battle and Winter horrorland, after that I tried to change the .json putting spaces between the name and the same thing happened, in the end I downloaded the kade engine again and passed everything to b side again but Satin panties, Philly and winter horrorland I had to leave them the same

**Comment by Kade-github** [comment]
all of these were changed recently to have spaces, I recently did a patch to revert the names in the data format to include -'s. For Philly nice though you'll have to change `philly` to `philly-nice` for every file containing that in bsides.

**Comment by Prod-42** [comment]
Wow it actually worked! thx Kade:)
