### ISSUE TITLE
in thorns dialouge the is a black image of the senpai portrait over spirit's one

### ISSUE THREAD

**Issue by bugreporter1243** [KadeArchive/Kade-Engine#726]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## Please describe your issue. Provide extensive detail and images if possible.
![bug](https://user-images.githubusercontent.com/85414478/120904022-735c9f80-c652-11eb-9c36-6d8bfd6c718f.png)

**Comment by epicbobmanbob** [comment]
That's meant to be there. It isn't a bug.

**Comment by TeleKiwi** [comment]
I think what they mean is that Senpai's portrait should be _behind_ Spirit, not in front of it. That's how it is in the OG Engine.

**Comment by epicbobmanbob** [comment]
> I think what they mean is that Senpai's portrait should be _behind_ Spirit, not in front of it. That's how it is in the OG Engine.

Yes. I haven't played week 6 in a while so I forgot that it was behind not in front.

**Comment by ghost** [comment]
Hi - This is a bug which I think is in the source code of Friday Night Funkin'. It was fixed in a Newgrounds release but has not been fixed on GitHub yet. Hopefully it should be fixed soon.

**Comment by puyoxyz** [comment]
this will be fixed when 0.2.8 source is out

**Comment by isakube** [comment]
> this will be fixed when 0.2.8 source is out

isnt it just like a layering issue lol
