### ISSUE TITLE
Enhancement: Bring back Eggnog to Winter Horrorland jumpscare transition

### ISSUE THREAD

**Issue by GGianniTheGG** [KadeArchive/Kade-Engine#727]
Honestly, I don't really understand why they removed it, or if it's a bug because let's be honest, this version of Kade is a buggy mess, so you really can't know what was and wasn't intentional. If this is a bug, please fix it, If this is intentional, please bring it back. 
I feel it should be brought back because it kind of ruins the whole scary aspect of Winter Horrorland, and it really sets the theme for the last song, paired with Monster's creepy looks, it's just really fitting.
https://www.youtube.com/watch?v=Ywhl8SRjpsQ

**Comment by puyoxyz** [comment]
this is because of the bug with dashes and spaces

**Comment by Lucky-56** [comment]
brought that back on my pr [#763](https://github.com/KadeDev/Kade-Engine/pull/763), we'll have to wait for that to be merged

**Comment by Lucky-56** [comment]
- PR #763 fixed this

reminder to close this issue
