### ISSUE TITLE
Enhancement: Make This Repository A GitHub Template

### ISSUE THREAD

**Issue by Ombrezz** [KadeArchive/Kade-Engine#728]
## What is your suggestion, and why should it be implemented?
This isn't a change to the engine itself, but rather a change to the repository.  If you make it a [template](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/creating-a-template-repository), then it would be much easier to make a mod with Kade Engine on Github.  Since the repo can be private, people won't get prompts to try and make a pull request for the original repo, and it gets rid of most other annoyances that come with forks.

**Comment by Kade-github** [comment]
I'll keep this in mind

**Comment by isakube** [comment]
oh hey that's cool

**Comment by ghost** [comment]
Will we still get Issues, Pull Requests, Discussions and releases?

**Comment by puyoxyz** [comment]
NO!!!!!!!!!!! DON'T DO THIS!!!!!!!!!

- i don't think u understand what the template option is actually for
- if someone tries to update the KE of their mod git WILL get confused because template doesn't give you the git history
- "the repo can be private" ~~you can private a fork.~~ (nvm apparently u cant thats kinda dumb) and if you're saying kade engine can be private, *no*, kade engine will always be open source
- "people won't get prompts to make a pr" it's not a PROMPT. it's a SMALL BOX that you can EASILY IGNORE and if someone accidentally PRs their mod into KE we can just close it
- "other annoyances that come with forks" what annoyances

**Comment by Ombrezz** [comment]
You raised some pretty good points, a template would be worse than I initially thought.  However I'm still pretty sure you can't private forks, I've tried multiple times on multiple repos and the option to private it is just grayed out.  Unless your talking about something like [this](https://stackoverflow.com/questions/10065526/github-how-to-make-a-fork-of-public-repository-private), which works but is tedious and a hacky solution.  I'm probably overlooking something here though.

**Comment by puyoxyz** [comment]
> You raised some pretty good points, a template would be worse than I initially thought. However I'm still pretty sure you can't private forks, I've tried multiple times on multiple repos and the option to private it is just grayed out. Unless your talking about something like [this](https://stackoverflow.com/questions/10065526/github-how-to-make-a-fork-of-public-repository-private), which works but is tedious and a hacky solution. I'm probably overlooking something here though.

![image](https://user-images.githubusercontent.com/15311104/120965639-77c5ad00-c765-11eb-89b4-d6a5db62d2fa.png)
You do realize this option (which appears when you make a completely empty repo) works with GitHub repos too, right? Just... make a private repo (and don't add a .gitignore/README/license if it asks you to) and then paste in `https://github.com/KadeDev/Kade-Engine.git` there

Alsoooooo I'm pretty sure if you want to update your mod's KE later on you can just `git pull https://github.com/KadeDev/Kade-Engine.git --allow-unrelated-histories` (i've done that before and it worked)

**Comment by puyoxyz** [comment]
Also, if you mean [this](https://help.github.com/articles/duplicating-a-repository), the *official way GitHub tells you how to make a duplicate of a repo without using the fork feature* which uses a *git feature* (mirrored push) is "hacky", then I don't know what to say.
