### ISSUE TITLE
Bug Report: Funkin.exe deleting itself

### ISSUE THREAD

**Issue by Rayray1703** [KadeArchive/Kade-Engine#73]
Whenever i compressed the zip files then try to launch the game almost all the time Funkin.exe will delete itself for no reason

**Comment by blackm1n** [comment]
Delete your anti-virus.

**Comment by Rayray1703** [comment]
also this is on Windows and the version im downloading is the 64x version

**Comment by Kade-github** [comment]
uhh I think thats probably your AV. Kade Engine doesn't have the functionality to delete itself.

**Comment by Rayray1703** [comment]
oh thanks for telling me lol
