### ISSUE TITLE
Bug Report: Discord Rich Presence doesn't go away after crash

### ISSUE THREAD

**Issue by TeleKiwi** [KadeArchive/Kade-Engine#730]
## Details
Windows ('x86_64') 
Kade Engine 5.0

## The Bug
I was playing Fresh when the game crashed because a replay couldn't save. However, when the game crashed, the Rich Presence status doesn't deactivate. It doesn't go away even after I reopen the game and then close it again. It doesn't seem to fix itself either, as it's been several hours since the crash and nothing's changed. 
## Steps To Reproduce
There isn't a way to consistently reproduce this glitch since it's triggered by a game crash, but here it is anyway.

1. Load into a level and play it all the way through.
2. Somehow cause the game to crash (might be only due to a replay not saving but I'm not sure)
3. You'll see that the game's RP doesn't go away.

## Screenshots
You can see that the RP is still here...
![image](https://user-images.githubusercontent.com/70376250/120904943-e19b6500-c646-11eb-9b46-c5d38f12ef5a.png)

Even though the game isn't even open.
![image](https://user-images.githubusercontent.com/70376250/120904972-05f74180-c647-11eb-93fd-d21b57409b3d.png)

**Comment by TeleKiwi** [comment]
Gonna close this issue as I found out that a PC restart fixes it pretty easily. lol

**Comment by TeleKiwi** [comment]
Gonna close this issue as I found out that a PC restart fixes it pretty easily. lol

**Comment by puyoxyz** [comment]
duplicate of https://github.com/KadeDev/Kade-Engine/issues/234
