### ISSUE TITLE
Bug report: game zooms in when switching songs

### ISSUE THREAD

**Issue by ItzYaBoiJosh** [KadeArchive/Kade-Engine#732]
So, when I open the phase/song the misses counter and all things are there but when it's the opponent's round it just turns off like I turned accuracy mode off but I didn't

Pictures : (when a note from the opponent didn't appear https://user-images.githubusercontent.com/68428075/120905226-741b1480-c605-11eb-9f46-046325f1f7a3.png)
(When a note appeared : https://user-images.githubusercontent.com/68428075/120905248-a88ed080-c605-11eb-8c70-2f08d94b979a.png)

**Comment by ItzYaBoiJosh** [comment]
Note : It appears on downscroll but I'm not used to play with downscroll
(https://user-images.githubusercontent.com/68428075/120905360-5a2e0180-c606-11eb-8e9f-9cfc56230108.png)

**Comment by Kade-github** [comment]
I cannot reproduce this bug at all, what version are you on?

**Comment by Kade-github** [comment]
> I cannot reproduce this bug at all, what version are you on?

I'm a dumbass, I looked at the bottom left and yeah I still can't reproduce that bug at all.

**Comment by ghost** [comment]
Hi - What is your current screen resolution? Does Pressing "f" on the credits/bopping GF screen to fullscreen the game fix the issue?

**Comment by ItzYaBoiJosh** [comment]
> Hi - What is your current screen resolution? Does Pressing "f" on the credits/bopping GF screen to fullscreen the game fix the issue?

my resolution is 1920 x 1080, what resolution would be required?

**Comment by ItzYaBoiJosh** [comment]
> > I cannot reproduce this bug at all, what version are you on?
> 
> I'm a dumbass, I looked at the bottom left and yeah I still can't reproduce that bug at all.

oh, thanks anyways for trying to help me tho

**Comment by puyoxyz** [comment]
[ i was wrong ]

**Comment by ghost** [comment]
> > Hi - What is your current screen resolution? Does Pressing "f" on the credits/bopping GF screen to fullscreen the game fix the issue?
> 
> my resolution is 1920 x 1080, what resolution would be required?

That is a high enough resolution. 1280x720 is minimum i believe. I recommend turning down the scale of your dispay though.

**Comment by ItzYaBoiJosh** [comment]
> > > Hi - What is your current screen resolution? Does Pressing "f" on the credits/bopping GF screen to fullscreen the game fix the issue?
> > 
> > 
> > my resolution is 1920 x 1080, what resolution would be required?
> 
> That is a high enough resolution. 1280x720 is minimum i believe. I recommend turning down the scale of your dispay though.

Hmm, still doesn't work for some reason.
