### ISSUE TITLE
Enhancement:  Option to Skip Countdown before song

### ISSUE THREAD

**Issue by Fgm320-9** [KadeArchive/Kade-Engine#733]
An option to skip the 3, 2, 1, go before a song would be nice because sometimes you just wanna get to playing and not have to wait for anything.

**Comment by Lucky-56** [comment]
kinda added this in my engine, but it's buggy on some songs that start immediately

**Comment by puyoxyz** [comment]
this would just completely break any song that starts immediately as lucky said; closing wontfix
