### ISSUE TITLE
how do i create an tutorial

### ISSUE THREAD

**Issue by NotTheCoderGb** [KadeArchive/Kade-Engine#734]
so i want to do docs/guides/character.md

How i should make it and how do i post?

**Comment by epicbobmanbob** [comment]
You will need to fork the repository, make the guide, then create a pull request when you are done.

**Comment by epicbobmanbob** [comment]
For the guide you should try using these resources: 

- https://gamebanana.com/tuts/13798 for the custom characters.
- https://medium.com/swlh/how-to-make-the-perfect-readme-md-on-github-92ed5771c061 for the .md file.

**Comment by NotTheCoderGb** [comment]
> For the guide you should try using these resources:
> 
> * https://gamebanana.com/tuts/13798 for the custom characters.
> * https://medium.com/swlh/how-to-make-the-perfect-readme-md-on-github-92ed5771c061 for the .md file.

well all i need is to know how to write an perfect .md file

**Comment by epicbobmanbob** [comment]
Then only use the bottom link.

**Comment by NotTheCoderGb** [comment]
ya so thx
