### ISSUE TITLE
1.5.1 web fixes are not working

### ISSUE THREAD

**Issue by epicbobmanbob** [KadeArchive/Kade-Engine#735]
(This is a extension of #720 which is a extension of #702. I'm pushing the limits aren't I?)
I tried to test with html5 with the new 1.5.1 source code but the fix it says in the changelog isn't working.
As it says in the changelog of 1.5.1 > "Made web builds work again."
Yet when I tried to test (with and without debug mode) it still doesn't work. 
Here is proof if you think I'm lying.
![still not fixed](https://user-images.githubusercontent.com/78581658/120905924-4daba800-c60a-11eb-9b87-579e2b75cba0.PNG)

**Comment by oketariq** [comment]
HEYY i fixed this in my pr so just get the code from that until kade merges!! https://github.com/KadeDev/Kade-Engine/pull/736

**Comment by Kade-github** [comment]
^

**Comment by epicbobmanbob** [comment]
DUDE. THANK YOU GUYS!!!

**Comment by ghost** [comment]
Hi - You might want to update Haxe and also update your Haxelibs. You appear to be running Flixel 4.8.1, whereas the latest is 4.9.0. I am aware that the issue is solved.
