### ISSUE TITLE
Mod problems and crashin

### ISSUE THREAD

**Issue by WDrawstic** [KadeArchive/Kade-Engine#738]
The problem I want to talk about is the issue of mods in the engine.
What happens is that when trying to play with a mod the game crashes, or if everything does not work except the background. There are still details of the mods using the 7 button but they don't load properly.

**Comment by Kade-github** [comment]
more information?

**Comment by WDrawstic** [comment]
Well another thing is of dad battle song cause say that doesnt exist and can be played

**Comment by WDrawstic** [comment]
But talking about the problem i say, thats all i can say cause actually i dont know about programation language at all

**Comment by WDrawstic** [comment]
And sorry if maybe some things i wrote doesnt understand, cause i dont speak to much english

**Comment by Kade-github** [comment]
yeah that was already fixed, redownload it from the release page.

**Comment by WDrawstic** [comment]
okey thanks
