### ISSUE TITLE
Bug Report: 1.5.1 HTML5 Build STILL does not load past 80% on startup

### ISSUE THREAD

**Issue by darshytheplayer** [KadeArchive/Kade-Engine#740]
Been sitting here at the loading screen for 30 minutes, didn't budge at all from 80%. 
Website's [https://funkin.puyo.xyz/nightly/](url)

Computer definitely ain't the problem.

**Comment by Kade-github** [comment]
p sure that hasn't been updated in awhile (cuz the change that fixed that was like a couple hours ago, not 23)
![image](https://user-images.githubusercontent.com/26305836/120907571-9322a200-c617-11eb-8fdf-b92d50a7795c.png)
