### ISSUE TITLE
Bug Report: Kade engine sound and music not working.

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#742]
So alot of times when i open up kade engine the sound and music stops working. Also the charts bug out so i have to restart it.

**Comment by Kade-github** [comment]
what

**Comment by ghost** [comment]
Hi - Try downloading 1.5.1 from the Releases page and checking if the issue persists. Otherwise try cloning the master branch.

**Comment by puyoxyz** [comment]
maybe ur accidentally pressing -= and muting it

**Comment by puyoxyz** [comment]
closing because ur not replying
