### ISSUE TITLE
Bug Report: Winter Horrorland (Any Difficulty) Crashes

### ISSUE THREAD

**Issue by PoikFox** [KadeArchive/Kade-Engine#744]
Horrorland just downright refuses to load, and crashes shortly after.

**Comment by ghost** [comment]
Got the same issue, it just straight up crashes.

**Comment by puyoxyz** [comment]
This is a known bug and we are fixing it -- closing all issues reporting this because y'all don't know how to use the search bar (and I dunno which one was first)

(pasted response)
