### ISSUE TITLE
Bug Report: okay so i was playing like a normal dude the original weeks with the 1.5.1 K.E, and then the game crashes and appears [lime.utils.Assets] ERROR: There is no TEXT asset with an ID of "assets/data/philly nice-hard.json"  the same happened to me in dad battle 

### ISSUE THREAD

**Issue by GenerLuna** [KadeArchive/Kade-Engine#746]

**Comment by InfinityPlus05** [comment]
can confirm, this happens with winter horrorland as well. the bug only occurs in week mode, where it appears to be trying to get a file "song name-hard.json" in "song name" folder instead of "song-name-hard.json" in "song-name" folder. free play does work with these songs

**Comment by theDetourist** [comment]
Not a bug, Kade forgot to mention that Winter Horrorland, Satin Panties, Philly Nice and Dad Battle were all conformed to #480. If you're compiling the game, delete your export folder entirely and recompile the game completely again and it should be fixed.

**Comment by puyoxyz** [comment]
This is a known bug and we are fixing it -- closing all issues reporting this because y'all don't know how to use the search bar (and I dunno which one was first)

(pasted response)
