### ISSUE TITLE
Dadbattle Crashes in new update 

### ISSUE THREAD

**Issue by pokeyjojo** [KadeArchive/Kade-Engine#750]
Dadbattle throws a null object reference error  without modifications is there a fix?

**Comment by isakube** [comment]
haha stupid alphabet issue (probably)
idk how its an alphabet issue though.

The only songs that have crashed so far have spaces in their data folder names, so im assuming something doesn't load.

**Comment by theDetourist** [comment]
Quoting back from https://github.com/KadeDev/Kade-Engine/issues/746#issuecomment-855347499

Not a bug, Kade forgot to mention that Winter Horrorland, Satin Panties, Philly Nice and Dad Battle were all conformed to #480. If you're compiling the game, delete your export folder entirely and recompile the game completely again and it should be fixed.

**Comment by ghost** [comment]
> Not a bug, Kade forgot to mention that Winter Horrorland, Satin Panties, Philly Nice and Dad Battle were all conformed to #480. If you're compiling the game, delete your export folder entirely and recompile the game completely again and it should be fixed.

Hi - adding `-clean` to the end of the build command should also fix it.

**Comment by puyoxyz** [comment]
This is a known bug and we are fixing it -- closing all issues reporting this because y'all don't know how to use the search bar (and I dunno which one was first)

(pasted response)
