### ISSUE TITLE
Bug Report: Can't play custom weeks in HTML5

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#751]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows x64
## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1 KE 1.5.1
## Please describe your issue. Provide extensive detail and images if possible.
I tried to play a custom week I made in KE but it gets stuck in the loading screen

**Comment by oketariq** [comment]
install latest code!! it's an error that is now fixed

**Comment by ghost** [comment]
still hasnt been fixed kek

**Comment by puyoxyz** [comment]
> still hasnt been fixed kek

yes it has (idk hdboye said it), try latest `master` branch

if ur console output when it gets stuck is same as #772 then just make a comment on #772
