### ISSUE TITLE
Bug Report: Songs with Spaces Don't Load as their Assets Have Been Changed (see example)

### ISSUE THREAD

**Issue by mangohs** [KadeArchive/Kade-Engine#752]
On Kade Engine 1.5.1,
Songs with spaces in their names in-game, such as Dad Battle or Winter Horrorland, don't load in-game as their files in assets/data have been changed to use dashes instead (e.g. dad-battle instead of dad battle). This causes the game to crash.

**Comment by ghost** [comment]
Hi - Try compiling with `-clean` at the end
