### ISSUE TITLE
Bug Report: Week 3 uses wrong song name

### ISSUE THREAD

**Issue by Lucky-56** [KadeArchive/Kade-Engine#753]
# I'm using the ~~pre~~ compiled version on Win x64
>we changed it back to philly
_Originally posted by @KadeDev [here](https://github.com/KadeDev/Kade-Engine/issues/741#issuecomment-855307570_)

In Story Mode on week 3 the second song (philly) still has the name "philly nice".
On freeplay it's fine.
If you want to play story mode and get to philly the game crashes saying that "philly nice.json; philly nice-hard.json; or philly nice-easy.json" is missing.

**Comment by Lucky-56** [comment]
well should've just compiled it myself before creating a issue... :/

**Comment by Lucky-56** [comment]
just compiled, issue is still present.
![image](https://user-images.githubusercontent.com/55949451/120919529-683d5a00-c6ba-11eb-9e67-0f4fd32626cf.png)

**Comment by ghost** [comment]
Hi - Compile with `-clean` and try again.

**Comment by ghost** [comment]
Step 1:Open up "StoryMenuState.hx" in the source folder of the KE source code
Step 2:Find this line in the picture below
![image](https://user-images.githubusercontent.com/79254366/120920953-8e2f2280-c6eb-11eb-9aee-ea894df8b9ca.png)
Step 3:Change "Philly Nice" to "Philly"

**Comment by Lucky-56** [comment]
already did after I saw that it wasn't fixed in the newest pull

**Comment by oketariq** [comment]
This is because the new alphabet now supports supposedly supports spaces, and since Philly Nice is the full name (but it didn't get into the official version of the game cuz of the space) Kade (or the person who made the pr) made it Philly Nice.

Well spaces in file names are broken.

**Comment by Lucky-56** [comment]
no they are not, like I mentioned in my issue on the top Kade said they changed it back to philly in the game files, but they forgot it in the story mode
EDIT: spaces do actually work really well in this engine while allowing spaces in game, they are translated into dashes at the point of getting the files

**Comment by puyoxyz** [comment]
This is a known bug and we are fixing it -- closing all issues reporting this because y'all don't know how to use the search bar (and I dunno which one was first)

(pasted response)
