### ISSUE TITLE
Bug Report: Game delete the Exe

### ISSUE THREAD

**Issue by Solotov103** [KadeArchive/Kade-Engine#757]
Im using 64x Bits Windows 10
Newest version Kade Engine 1.5.1

When i try to play Kade Engine the game closes and delete the exe.

**Comment by isakube** [comment]
**..........................................It deleted itself??.........................................**

`When i try to play Kade Engine the game closes and delete the exe.`

**................................................What???.................................................**

(this took me forever)

Yeah i don't know how to fix that, never heard of the exe deleting itself before so uhhhh

**Comment by dougy2shoez** [comment]
do u have Avast?
maybe it was that

**Comment by Pietrodjaowjao** [comment]
i use avast and make the same

**Comment by Pietrodjaowjao** [comment]
the avast delete the exe

**Comment by puyoxyz** [comment]
Avast is being a bitch, make an exception in your settings or give us 200$ for a cert
