### ISSUE TITLE
Bug Report:  Up and Down Arrow in Downscroll Swapped!

### ISSUE THREAD

**Issue by Jakeneutron** [KadeArchive/Kade-Engine#76]
In 1.3.1, the up and down arrows seem to be swapped when using downscroll. But works fine in upscroll.

![image](https://user-images.githubusercontent.com/80853497/112744319-1adf9680-8f6d-11eb-9ebd-9ea32945ff28.png)

**Comment by Kade-github** [comment]
this has been fixed for awhile
