### ISSUE TITLE
Custom GF skin not working

### ISSUE THREAD

**Issue by GamingInfinite** [KadeArchive/Kade-Engine#766]
The if statement below is erroring out for reasons I can't seem to understand, and I'm struggling to see where it error is.  For more information it's saying it's referencing a null object, and for those that want a specific file it's in character.hx
if (!animation.curAnim.name.startsWith('hair'))

Ask for more information if you'd like more

**Comment by isakube** [comment]
what does the error actually say when you hover over the line, if anything

**Comment by GamingInfinite** [comment]
My ide doesn't actually throw an error.  When I run lime run windows -debug and try and run the week and or song that the skin is part of it just says null object and in the console it throws this:
Called from hxcpp::__hxcpp_main
Called from ApplicationMain::main ApplicationMain.hx line 25
Called from ApplicationMain::create ApplicationMain.hx line 130
Called from lime.app.Application::exec lime/app/Application.hx line 150
Called from lime._internal.backend.native.NativeApplication::exec lime/_internal/backend/native/NativeApplication.hx line 146
Called from lime._internal.backend.native.NativeApplication::handleRenderEvent lime/_internal/backend/native/NativeApplication.hx line 370
Called from lime.app._Event_lime_graphics_RenderContext_Void::dispatch lime/_internal/macros/EventMacro.hx line 91
Called from openfl.display.Stage::__onLimeRender openfl/display/Stage.hx line 1950
Called from openfl.display.Stage::__broadcastEvent openfl/display/Stage.hx line 1166
Called from openfl.display.DisplayObject::__dispatch openfl/display/DisplayObject.hx line 1399
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 402
Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 545
Called from flixel.FlxGame::step flixel/FlxGame.hx line 677
Called from flixel.FlxGame::update flixel/FlxGame.hx line 724
Called from flixel.FlxGame::switchState flixel/FlxGame.hx line 637
Called from PlayState::create PlayState.hx line 838
Called from Character::new Character.hx line 652
Called from Character::dance Character.hx line 763

**Comment by puyoxyz** [comment]
***When your issue gets turned into a discussion, you don't make a new fucking issue, you go to the fucking discussion. Closing and locking.***
---------------> https://github.com/KadeDev/Kade-Engine/discussions/765 <----------------

**Comment by GamingInfinite** [comment]
to be fair you never said on the original post that you were moving it so I didn't know cuz when I refreshed, it just said closed

**Comment by ghost** [comment]
> _**When your issue gets turned into a discussion, you don't make a new fucking issue, you go to the fucking discussion. Closing and locking.**_
> ---------------> #765 <----------------

Forgot to lock @daniel11420
