### ISSUE TITLE
help: dad third song on hard not working

### ISSUE THREAD

**Issue by stefanobarbon** [KadeArchive/Kade-Engine#767]
what does it mean by this
![imagen](https://user-images.githubusercontent.com/62155792/120945239-a8c6c300-c70e-11eb-9563-138447d9b97a.png)

**Comment by isakube** [comment]
you did a bad (probably not you though) and the file doesnt exist so just rename the file to that and you should be good

edit: wait fuck what
edit 2: this is being worked on by #763 currently, so wait for that to merge i guess

**Comment by stefanobarbon** [comment]
i fixed it, was trying to get b-sides working.

had to delete the old data folder in assets and put the kade one, the only thing is that the notes are the original ones
but if i put the b side one and rename it, it crashes without giving an error
![imagen](https://user-images.githubusercontent.com/62155792/120950053-4bd20980-c71c-11eb-8198-b7ef7ecf06bc.png)

**Comment by Lucky-56** [comment]
- PR #763 fixed this

reminder to close this issue
