### ISSUE TITLE
Bug Report: Philly Nice and Dad Battle not working

### ISSUE THREAD

**Issue by DoomEternal** [KadeArchive/Kade-Engine#768]
Every time I play either Pico's Week or Dad's Week, when I get to Philly Nice or Dad Battle the game just pulls out an error then crashes

**Comment by Rayray1703** [comment]
yeah it happened to me

**Comment by Lucky-56** [comment]
the Philly Nice bug is fixed in the master branch
and the fix for Dad Battle we'll just have to wait for my pr [#763](https://github.com/KadeDev/Kade-Engine/pull/763) to get merged

**Comment by Colby3554** [comment]
> the Philly Nice bug is fixed in the master branch
> and the fix for Dad Battle we'll just have to wait for my pr to get merged

Where is the master version?

**Comment by Lucky-56** [comment]
you need to compile it yourself though

**Comment by Lucky-56** [comment]
- PR #763 fixed this

reminder to close this issue
