### ISSUE TITLE
Bug Report: B-sides skins not working at all

### ISSUE THREAD

**Issue by stampyfan22** [KadeArchive/Kade-Engine#769]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows (x86_64)
## What version of the game are you using? Look in the bottom left corner of the main menu.
fnf 0.2.7.1 KE 1.5.1
## Please describe your issue. Provide extensive detail and images if possible.
When playing no b-side skins work and all backgrounds are the stage. My custom note skin works as well as the B-Sides audio works.

**Comment by Lucky-56** [comment]
Where did you get the B-Side mod?
Did it say 'Kade Engine supported' because Kade Engine stores files differently

**Comment by ACardboardBox1** [comment]
im pretty sure there's also a no recolors for the b side kade engine vesion as well, since he did mention the bsides audio worked

**Comment by stampyfan22** [comment]
> Where did you get the B-Side mod?
> Did it say 'Kade Engine supported' because Kade Engine stores files differently

sorry for the late response I got the B-Side remixes from gamebanana and I got the full "new file system" version which was said to support kade engines file system
I got this one
![chrome_99Z6iy0kbY](https://user-images.githubusercontent.com/35874867/121062995-a00bd680-c77a-11eb-9620-9c3583f70d12.png)

**Comment by Lucky-56** [comment]
I installed it myself to see whats the problem.

1. Skins worked
2. Stages don't load as they are no longer hard coded to the weeks, but instead being loaded by the chart #334
3. 'Dad Battle' doesn't work because 'dadbattle' has been renamed to 'dad-battle', but I will try to fix this in the name of compatibility

**Comment by Lucky-56** [comment]
I have fixed 'Dad Battle' not being able to be modded directly with #789, but we'll have to wait for that to get merged.
with the stages I could help you if you'd like

**Comment by Lucky-56** [comment]
hey I'm [done](https://github.com/Lucky-56/FNF-KE-B-Side-remixes), you may close this issue now

**Comment by RagdollClash** [comment]
It may be due to the character files all being moved to the shared folder

**Comment by puyoxyz** [comment]
edit the charts to make them use the right stage, they are on the chart now and not hard coded
