### ISSUE TITLE
Bug Report: Whenever i load a song it crashes

### ISSUE THREAD

**Issue by Enteristic** [KadeArchive/Kade-Engine#77]
Whenever I want to do a week my game crashes. How do I fix this?

**Comment by theDetourist** [comment]
1. What OS are you on?
2. Is the game from the [releases page ](https://github.com/KadeDev/Kade-Engine/releases) or did you compile it yourself?
2b. If you compiled it yourself, what shows on the command line when the game crashes?

**Comment by Enteristic** [comment]
1. windows 10 32bit pro
2. the game is from releases oage
