### ISSUE TITLE
Bug Report: custom weeks in HTML5 still doesn't  work .-.

### ISSUE THREAD

**Issue by JustALilGuy** [KadeArchive/Kade-Engine#772]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows x64
## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1 KE 1.5.1
## Please describe your issue. Provide extensive detail and images if possible.
Basically custom weeks in HTML5 still doesn't work, it shows this in the console
![image](https://user-images.githubusercontent.com/85480404/120976363-7794d400-c79c-11eb-90f4-6e4e13af4454.png)

**Comment by JustALilGuy** [comment]
Edit: This is on Freeplay mode
Story mode also gives similar errors

**Comment by daniel11420** [comment]
reopening ur old issue

**Comment by puyoxyz** [comment]
(i thought u were someone else IGNORE ME NOOOOO)

**Comment by JustALilGuy** [comment]
> (i thought u were someone else IGNORE ME NOOOOO)

lol

**Comment by sydenlous** [comment]
you must add the library week7 in your project.xml file, along with the asset path.
for example: 
library name="yourweekname"    preload="true/false" 
<assets path="assets/week7"    library="week7"    exclude="*.ogg" if="web"/>
	assets path="assets/week7"    library="week7"    exclude="*.mp3" unless="web"
the week folder is named "week7" but in order to add another week on html5, the library MUST be named week7.

**Comment by JustALilGuy** [comment]
> you must add the library week7 in your project.xml file, along with the asset path.
> for example:
> library name="yourweekname" preload="true/false"
> 
> assets path="assets/week7" library="week7" exclude="*.mp3" unless="web"
> the week folder is named "week7" but in order to add another week on html5, the library MUST be named week7.

still doesn't work
dang
thanks anyway
