### ISSUE TITLE
[Bug Report] Certain UI elements don't function with Botplay enabled

### ISSUE THREAD

**Issue by albert-softie** [KadeArchive/Kade-Engine#773]
Please check for duplicates, similar issues or closed issues with the same problem, as well performing simple troubleshooting steps (such as deleting the export folder if it's an issue with compiling, reinstalling Kade Engine) before submitting an issue.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

I don't know if it's x86 or x86_64, but I know for a fact it's a windows build, plus at the time of writing it's currently the only build of 1.5.1 available from the releases page.

### What version of the game are you using? Look in the bottom left corner of the main menu.
1.5.1 Stable

### Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Enable Botplay and load any song.

### Please describe your issue. Provide extensive detail and images if possible.
Enabling Botplay makes p1's strumline stay static instead of lighting up when notes hit (intended behavior can be seen on p2's side with light cpu strums enabled), as well as prevents note rankings (i.e. the `SICK!!`, `GOOD!`, `BAD`, `SHIT` popups that appear based on note accuracy) from appearing.
[https://youtu.be/AWAgwKQfnVA](https://youtu.be/AWAgwKQfnVA)

**Comment by ghost** [comment]
Hi - Note ranking disable is purposeful. BF with static notes is a bug.

**Comment by theDetourist** [comment]
> 
> 
> Hi - Note ranking disable is purposeful. BF with static notes is a bug.

Wasn't a bug before CPU strums lighted up as well, guess there's that to "fix" now too.

**Comment by puyoxyz** [comment]
#893
