### ISSUE TITLE
Bug Report: Added song, no music plays and won’t play song at all

### ISSUE THREAD

**Issue by Oddsock833** [KadeArchive/Kade-Engine#774]
I add a new song, put the Inst into the folder, it's in ogg format, the JSON has the song name correct, but the song won't play in the menu and when I select the song I get an error saying "[lime.utils.Assets] ERROR: There is no TEXT asset with an ID of "assets/data/overheat/overheat.json". I'm pretty new to this so this could be something really simple but I don't know. The json files are in the exact folders that the error describes.

Edit: Overheat is the name of the song I was making, of course.

**Comment by isakube** [comment]
haha yeah that happens

idk the fix

**Comment by Oddsock833** [comment]
So should I just... remake it and hope it works this time???? I mean, if it continues to happen then Kade Engine is just useless to me unless I use the thing where you manually attach it to FNF using Haxeflixel, which I did not do, and instead used the downloadable- but either way both should work...

**Comment by ghost** [comment]
> So should I just... remake it and hope it works this time???? I mean, if it continues to happen then Kade Engine is just useless to me unless I use the thing where you manually attach it to FNF using Haxeflixel, which I did not do, and instead used the downloadable- but either way both should work...

If you find KE useless try [ProjectFNF](https://github.com/aflacc/ProjectFNF)
It has a [discord server](https://discord.gg/aWCYNHF7)

**Comment by RagdollClash** [comment]
the manifest needs to be modified as well, which the best way to do that (to my knowledge) seems to be compiling the game with the files in the source code's assets folder

**Comment by puyoxyz** [comment]
Build again with the new song in the assets.
