### ISSUE TITLE
Enhancement: Add ARM/aarch64 support?

### ISSUE THREAD

**Issue by NoozAbooz** [KadeArchive/Kade-Engine#782]
## What is your suggestion, and why should it be implemented?

I suggest adding ARM CPU build support. It should be implemented because there is a growing community of people gaming on PineBooks and Raspberry Pis, and it would be nice for Kade to run as vanilla FNF is to bugged down with bug requests and such to add it in. Lime itself already supports building to armhf.

Here's the output of running a arm build though:
```
Called from hxcpp::__hxcpp_main
Called from ApplicationMain::main ApplicationMain.hx line 25
Called from ApplicationMain::create ApplicationMain.hx line 99
Called from openfl.display.Application::createWindow openfl/display/Application.hx line 90
Called from lime.app._Event_lime_ui_Window_Void::dispatch lime/_internal/macros/EventMacro.hx line 91
Called from openfl.display.Stage::__onLimeCreateWindow openfl/display/Stage.hx line 1720
Called from openfl.display.Stage::__onLimeWindowCreate openfl/display/Stage.hx line 2191
Called from openfl.display.Stage::__createRenderer openfl/display/Stage.hx line 1196
Called from openfl.display.OpenGLRenderer::new openfl/display/OpenGLRenderer.hx line 166
Called from openfl.display.OpenGLRenderer::__initShader openfl/display/OpenGLRenderer.hx line 538
Called from openfl.display.Shader::__init openfl/display/Shader.hx line 454
Called from openfl.display.Shader::__initGL openfl/display/Shader.hx line 505
Called from openfl.display.Shader::__createGLProgram openfl/display/Shader.hx line 341
Called from openfl.display.Shader::__createGLShader openfl/display/Shader.hx line 331
Called from lime.utils.Log::error lime/utils/Log.hx line 34
Error : ValueException
```

**Comment by puyoxyz** [comment]
What are you running to make ARM builds? I don't see anything about ARM builds on the Lime docs but I might just be blind

**Comment by NoozAbooz** [comment]
> What are you running to make ARM builds? I don't see anything about ARM builds on the Lime docs but I might just be blind

Lime has a RPi build target.

**Comment by RSDNTWK** [comment]
> > What are you running to make ARM builds? I don't see anything about ARM builds on the Lime docs but I might just be blind
> 
> Lime has a RPi build target.

The rpi target only works with older pi's using the VC4 chip and not the Pi4 since it uses mesa for the VC6 chip it uses. We did test FNF on a Pi 3B+ however performance was terrible and suffered buggy graphics while running at less than 1fps due to the lack of support.

Also the rpi build strings were introduced in the hxcpp compiler library.

**Comment by NoozAbooz** [comment]
Ahh ok. I guess I'll have to use the HTML 5 version of the game, but it's quite laggy on the pi4 too since Chromium.

**Comment by RSDNTWK** [comment]
We did open an issue about this for the hxcpp compiler. https://github.com/HaxeFoundation/hxcpp/issues/959

**Comment by RSDNTWK** [comment]
We made 2 separate issues for the lack of pi4 support.
