### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by GhostFire90** [KadeArchive/Kade-Engine#783]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows x86_64
## What version of the game are you using? Look in the bottom left corner of the main menu.
KE 1.5.1
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
1. Play almost any of the weeks (Dad battle, pico, spooky kids are the ones i remember but i believe milf does as well)
2. around the 2nd or third song the game will crash with(this is assuming dad battle) "ERROR: There is no TEXT asset with an ID of "assets/data/dad battle/dad battle-hard.json""
3. EXTRA: Freeplay works fine
## Please describe your issue. Provide extensive detail and images if possible.
Almost any week has a missing song and it crashes the engine seemingly, i've fresh installed multiple times
![Capture](https://user-images.githubusercontent.com/31078396/121099577-f42fae80-c7ac-11eb-927d-32d1a0e68860.PNG)

**Comment by GhostFire90** [comment]
NOTE: i am just installing the release, no modified code

**Comment by Lucky-56** [comment]
duplicate: #778
this is fixed in the master branch
