### ISSUE TITLE
How does  it work?

### ISSUE THREAD

**Issue by TheALt-creator** [KadeArchive/Kade-Engine#788]
What do i  do?

**Comment by Lucky-56** [comment]
you mean how to compile ?

**Comment by Lucky-56** [comment]
go to their [website](https://kadedev.github.io/Kade-Engine/) and look for yourself

**Comment by puyoxyz** [comment]
Read the [README](https://KadeDev.github.io/Kade-Engine/)!

- You can compile it yourself with the instructions at [docs/building](https://KadeDev.github.io/Kade-Engine/building)
- Or you can download a build with the links in the README
- If you want to make your own mod, there are guides at [docs/guides/](https://KadeDev.github.io/Kade-Engine/guides/)
