### ISSUE TITLE
Bug Report: You renamed Dadbattle to Dad-battle breaking compatibility with all other mods

### ISSUE THREAD

**Issue by ScarabWasTaken** [KadeArchive/Kade-Engine#792]
Kade: 1.5.1.7
Im hooking File Daddy onto a blank Kade engine updated to latest. In the latest update you renamed everything relating to dadbattle to dad-battle. This means that any replacement mods need every dadbattle file to be manually renamed to dad-battle to function. 
I don't even understand why you made this change. It's still called DADBATTLE in the Week 7 update.
Please revert.

**Comment by isakube** [comment]
we could always ask ninjamuffin what it was supposed to be, but that involves asking ninjamuffin something. just rename the files and deal w it for now i guess

**Comment by ScarabWasTaken** [comment]
Whats even the point.
Cost:
-Break compatibility within the same main game version with other mods
-Force all modders that want to remix/replace the song to publish 2 downloads of the song OR:
-Force all players to rename 2 folders, 3 files, and edit 1 file.

Benefit:
+A space in the word on the bottom left of the screen.

**Comment by ACardboardBox1** [comment]
this is in the works i think #789

**Comment by isakube** [comment]
> -Force all players to rename 2 folders, 3 files, and edit 1 file.

Yeah. TWO FOLDERS, THREE FILES, AND EDITING ONE FILE. THAT'S LIKE SIX THINGS

AND I THOUGHT **I** WAS LAZY

**Comment by ACardboardBox1** [comment]
atleast it isnt as long as having to rename all the bside tracks to put them in kade engine before they came out with the new file system

**Comment by puyoxyz** [comment]
#789
