### ISSUE TITLE
Tutorial 

### ISSUE THREAD

**Issue by TheALt-creator** [KadeArchive/Kade-Engine#794]
I need a tutorial on what to do. Help me since I do not know what to do, Dont delete since I need help what to do.

**Comment by leafiamusic** [comment]
BrightFrye has really good tutorials on YouTube for modding Friday Night Funkin: https://www.youtube.com/playlist?list=PLAPMw90C3Tr58Z7ayeQvdod5Mxb7D_ciN

**Comment by puyoxyz** [comment]
https://kadedev.github.io/Kade-Engine/building

https://kadedev.github.io/Kade-Engine/guides/
