### ISSUE TITLE
Bug Report: Philly Nice crashes the game

### ISSUE THREAD

**Issue by PumpKingIsCool** [KadeArchive/Kade-Engine#795]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows 64x

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.5.1

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Just playing Philly Nice on the Story Mode, on Free Play it doesn't crash

## Please describe your issue. Provide extensive detail and images if possible.
![Screenshot_2](https://user-images.githubusercontent.com/85590515/121267081-020b2f80-c892-11eb-9c04-4d95a1479b2f.png)
As you can see in the image, it just crashes, i'm guessing it's because in StoryMenuState.hx, which may have "Philly Nice" instead of just "Philly"

**Comment by Lucky-56** [comment]
fixed in master

**Comment by isakube** [comment]
DUPLICATE
