### ISSUE TITLE
MacOS build

### ISSUE THREAD

**Issue by ALX-00** [KadeArchive/Kade-Engine#798]
I have successfully compiled the game for MacOS . I tested it in High Sierra, Mojave, Catalina and Big Sur and it works flawlessly.
The game is stable at 128 fps and DiscordRPC also works.
It would be cool if Kade put the build in his website, as of now there are only Windows and Linux download links

**Comment by puyoxyz** [comment]
We know they work, and there are automated CI builds. 

![image](https://user-images.githubusercontent.com/15311104/121339912-44c71900-c91f-11eb-9408-8c3cdf60eea6.png)
![image](https://user-images.githubusercontent.com/15311104/121339943-4d1f5400-c91f-11eb-842c-fb56be18d398.png)
