### ISSUE TITLE
Bug Report: Info-bar in options doesn't update unless pressing up/down

### ISSUE THREAD

**Issue by Lucky-56** [KadeArchive/Kade-Engine#799]
## What version of the game are you using? Look in the bottom left corner of the main menu.
1.5.2 (at the time of creating the issue: 1.5.1 (master) + my fork (#789))
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
go into options, adjust your offset for example, or go into a category and see the description not changing
## Please describe your issue. Provide extensive detail and images if possible.
Info-bar at the bottom of the screen in options doesn't update unless pressing up/down.
![optionBug](https://user-images.githubusercontent.com/55949451/121314865-1427b500-c908-11eb-8c39-cbcf259938e0.png)

**Comment by puyoxyz** [comment]
#891
