### ISSUE TITLE
Bug Report: when i use a new use a new chart insted of the normal one the game makes me go on the basic stage it doesn't depend on witch week

### ISSUE THREAD

**Issue by Editix08** [KadeArchive/Kade-Engine#800]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by Lucky-56** [comment]
Stages don't load as they are no longer hard coded to the weeks, but instead being loaded by the chart #334

**Comment by Lucky-56** [comment]
just go in the chart editor and change the stage property
![image](https://user-images.githubusercontent.com/55949451/121360086-6252ad80-c934-11eb-87b8-3196fa3f2910.png)
if you don't know how to use the chart editor go [here](https://kadedev.github.io/Kade-Engine/guides/charting)

**Comment by puyoxyz** [comment]
answered by @Lucky-56
