### ISSUE TITLE
Not really a Issue: How do you port kade engine to web? I really want to know.

### ISSUE THREAD

**Issue by gordonite** [KadeArchive/Kade-Engine#801]
Im not trying to make a mod out of it, but I would love to know how to port kade to web. Can anyone give me the steps or tell me how to?

**Comment by gordonite** [comment]
oh yeah and btw, 7 crashes the game most of the time in web...

**Comment by puyoxyz** [comment]
https://KadeDev.github.io/Kade-Engine/building; build to target `html5`

**Comment by gordonite** [comment]
oh ok
