### ISSUE TITLE
DON'T REPORT MISSING TEXT FILES

### ISSUE THREAD

**Issue by isakube** [KadeArchive/Kade-Engine#806]
If you get an error from lime.utils.Assets reporting a missing level json (i.e. assets/data/philly nice/philly nice-hard.json), DO NOT REPORT IT. WE KNOW ABOUT IT AND IT WILL BE FIXED IN THE NEXT RELEASE.

In the meantime, compile the "master" branch instead of the "stable" branch.
##### Thank you.

**Comment by Lucky-56** [comment]
well it is fixed in master 🤣

**Comment by isakube** [comment]
> well it is fixed in master 🤣

there i fixed the message lol

**Comment by Lucky-56** [comment]
good boi

**Comment by ACardboardBox1** [comment]
yeah i've been had enough of these issues at this point :/

**Comment by puyoxyz** [comment]
closing but itll be pinned just closed so it doesnt appear as open

**Comment by isakube** [comment]
cool
