### ISSUE TITLE
Where is the .7z?

### ISSUE THREAD

**Issue by TabTray** [KadeArchive/Kade-Engine#816]
just where is it? (1.5.2)

**Comment by isakube** [comment]
not a 7z anymore
![Screen Shot 2021-06-10 at 4 04 15 PM](https://user-images.githubusercontent.com/68293280/121607871-b11c4800-ca05-11eb-81a4-319299b24a1c.png)

**Comment by TabTray** [comment]
> not a 7z anymore

there used to be a zip and a 7z, the 7z i would use because it already had the stuff there set up

**Comment by ACardboardBox1** [comment]
https://drive.google.com/file/d/1M_fGBitYCf8slOxLw5Kcps4HhROQyV-j/view?usp=sharing dunno if this is what you wanted, but here

**Comment by puyoxyz** [comment]
there are 2 zips

kadeengine-windows.zip -> what you think of as the "7z". this is a build of the game ("already had the stuff there set up")
source code zip -> what you think of as the "zip". this is the source code, (the one u would have to "set up"/build)
