### ISSUE TITLE
Bug Report: Downloading 1.5.2's Source Code still gives the "You're Using An Outdated Version" screen for 1.5.1

### ISSUE THREAD

**Issue by yourlocalfox** [KadeArchive/Kade-Engine#819]
I have installed Kade Engine 1.5.2's Source Code both through Command Prompt and manually through the website, and a basic compile with no changes still results in the screen explaing that the game is outdated and running on 1.5.1.

**Comment by fizzybombzz** [comment]
i tried downloading the normal kade engine and it's doing the exact same thing, maybe kadedev forgot to change the version number ingame

**Comment by Lucky-56** [comment]
> 
> 
> i tried downloading the normal kade engine and it's doing the exact same thing, maybe kadedev forgot to change the version number ingame

yes I thought so too seeing nobody commiting the version change

**Comment by Lucky-56** [comment]
while you are at it you can change that too in `MainMenuState.hx`
change the line 42 from
```haxe
	public static var kadeEngineVer:String = "1.5.1" + nightly;
```
to

```haxe
	public static var kadeEngineVer:String = "1.5.2" + nightly;
```

**Comment by puyoxyz** [comment]
#822
