### ISSUE TITLE
Allow different weeks to default to their own stages

### ISSUE THREAD

**Issue by fizzybombzz** [KadeArchive/Kade-Engine#820]
If there is no stage value in the .json, allow it to default to the stage typically used for the week. This should fix mods like B-Sides using the Week 1 stage for every week. (Same goes for GF and note skins.)

**Comment by Lucky-56** [comment]
well this is a good enhancement that I'll try to add,
but I actually got around to fixing and enhancing the B-Side mod myself seen [here](https://github.com/Lucky-56/FNF-KE-B-Side-remixes)

**Comment by puyoxyz** [comment]
Resolved by #840
