### ISSUE TITLE
Bug Report: Version outdated screen still appears

### ISSUE THREAD

**Issue by Scynette** [KadeArchive/Kade-Engine#821]
Upon downloading and entering the game, you are still greeted with the outdated version warning, and all screens still say 1.5.1, despite the fact that it is, in fact, 1.5.2. All updates apply as far as I can tell, the songs work, and all of the assets are fresh. Very strange bug, perhaps Kade forgot to update some numbers? You're getting really close to creating the perfect version...

**Comment by Lucky-56** [comment]
DUPLICATE #819,
do what the damn thing says and look for duplicates

**Comment by puyoxyz** [comment]
#822
