### ISSUE TITLE
Enhancement: New Logo?

### ISSUE THREAD

**Issue by Lucky-56** [KadeArchive/Kade-Engine#823]
## What is your suggestion, and why should it be implemented?
**what:** a new Kade Engine logo me and my friend made (my friend did all the letters individually and I pieced them together)
**why:** new look, old one is meh at most

alone with glow
![dunno_v4_butNoVersion](https://user-images.githubusercontent.com/55949451/121623141-7b13ae00-ca6f-11eb-834e-d3d4d4604661.png)

with FNF logo but without glow
![KadeEngineLogoNew](https://user-images.githubusercontent.com/55949451/121623184-8c5cba80-ca6f-11eb-94cd-1a49bbb1e1ae.png)

**Comment by Lucky-56** [comment]
just a note:
I did not take the color from the FNF logo.
I actually used this color and then on another layer the same color again but blurred and with the 'glow' Blend.
![color_AA4688](https://user-images.githubusercontent.com/55949451/121624682-3dfceb00-ca72-11eb-96d4-334aaaf44d79.png)

**Comment by isakube** [comment]
dude that's kinda gaming

**Comment by puyoxyz** [comment]
drip

@KadeDev

**Comment by isakube** [comment]
> drip

/!\ Kade Engine drip required beyond this point /!\

Without Kade Engine drip, you will be:
* unaffected
* still cool :+1:

**Comment by ACardboardBox1** [comment]
![logoBumpin](https://user-images.githubusercontent.com/81185552/121718710-98b53780-cab0-11eb-960a-3fe1b7803089.png)

**Comment by ACardboardBox1** [comment]
the spritesheet if it ever gets accepted (https://drive.google.com/file/d/13rElOJhCEiYOMPCD3roFHELVPaLz79fQ/view?usp=sharing the xml)
edit: got rid of the old logo popping out 
edit 2: downscaling

**Comment by Lucky-56** [comment]
thanks I guess :)

contributing as a family, as it should be

**Comment by ACardboardBox1** [comment]
The new logo spritesheet i put above works, just needs some offset changing 👍

**Comment by Lucky-56** [comment]
Kade could add this to the 'watermark' section in options to enable/disable it
or I could, if he'd accept

**Comment by aflacc** [comment]
honestly I like it

**Comment by aflacc** [comment]
> > drip
> 
> /!\ Kade Engine drip required beyond this point /!\
> 
> Without Kade Engine drip, you will be:
> 
> * unaffected
> * still cool 👍

i have aflac drip

**Comment by isakube** [comment]
> > > drip
> > 
> > 
> > /!\ Kade Engine drip required beyond this point /!\
> > Without Kade Engine drip, you will be:
> > 
> > * unaffected
> > * still cool 👍
> 
> i have aflac drip

We also accept aflac drip (alfac 😳 )

**Comment by Lucky-56** [comment]
we really out here friday night drippin'

**Comment by Kade-github** [comment]
this is sick, since this isn't a pr. consider it accepted??? idk lol
