### ISSUE TITLE
Bug Report: more game crashes with spaces in songs

### ISSUE THREAD

**Issue by Lucky-56** [KadeArchive/Kade-Engine#825]
## What version of the game are you using? Look in the bottom left corner of the main menu.
1.5.2 + #824 
## Please describe your issue. Provide extensive detail and images if possible.
simply I did not fix everything with spaces, when loading a replay with spaces... you guessed it it crashes
\
\
\
\
\
\
_sigh_
\
\
I'll get to fixing it now

**Comment by Lucky-56** [comment]
I just noticed I shouldn't close these issues manually.
(copied)

**Comment by puyoxyz** [comment]
lets keep this closed theres a PR anyways
