### ISSUE TITLE
Bug Report: Replay Details doesn't show version

### ISSUE THREAD

**Issue by Lucky-56** [KadeArchive/Kade-Engine#830]
## What version of the game are you using? Look in the bottom left corner of the main menu.
1.5.2 + #824 
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
go into replay viewer with replays loaded
## Please describe your issue. Provide extensive detail and images if possible.
it does not show the replay version
![image](https://user-images.githubusercontent.com/55949451/121718836-05e1c080-cae3-11eb-87b1-fda6b845ca0b.png)

**Comment by Lucky-56** [comment]
the dash is, what confused me

**Comment by Lucky-56** [comment]
I just noticed I shouldn't close these issues manually.
(copied)

**Comment by puyoxyz** [comment]
Resolved by #840
