### ISSUE TITLE
how simple is the base inputs

### ISSUE THREAD

**Issue by aflacc** [KadeArchive/Kade-Engine#831]
like I mean like how hard would it be to remake the inputs this uses. and just the inputs and nothing else

**Comment by isakube** [comment]
Duplicate PlayerSettings and Controls into a new flixel project. Also duplicate KeyBinds. I think that's it for keybinds lol

**Comment by ghost** [comment]
> like I mean like how hard would it be to remake the inputs this uses. and just the inputs and nothing else

so thats how you did it

**Comment by aflacc** [comment]
I figured it out on my own in like 5 minutes

And it took me 5 months to figure it out.
