### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by FiFi301** [KadeArchive/Kade-Engine#832]
Hello
so, when i tried to build game, its gave me this information:
PS C:\Users\FiFi\Desktop\modding\Kade-Engine-stable> lime test windows
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/PlayState.hx:299: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:\Users\FiFi\Desktop\modding\Kade-Engine-stable\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

Can somebody tell me how to fix it? I tried to search this for like 2 days and nothing

Thanks

**Comment by oketariq** [comment]
Are you 100% sure you have all of the Visual Studio dependencies installed?

**Comment by Lucky-56** [comment]
it looks like you're missing `Visual Studio 2017 VsDevCmd`
what version of Visual Studio do you have installed

**Comment by FiFi301** [comment]
> it looks like you're missing `Visual Studio 2017 VsDevCmd`
> what version of Visual Studio do you have installed

2019

**Comment by FiFi301** [comment]
> Are you 100% sure you have all of the Visual Studio dependencies installed?

I searched and i can not find "MSVC v142 - VS 2019 C++ x64/x86 build tools" in my Visual Studio

**Comment by Lucky-56** [comment]
have you read this?
![image](https://user-images.githubusercontent.com/55949451/121743567-d1c9c800-cb01-11eb-8c48-038614ad6f5e.png)

**Comment by FiFi301** [comment]
Yes, and when i go to individual components and tyle this nothing was found

**Comment by puyoxyz** [comment]
> > Are you 100% sure you have all of the Visual Studio dependencies installed?
> 
> I searched and i can not find "MSVC v142 - VS 2019 C++ x64/x86 build tools" in my Visual Studio

doesnt have to be necesarily v142 i think? try searching just MSVC in the installer

**Comment by isakube** [comment]
don't we all

**Comment by FantasyDev15** [comment]
i also have the same problem, did someone fix it?
=(

**Comment by Di4mnd** [comment]
I'm having almost the same exact issue, and even after I installed Visual Studio (with all the required dependencies), it still gave me a bunch of errors. :(

**Comment by Lucky-56** [comment]
try to reinstall (or add I still don't know how VS works) with these
![image](https://user-images.githubusercontent.com/55949451/121802025-b9a99400-cc3a-11eb-9544-b98b7f25e1e4.png)

it's the required ones of the Mic'd Up engine wich I was modding before getting onto the Kade Engine and I had no issues what so ever do try that (don't ask me why I switched from Mic'd Up to Kade Engine, it just seems more not 'overhaul' like)

**Comment by Lucky-56** [comment]
comment from **VMGuy23** on [#835](https://github.com/KadeDev/Kade-Engine/issues/835#issuecomment-860023768):
> 
> 
> [get this and will work](https://download.visualstudio.microsoft.com/download/pr/67f7bfaa-2635-43d9-ba82-26564f458881/bb057808eeff7d02561cab636b32397e298c3e770ed278602c46d119fa2e4ee8/vs_BuildTools.exe)

**Comment by Di4mnd** [comment]
I can't find anything related to "MSVC" when I search it up on the Visual Studio 2017 installer.

**Comment by ghost** [comment]
@Di4mnd Its the 2019 one plus that you need

**Comment by FiFi301** [comment]
> try to reinstall (or add I still don't know how VS works) with these
> ![image](https://user-images.githubusercontent.com/55949451/121802025-b9a99400-cc3a-11eb-9544-b98b7f25e1e4.png)
> 
> it's the required ones of the Mic'd Up engine wich I was modding before getting onto the Kade Engine and I had no issues what so ever do try that (don't ask me why I switched from Mic'd Up to Kade Engine, it just seems more not 'overhaul' like)

thanks i found this!

**Comment by kvuimer** [comment]
I don't know how but I fix the problem. I just reinstall kade engine and then in the code window it asked me: You need to install visual studio components? And I say yes and then everything start to work. (Sorry for my bad english)
