### ISSUE TITLE
Keys aren't working

### ISSUE THREAD

**Issue by stormzyyyy** [KadeArchive/Kade-Engine#834]
This started happening with a new release of KE a couple while back.  I would press keys at the correct time but it would count it as missed. I've looked through settings and have tried almost everything but nothing is working. Did I mess something up in settings or I am just being dumb? The colors of the keys change but as I've mentioned earlier, it counts it as missed.

**Comment by Lucky-56** [comment]
mybe your offset is very high ?
try looking in options at the bottom of your screen

**Comment by stormzyyyy** [comment]
> mybe your offset is very high ?
> try looking in options at the bottom of your screen

my offset is zero but keys still are being counted as missed

**Comment by Lucky-56** [comment]
hmm are you using the base Engine with no mods installed whatso ever

**Comment by stormzyyyy** [comment]
KE Version is 1.4.2 with FNF version 0.2.7.1 and looking at the mods folder, only introMod shows up (along with a readme, modlist, and controls.hx).

**Comment by stormzyyyy** [comment]
If you meant mods by a modded new week, yes.

**Comment by Lucky-56** [comment]
maybe in your songs. is there a .offset file ?
in `data/<SONGNAME>/`

**Comment by stormzyyyy** [comment]
> maybe in your songs. is there a .offset file ?
> 
> in `data/<SONGNAME>/`

There is. It's a file called 0.offset and there is no data inside it.

**Comment by Lucky-56** [comment]
yeah it's just the name of the file that counts.
does the offset happen if you rename the chart and use it in another song?

**Comment by stormzyyyy** [comment]
> yeah it's just the name of the file that counts.
> 
> does the offset happen if you rename the chart and use it in another song?

Can't exactly test that as no song in the mod is playable.

**Comment by Lucky-56** [comment]
just add another song in freeplay

**Comment by stormzyyyy** [comment]
> just add another song in freeplay

Nope. Doesn't work. Might as well just stick with old KE versions that still work.

**Comment by Lucky-56** [comment]
sure, let's wait for other people that can help you better *hehe*

**Comment by puyoxyz** [comment]
@stormzyyyy are your safe frames set to 10? you might have accidentally changed it to like 0

**Comment by stormzyyyy** [comment]
> @stormzyyyy are your safe frames set to 10? you might have accidentally changed it to like 0

They were set to 1! Changing them to 10 lets me play again. Thanks!

**Comment by puyoxyz** [comment]
epic, closing
