### ISSUE TITLE
Bug Report: Can't build the game, Missing HXCPP_VARS

### ISSUE THREAD

**Issue by FantasyDev15** [KadeArchive/Kade-Engine#835]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows x64
## What version of the game are you using? Look in the bottom left corner of the main menu.
I can't look at it because i can't build it, but it's the master branch.
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
I just wrote "lime test windows" and i can't build it
## Please describe your issue. Provide extensive detail and images if possible.
Errror log: [https://pastebin.com/5Q6tWwAB](https://pastebin.com/5Q6tWwAB)
I have installed everything (including the 4gb of crap and all the libraries from haxelib) and still can't build it. I don't know if im stupid or what, but yeah, i've been trying for days.

**Comment by FantasyDev15** [comment]
didn't know there was another one with the same problem. does that count as a duplicate?

**Comment by Lucky-56** [comment]
yes this would defenitely be a duplucate of #832 
but it wouldn't have been very clear of the title of the issue

**Comment by ghost** [comment]
[get this and will work](https://download.visualstudio.microsoft.com/download/pr/67f7bfaa-2635-43d9-ba82-26564f458881/bb057808eeff7d02561cab636b32397e298c3e770ed278602c46d119fa2e4ee8/vs_BuildTools.exe)

**Comment by Lucky-56** [comment]
@VMGuy23 you should've commented on the issue _**not**_ being a duplicate

**Comment by ghost** [comment]
Will do

**Comment by FantasyDev15** [comment]
> [get this and will work](https://download.visualstudio.microsoft.com/download/pr/67f7bfaa-2635-43d9-ba82-26564f458881/bb057808eeff7d02561cab636b32397e298c3e770ed278602c46d119fa2e4ee8/vs_BuildTools.exe)

thank u so much! this worked very well :D. closing the issue now becuase it's fixed :)
