### ISSUE TITLE
Enhancement: StrumLine Y like Week 7 Update with downscroll

### ISSUE THREAD

**Issue by gamerbross** [KadeArchive/Kade-Engine#843]
In Kade Engine, strumLine.y with downscroll is FlxG.height - 165
![image](https://user-images.githubusercontent.com/55158797/121773735-11ce9080-cb7e-11eb-8997-ed7d813a8c36.png)

And in Week 7 Update is FlxG.height - 150
![image](https://user-images.githubusercontent.com/55158797/121773749-214dd980-cb7e-11eb-9e9f-a144d6fd85f5.png)

**Comment by isakube** [comment]
wait the week 7 source is out?

also this is like 15 pixels who cares lol

**Comment by Kiffolisk** [comment]
probably only a source code remake idk. it looks like its beautified unobfuscated funkin.js

**Comment by puyoxyz** [comment]
It's 15 pixels

**Comment by NukeThief** [comment]
I would prefer for this to be added

**Comment by puyoxyz** [comment]
*15 pixels*

**Comment by ACardboardBox1** [comment]
> 
> 
> I would prefer for this to be added

it's 15 pixels 😭
