### ISSUE TITLE
Can't remove notes in charting menu of newest update

### ISSUE THREAD

**Issue by Cyanned** [KadeArchive/Kade-Engine#845]
I don't know if this is my problem or not but when I go to the charting menu, I can place notes but I can't remove them.
I can remove the notes on the first line of the chart, but nothing else.
I already tried getting the ChartingState from the latest versions, but it keeps the same error.

**Comment by isakube** [comment]
i don't know how to fix this. this literally never happened to me frf

**Comment by puyoxyz** [comment]
are you scrolling down? maybe u can only remove stuff on the beat that ur on i think?

**Comment by ghost** [comment]
Yeah I can't remove any either

**Comment by Kade-github** [comment]
fixed
