### ISSUE TITLE
Bug Report: Fucked optimalization

### ISSUE THREAD

**Issue by NukeThief** [KadeArchive/Kade-Engine#846]
So after i downloaded Kade Engine 1.5.2 x64 the framerate was much worse than on Kade Engine 1.5.1 and i'm 100% sure that i have 120 FPS cap beacuse i checked

**Comment by NukeThief** [comment]
i forgot i didn't plug my laptop before gaming.

**Comment by isakube** [comment]
LMAOOOOO

best Issue on the repo no cap

**Comment by puyoxyz** [comment]
I love this

**Comment by NukeThief** [comment]
same XDD
