### ISSUE TITLE
Errors when compiling

### ISSUE THREAD

**Issue by Di4mnd** [KadeArchive/Kade-Engine#847]
I'm making a mod for a character called "Zalowit". But for some reason, whenever I try to compile the game, it gives me a BUNCH of errors. How do I fix this? Do I need to download earlier versions of some libraries? Or did I just type something wrong in the source code? Someone please help me.
![image](https://user-images.githubusercontent.com/85621240/121785167-cc947800-cbea-11eb-9340-cd1139d15951.png)

**Comment by Lucky-56** [comment]
it says `Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths`
I just googled that and it said: `that error usually appears when you don't have MSVC installed`

so reinstall Visual Studio with these options enabled (or maybe you can add them now I don't know Visual Studio)

![image](https://user-images.githubusercontent.com/55949451/121785335-82df6980-cbb9-11eb-96eb-eda7568206ce.png)
*from https://kadedev.github.io/Kade-Engine/building*

**Comment by Di4mnd** [comment]
> it says `Error: 64bit is not automatically supported for this version of VC. Set HXCPP_MSVC_CUSTOM and manually configure the executable, library and include paths`
> I just googled that and it said: `that error usually appears when you don't have MSVC installed`
> 
> so reinstall Visual Studio with these options enabled (or maybe you can add them now I don't know Visual Studio)
> 
> ![image](https://user-images.githubusercontent.com/55949451/121785335-82df6980-cbb9-11eb-96eb-eda7568206ce.png)
> _from https://kadedev.github.io/Kade-Engine/building_

Hey, so I installed Visual Studio with all the steps, but all it did was change the errors. :(
![image](https://user-images.githubusercontent.com/85621240/121800245-5ed86280-cc63-11eb-8de9-e6c951168132.png)

It also didn't have any changes on the other errors :(

**Comment by Di4mnd** [comment]
It also didn't have any changes on the other errors :(

**Comment by Lucky-56** [comment]
well it changed alright... now it's a duplicate of #832

**Comment by ACardboardBox1** [comment]
https://github.com/KadeDev/Kade-Engine/issues/835#issuecomment-860023768

**Comment by ghost** [comment]
[To be more helpful heres a direct link](https://download.visualstudio.microsoft.com/download/pr/67f7bfaa-2635-43d9-ba82-26564f458881/bb057808eeff7d02561cab636b32397e298c3e770ed278602c46d119fa2e4ee8/vs_BuildTools.exe)

**Comment by puyoxyz** [comment]
duplicate
