### ISSUE TITLE
A lil' building problem

### ISSUE THREAD

**Issue by JustALilGuy** [KadeArchive/Kade-Engine#853]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows x64
## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1 KE 1.5.2
## Please describe your issue. Provide extensive detail and images if possible.
Every time I try to build, This pops up, and basically I can't build because of it?
![image](https://user-images.githubusercontent.com/85480404/121805326-09a54c80-cc75-11eb-91c0-1e880ec19d60.png)

**Comment by isakube** [comment]
those are all deprecations. you're fine.

**Comment by ACardboardBox1** [comment]
> 
> 
> those are all deprecations. you're fine.

I'm pretty sure you have to wait a little bit after those deprecations for it to start getting to work as well.

**Comment by JustALilGuy** [comment]
> those are all deprecations. you're fine.

do i still have to do anything?
because it still refuses to build

**Comment by ACardboardBox1** [comment]
> 
> 
> > those are all deprecations. you're fine.
> 
> do i still have to do anything?
> because it still refuses to build

no

**Comment by JustALilGuy** [comment]
> > > those are all deprecations. you're fine.
> > 
> > 
> > do i still have to do anything?
> > because it still refuses to build
> 
> no

so basically I just have to wait?

**Comment by ACardboardBox1** [comment]
> 
> 
> > > > those are all deprecations. you're fine.
> > > 
> > > 
> > > do i still have to do anything?
> > > because it still refuses to build
> > 
> > 
> > no
> 
> so basically I just have to wait?

yeah im pretty sure

**Comment by JustALilGuy** [comment]
> > > > > those are all deprecations. you're fine.
> > > > 
> > > > 
> > > > do i still have to do anything?
> > > > because it still refuses to build
> > > 
> > > 
> > > no
> > 
> > 
> > so basically I just have to wait?
> 
> yeah im pretty sure

aight thx man

**Comment by ghost** [comment]
Go to [here](localhost:3000) (localhost:3000) 10 seconds after those warnings and see what happens
