### ISSUE TITLE
Enhancement: Add Change Difficulty Feature

### ISSUE THREAD

**Issue by newintownreal** [KadeArchive/Kade-Engine#856]
Yes just,
Add Change Difficulty Feature

**Comment by ACardboardBox1** [comment]
I think this is gonna be added lol

**Comment by newintownreal** [comment]
> I think this is gonna be added lol

yeah, i think

**Comment by isakube** [comment]
week 7

it's already easy to implement but eh

**Comment by puyoxyz** [comment]
week 7 features will be added when week 7 source is out
