### ISSUE TITLE
Enhancement: Note splash like in Funkin' 0.2.8

### ISSUE THREAD

**Issue by NukeThief** [KadeArchive/Kade-Engine#858]
## What is your suggestion, and why should it be implemented?
Adding note splash when the note is hit perfectly like in Funkin' 0.2.8 would be very nice and cool.
And getting the assets for the splash won't be hard beacuse in certain browsers you can get the yoink the note asset from Funkin' 0.2.8.

**Comment by ACardboardBox1** [comment]
That's already added in recent Kade Engine versions if I remember clearly

**Comment by NukeThief** [comment]
No it isn't. I have the newest version which is 1.5.2 and it isn't here.

**Comment by isakube** [comment]
is the source out?

**Comment by AtonyGit** [comment]
> That's already added in recent Kade Engine versions if I remember clearly

It was never added. What you are thinking about is the notes flashing on the bot side, not the splash from week 7.

**Comment by ACardboardBox1** [comment]
> 
> 
> > That's already added in recent Kade Engine versions if I remember clearly
> 
> It was never added. What you are thinking about is the notes flashing on the bot side, not the splash from week 7.

well not exactly i must have been thinking about the wrong thing lol

**Comment by ACardboardBox1** [comment]
> 
> 
> No it isn't. I have the newest version which is 1.5.2 and it isn't here.

ok

**Comment by Lucky-56** [comment]
FNF v0.2.8.0 source is not public yet.

won't add

**Comment by Kade-github** [comment]
embargo, cannot add this.

**Comment by NukeThief** [comment]
Waiting for A.G.O.T.I SC so this could be added
