### ISSUE TITLE
Enhancement: Change Downscroll note pos to the same like in Funkin' 0.2.8

### ISSUE THREAD

**Issue by NukeThief** [KadeArchive/Kade-Engine#859]
## What is your suggestion, and why should it be implemented?
Changing the Downscroll note pos to the same like in Funkin' 0.2.8 is very easy just change one value from probably 136/4 to 130, and it will look nicer.

**Comment by isakube** [comment]
its like 15 pixels dude

**Comment by isakube** [comment]
also duplicate

**Comment by Lucky-56** [comment]
duplicate #843 

won't fix

**Comment by NukeThief** [comment]
I couldn't find a duplicate that's why i posted it
