### ISSUE TITLE
Are you pulling our leg about the delete note bug in the chart editor??

### ISSUE THREAD

**Issue by xiiixvv** [KadeArchive/Kade-Engine#86]
So ive been trying to edit a chart and ive had many problems cause I cannot delete any of the notes I place. And ive tried every kind of bind I can think of, I spammed every button on my mouse and ive tried multiple keys on my keyboard. And ive seen multiple other issues on this repo mentioning the bug, and almost all of them were replied with "works for me so idk" and then it was closed.

Also, I am using version 1.3.1 on Windows

**Comment by Kade-github** [comment]
Again, already fixed. Build from the github.
