### ISSUE TITLE
Bug Report: I can't mod it without the bg always being set as the stage from the tutorial and week 1

### ISSUE THREAD

**Issue by Zeldagamerboy** [KadeArchive/Kade-Engine#862]
I moded b side remixes into kade engine v1.4.2 and wanted to update it to v1.5.2 by putting the assets folder into v1.5.2. It worked but the characters didn't look like they would in b side and the background would always be the tutorial background. I quickly learned that there was a new folder specifically for characters. I still don't know how to get the backgrounds to change to what they should look like. I have tried putting only the songs and data folders from my b side  assets in Kade engine v1.4.2  folder into v1.5.2 but that doesn't work. Please fix this or tell me how to fix it myself because it's really pissing me off.

**Comment by isakube** [comment]
Step 1. Go into the chart editor by pressing `7` on your keyboard.

Step 2. Click on the "Assets" tab.

Step 3. Click on the "Stage" dropdown on that tab and change the selected option to the correct stage.

Step 4. Realize this is entirely the modder's fault and we didn't do anything.

**Comment by Lucky-56** [comment]
uh hey I have already done that
if you're interested https://gamebanana.com/mods/293995

**Comment by Lucky-56** [comment]
but please close this, as this isn't really our problem

**Comment by ACardboardBox1** [comment]
> 
> 
> but please close this, as this isn't really our problem

^ yes please

**Comment by Lucky-56** [comment]
oh wait this is kind of our problem... well it'll be fixed when #840 gets accepted

still close this tho
