### ISSUE TITLE
Bug Report: Offset Buggin

### ISSUE THREAD

**Issue by KlutchDj** [KadeArchive/Kade-Engine#865]
#### Please check for duplicates, similar issues or closed issues with the same problem, as well performing simple troubleshooting steps (such as deleting the export folder if it's an issue with compiling, reinstalling Kade Engine) before submitting an issue.

im using windows 64 , when changing the offset thru the options menu , it doesn't change the numbers visually , but instead , it changes when hovering to another option . For example : 

https://user-images.githubusercontent.com/81717689/122011374-a05f2f80-cd81-11eb-8ba1-8afe6935ab09.mp4

**Comment by Lucky-56** [comment]
duplicate #799

**Comment by puyoxyz** [comment]
#891
