### ISSUE TITLE
Bug Report: Arrows upside down

### ISSUE THREAD

**Issue by Lychee-Bear** [KadeArchive/Kade-Engine#87]
The images for the up and down arrow seem to be upside down, but only when downscroll is enabled

Im playing on the windows downloaded verion

Im using 1.3.1

![image](https://user-images.githubusercontent.com/81586319/112882885-ecb0a280-90a3-11eb-91c5-10157b1290b5.png)

**Comment by theDetourist** [comment]
Already fixed, just gotta wait for Week 7 to drop (or a quick hotfix update).

**Comment by Kade-github** [comment]
> Already fixed, just gotta wait for Week 7 to drop (or a quick hotfix update).

^
