### ISSUE TITLE
Bug Report: "cmd.exe - Application Error The application was unable to start correctly (0xc0000142). Click OK to close the application" 

### ISSUE THREAD

**Issue by EmeraldGamer124** [KadeArchive/Kade-Engine#871]
Every time I finish compiling the game, An error will always pop up saying "[cmd.exe - Application Error] The application was unable to start correctly (0xc0000142). Click OK to close the application" and sometimes, It would ruin the audio driver (fixed by restarting the computer) and the game would function weirdly, but other than all of that, everything seems to work fine. Is there anything to fix this?

**Comment by isakube** [comment]
go into the search filters on Issues and paste in that `0xc0000142`. If nothing shows up, then I don't really know what to do.

edit: Duplicate of #453, Unresolved

**Comment by puyoxyz** [comment]
duplicate #453
