### ISSUE TITLE
Changing senpai sprite causes Roses to immediately crash

### ISSUE THREAD

**Issue by yuh-mkv** [KadeArchive/Kade-Engine#873]
I changed senpai's sprite to make his left eye green like in PhantomArcade's concept art, and after putting it in to the game, Senpai and Thorns run fine, but Roses crashes instantly.

https://user-images.githubusercontent.com/85563892/122263430-6b97c900-cea4-11eb-9d29-714e025e10db.mp4

**Comment by yuh-mkv** [comment]
nvm, xml was broken and that made by game have a stroke, closing.

**Comment by puyoxyz** [comment]
next time make a discussion =)
