### ISSUE TITLE
Bug Report: Error upon loading week 3

### ISSUE THREAD

**Issue by R-asazy** [KadeArchive/Kade-Engine#874]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows (x86_64)
## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Loading week 3 on hard shows it.
## Please describe your issue. Provide extensive detail and images if possible.
Loading week 3 on hard mode shows a pop-up saying "FlxBar: max cannot be lower than or equal to min"

**Comment by isakube** [comment]
issue with the audio files. generally happens if the file extension is just renamed instead of converted. Which song does this happen on? is it philly nice? it's philly nice, isn't it?

**Comment by R-asazy** [comment]
no, it's pico. i think it was created when filedaddy was removing the annie mod

**Comment by puyoxyz** [comment]
filedaddy is dumb as hell, redownload and stop using file daddy, just learn how to Drag and drop files
