### ISSUE TITLE
Bug Report: Can't switch characters in the debug menu

### ISSUE THREAD

**Issue by PerforatedCat** [KadeArchive/Kade-Engine#88]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86_64`).

## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1, kade engine v1.3.1.

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
switching any character in any song.

## Please describe your issue. Provide extensive detail and images if possible.
when i try to switch character (doesn't matter with each character) in any song the game just crashes without displaying an error.

**Comment by Weege3** [comment]
been having the same problem

**Comment by libauror-a** [comment]
I think the bug is because of how characters work in this engine. You can't change to a character that isn't in the week files itself.

Note:
It didn't work.

**Comment by Kiffolisk** [comment]
dunno. for me it works fine.

**Comment by Fefe543** [comment]
Same problem! It's so annoying, i don't know how to fix it

**Comment by caserreal** [comment]
I also have this issue, except it's only my custom character. I have all the info in shared assets in a folder, and have coded it in, but everytime i try to test it, It crashes

**Comment by Kade-github** [comment]
p sure this was fixed

**Comment by chettxi** [comment]
same here doesn't help that i have no idea what im doin

**Comment by Kade-github** [comment]
build from the latest commit or use nightly

**Comment by Fefe543** [comment]
download the latest version it's working now
