### ISSUE TITLE
Enhancement: Kade Engine EasyCompile

### ISSUE THREAD

**Issue by te-agma-at** [KadeArchive/Kade-Engine#881]
## Kade Engine EasyCompile is an easier way to compile the latest source-code version of Friday Night Funkin' (either the OG engine or Kade Engine) without getting an error thrown something across the lines of:

"C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/ParseRules.hx:878: characters 28-46 : Warning : Std.is is deprecated. Use Std.isOfType instead.",

or;

"Error: Stdout.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\crtdefs.h(10): fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory".

How does it work? It's simple!
Install "KE EasyCompile.rar" either from GameBanana or a mirror download link
Choose the directory you wish to compile using EasyCompile (must be a Friday Night Funkin'/Kade Engine FNF haxe directory or else it won't work, other engines aren't supported)
Click the "Compile Source" button below to automatically compile the directory of the source directory you have into a haxe project (don't forget to include Project.xml)
Once it's done compiling, you are now ready to play YOUR build/mod of Friday Night Funkin' without the frustration of having to deal with errors thrown every single time!

**Comment by isakube** [comment]
lol nice ad

hey Kade check this out

**Comment by ACardboardBox1** [comment]
@KadeDev check this out

**Comment by puyoxyz** [comment]
I think they mean like they want us to make that @prokube

**Comment by isakube** [comment]
> I think they mean like they want us to make that

fair point
idk any way of making this other than perhaps an IDE extension. Even then seeing errors is important soooooo high doubt of this getting made.

Also @te-agma-at that second error is one that prevents the game from building lol

**Comment by theDetourist** [comment]
The only thing that can be simplified is making a `.bat` or something like that that opens the programs for you and installs the plugins and everything on its own the first time, eventually you'll really need to use a single command: `lime test [target]` and you're done. Regarding _"dealing with errors"_, do you want to make a mod or not?

If yes, then get used to the concept of trial and error, even literal errors.

**Comment by Kade-github** [comment]
bro just look at buidling on the website ez fix
