### ISSUE TITLE
Bug Report: Cannot remove notes.

### ISSUE THREAD

**Issue by Thebig44** [KadeArchive/Kade-Engine#89]
Running the most recent version of the mod 1.3.1.

I have seen the previous bug reports on the issue, and downloaded the new version accordingly. It still fails to remove the note when i click on it the second time. 
![halp1](https://user-images.githubusercontent.com/52110454/112911038-7dab6c00-90ec-11eb-8100-b66e4fdf55d2.png)

It's worth noting here that I tried to replace ChartingState.hx with the original engine's and the issue persisted, still. Maybe it's getting overwritten with something else?

**Comment by theDetourist** [comment]
As told in #86, if you really need it, build the game yourself from Github instead of using the latest released build. Seems to be fixed there.

**Comment by Thebig44** [comment]
> As told in #86, if you really need it, build the game yourself from Github instead of using the latest released build. Seems to be fixed there.

I guess my question now would be if it'll get fixed in a release version down the line?

**Comment by theDetourist** [comment]
Yeah, either when Week 7 drops or if Kade decides to release "nightly builds" of the latest Github code from now on.
