### ISSUE TITLE
Help Installing On Mac OS

### ISSUE THREAD

**Issue by SSaucyK** [KadeArchive/Kade-Engine#90]
Ive been attempting to install the mod into the actual game files and the files go in with little to no problem. It's just when I load up the game it doesn't seem to work. I also tried reinstalling the game to reset anything I might've done to the files and even still it doesnt work or my game crashes. Can someone help me figure out what im doing wrong?

**Comment by Kiffolisk** [comment]
Kade Engine isn't made for MacOS. Use Wine.

**Comment by whatthezip** [comment]
Wine is horrible for FNF on older devices, Heck, doesn't even open (I have tried multiple wine versions, engines, wrappers, and I even paid for crossover) at least I can run the original FNF on the title screen at 13 fps. I EVEN UPDATED MACOS TO MOJAVE. 
so I guess I gotta do this myself and compile this.

**Comment by Kade-github** [comment]
Try mono

**Comment by whatthezip** [comment]
i did

**Comment by whatthezip** [comment]
sorry if i sounded angry above. wasn't having a good day.

**Comment by Kade-github** [comment]
Compile on mac then, I don't have any other solution.
