### ISSUE TITLE
How do i open the App

### ISSUE THREAD

**Issue by zxarde** [KadeArchive/Kade-Engine#905]
### Discussed in https://github.com/KadeDev/Kade-Engine/discussions/904

<div type='discussions-op-text'>

<sup>Originally posted by **richxboy** June 18, 2021</sup>
I recently downloaded Kade Engine. I dont find the EXE. But it only shows me assets and something other. I searched in youtube. How do i Open fnf now?
![KadeDev-Kade-Engine-1 5 2-18-gd667e2e zip (Nicht lizenzierte Testversion) 2021-06-18 18_49_33 Uhr](https://user-images.githubusercontent.com/77019859/122593441-f7a51e80-d065-11eb-99cf-9be1cd781626.png)
</div>

**Comment by isakube** [comment]
compile the game :trollface: https://kadedev.github.io/Kade-Engine/building

**Comment by ACardboardBox1** [comment]
please close

**Comment by Lucky-56** [comment]
you downloaded the source code, not the pre-compiled exe
if you want to compile, prokube answered your question
if you only want to play, download the pre-compiled version [here](https://github.com/KadeDev/Kade-Engine/releases)

![image](https://user-images.githubusercontent.com/55949451/122610465-fb459f00-d07f-11eb-91b8-9fbbe5d5b695.png)
