### ISSUE TITLE
Bug Report: "miss" rating has no texture

### ISSUE THREAD

**Issue by Trayfellow** [KadeArchive/Kade-Engine#911]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

windows 64 bit, or basically anything

## What version of the game are you using? Look in the bottom left corner of the main menu.
kade engine 1.5.2

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
![whenthemisspngismissing](https://user-images.githubusercontent.com/48515908/122628138-9d946f80-d0de-11eb-8cab-15ea0e52034f.PNG)

## Please describe your issue. Provide extensive detail and images if possible.
so when i was compiling on kade engine and when i was playing i got this warning saying there was no miss.png texture, i checked the games code and it looks like when you guys added a rating that when you hit a note so early it says "miss"
but theres no texture for "miss.png" so it gives that warning, i think you guys forgot to add a texture for the miss rating lol

**Comment by puyoxyz** [comment]
this should probably point to shit.png not miss.png i think?

**Comment by Kade-github** [comment]
p sure this was fixed in the latest ke
