### ISSUE TITLE
Bug Report: Options Menu buggy

### ISSUE THREAD

**Issue by Lucky-56** [KadeArchive/Kade-Engine#913]
## What version of the game are you using? Look in the bottom left corner of the main menu.
1.5.2 + #894
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Go into options, select a category, scroll down and select an option.
## Please describe your issue. Provide extensive detail and images if possible.
When selecting an option it scrolls to a almost random option (but most of the time it's the top of the list).

![image](https://user-images.githubusercontent.com/55949451/122632404-e34b3b00-d0d2-11eb-9a0f-d08aa1b37a91.png)

I pressed `Enter`.

![image](https://user-images.githubusercontent.com/55949451/122632434-142b7000-d0d3-11eb-8fcd-831421766b10.png)

And again...

![image](https://user-images.githubusercontent.com/55949451/122632441-1f7e9b80-d0d3-11eb-9766-777ec4e06ded.png)

**Comment by Kade-github** [comment]
fixed in https://github.com/KadeDev/Kade-Engine/commit/ff472ca6e8b9cd47ee4c94048c52d300c096b7f7
