### ISSUE TITLE
Useless issue, pls close or ignore (see below)

### ISSUE THREAD

**Issue by te-agma-at** [KadeArchive/Kade-Engine#916]
USELESS EasyCompile
USELESS KE EasyCompile
USELESS KE EasyCompile
USELESS EasyCompile
USELESS EasyCompile
USELESS EasyCompile
USELESS KE EasyCompile
USELESS KE EasyCompile
USELESS EasyCompile
USELESS EasyCompile
USELESS EasyCompile
USELESS KE EasyCompile
USELESS KE EasyCompile
USELESS EasyCompile
USELESS KE EasyCompile
USELESS KE EasyCompile
USELESS EasyCompile
USELESS EasyCompile
USELESS EasyCompile
USELESS KE EasyCompile

the following above aside, i just don't think compiling fnf is my strong suit
sure i did get used to it already but if someone can link me a tutorial on compiling KE, it would be appreciated

**Comment by Lucky-56** [comment]
a full on tutorial with steps to follow ? [this](https://kadedev.github.io/Kade-Engine/building)
or a video/somebody explaining it to you ?

**Comment by isakube** [comment]
you can literally close it yourself lol
