### ISSUE TITLE
Bug Report: Cannot copy to "export/release/windows/bin/Funkin.exe", is the file in use?

### ISSUE THREAD

**Issue by IndigoVoidigo** [KadeArchive/Kade-Engine#92]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows x86_64
## What version of the game are you using? Look in the bottom left corner of the main menu.
I would use 1.3.1, but I downloaded its source code and it says that 1.3 is my version. So version is 1.3
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Every time I perform "lime test windows", I'm given the error in the image below.
I don't have Funkin.exe open when performing the command at any time.
And when this happens, no changes I make are made to the executable file.
## Please describe your issue. Provide extensive detail and images if possible.
![error](https://user-images.githubusercontent.com/78701030/112918604-3b296580-90d3-11eb-8fb0-ab96f00410b6.PNG)

**Comment by IndigoDarkw0lf** [comment]
Forgot to mention, I don't have Funkin.exe open when performing the command at any time.

**Comment by Kade-github** [comment]
you have to close the game to compile to it again. Task kill it or smth.
