### ISSUE TITLE
Enhancement: Swap default branch to `master`

### ISSUE THREAD

**Issue by isakube** [KadeArchive/Kade-Engine#921]
## What is your suggestion, and why should it be implemented?
Change the master branch to `master`, because `stable` seems to only be updated occasionally or when the documentation needs updating. (That's what I can tell at least)

**Comment by Kade-github** [comment]
naw people will pull developmental changes and get mad that kade engine broke

**Comment by puyoxyz** [comment]
@prokube, the point is that people clone stable so they don't have a broken as hell kade engine as the base of their mod, thats why its the main branch

**Comment by isakube** [comment]
a
