### ISSUE TITLE
Bug Report: Charting Menu seems to be really buggy

### ISSUE THREAD

**Issue by StellaBiscuit** [KadeArchive/Kade-Engine#926]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Windows (`x86_64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.5.3

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Open the charting menu and depending of the bug, there is different steps (specified in the next part)

## Please describe your issue. Provide extensive detail and images if possible.
There is multiple things that are strange

First of all, most notes cannot be removed using the mouse except by using "Clear Section" or by using 1-8
I say most because in some location (different for every song,Dad Battle 18th step for exemple) I can remove the note using the mouse like if nothing happened

Second, when I scroll, the game will just block me and I'm not able to go any further in the song, using other method to move around the chart work tho

Last thing, if you put a larger music then the original, it will make you unable to go further then the original song, (blammed is 75 sections for exemple, I won't be able to go past it) a workaround is to "load" the sections, that allow to move freely on the new loaded sections
So if the limit is 75 section and you load the music up to section 94, your new limit is 94 instead of 75

**Comment by StellaBiscuit** [comment]
Ok, last problem was really cause I put a longer song then the original one, since in Monster I can go past 75 sections, my bad
Updated the report

**Comment by KlutchDj** [comment]
i can back this claim up. while you can still delete notes if you use 1-8 keys to set notes, you can't delete them if you accidently use the mouse to set notes.

**Comment by Kade-github** [comment]
fixed in https://github.com/KadeDev/Kade-Engine/commit/fcc6ae72a5ed436cc5a5f3902172af5888212d29
