### ISSUE TITLE
"extension-webm"

### ISSUE THREAD

**Issue by GuyOnAComputer** [KadeArchive/Kade-Engine#928]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows (x86)

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.5.3

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Not really any steps I know.

## Please describe your issue. Provide extensive detail and images if possible.
When trying to compile the game I get:

Error: Could not find haxelib "extension-webm", does it need to be installed?

Mostly just wondering how to install "extension-webm" or what I'm doing wrong that causes it to not compile.

**Comment by NoiceBroice** [comment]
update the webm extension

do:
`haxelib git extension-webm`
when asked for the git path:
`https://github.com/KadeDev/extension-webm`
then rebuild:
`lime rebuild extension-webm windows`

**Comment by GuyOnAComputer** [comment]
thanks this worked
