### ISSUE TITLE
Balancing: Every level is beatable with keyspam

### ISSUE THREAD

**Issue by Saalvage** [KadeArchive/Kade-Engine#93]
Due to wrong presses not counting against health, every level can simply be beaten by spamming the arrow keys.

**Comment by Kade-github** [comment]
I don't think you know what an enhancement is or a bug, and I seriously doubt you know what Kade Engine does. Please do not make issues about features of kade engine being misused.

**Comment by Saalvage** [comment]
Enlighten me then. A "feature" that makes the game trivial to beat is a bad one in my humble opinion.
And your rude response suggests to me you aren't interested in seeing any more pull requests? That's sad, I would not have expected such a reaction.

**Comment by Kade-github** [comment]
I don't find it useful to respond to these "issues" when you obviously have no interest in the competitive community. If people wish to not play the game, then let them not play the game. Your score will be shit anyways, so its not really a problem. Kade Engine is made for competitive purposes, and any mash scores will have little score with terrible accuracy.

And I do look into PRs.

**Comment by Saalvage** [comment]
I fail to find the part of the description on GitHub or Gamebanana that states Kade Engine is purely geared towards competitive play. It sounds to me like it's just intended to be a general mechanics improvement.
Now, since it is made for competitive purposes I can see why this is a non-issue, but even then I find your response unnecessarily rude.
