### ISSUE TITLE
Someone create an kade engine android port

### ISSUE THREAD

**Issue by ReylordFX** [KadeArchive/Kade-Engine#934]
We need it.

**Comment by Lucky-56** [comment]
just build using `lime build android -final` or am I wrong?

**Comment by polybiusproxy** [comment]
> We need it.

finally you made the issue in kade engine repo lol

**Comment by isakube** [comment]
> just build using `lime build android -final` or am I wrong?

idk if that works. you need some SDKs or something for it to work i think

**Comment by Kappandrew** [comment]
https://github.com/KlavierGayming/K-Dev-Android/tree/master

**Comment by Kappandrew** [comment]
Its not up to date but it gets to job done (not mine at all i just am in the android FNF community rn, just wantin to help a pal out)

**Comment by Kade-github** [comment]
not an issue

**Comment by polybiusproxy** [comment]
> not an issue

thanks

**Comment by Xrelony** [comment]
"* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper"

**Comment by ACardboardBox1** [comment]
this man gives me a anyuersm

**Comment by moha123579** [comment]
> Its not up to date but it gets to job done (not mine at all i just am in the android FNF community rn, just wantin to help a pal out)



> https://github.com/KlavierGayming/K-Dev-Android/tree/master

the link is not open
