### ISSUE TITLE
Bug Report: Combo Breaks on results screen not matching with the ones under the health bar.

### ISSUE THREAD

**Issue by lamarrite** [KadeArchive/Kade-Engine#938]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows x86_64 I believe 

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.5.3

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
No

## Please describe your issue. Provide extensive detail and images if possible.
Combo breaks on the results screen do not match combo breaks under the health bar (see image below)

![Screenshot_63](https://user-images.githubusercontent.com/76110568/122673237-c21c4480-d1cf-11eb-8d43-276b22d2b9a6.png)

**Comment by Kade-github** [comment]
shits are also counted, while on the health bar they are not. I'll be making it more clear in the next update.
