### ISSUE TITLE
Enhancement: Option to turn off the timing text

### ISSUE THREAD

**Issue by ramadoor** [KadeArchive/Kade-Engine#94]
## What is your suggestion, and why should it be implemented?
So I was making a mod that has that "vanilla fnf" feel to it and I was kinda bothered that the timing text was still there. Is there a file in the Kade Engine souce code that disables the timing text? Rather, are you planning to add a feature where you can turn it off?

**Comment by theDetourist** [comment]
If you're comfortable dealing with code, make the following changes:

```
@ PlayState.hx:
    @ Line 2319, change to -> // add(currentTimingShown);
```

Mind you, that with this quick _'workaround'_, the system will work normally behind the scenes, it just won't be showing the text on the screen.

**Comment by ramadoor** [comment]
thanks man. big help!
