### ISSUE TITLE
Enhancement: Main.hx video thingy

### ISSUE THREAD

**Issue by Fefe543** [KadeArchive/Kade-Engine#940]
## What is your suggestion, and why should it be implemented?
Due to week 7 releasing soon, we gonna need the video support, so, why at main, add (with the video assets folder)
		var ourSource:String = "assets/videos/DO NOT DELETE OR GAME WILL CRASH/dontDelete.webm";

		#if web
		var str1:String = "HTML CRAP";  // haxelib git extension-webm https://github.com/KadeDev/extension-webm, lime rebuild extension-webm {windows/mac/linux}
		var vHandler = new VideoHandler(); 
		vHandler.init1();
		vHandler.video.name = str1;
		addChild(vHandler.video);
		vHandler.init2();
		GlobalVideo.setVid(vHandler);
		vHandler.source(ourSource);
		#elseif desktop
		var str1:String = "WEBM SHIT"; 
		var webmHandle = new WebmHandler();
		webmHandle.source(ourSource);
		webmHandle.makePlayer();
		webmHandle.webm.name = str1;
		addChild(webmHandle.webm);
		GlobalVideo.setWebm(webmHandle);
		#end

then it should look like this
![image](https://user-images.githubusercontent.com/77512259/122677471-c5580600-d1b8-11eb-8b8f-038850a60665.png)

**Comment by Lucky-56** [comment]
wdym Kade added video support

**Comment by Lucky-56** [comment]
if you remember the Tricky mod had video support before Kade Engine

**Comment by Fefe543** [comment]
1.5.3 doesn't have main edited to videos work. If you look at the tricky main, it has this...think before commenting.

**Comment by Fefe543** [comment]
Kade engine (now)
![image](https://user-images.githubusercontent.com/77512259/122677874-a5294680-d1ba-11eb-95af-090da611bb78.png)
Ticky
![image](https://user-images.githubusercontent.com/77512259/122677898-bd996100-d1ba-11eb-9520-9d881b7336a3.png)

**Comment by Kade-github** [comment]
no we do, look at https://github.com/KadeDev/Kade-Engine/blob/stable/source/PlayState.hx#L3256 also week 7 wont have videos so.
