### ISSUE TITLE
Bug Report: Song loops after finishing it

### ISSUE THREAD

**Issue by domcarminefilix** [KadeArchive/Kade-Engine#946]
In the newest update, 1.5.3, the ability to see your score at the end of a song was added. I accidentally disabled this and when I went to play a bit, I noticed that the song kept looping. After a bit of testing I found that, at least for me, it only happens in freeplay and reenabling the score screen prevents it from happening. I didn't test every song but I tested a good majority to confidently say it will happen with every song.

Example of the song looping: https://youtu.be/-17kVQ_hCc8

**Comment by Lucky-56** [comment]
this will be fixed in next version

**Comment by Kade-github** [comment]
looks to be fixed in pr #930
