### ISSUE TITLE
I'm doing something wrong for sure, but still gonna ask for help about modcharts

### ISSUE THREAD

**Issue by TheCapitalist** [KadeArchive/Kade-Engine#948]
So I've been trying to make player's notes dissapear(dont ask why), but when I open up the song this message appears in console
"source/PlayState.hx:246: Mod chart: false - assets/data/notgonnagivenamelol/modchart.lua", using -debug doesnt show anything
I did everything what I should, any ideas why it shows it?

**Comment by isakube** [comment]
if the folder name has a space in it, something (probably Lime) dies inside and doesn't return the file properly.
also the modchart has to be named `modchart` (saying this just in case)

**Comment by TheCapitalist** [comment]
> if the folder name has a space in it, something (probably Lime) dies inside and doesn't return the file properly.
> also the modchart has to be named `modchart` (saying this just in case)

It is named modchart, and the folder has space in it, I'm guessing I just have to remove the spaces and use dashes instead

**Comment by isakube** [comment]
> > if the folder name has a space in it, something (probably Lime) dies inside and doesn't return the file properly.
> > also the modchart has to be named `modchart` (saying this just in case)
> 
> It is named modchart, and the folder has space in it, I'm guessing I just have to remove the spaces and use dashes instead

yeah spaces mess with asset loading. idk why

**Comment by Lucky-56** [comment]
excuse me, do I hear another issue with spaces
### _dies inside_

**Comment by Lucky-56** [comment]
> It is named modchart, and the folder has space in it, I'm guessing I just have to remove the spaces and use dashes instead

**You can** name your song with spaces in-game,
**but** the files will be loaded with dashes instead

Example:
**song name:** This Song is Cool
**internal name:** this-song-is-cool

**Comment by TheCapitalist** [comment]
Yeah I had a name of my song with dashes in name for Dialogue and with spaces for charts, I was too lazy to change the name so I let the folder stay, now its usefull
