### ISSUE TITLE
Bug Report: I can't test the game

### ISSUE THREAD

**Issue by ChiIIWolf** [KadeArchive/Kade-Engine#949]
When I put in "lime test windows" it doesn't work and says that "/MSVC/extension-webm/git/ndll/Windows64/extension-webm.ndll" doesn't exist can someone help with the problem?

**Comment by Kade-github** [comment]
Line 32 building.md read it https://github.com/KadeDev/Kade-Engine/edit/stable/docs/building.md#L32
