### ISSUE TITLE
Release latest "Nightly Builds" for download

### ISSUE THREAD

**Issue by theDetourist** [KadeArchive/Kade-Engine#95]
Every time a PR or a new significant commit is made to the engine (in this case, there are big fixes waiting on Week 7 that are being reported as problems still), a "nightly build" of the latest source could be released for those that want these changes for testing or personal use.

Nothing like archiving in specific, just keeping the latest source code in a compiled state for easier access to people who just want to play. Hopefully, that would give the incentive for better feedback in the future as well.

**Comment by Kade-github** [comment]
yeah I would probably need to set these up.

**Comment by theDetourist** [comment]
But it doesn't have to be automatic just yet though, just compiled off of the latest stable Github source and linked on Readme or something.
