### ISSUE TITLE
Bug Report: Can't remove arrows in the chart editor.

### ISSUE THREAD

**Issue by BROhanBK** [KadeArchive/Kade-Engine#950]
**Kade Engine v1.5.3 Issue**

I'm trying to make a custom chart for a song I'm working on but I can't delete the preexisting arrows, or any arrow of that matter like it normally should.

**Comment by sjl057** [comment]
Same issue here. Wasn't this fixed a few months ago?

It occasionally works for songs, but most of the time I can't remove arrows at all, except in the first row.

**Comment by Kade-github** [comment]
fixed in https://github.com/KadeDev/Kade-Engine/commit/fcc6ae72a5ed436cc5a5f3902172af5888212d29
