### ISSUE TITLE
Negative scores??

### ISSUE THREAD

**Issue by Trentagonal** [KadeArchive/Kade-Engine#96]
![3D50347B-6409-45EC-B7C3-1DB04A8FF042](https://user-images.githubusercontent.com/81627795/112987974-eadcf280-9128-11eb-921a-5dc436561075.jpeg)

i keep getting negative scores?
is this normal??

**Comment by Kiffolisk** [comment]
either antimash or whatever, because negative scores is normal

**Comment by xiiixvv** [comment]
Perhaps hit the damn notes?

**Comment by Trentagonal** [comment]
Yeah but why not have it behave like regular fnf
that way your hard effort
that _isnt_ mashing and spamming and what be it
ACTUALLY gives you a high score

I dONt CaRe If THe SCOrE is 1 JUSt
ANY SCORe bc THis MAKEs Me MIsErABLE

**Comment by Kade-github** [comment]
get gud
