### ISSUE TITLE
Bug Report: The show score screen button doesn't change text when pressed

### ISSUE THREAD

**Issue by Supersonicboss1** [KadeArchive/Kade-Engine#967]
OS: Windows 10 Pro x64
Version: KE 1.5.3

To reproduce: press the button, no change, exit the entire settings menu and come back, and it is now changed

Pressing enter doesn't change the show score screen button's text to "no score screen" until you exit and re-enter the settings menu, but it does still change the setting

**Comment by Lucky-56** [comment]
84c2b06c8bf3b77f4ac0e59078936bb65bc5f87e
fixed in next release
