### ISSUE TITLE
Bug Report: Downscroll flips Up/down notes wrong

### ISSUE THREAD

**Issue by libauror-a** [KadeArchive/Kade-Engine#97]
This bug has been happening on Windows x64/86 (can't try on linux) 

Basicaly the up and down notes are flipped so **up** looks like **down** and **down** looks like **up**

Here is a example:
![image](https://user-images.githubusercontent.com/75984453/113007702-b98b1380-9176-11eb-9806-568e12a1670c.png)

**Comment by gamerbross** [comment]
i know how to fix this. in "Note.hx" delete this
![image](https://user-images.githubusercontent.com/55158797/113016064-67e68700-917e-11eb-894b-0583f71d274b.png)
;)

**Comment by theDetourist** [comment]
> 
> 
> i know how to fix this. in "Note.hx" delete this
> ![image](https://user-images.githubusercontent.com/55158797/113016064-67e68700-917e-11eb-894b-0583f71d274b.png)
> ;)

Don't do this btw, just update to the latest version of the game.
