### ISSUE TITLE
Cant build because it says theres no extension-webm folder

### ISSUE THREAD

**Issue by Touchcreator** [KadeArchive/Kade-Engine#973]
When I try to build the game it says `Error: Source path "C:/HaxeToolkit/haxe/lib/extension-webm/git/ndll/Windows64/extension-webm.ndll" does not exist` even though i installed extension-webm

**Comment by Webbyson** [comment]
I have the same issue it sucks

**Comment by nahiassis** [comment]
hey, at the cmd type: lime rebuild extension-webm windows
this should fix it

**Comment by nahiassis** [comment]
if it doesn't ill pass the files

**Comment by nahiassis** [comment]
i was having the same issue

**Comment by Whizziy** [comment]
Same

**Comment by Webbyson** [comment]
It did not work it still says its missing
Also when I do the lime rebuild thing it has a error at the end.

Error: ExternalInterface.cpp
D:\Fnf Modding Stuff\haxe\lib\hxcpp\4,2,1\include\hx\OS.h(59): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory

**Comment by Webbyson** [comment]
I don't know if I did something wrong but also I already did that before

**Comment by guizinhomartinez** [comment]
anyone knows how to see the building page????
u need to see all the haxelib installing part

**Comment by Webbyson** [comment]
go to you kade engine folder and type cmd in the search bar thing where for example says C: / Cool Folder / Steam / Castle Crashers

**Comment by Webbyson** [comment]
Also Nintendofan44 you said you could pass the file so could you send me the extension-webm.ndll file

**Comment by nahiassis** [comment]
In C:\HaxeToolkit\haxe\lib delete your current extension-webm and place this one: https://drive.google.com/file/d/1l9EYYBaE9jLi_nQUhQoXYSrOVeaciN5Z/view?usp=sharing

and dont forget to click 'extract here'

**Comment by Webbyson** [comment]
I know the problem you might also have to do lime build windows

**Comment by ibyxlz** [comment]
> hey, at the cmd type: lime rebuild extension-webm windows
> this should fix it
tysm my fnf mod is saved!
joy!

**Comment by Thefrickencrap** [comment]
i know what to do you have to check if its there if its not search it up on the top of your directory you should see the file save it as and put it at haxe toolkit at lib extension-webm-git-ndll-windows and rename windows to windows64 and it should work if have to reinstall

**Comment by mookayrah** [comment]
i am still confused

**Comment by Dramasso** [comment]
this text just keeps repeating over and over:
source/LuaClass.hx:35: characters 46-58 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:1669: characters 42-54 : Type not found : StatePointer

**Comment by mookayrah** [comment]
nvm me

**Comment by minecraftiscoolbutnotcool** [comment]
For me it says "Type not found : StatePointer"

**Comment by exmenis** [comment]
sus

**Comment by exmenis** [comment]
when you run haxe put the file name in the folder when downloading haxe it it should be done
