### ISSUE TITLE
Bug Report: Compiling issue with WebmPlayer

### ISSUE THREAD

**Issue by RonnieFilms** [KadeArchive/Kade-Engine#974]
I'm trying to compile the newest build 1.5.3 for windows but keep getting met with the same error. I also have extension-webm installed and I still get this error.

source/PlayState.hx:3247: characters 17-32 : Class<webm.WebmPlayer> has no field SKIP_STEP_LIMIT

**Comment by exiliph** [comment]
go to Playstate.hx at line and remove line 3264. it worked for me

**Comment by Kade-github** [comment]
https://github.com/KadeDev/Kade-Engine/blob/stable/docs/building.md

**Comment by DomeDoppiaggi** [comment]
![Immagine 2021-11-19 223536](https://user-images.githubusercontent.com/94015519/142688435-b2772e8c-b992-48e0-82b1-faac4cfc6e3c.png)

**Comment by CPPxfnfmodsmaker** [comment]
OMG THANKS YOU HELPED ME!
