### ISSUE TITLE
Two issues.

### ISSUE THREAD

**Issue by ScrubRTA** [KadeArchive/Kade-Engine#975]
1. Complex accuracy doesn't work. If I had to guess, I'd say it broke because hit timing numbers can now have negative values instead of using absolute values, and it still takes the same average.
2. In settings, it says a Sick window is +-22ms and Good is +-45ms, when they are still +-45ms and +-90ms respectively like they used to be. I see "Rewrote the entire hit ranking system" in your changelog, I'm guessing you forgot something?

**Comment by Kade-github** [comment]
shoulda been fixed
