### ISSUE TITLE
Three major ideas.

### ISSUE THREAD

**Issue by ScrubRTA** [KadeArchive/Kade-Engine#976]
1. Song speed modifier.  Default to 100% which is just the normal song, punch in a number X, the song plays at X% of that speed. Clone Hero has this and I'd like to see it in FNF (afaik there are no mods that fully have this function)
2. "Marvelous" hit window. osu!mania has less than +-20ms window for a perfect hit (specifically, I've heard +-16.5ms), whereas FNF allows up to 45ms deviation. For any high level 4key player (which I'm not), 45ms is effortless, even on something as hard as MILF or Spookeez. With a Marvelous hit window, experienced players would have something more to shoot for than full Sick (currently called MFC, should be renamed to SFC if this is implemented).
3. Show more statistics. One idea I had is a "Sick Combo" counter, which counts the number of Sick notes hit in a row instead of just notes in general. Some other examples from Etterna include WF (White Flag; 1 non-perfect hit off of a MFC), BF (Black Flag; 1 Bad note off of a GFC. Not to be confused with Boyfriend, the main character), MF (Miss Flag; 1 combo break), and SDG (Single Digit Greats, a FC with less than 10 non-perfect hits). This could be made more complicated if my last suggestion (Marvelous hits) is introduced.

**Comment by Kade-github** [comment]
1. scroll speed already exists
2. no, just no.
3. results screen

**Comment by puyoxyz** [comment]
kade they didn't mean scroll speed

**Comment by ScrubRTA** [comment]
> 1. scroll speed already exists

Not note speed. Chart speed.
