### ISSUE TITLE
Bug Report: whatever the fuck happened here with my score

### ISSUE THREAD

**Issue by arceuss** [KadeArchive/Kade-Engine#98]
![image](https://user-images.githubusercontent.com/28229451/113038459-cb0ef400-9153-11eb-8336-540feef6c8d5.png)
i set the scrollspeed to 2.4 if it helps anyway

**Comment by arceuss** [comment]
cuz it seems like my score turns to 0 if i miss or something

**Comment by Kade-github** [comment]
etterna mode is funny amirite

**Comment by arceuss** [comment]
etterna mode funny moments
