### ISSUE TITLE
Bug Report:  Type not found : webm.WebmPlayer

### ISSUE THREAD

**Issue by bloodiey** [KadeArchive/Kade-Engine#986]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`),

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.5.3
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
the file PlayState.HX import webm.WebmPlayer;
## Please describe your issue. Provide extensive detail and images if possible.
this happens and ihave installed the haxelib Since yesterday
![2021-06-22](https://user-images.githubusercontent.com/71611133/122944007-17299900-d33d-11eb-8800-942b9644d368.png)

**Comment by MoezTrigui** [comment]
same

**Comment by Webbyson** [comment]
same

**Comment by puyoxyz** [comment]
run the rebuild thingy
