### ISSUE TITLE
Webm Player Not Working

### ISSUE THREAD

**Issue by cuzsie** [KadeArchive/Kade-Engine#989]
When trying to build the game, i get the error:

C:/Program Files/Haxe/haxe/lib/extension-webm/git/webm/WebmPlayer.hx:3: characters 8-15 : You cannot access the cpp package while targeting js (for cpp.Lib)source/Main.hx:4: characters 8-23 :     referenced here
export/release/html5/haxe/ApplicationMain.hx:299: characters 48-52 :     referenced here

**Comment by isakube** [comment]
lol you're building to html5

dont

**Comment by x8c8r** [comment]
> lol you're building to html5
> 
> dont

so i can't build for html5 now? that sucks

**Comment by Kade-github** [comment]
shoulda been fixed now
