### ISSUE TITLE
Enhancement: Anti-Keyspam?

### ISSUE THREAD

**Issue by Boii1** [KadeArchive/Kade-Engine#99]
Could there be an option to disable key spamming in songs? I want to get better at this game but the old input system makes it hard to learn, but this one makes it so I can just spam keys and win the song. Sort of ruins the fun :/

Like I get for competitive community it's nice to have it off but at least an option for it would be nice for newer players.

**Comment by Kade-github** [comment]
If you want to get better, don't spam :). Most 4k games do this. Try to get a good score on the leaderboards.

You can find them here https://discord.gg/n3fXZdCsab
