### ISSUE TITLE
Notes that go below the strumline gets "skipped"

### ISSUE THREAD

**Issue by PixelHUN** [KadeArchive/Kade-Engine#990]
I started noticing this issue when I first played my chart on the new version (fresh from GitHub, and freshly built)
However, it's also noticeable on other charts too.

If there are multiple notes on the same lane, following each other (jacks), and one of the notes gets under the strumline, it will get skipped and it will instantly hit the next note, resulting in a Bad hit.

I bumped up the scroll speed of Thorns so that the bug is clearly visible.
(Kade Engine 1.5.3)

https://user-images.githubusercontent.com/59181913/122974102-3bfc2b80-d392-11eb-9d74-b5ca01810c87.mp4

**Comment by Kade-github** [comment]
The game prioritizes the closest note to the strum line to avoid double judgments. Thus this is intended.

**Comment by PixelHUN** [comment]
> The game prioritizes the closest note to the strum line to avoid double judgments. Thus this is intended.

Thanks for the answer, however I think there's still an issue...
Don't tell me that, the note on the strum line is further than the next note:

https://user-images.githubusercontent.com/59181913/123071581-12d0af00-d415-11eb-99f4-0fa29562f357.mp4

**Comment by Gityc101** [comment]
If you prefer the old hit detection, edit line 214-215 of Note.hx from:
- if (strumTime > Conductor.songPosition - Conductor.safeZoneOffset
&& strumTime < Conductor.songPosition + Conductor.safeZoneOffset)
to:
- if (strumTime > Conductor.songPosition - Conductor.safeZoneOffset
&& strumTime < Conductor.songPosition + (Conductor.safeZoneOffset * 0.5))

**Comment by Kade-github** [comment]
Fixed in the latest release.
