### ISSUE TITLE
Bug Report: E:/Mod/Kade-Engine-stable/MSUV/Polymod/git/polymod/format/XMLMerge.hx:189:characters 10-23 : this typefed is deprecated in favor of haxe.xml.Access 30-43 : Warning : This typedef is deprecated in favor of haxe.xml Access ERROR

### ISSUE THREAD

**Issue by JoaIsPogXD** [KadeArchive/Kade-Engine#991]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), this one

## I was trying to do the steps of make the game, but i had alot of problems and i fix them, but there is a messenge what i dont know what i have to do, the messenges are 
''E:/Mod/Kade-Engine-stable/MSUV/Polymod/git/polymod/format/XMLMerge.hx:189:characters 10-23 : this typefed is deprecated in favor of haxe.xml.Access 30-43 : Warning : This typedef is deprecated in favor of haxe.xml Access''

and i tried with ''haxelib run lime test windows''

##

**Comment by MagnusStrom** [comment]
cmon bro, do you not say the thing WARNING?

**Comment by JoaIsPogXD** [comment]
> cmon bro, do you not say the thing WARNING?
BUT HOW I CAN FIX THAT

**Comment by isakube** [comment]
> BUT HOW I CAN FIX THAT

dont

**Comment by JoaIsPogXD** [comment]
> > BUT HOW I CAN FIX THAT
> 
> dont

wdym

**Comment by Burger-Gaming** [comment]
> > > BUT HOW I CAN FIX THAT
> > 
> > 
> > dont
> 
> wdym

that's only a warning and that's not what's causing the compiling to mess up. you can't do anything about the warning.

**Comment by Kade-github** [comment]
these are warnings

**Comment by Goostiny** [comment]
can't believe i had to make a github account to ask a question. im sure its a warning but it completely stops the whole compile and just leaves me off with nothing. i might be dumb so just please tell me. if i have to change or fix something then ill be sure to.
