### ISSUE TITLE
Bug Report: everytime I run "lime test windows" it says " Could not find haxelib "extension-webm", does it need to be installed?" What do I do?

### ISSUE THREAD

**Issue by ShivaFoxx** [KadeArchive/Kade-Engine#993]
I am trying to create an FNF mod and I had downloaded the Kade Engine, the setup.bat application, and everything else that is needed. I followed a tutorial I saw on youtube the entire way through, and successfully downloaded everything that was needed, until I tried to run "line test windows" it said I needed an application that was not suggested through the setup, so I searched it online, found it, downloaded it, set it up, and put it in the Kade Engine folder. It still didn't work. I tried asking FNF modders themselves and they didn't know, what do I do??

**Comment by staring-hamster** [comment]
Open CMD or Powershell and type:

`haxelib install actuate` 
`haxelib git extension-webm https://github.com/KadeDev/extension-webm`
`lime rebuild extension-webm windows`

This will install the required extensions to compile Kade Engine 1.5.3

**Comment by JoaIsPogXD** [comment]
> Open CMD or Powershell and type:
> 
> `haxelib install actuate`
> `haxelib git extension-webm https://github.com/KadeDev/extension-webm`
> `lime rebuild extension-webm windows`
> 
> This will install the required extensions to compile Kade Engine 1.5.3

Callate sebas ahora ayudame en mi problema

**Comment by staring-hamster** [comment]
> Callate sebas ahora ayudame en mi problema

Perdon?

**Comment by JoaIsPogXD** [comment]
> > Callate sebas ahora ayudame en mi problema
> 
> Perdon?

XD

**Comment by Whizziy** [comment]
same problem but i did lime rebuild haxelib install actuate
haxelib git extension-webm https://github.com/KadeDev/extension-webm
lime rebuild extension-webm windows


> Open CMD or Powershell and type:
> 
> `haxelib install actuate`
> `haxelib git extension-webm https://github.com/KadeDev/extension-webm`
> `lime rebuild extension-webm windows`
> 
> This will install the required extensions to compile Kade Engine 1.5.3

**Comment by Whizziy** [comment]
bu i did receave a error in lime rebuild extension-webm windows

**Comment by Whizziy** [comment]
C:\HaxeToolkit\haxe\lib\extension-webm\git\project>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC

**Comment by staring-hamster** [comment]
I know it might sound stupid but, have you installed the Visual Studio 2019 workloads?

**Comment by hdfsyu** [comment]
Please close this as this has been already solved by doing these steps:
>  Open CMD or Powershell and type:
>  `haxelib install actuate`
>  `haxelib git extension-webm https://github.com/KadeDev/extension-webm`
>  `lime rebuild extension-webm windows`
>  This will install the required extensions to compile Kade Engine 1.5.3

**Comment by puyoxyz** [comment]
idiots
