### ISSUE TITLE
Enhancement:  Difficulty Rating

### ISSUE THREAD

**Issue by KlutchDj** [KadeArchive/Kade-Engine#994]

**Comment by Kade-github** [comment]
this is a pretty advanced topic I think I might dabble into it later but not now, it's really hard to do WELL

**Comment by isakube** [comment]
> this is a pretty advanced topic I think I might dabble into it later but not now, it's really hard to do WELL

Some equation involving note density, bpm, scroll speed, and length I think

**Comment by KlutchDj** [comment]
> d t

i don't think scroll speed will play a role into the difficulty rating. as other people prefer slower/higher scrolls speeds that fits their standards.

**Comment by Kade-github** [comment]
done in https://github.com/KadeDev/Kade-Engine/commit/b16237ab92c14d66210a9653e314d706dde968f7
