### ISSUE TITLE
Bug Report: Source path "C:/Users/Uzivatel/lime/extension-webm/git/ndll/Windows64/extension-webm.ndll" does not exist

### ISSUE THREAD

**Issue by zenolth** [KadeArchive/Kade-Engine#999]
Hello, I was working on my mod, and i ran "lime test windows" and only thing it showed was "Error: Source path "C:/Users/Uzivatel/lime/extension-webm/git/ndll/Windows64/extension-webm.ndll" does not exist"... So how can I fix it.
PS : i did "haxelib git" already, so don't say "Install extension-webm from https://github.com/KadeDev/extension-webm/"

**Comment by GenericGaming** [comment]
Oh, okay, this is easy to fix, use the command "lime rebuild extension-webm windows"

**Comment by zenolth** [comment]
Shows this "Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC"

**Comment by GenericGaming** [comment]
dang, way easier on my computer (due to not being on a windows pc)

**Comment by isakube** [comment]
find Visual Studio 2017 VsDevCmd then

**Comment by zenolth** [comment]
> find Visual Studio 2017 VsDevCmd then

Or i can just install Visual Studio Community 2019 then...

**Comment by ShinyMattC** [comment]
> Oh, okay, this is easy to fix, use the command "lime rebuild extension-webm windows"

Oh ok now it shows this:
d:\hax\haxe\lib\hxcpp\4,2,1\include\hx\OS.h(59): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory

**Comment by Kade-github** [comment]
you need to install MSVC which can be done by downloading visual studio 2019

**Comment by puyoxyz** [comment]
WHY DOES NOONE READ THE BUILD INSTRUCTIONS

**Comment by RealLumiOff** [comment]
> Oh, okay, this is easy to fix, use the command "lime rebuild extension-webm windows"
shows: GetThreadContent failed.

**Comment by kantaphat7** [comment]
> you need to install MSVC which can be done by downloading visual studio 2019

if i install virall studio finish what i have to do next

**Comment by te-agma-at** [comment]
> you need to install MSVC which can be done by downloading visual studio 2019

kade. i know exactly what you're doing.

**Comment by FunkinRobloxFNFMadness** [comment]
jjj

**Comment by Exzyte** [comment]
If u need a problem getting extension-webm.ndll , install Visual Studio build tools, I personally selected them all when installing, but yeah, hopefully, it solves your problem.

**Comment by BrandonHatesAnime** [comment]
Assuming you have the basic software to compile, download this https://drive.google.com/file/d/1JT3EE7dJk9MKNzr2-YbojiMwJ23Mh4L2/view (It's not a virus I can guarantee). Complete all the steps, then get Visual Studio 2017 VsDevCmd. then type in "lime rebuild extension-webm windows". It worked for me so I hope it worked for you, just incase put "Install extension-webm from https://github.com/KadeDev/extension-webm/" also lol.

PS: Do "flixel configure . -ide vscode" as well.

**Comment by johne69** [comment]
what
